### ISSUE TITLE
Desktop Agent Bridging Discussion group 28th June 2023

### ISSUE THREAD

**Issue by kriswest** [finos/FDC3#1016]
# Group overview
Discussion group for developing proposals for producing bridges between FDC3 implementations (aka Desktop Agents), allowing applications running on one Desktop Agent, to integrate with FDC3 applications running on a second Desktop Agent for the same user.

The interop between applications running on different Desktop Agents aka Platforms would ideally cover
- Channels
- Raising and resolving Intents
- Launching Applications

Current proposal:
- PR: https://github.com/finos/FDC3/pull/968
[PR preview](https://deploy-preview-968--fdc3.netlify.app/)
- [Specification link](https://deploy-preview-968--fdc3.netlify.app/docs/next/api-bridging/spec)
- Overview deck from the FINOS members meeting ([Google slides](https://docs.google.com/presentation/d/1v2GcL8kh82cIVu5c7zsjM2nHcubbRnXyKmiV2ElV5fI/edit?usp=sharing), [PDF](https://github.com/finos/FDC3/files/11837521/Desktop.Agent.Bridging.-.FINOS.Members.Meeting.2023.pdf)) (covers use-cases and impact on the FDC3 API)

### Relevant issue tags
- Current open issues that relate to the above concepts with the label: 
  [![image](https://user-images.githubusercontent.com/1701764/144856698-e49821ab-9c8e-4daf-99a1-23f4774c1fcd.png)](https://github.com/finos/FDC3/labels/Desktop%20Agent%20Bridging)
- The original issue is now a github discussion where content can be added and this issue discussed: 
#544

## Meeting Date
Wednesday 28 June 2023 - 9am EST / 2pm BST

### WebEx info
- Meeting link: [https://finos.webex.com/finos/j.php?MTID=m55d4aa79e148c948bf53163690e74fee](https://finos.webex.com/finos/j.php?MTID=m55d4aa79e148c948bf53163690e74fee)
- Meeting number: 2558 920 8729

*More ways to join*
- Join by video system:
   - Dial 25589208729@finos.webex.com
   - You can also dial 173.243.2.68 and enter your meeting number
- Join by phone
   - +1-415-655-0003 US Toll
   - +44-20319-88141 UK Toll
- Access code: 2558 920 8729

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies).

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.
  
- A Discussion Group has no direct decision-making power regarding the FDC3 standard - rather it is intended that anything they propose or work on will result in proposals (via Github issues and PRs) for the Standards Working Group participants to consider and vote on for inclusion in the standard.
   
## Agenda
- [x] Convene & roll call, review meeting notices (5mins)
- [x] Review action items from previous meeting (5mins)
  - #998
- [x] Recent changes to the proposal based on review feedback (10 mins)
- [x] Q&A session for FDC3 voting participants (20 mins)
- [x] Updates from the Backplane project (15 mins)
  - Async API spec & generated docs 
- [x] AOB & Adjourn (5mins)

## Minutes
- Summary of recent (last couple of months) small changes to the proposal
  - Changed GUID -> UUID throughout docs and schemas
  - Splitting schemas for agent and bridge messages (to allow precise massage validation)
    - better structure for schema composition 
- Questions about proposed addition to Standard:
  - Does an app need to do anything to make use of bridging?
    - No - Desktop Agent's responsibility, but limited visibility provided to apps through AppIdentifiers
      - Add some details of how apps interact with DAs - not super clear in overview
        - Perhaps in intro and each mermaid diagram for an exchange 
  - How does naming of desktop agents work? How are conflicts or duplicate names dealt with
    - Names requested in setup steps
    - Actual name assigned by a bridge so that clashes are avoided
      - Note that its also the bridge's responsibility to correctly label messages and appIdentifiers in them from DAs, to avoid spoofing 
  - Bridge discovery/detection procedure
    - Currently always on localhost/127.0.0.1 - simplifying assumption for security, until FDC3 does more about user and desktop agent identity.
    - Port range is available and could be scanned - hello message allows identification and auth (if desired) of bridge
    - can also use config for a specific port
      - discovery method was included to solve for cases where a vendor is putting something out and doesn't support config - potentially simpler to use.
      - all supported methods can work together.
-  Async API spec & generated docs
  - @Vivek-NatWest demonstrated the aysnc-api spec that was assembled from from the individual message schema
    - Two documentation generator templates available (markdown and HTML)
    - Various Client and Server stub generators available for node/typescript/.Net/Python/Java etc..
      - Title fields are really important to generated code (but not used in validation so are optional)
        - Bridging schemas all have titles, API schemas don't, but need them to be added (or you get anonymous types/interfaces/classes generated). 
  - Consent was requested and received to add some optional asyncAPI files to the proposed addition (doesn't change it, but might provide some implementation help)

## Action Items
- [x] @kriswest @tpina add some content to the overview to better explain how apps are insulated from working with bridging directly
- [x] @kriswest @tpina add apps to the individual exchange mermaid diagrams to further clarify interactions.
- [x] @Vivek-NatWest @kriswest @tpina Meet offline and review API schema generation, missing titles, etc. and work towards a PR to add asyncAPI files to the repository
- [x] ALL Vote on including Desktop Agent Bridging in FDC3 by EOD 11th July.

## Untracked attendees

| Full name | Affiliation | GitHub username |
|-----------|-------------|-----------------|
|           |             |                 |

**Comment by novavi** [comment]
Derek Novavi / S&P Global

**Comment by sarahstone-cosaic** [comment]
Sarah Stone / interop.io

**Comment by mattjamieson** [comment]
Matt / WhiteDog :cactus:

**Comment by tpina** [comment]
Tiago Pina / interop.io

**Comment by Vivek-NatWest** [comment]
Vivek/NatWest

**Comment by mistryvinay** [comment]
Vinay Mistry / Symphony 🎵

**Comment by aaronhaines** [comment]
Hi.

**Comment by openfin-johans** [comment]
Johan Sandersson / OpenFin 🎁

**Comment by greyseer256** [comment]
Hugh Troeger / FactSet

**Comment by robmoffat** [comment]
Rob / FINOS 0️⃣
