### ISSUE TITLE
Context Data & Intents Discussion group - 6 Jul 2023

### ISSUE THREAD

**Issue by mistryvinay** [finos/FDC3#1019]
## Group overview
At the FDC3 Use Cases Roundtable London, October 5th 2021 participants agreed that the FDC3 lexicon needs to be expanded, both with additional intents and context types to support Use Cases, but also to include more primitive data types in order to construct complex types. A number of participants also agreed that now is an appropriate time to expand the Lexicon.
​
See https://github.com/finos/FDC3/issues/455 for full details of the meeting outcomes.
​
This group is being convened to discuss and arrange work to contribute further Context types and Intents to support Use Cases being implemented by participants.

### Relevant issue tags
Current open issues that relate to the discussion group: 
[![image](https://user-images.githubusercontent.com/1701764/139841356-416d9276-81f5-4fce-b5d8-f856d4bda855.png)](https://github.com/finos/FDC3/labels/Context%20Data%20%26%20Intents)

Issues will also be tagged with the labels:
[![image](https://user-images.githubusercontent.com/1701764/139841631-c6bf8697-fafe-4266-8552-63a648625e8b.png)](https://github.com/finos/FDC3/labels/context-data)
[![image](https://user-images.githubusercontent.com/1701764/139841690-969a9d14-a0aa-44a7-bdfe-8c4a43ad30d9.png)](https://github.com/finos/FDC3/labels/intents)

## Meeting Date
Thursday 6 July 2023 - 9am EST / 2pm GMT

### WebEx info
- Meeting Link: https://finos.webex.com/finos/j.php?MTID=mbb193ae433ce8d4366adcecd94355734
- Meeting number: 2556 257 8293

*More ways to join*
- Join by video system:
   - Dial 25562578293@finos.webex.com
   - You can also dial 173.243.2.68 and enter your meeting number
- Join by phone
   - +1-415-655-0003 US Toll
   - +44-20319-88141 UK Toll
- Access code: 2556 257 8293

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies).

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.
  
- A Discussion Group has no direct decision-making power regarding the FDC3 standard - rather it is intended that anything they propose or work on will result in proposals (via Github issues and PRs) for the Standards Working Group participants to consider and vote on for inclusion in the standard.
   
## Agenda
- [x] Convene & roll call, review meeting notices (5mins)
- [x] Review action items from previous meeting (5mins)
  - [x] #1011  
- [x] Discussion of open issues (35mins)
  - [x] #940  
    - Continuation discussion from last month
    - Draft Proposal #1020 
    - [Google Doc tracking proposal](https://docs.google.com/document/d/183KJ6tIkrgsboFYp-cMEjCOvtumLwkFD1IRJ0Nzx5-8/edit?usp=sharing)
- [x] Issues requiring a PR (5mins)
  - [x] #828 
  - [x] #904 (SWG - Consent received to add @experimental `Order` and `Trade` basic context types to FDC3 2.1
- [x] CD&I 2.1 Consolidated PR (1min)
  - [x] #994 
- [x] AOB & Adjourn (5mins)

## Minutes
- #940
  - Requirement for a new approach to proposing, documenting and publishing intents and contexts that's more efficient. Something that doesn't require as many meetings and can be uncoupled from the FDC3 Standard, so we can release more quicker
  - Incorporate the ability to publicise proprietary types so that people can advertise the fact that they integrate with FDC3. It will also give us a bit more information to look for common denominators to standardize
  - We think we will need to build some machinery for FDC3 to facilitate this. 
  - Currently you have to do several things to get something published into the standard
    - You need to raise a GitHub issue
    - then you need to raise a PR
      - Within that PR, you need to implement JSON schema defining the `type`
      - Then need to implement documentation in the website defining the `type` again
      - Duplicative effort which is unnecessary
  - Proposal
    - We should not take away the JSON schema files as they are a great tool for an accurate definition of what is going into an object, and can be used to validate that one is correct.
    - FDC3 uses typescript to define the API even though they're intended to be implemented in other languages. 
    - Primary type is a JSON schema. We already have machinery that can generate typescript types from that for people to use. 
    - These then go into the NPM module 
    - Various other people are looking at making concrete objects for .NET, Java and other languages.
    - What isn't handled well is the documentation.
    - There's lots of good information in the markdown files for documentation, but it can be put into a schema file as well
    - There are tools for generating documentation from schema files that we could build something based on
    - #1020 
      - Bring in the documentation so pretty much everything that's in that documentation page can make it into the schema.
        - We've added in a description and documentation of the individual field, so a title and description for each field.
        - These will become comments and field names in generated source code. But it's just really demonstrating that you can put all of that information right the way down to the examples in a schema file.
        - Next step is to use tooling for rendering documentation pages out of these schema files to generate HTML pages
        - We can generate markdown that we could bring into the FDC3 website.
        - Simplifies process as there's only 1 file, the JSON schema file.  It will generate documentation page, when it goes in. 
        - We generate all source code for other languages from it, we generate our documentation for it and we build tooling.
          - That means somebody could perhaps do this with a form rather than having to learn JSON schema
        - So we should be able to get to a place where somebody could submit a schema as a proposal for standardization that could become an @experimental type quite quickly if it doesn't conflict with other things.
        - Freeing up the Context Data & Intents group meetings for just governance purposes.
        - @nemery-flextrade the reference to FIX _where it is often better to refer to the messages that you've actually seen across the wire than the specification_. With this being largely driven through the standard, it shouldn't, in theory, vary too far away from it. So I think generating it from a sample message is a good way to go about it. You get all within one file that it would really streamline it as well.
          - @kriswest We will still have to make sure it goes through the Easy CLA process of course.  Because they will represent contributions.
- #904 
  - Proposed to the Standards Working Group, to include some empty objects, basically giving them a type FDC3 `Order` and `Trade`.  Include some Id fields, as the absolutely lowest possible common denominative to these types.
    - Mark them as @experimental so that we can keep adding to them, this allows us to release them in the FDC3 2.1 release
    - Propose to build an `Order` and `Trade` object based on the below. 
      - They will both have `id` fields as their primary content.
      - We won't include any predefined keys (in the `id` object) initially. However, firms with products used externally with names for the Ids may propose somr to include. 
      - There will be an optional `product` field on the `Order` type, which is of type `Context`.
        - @dominicgifford stated that his firm processes orders without a product for cash raises.
        - A `Product` context type has yet to be defined and will potentially be highly complex (as demonstrated by the existing attempt to do so: #644), hence, we initially propose a place to put it before defining it later.
      - On the `Trade` type, there will be a `Product` field of type context, but it will be required there (as trades will always relate to a product.
      - Finally, we would allow the objects to have additional properties until they're no longer experimental.

## Action Items
- [x] @kriswest to work on building `Trade` and `Order` types for submission into the 2.1 release
- [x] @mistryvinay work with maintainers to proposal for governing Context and Intents
- [ ] @kriswest request to raise a PR for #828  (for after FDC3 2.1)

## Untracked attendees

| Full name | Affiliation | GitHub username |
|-----------|-------------|-----------------|
|           |             |                 |

**Comment by robmoffat** [comment]
Rob / FINOS 🚚

**Comment by hampshanubs** [comment]
Andrew Hampshire @ UBS

**Comment by milindchidrawar** [comment]
Milind Chidrawar / Singletrack

**Comment by dominicgifford** [comment]
Dom / S&P

**Comment by mistryvinay** [comment]
Vinay Mistry / Symphony 🎵
