### ISSUE TITLE
FDC3 General Meeting - August 08, 2023

### ISSUE THREAD

**Issue by Julia-Ritter** [finos/FDC3#1039]
## Date
8th August 2023 - 10am EST / 3pm BST

### WebEx info
- [Meeting Link](https://finos.webex.com/finos/j.php?MTID=m3015a7e4a511656ceafebda5eadcbe6d)
- Meeting number: 403 028 328

*More ways to join*
- Join by video system: dial 173.243.2.68 and enter your meeting number
- Join by phone
   - +1-415-655-0003 US Toll
   - +44-20319-88141 UK Toll
- Access code: 403 028 328

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies).

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [ ] Convene & roll call, review meeting notices (5 mins)
- [ ] Announcements (20 mins)
  - Voting open on the adoption of FDC3 2.1
    - Whats new in 2.1? 
  - FDC3 2.0 Training & Certification update
- [ ] Whats next for FDC3? (10 mins)
  - FDC3 for Web Browsers
  - Updating Context & Intents governance & continuing to expand the dictionary
  - FDC3 bindings for other languages
  - Identity & Threat Modelling discussion group
  - Updating the FDC3 charter
- [ ] Recruiting maintainers, editors & participants (5 mins)
- [ ] DEMO: Desktop Agent Bridging with Backlplane (10 mins)
- [ ] Q&A (not recorded) (upt0 15 mins)

## Recording

https://github.com/finos/FDC3/assets/1701764/3dd6a569-b9a3-47ee-a0a7-288bb8b8db61

## Untracked attendees

| Full name | Affiliation | GitHub username |
|-----------|-------------|-----------------|
|           |             |                 |

**Comment by novavi** [comment]
Derek Novavi / S&P Global

**Comment by mistryvinay** [comment]
Vinay Mistry / Symphony 🎵

**Comment by pierreneu** [comment]
Pierre Neu / Symphony

**Comment by openfin-johans** [comment]
Johan Sandersson / OpenFin 🎁

**Comment by psmulovics** [comment]
Peter Smulovics / Morgan Stanley 🏦

**Comment by mattjamieson** [comment]
Matt Jamieson / WhiteDog :coffee:

**Comment by Vivek-NatWest** [comment]
Vivek / NatWest

**Comment by lspiro-Tick42** [comment]
Leslie Spiro / interop.io

**Comment by timjenkel** [comment]
Tim Jenkel / Wellington

**Comment by kriswest** [comment]
Kris West / Interop.io 🚀

**Comment by hughtroeger** [comment]
Hugh Troeger / FactSet
