### ISSUE TITLE
Context Data & Intents Discussion group - 3 Aug 2023

### ISSUE THREAD

**Issue by mistryvinay** [finos/FDC3#1048]
## Group overview
At the FDC3 Use Cases Roundtable London, October 5th 2021 participants agreed that the FDC3 lexicon needs to be expanded, both with additional intents and context types to support Use Cases, but also to include more primitive data types in order to construct complex types. A number of participants also agreed that now is an appropriate time to expand the Lexicon.
​
See https://github.com/finos/FDC3/issues/455 for full details of the meeting outcomes.
​
This group is being convened to discuss and arrange work to contribute further Context types and Intents to support Use Cases being implemented by participants.

### Relevant issue tags
Current open issues that relate to the discussion group: 
[![image](https://user-images.githubusercontent.com/1701764/139841356-416d9276-81f5-4fce-b5d8-f856d4bda855.png)](https://github.com/finos/FDC3/labels/Context%20Data%20%26%20Intents)

Issues will also be tagged with the labels:
[![image](https://user-images.githubusercontent.com/1701764/139841631-c6bf8697-fafe-4266-8552-63a648625e8b.png)](https://github.com/finos/FDC3/labels/context-data)
[![image](https://user-images.githubusercontent.com/1701764/139841690-969a9d14-a0aa-44a7-bdfe-8c4a43ad30d9.png)](https://github.com/finos/FDC3/labels/intents)

## Meeting Date
Thursday 3 August 2023 - 9am EST / 2pm BST

### WebEx info
- Meeting Link: https://finos.webex.com/finos/j.php?MTID=mbb193ae433ce8d4366adcecd94355734
- Meeting number: 2556 257 8293

*More ways to join*
- Join by video system:
   - Dial 25562578293@finos.webex.com
   - You can also dial 173.243.2.68 and enter your meeting number
- Join by phone
   - +1-415-655-0003 US Toll
   - +44-20319-88141 UK Toll
- Access code: 2556 257 8293

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies).

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.
  
- A Discussion Group has no direct decision-making power regarding the FDC3 standard - rather it is intended that anything they propose or work on will result in proposals (via Github issues and PRs) for the Standards Working Group participants to consider and vote on for inclusion in the standard.
   
## Agenda
- [x] Convene & roll call, review meeting notices (5mins)
- [x] Review action items from previous meeting (5mins)
  - [x] #1019 
- [x] Discussion of open issues (35mins)
  - [x] #940  
    - Working meeting on defining new governance process
    - Draft Proposal #1020 
    - [Google Doc tracking proposal](https://docs.google.com/document/d/183KJ6tIkrgsboFYp-cMEjCOvtumLwkFD1IRJ0Nzx5-8/edit?usp=sharing)
- [x] Issues requiring a PR (5mins)
  - [x] #828 
- [x] AOB & Adjourn (5mins)

## Minutes
- #940
  - Walk through of proposal to publish new types which is documented here [Governance of Context and Intents Types from the FDC3 API(https://docs.google.com/document/d/183KJ6tIkrgsboFYp-cMEjCOvtumLwkFD1IRJ0Nzx5-8/edit?usp=sharing)
  - @kriswest making it easier to submit experimental types, have them incubated for a period of time.  Then the community could provide opinions and then elevate them up into the standard.
  - Similar process for submitting proprietary types.  With remotely hosted schema.
    - It's a lot more difficult for us to know when a remote schema is updated if it's remotely hosted.
    - So it may be that we have just a stub, with a version number and a remote reference might be enough.  So if you know you're updated your types and you're ready for the rest of the world to start using them, you would then do a little push, which can trigger a workflow on the FDC3 Github repo to republish.
    - @nemery-flextrade like that approach.  Because if we were to leave it to some sort of automated set up, then there's every chance that, we might publish a new version of a type that's not actually ready for consumption yet.
    - Whereas leaving it, with that stub file, with a version and a reference to an upstream location means that we can still keep everything nicely automated.  We don't have to worry about exposing stuff before it's ready.
  - #1020 
    - Walk through of draft JSON schema which we can derive documentation and software from.
    - JSON schema can only define the shape of data structures.  We would then be generating typescript from those.  Or if somebody finds a way of delivering the dot net types for example, generating things from those.
    -  Bringing all the documentation up into the context objects, which has the advantage that they go into all the generated software as well. So you get intellisense, if you're trying to type in, an action object into your IDE. It will propose the fields to, which it did before, but it now gives you the documentation for the fields as well.
    - Planning to add this proposal as a late PR into the upcoming FDC3 2.1 release
  - Next step to work with maintainers and FINOS to understand what tooling / automation is required for this proposal.
    - Look to leverage Github actions to carry out the schema validation prior to NPM builds.
    - Open question on whether we actually go and split the current NPM module into the FDC3 API and one for Context and Intents. 

## Action Items
- [ ] ...

## Untracked attendees

| Full name | Affiliation | GitHub username |
|-----------|-------------|-----------------|
|           |             |                 |

**Comment by mistryvinay** [comment]
Vinay Mistry / Symphony 🎵

**Comment by nemery-flextrade** [comment]
Nathan Emery / FlexTrade

**Comment by milindchidrawar** [comment]
Milind Chidrawar / Singletrack

**Comment by Julia-Ritter** [comment]
Julia / FINOS

**Comment by cristiano-belloni** [comment]
Cristiano Belloni / UBS

**Comment by kriswest** [comment]
Kris West / Interop.io 🚀
