### ISSUE TITLE
Desktop Agent Bridging Discussion group 27th Sept 2023

### ISSUE THREAD

**Issue by kriswest** [finos/FDC3#1075]
## Group overview
Discussion group devoted to 'bridging' between FDC3 implementations (aka Desktop Agents), allowing applications running on one Desktop Agent to integrate with FDC3 applications running on additional Desktop Agents and devices for the same user.

Desktop Agent Bridging was added to FDC3 in the 2.1 release as an [@experimental](https://fdc3.finos.org/docs/fdc3-compliance#experimental-features) 5th-Part to the Standard. The group is now dedicated to the discussion of implementations, Q&A on the protocol, and working to improve the protocol further.

### Relevant issue tags
Issues that relate to Desktop Agent Bridging bear the label: 
  [![image](https://user-images.githubusercontent.com/1701764/144856698-e49821ab-9c8e-4daf-99a1-23f4774c1fcd.png)](https://github.com/finos/FDC3/labels/Desktop%20Agent%20Bridging)

## Meeting Date
Wednesday 27 Sept 2023 - 9am(US eastern timezone EDT) / 2pm (London, BST)

### Zoom info
- [Join Zoom Meeting](https://zoom.us/j/96940294948?pwd=SjFibVdiN25QSWxva3FqRHY2RUFCdz09)
- Meeting ID: 969 4029 4948
- Passcode: 636931
- Dial-in:
  - [+1 929 205 6099 (New York)](tel:+19292056099) US
  - [877 853 5247](tel:8778535247) US Toll-free
  - [+44 330 088 5830](tel:+443300885830) UK
  - [0800 031 5717](tel:08000315717) UK Toll-free
  - [+33 1 8699 5831](tel:+33186995831) France
  - [0 800 940 415](tel:0800940415) France Toll-free
  - [Find your local number](https://zoom.us/u/ad2WVnBzb8) 

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies).

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.
  
- A Discussion Group has no direct decision-making power regarding the FDC3 standard - rather it is intended that anything they propose or work on will result in proposals (via Github issues and PRs) for the Standards Working Group participants to consider and vote on for inclusion in the standard.
   
## Agenda
- [x] Convene & roll call, review meeting notices (5mins)
- [x] Review action items from previous meeting (5mins)
  - #1038
- [x] FDC3 2.1 was released with Bridging included! Overview of support provided in the FDC3 NPM module.
  - <https://www.npmjs.com/package/@finos/fdc3/v/2.1.0-beta.2>
- [x] Discussion of minor issues found during implementation
  - #1050
  - #1067
  - #1074
- [x] Updates from the BackPlane project
- [x] AOB & Adjourn (5mins)

## Minutes
- Fixes applied or proposed to minor issues in the specs and docs were reviewed and approved by the meeting participants.
- A need to recruit more maintainers for the BackPlane project was expressed. @kriswest to contact some interested parties.

## Action Items
- [x] @finos/fdc3-maintainers merge outstanding docs correction #1074
- [x] @kriswest to contact parties that might be interested in helping to complete and/or adopt the BackPlane bridge implementation.

## Untracked attendees

| Full name | Affiliation | GitHub username |
|-----------|-------------|-----------------|
|           |             |                 |

**Comment by mistryvinay** [comment]
Vinay Mistry @ Symphony 🎵

**Comment by robmoffat** [comment]
Rob / FINOS 🦈

**Comment by kriswest** [comment]
Kris West / interop.io 🚀

**Comment by Vivek-NatWest** [comment]
Vivek/NatWest

**Comment by tpina** [comment]
Tiago Pina / interop.io

**Comment by robmoffat** [comment]
Alexandru Dumitru
