### ISSUE TITLE
FDC3 Identity & Threat Modelling - Discussion group

### ISSUE THREAD

**Issue by Yannick-Malins** [finos/FDC3#1078]
## Group overview

FDC3 revolves around several types of independent entities:

- Applications
- Desktop Agents
- App Directories
- Users

Each of these has an identity, and needs to know and trust the identities of several of the others in order to work seamlessly.However, at present there are few or no methods for them to validate those identities within the FDC3 Standard, meaning trust must be assumed. This comes with problems and risks : data loss, identity theft, oauth hell, or an inability to adopt interop via FDC3 - all of which are a threat to the FDC3 ecosystem’s continued growth. This complexity is multiplied by the different types of FDC3 setups now possible - desktop app interop, in-container interop, web interop, and interop between Desktop Agents (Bridging). 

Over the past few years, various [discussions](https://github.com/finos/FDC3/issues/684), [demos](https://drive.google.com/file/d/1N05MeL6IkKhOsG8SqmdVMRJEVUcJL3LK/view) and [roundtables](https://docs.google.com/presentation/d/1fGvWWohd1tji4J7lj3AqHeHNd1BF3cfF0ZarCPC6rcM/edit#slide=id.p) have addressed this topic, but the outcome each time has been “what do our users need?”.

Therefore our first objective in this stream is to dig into what these risks and problems are, before we discuss and work on potential solutions

### Relevant issue tags

https://github.com/finos/FDC3/labels/identity-security

## Meeting Date
Thursday 12 Oct 2023 - 11am (US eastern timezone EDT/EST) / 4pm (London, GMT/BST)

### Zoom info
- **[Join Zoom Meeting](https://zoom.us/j/96940294948?pwd=SjFibVdiN25QSWxva3FqRHY2RUFCdz09)**
- **Meeting ID:** 969 4029 4948
- **Passcode:** 636931
- **Dial-in:**
    | Country      | International Dial-in | Toll-free Dial-in |
    | :---        | :---        | :---        |
    | **US** | [+1 929 205 6099 (New York)](tel:+19292056099) | [877 853 5247](tel:8778535247) |
    | **UK** | [+44 330 088 5830](tel:+443300885830) | [0800 031 5717](tel:08000315717) |
    | **France** | [+33 1 8699 5831](tel:+33186995831) | [0 800 940 415](tel:0800940415) 
    | Find your local number | <https://zoom.us/u/ad2WVnBzb8> | |

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies).

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.
  
- A Discussion Group has no direct decision-making power regarding the FDC3 standard - rather it is intended that anything they propose or work on will result in proposals (via Github issues and PRs) for the Standards Working Group participants to consider and vote on for inclusion in the standard.
   
## Agenda
- [ ] Convene & roll call, review meeting notices (5mins)
- [ ] Presentation of the Working Group (5mins)
- [ ] Round-table discussion on what is expected/needed from this stream (15mins)
- [ ] AOB & Adjourn (5mins)

## Minutes
- ...

## Action Items
- [ ] ...

## Untracked attendees

| Full name | Affiliation | GitHub username |
|-----------|-------------|-----------------|
|           |             |                 |

**Comment by novavi** [comment]
Derek Novavi / S&P Global

**Comment by mistryvinay** [comment]
Vinay Mistry / Symphony 🎵

**Comment by Yannick-Malins** [comment]
Yannick Malins / Symphony

**Comment by kriswest** [comment]
Kris West / Interop.io 🚀

**Comment by hughtroeger** [comment]
Hugh Troeger / FactSet

**Comment by Yannick-Malins** [comment]
### Minutes

_Agreement to start the identity stream with "app and agent identity"_

The idea of web interop raises new questions:

- until then fdc3 assumed it was in a container, so all apps were explicitly started by the desktop agent
- now since a user can open arbitrary URLs at any time, a new webapp could “appear” in the agent - but should it be trusted? (this issue was technically possible in the container case, if the user navigates to the webapp from an existing one, but a bit of a corner case)
- in addition. apps can now start before the agent starts! so how to know if the agent itself (when it appears) can be trusted?
- these issues do exist for desktop app interop, but in that scope everyhting has to be run locally, so the risks are not the same

**It is important to note and communicate that whatever the issues we describe, FDC3 doen’t open access to arbitrary data - by design any malicious connection to an FDC3 conversation will only see the data the user is already choosing to share between apps**

Web of (dis)trust:
- App might not trust other Apps
- Agent might not trust Apps
- Apps might not trust Agent

The DA has a role in mediating identity - if it isn’t trusted, we need to find ways to pass information securely through it (e.g. app-app encryption)

One possibility is that all can agree to trust a specific App Directory? Or all app directories hosted on specific domains? Which would itself link to certificates to help the others prove their identity to each other? 

Today, multiple agent implementations have a form of app identity verification built on top of the app directory. but this isn’t in the standard. If we don’t define a standard on this rapidly, vendors will implement independent verification mechanisms, fragmenting the ecosystem.

_App Visibility_

It is possible for one app to know which other apps are running by making various FDC3 API calls to the desktop agent -  this isa core part of interop, apps need to know who they are interoperating with!

_User Identity_

Agent bridging brings a new risk - is it the same user on both sides?
Opportunities around app leveraging FDC3 to identify user (easier than implementing SSO everywhere or having many logins)
Apps could then build trust around the user?
