### ISSUE TITLE
finos_wordmark.svg should not exist in root folder

### ISSUE THREAD

**Issue by rikoe** [finos/FDC3#109]
@grizzwolf is the svg in the root folder a duplicate of the one in `website/static/img`? I don't think we should have images in the root folder...

**Comment by grizzwolf** [comment]
@rikoe yes sorry. I was trying to figure out the URL scheme for the FINOS logo in the footer to not make it an absolute URL (which is what I had to ultimately make it). The relative URL changes with the Docusaurus footer in the Home Page vs Interior (Doc) pages - so it kept breaking in the interior. I forgot to remove my instances of img/ and logo files. We have a meeting this afternoon and are discussing one more thing with all of the microsites (tag line at bottom for FINOS) - so once I get guidance on that, I'll submit 1 PR with changes for that and taking out the extra img/ folders and files.

**Comment by rikoe** [comment]
Bump @grizzwolf

**Comment by rikoe** [comment]
@grizzwolf @maoo @mcleo-d can we get a PR for this one please?

**Comment by mcleo-d** [comment]
@rikoe - #204 has been raised to resolve this issue 👍
