### ISSUE TITLE
FDC3 Identity & Threat Modelling - 9 Nov 2023

### ISSUE THREAD

**Issue by Yannick-Malins** [finos/FDC3#1101]
## Group overview

FDC3 revolves around several types of independent entities:

- Applications
- Desktop Agents
- App Directories
- Users

Each of these has an identity, and needs to know and trust the identities of several of the others in order to work seamlessly.However, at present there are few or no methods for them to validate those identities within the FDC3 Standard, meaning trust must be assumed. This comes with problems and risks : data loss, identity theft, oauth hell, or an inability to adopt interop via FDC3 - all of which are a threat to the FDC3 ecosystem’s continued growth. This complexity is multiplied by the different types of FDC3 setups now possible - desktop app interop, in-container interop, web interop, and interop between Desktop Agents (Bridging). 

Over the past few years, various [discussions](https://github.com/finos/FDC3/issues/684), [demos](https://drive.google.com/file/d/1N05MeL6IkKhOsG8SqmdVMRJEVUcJL3LK/view) and [roundtables](https://docs.google.com/presentation/d/1fGvWWohd1tji4J7lj3AqHeHNd1BF3cfF0ZarCPC6rcM/edit#slide=id.p) have addressed this topic, but the outcome each time has been “what do our users need?”.

Therefore our first objective in this stream is to dig into what these risks and problems are, before we discuss and work on potential solutions

### Relevant issue tags

https://github.com/finos/FDC3/labels/identity-security

## Meeting Date
Thursday 9 Nov 2023 - 11am (US eastern timezone EDT/EST) / 4pm (London, GMT/BST)

### Zoom info
- **[Join Zoom Meeting](https://zoom.us/j/96940294948?pwd=SjFibVdiN25QSWxva3FqRHY2RUFCdz09)**
- **Meeting ID:** 969 4029 4948
- **Passcode:** 636931
- **Dial-in:**
    | Country      | International Dial-in | Toll-free Dial-in |
    | :---        | :---        | :---        |
    | **US** | [+1 929 205 6099 (New York)](tel:+19292056099) | [877 853 5247](tel:8778535247) |
    | **UK** | [+44 330 088 5830](tel:+443300885830) | [0800 031 5717](tel:08000315717) |
    | **France** | [+33 1 8699 5831](tel:+33186995831) | [0 800 940 415](tel:0800940415) 
    | Find your local number | <https://zoom.us/u/ad2WVnBzb8> | |

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies).

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.
  
- A Discussion Group has no direct decision-making power regarding the FDC3 standard - rather it is intended that anything they propose or work on will result in proposals (via Github issues and PRs) for the Standards Working Group participants to consider and vote on for inclusion in the standard.
   
## Agenda
- [ ] Convene & roll call, review meeting notices (5mins)
- [ ] Recap of the previous session (5mins)
- [ ] Discussion of requirements around user identity (15mins)
- [ ] AOB & Adjourn (5mins)

## Minutes
- ...

## Action Items
- [ ] ...

## Untracked attendees

| Full name | Affiliation | GitHub username |
|-----------|-------------|-----------------|
|           |             |                 |

**Comment by Yannick-Malins** [comment]
After a[first session](https://github.com/finos/FDC3/issues/1078) focused mainly on application and agent identity, this second session will focus on user identity

**Comment by bingenito** [comment]
Brian Ingenito / Morgan Stanley

**Comment by mattjamieson** [comment]
Matt Jamieson / WhiteDog

**Comment by kriswest** [comment]
Kris West / Interop.io 🚀

**Comment by robmoffat** [comment]
Rob / FINOS 🐟

**Comment by hughtroeger** [comment]
Hugh Troeger / FactSet

**Comment by paulgoldsmith** [comment]
Paul Goldsmith / Morgan Stanley

**Comment by kriswest** [comment]
Need minutes before closing - perhaps worth trying an AI summarize on recording/transcript?

**Comment by bingenito** [comment]
@kriswest This might have to be an update to agreements and reviewed by participants Legal teams.  There is currently an assumption that the recordings are private and only for internal use, sending that to a service for summary might require notification and sign-off from all participants.
