### ISSUE TITLE
Bridging: PrivateChannel event contextTypes should be nullable in JSON

### ISSUE THREAD

**Issue by robmoffat** [finos/FDC3#1109]
In: https://fdc3.finos.org/assets/files/privateChannelOnUnsubscribeAgentRequest.schema-e934cc3a435cc7bf3f4857e487164cd7.json

the payload of the contextType can't be null.  But it should be allowed if you register a context listener that listens to all types.

**Comment by kriswest** [comment]
I see what you mean @robmoffat. You could of course use the string "null" here. I'll check what we've done and report back.

N.b. The same applies to the onAddContextListener event schema: https://fdc3.finos.org/assets/files/privateChannelOnAddContextListenerAgentRequest.schema-9bb3e8310df87de3110b728f68b27745.json
