### ISSUE TITLE
Standard WG Meeting - November 30th, 2023

### ISSUE THREAD

**Issue by kriswest** [finos/FDC3#1114]
## Date
Thursday 30 Nov 2023 - 10am (US eastern timezone EST) / 3pm (London, GMT)

### Zoom info
- **[Join Zoom Meeting](https://zoom.us/j/96940294948?pwd=SjFibVdiN25QSWxva3FqRHY2RUFCdz09)**
- **Meeting ID:** 969 4029 4948
- **Passcode:** 636931
- **Dial-in:**
    | Country      | International Dial-in | Toll-free Dial-in |
    | :---        | :---        | :---        |
    | **US** | [+1 929 205 6099 (New York)](tel:+19292056099) | [877 853 5247](tel:8778535247) |
    | **UK** | [+44 330 088 5830](tel:+443300885830) | [0800 031 5717](tel:08000315717) |
    | **France** | [+33 1 8699 5831](tel:+33186995831) | [0 800 940 415](tel:0800940415) 
    | Find your local number | <https://zoom.us/u/ad2WVnBzb8> | |

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies).

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call, review meeting notices (5mins)
- [x] Updating participant CLAs for the Community Spec License (required for meeting participation in future) (5mins)
   - [View the CSL](https://raw.githubusercontent.com/finos/FDC3/master/LICENSE)
   - [View the GOVERNANCE of the Project](https://github.com/finos/FDC3/blob/master/GOVERNANCE.md)
   - [Click here to raise a PR](https://github.com/finos/FDC3/edit/master/NOTICES.md)
   - [Click here to send email to become a voting participant on the FDC3 Project](mailto:fdc3-participants+subscribe@finos.org?subject=Please%20enroll%20me%20as%20an%20FDC3%20Standards%20Participant&amp;body=HI%2C%20my%20name%20is%20%3CFirstName%20LastName%3E%20and%20I'd%20like%20to%20formally%20participate%20to%20the%20FDC3%20standard%20process.%20I%20plan%20to%20contribute%20as%20%3Cindividual%7Con%20behalf%20of%20organizationName%3E%20and%20I%20have%20reviewed%20the%20policies%20described%20at%20https%3A%2F%2Fgithub.com%2Ffinos%2FFDC3%2Fblob%2Fmaster%2FGOVERNANCE.md%20and%20read%20the%20license%20at%20https%3A%2F%2Fgithub.com%2Ffinos%2FFDC3%2Fblob%2Fmaster%2FLICENSE%20.%20Thank%20you!")
- [x] Review action items from previous meeting (5mins)
  - #1076 
- [x] #990 (15mins)
  - #931
  - Contribution submitted and being considered by the FINOS TSC: https://github.com/finos/community/issues/297
  - Proposal of @bingenito as an FDC3 maintainer
- [x] #1105 (10mins)
  - #1102  
- [x] #1107 (5mins)
- [ ] FDC3 maintenance & contribution opportunities (10mins)
  - Recent and pending updates the FDC3 NPM Module
    - Switch to string constants for bridging and context type fields: https://github.com/finos/FDC3/commit/9ab8f9d2dc1dea90eac5ee20d83d03edcf4f9e02
    - Feedback needed to remove beta label
  - FDC3 maintenance tasks (mostly software and docs) and recruiting contributors
    - Work is underway to replace the build system for the NPM module (tsdx -> Vite library mode)
    - Update npm-build action and other github actions to later version of node #1072
    - Update Use Cases #1096
      FDC3 homepage needs to do a better job of explaining what FDC3 is trying to achieve and then link you to technical use cases for more detail
    - Add details of the FDC3 conformance testing program to the compliance page #1077
    - Update workbench for 2.1 #1103
    - Replace existing Context pages with JSON schema definitions #1068
      - The next step in revising Context & Intents governance
  - Recruiting participants for the Identity & threat modelling discussion group
    - Several different entities  each with their own identity (Multiple apps, Desktop Agents, Users, App Directories) - several are not validated by the current API design
    - Interesting summary of issues faced by firms looking to provide execution tools through FDC3
      - Proposed different levels of identity validation
  - FDC3 for Web Browsers progress
- [ ] What else does FDC3 need to address? (5mins) 
- Adjourn

## Minutes
- Updating participant CLAs for the Community Spec License
  - An active CLA is required for meeting participation (as FDC3/FINOS considers meeting participation to constitute contribution)
  - @kriswest demonstrated how to check your CLA by opening a a dummy PR and requested all participants do so during the meeting - where a CLA for the new license is not present EasyCLA can then be used to sign a new one.
  - Meeting templates will be updated with information on this - and we'll cover it again at the next meeting in January
- #990 and #931
  - Details were provided on how to review the proposed signatures and contribution issue and how it is proposed that governance will work (as a part of the FDC3 project itself, rather than a separate project)
    - There was consensus at the meeting that this was the right approach and should be used for these signature and others proposed for adoption.
    - Work is already underway (and ennearly complete according to @bingenito) on adding .NET signatures to the FDC3 documentation - when avaialble these will help enable further review
  - @kriswest, on behalf of the FDC3 maintainers, proposed @bingenito as an FDC3 maintainer (to support the .NET signatures, alongside a number of colleagues from his firm that will wor as contributors) and requested the SWG's consent, which was given.
- #1105
  - @bingenito & @kriswest discussed why union types are a problem for FDC3 implementations written in languages other than TypeScript and JSON Schema:
    - Its a type of polymorphism that is hard (or impossible, where unions with primitive types are used) to emulate in other languages.
    - It can sometimes be solved in API signatures via function/method overloads - but these can add both cognitive and code complexity or marker interfaces (an interface thats added to multiple classes, just so it can be used as a type)
  - There was consensus at the meeting that FDC3 must avoid such constructs whereever possible if its to be implemented in multiple languages
  - There was consensus that PR #1102 should go ahead and make a retrospective change to FDC3 2.1 to remove the union type that fdc3.chat.message contains 
- #1107
  - @openfin-johans & @kriswest described the issue: FDC3 2.0 had (what the authors consider) an error in it. It was intended that Intent handler be able to return void and that intentResolution.getResult() resolve to void. However, as written in the standard docs, an error would have to be thrown (as the `IntentResult` type does not include `void`). This was corrected in FDC3 2.1 and was implemented in the FDC3 2.0 conformance tests such that a void result is expected - hence, all FDC3 Desktop Agents that have been tested for 2.0 conformance (3) already use this approach. The proposal is to make a retropsective change to 2.0 to apply that correction.
    - There were no strong objections to doing so at the meeting. It was resolved to move this to a concrete PR and then re-check consensus on making the change.
- @kriswest provided a brief overview of changes to the FDC3 NPM module (2.1.0-beta.4) and work underway to update its build (to be completed before the beta label is removed).
  - Feedback is desired from the community on the new module, which can be used with existing 2.0 Desktop Agent implementations.

## Action Items
- [x] All meeting participants: raise a dummy PR (as demosntrated in the meeting) to check your CLA status - for most this will show 'not authorized' due to the FDC3 license update, click to be authorized and then follow the instructions to sign (or have your firm sign) the new CLA.
- [x] @fdc3-maintainers review and merge #1102
- [ ] ALL test the FDC3 NPM module 2.1.0-beta.4 and report back on any issues - its should be compatible with all apps using the 2.0.x modules
- [x] @kriswest Implement a PR to resolve #1107

## Untracked attendees

| Full name | Affiliation | GitHub username |
|-----------|-------------|-----------------|
|           |             |                 |

**Comment by psmulovics** [comment]
Peter Smulovics / Morgan Stanley

**Comment by kriswest** [comment]
Kris West / interop.io

**Comment by smocarski** [comment]
Steven Mocarski / OpenFIn

**Comment by lspiro-Tick42** [comment]
Leslie Spiro / Interop.io

**Comment by paulgoldsmith** [comment]
Paul Goldsmith / Morgan Stanley

**Comment by mattjamieson** [comment]
Matt Jamieson / WhiteDog
