### ISSUE TITLE
New intent from UseCase 9: 'storeDictation'?

### ISSUE THREAD

**Issue by tschady** [finos/FDC3#113]
## Feature Request

First, How do you want to receive these new intent ideas based on the UseCase working group's efforts?  I thought I'd give a stab at an Issue, but we're happy to work however you'd like.

### Description of Problem:

Use Case 9: https://github.com/FDC3/FDC3/blob/master/docs/use-cases/009-call-transcription-to-crm.md needs new intent and context for storing audio transcripts into a CRM.

### Potential Solutions:

verb ideas:  store/save/log?
noun ideas: AudioTranscript, Dictation

e.g. "storeAudioTranscription", "logDictation"

The context would need a payload of text to store, and which Customer in the CRM to store them under.

**Comment by rikoe** [comment]
@tschady I don't understand why you would do audio description via desktop interoperability. Could you please elaborate? I would imagine that for security reasons audio transcriptions would always go to a back-end system with proper security and the ability to pull in other back-end services required for transcription.

I.e. FDC3 is intended for interoperability on the desktop, and I would imagine that the handoffs mentioned in the use case (e.g. to transcription service, CRM system) would go via server URLs.

**Comment by rikoe** [comment]
@tschady can we close this one?

**Comment by tschady** [comment]
@rikoe yes, riko, at least until I think it through better.
