### ISSUE TITLE
Desktop Agent Bridging Discussion group 24th Jan 2024

### ISSUE THREAD

**Issue by kriswest** [finos/FDC3#1145]
## Group overview
Discussion group devoted to 'bridging' between FDC3 implementations (aka Desktop Agents), allowing applications running on one Desktop Agent to integrate with FDC3 applications running on additional Desktop Agents and devices for the same user.

Desktop Agent Bridging was added to FDC3 in the 2.1 release as an [@experimental](https://fdc3.finos.org/docs/fdc3-compliance#experimental-features) 5th-Part to the Standard. The group is now dedicated to the discussion of implementations, Q&A on the protocol, and working to improve the protocol further.

### Relevant issue tags
Issues that relate to Desktop Agent Bridging bear the label: 
  [![image](https://user-images.githubusercontent.com/1701764/144856698-e49821ab-9c8e-4daf-99a1-23f4774c1fcd.png)](https://github.com/finos/FDC3/labels/Desktop%20Agent%20Bridging)

## Meeting Date
Wednesday 24 Jan 2024 - 9am (US eastern timezone EDT/EST) / 2pm (London, GMT/BST)

### Zoom info
- **[Join Zoom Meeting](https://zoom.us/j/96940294948?pwd=SjFibVdiN25QSWxva3FqRHY2RUFCdz09)**
- **Meeting ID:** 969 4029 4948
- **Passcode:** 636931
- **Dial-in:**
    | Country      | International Dial-in | Toll-free Dial-in |
    | :---        | :---        | :---        |
    | **US** | [+1 929 205 6099 (New York)](tel:+19292056099) | [877 853 5247](tel:8778535247) |
    | **UK** | [+44 330 088 5830](tel:+443300885830) | [0800 031 5717](tel:08000315717) |
    | **France** | [+33 1 8699 5831](tel:+33186995831) | [0 800 940 415](tel:0800940415) 
    | Find your local number | <https://zoom.us/u/ad2WVnBzb8> | |

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies).

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.
  
- A Discussion Group has no direct decision-making power regarding the FDC3 standard - rather it is intended that anything they propose or work on will result in proposals (via Github issues and PRs) for the Standards Working Group participants to consider and vote on for inclusion in the standard.

## Participation Requirements

**Note:** Meeting participants are expected to accept the terms of the FDC3 license (Community Specification License), understand the governance process and have a CLA in place.  

Please click the following links at the start of the meeting if you have not done so previously.

 - [View the CSL](https://raw.githubusercontent.com/finos/FDC3/master/LICENSE.md)
 - [View the GOVERNANCE of the Project](https://github.com/finos/FDC3/blob/master/GOVERNANCE.md)
 - [Click here to start a PR](https://github.com/finos/FDC3/edit/master/NOTICES.md). 
   - Edit the page to add your details.
   - Hit the save button.
   - Click "Create Pull Request".
   - Click "Accept" on the EasyCLA dialog in the PR's discussion section.
 - [Click here to send email to become a voting participant on the FDC3 Project](mailto:fdc3-participants+subscribe@finos.org?subject=Please%20enroll%20me%20as%20an%20FDC3%20Standards%20Participant&amp;body=HI%2C%20my%20name%20is%20%3CFirstName%20LastName%3E%20and%20I'd%20like%20to%20formally%20participate%20to%20the%20FDC3%20standard%20process.%20I%20plan%20to%20contribute%20as%20%3Cindividual%7Con%20behalf%20of%20organizationName%3E%20and%20I%20have%20reviewed%20the%20policies%20described%20at%20https%3A%2F%2Fgithub.com%2Ffinos%2FFDC3%2Fblob%2Fmaster%2FGOVERNANCE.md%20and%20read%20the%20license%20at%20https%3A%2F%2Fgithub.com%2Ffinos%2FFDC3%2Fblob%2Fmaster%2FLICENSE%20.%20Thank%20you!")

## Tracking Attendance

**Note:** Meeting participants are expected to _add a comment to this GitHub issue_ in order that we can track attendance of FDC3 project meetings.  Please do this at the start of the meeting.
   
## Agenda
- [x] Convene & roll call, review meeting notices (5mins)
- [x] Review action items from previous meeting (5mins)
  - #1110 
- [ ] Updates from and discussion of the Backplane project, and interactions with the fdc3-dotnet project.
  - Suggested topics
    - Publishing Bridging message interfaces for C#
    - Nuget releases
    - Is it possible to implement cross-repo workflows so that changes in the FDC3 repo's schema files can trigger builds and releases in the BackPlane repo or the proposed .NET FDC3 bindings project?
    - Release process
- [ ] AOB & Adjourn (5mins)

## Minutes
- The publishing of bridging interfaces/types defining bridging message formats for C# was discussed
  - There was consensus that this should be done from the fdc3-dotnet project (as a Standards project), from where they can be imported into the BackPlane project (an implementation project), along with types/interfaces for the Desktop Agent API (which are used to implement the .NET DesktopAgent client provided by the BackPlane project).
  - The C#bridging types/interfaces may be generated via quicktype - in a similar fashion to how they are generated for TypeScript, from the JSON Schema files.
    - The schemas are identified by URL and it should be possible to retrieve them remotely via URL from the fdc3-dotnet project on build.
- Overlapping needs for reviewers and contributors with .NET skillsets on both the BackPlane and fdc3-dotnet projects was discussed.
  - An exchange was proposed, where participants from each project would be appointed as maintaners/reviewers on the other project (no need to appoint as FDC3 maintainers as this is primarily to cover software changes, rather than standard changes).
  - An additional offer of support to the fdc3-dotnet project was also received.
- Enabling the use of a remotely hosted bridge vs. the clustering approach (via SignalR) used in Backplane was discussed.
  - Bridging was designed to support remote bridges and is entirely compatible with it. 
  - However, the initial version adopted was limited to the use of localhost to mitigate underdeveloped Identity and authentication features in FDC3. 
  - The Identity and Threat Modelling group is attempting to address these issues currently
- The current state of the BacklPlane project was discussed
  - Many of the workflows currently in use are not according to the standard and work is still needed to fully implement the specification. Additional contributors are sought.
  - Moving away from SignalR or working out how to address the the underlying socket is necessary
  - A remote bridge would not need to use SignalR - however, logic needs to be implemented to support each workflow and such an implementation should be reuable (in a remote bridge implementation)
- Testing of bridge implementations was discussed
  - @kriswest offered to look into contributing a set of tests for a Desktop Agent bridge and to demonstrate those at the next meeting - as there was consensus that the existence of OS tests would simplify the (accurate) implementation of bridges, in including backplane.

## Action Items
- [x] @kriswest Email help@finos.org regarding (software) maintainer appointments on the BackPlane and fdc3-dotnet projects and the setup of a finos lab repo to house DAB tests.
- [x] @kriswest Add a demo of bridging tests proposed for contribution to the next meeting
- [ ] @robmoffat Arrange a meeting with @maoo, @bingenito and @Vivek-NatWest to discuss action items relating to releases etc. - action items rolled over from our last meeting - please work with Brian and Vivek to complete:
   - [ ] @maoo @robmoffat to review BackPlane's release process and the NWM release bot (which should likely be a FINOS owned bot) and advise on what they would like to happen (see minutes from https://github.com/finos/FDC3/issues/1110).
   - [ ] @maoo @robmoffat @kriswest to discuss Nuget releases for FDC3 (both bridging and standard .NET) and whether these can be triggered cross-repo

## Untracked attendees

| Full name | Affiliation | GitHub username |
|-----------|-------------|-----------------|
|           |             |                 |

**Comment by robmoffat** [comment]
Rob / FINOS 🇺🇸

**Comment by mimiflynn** [comment]
Mimi Flynn / Morgan Stanley

**Comment by gilesstevenson** [comment]
Giles Stevenson / OpenFin

**Comment by kriswest** [comment]
Kris West / interop.io 🚀

**Comment by aateeque** [comment]
Asad Ateeque / NatWest

**Comment by tomhealey-icma** [comment]
Tom Healey/ICMA
