### ISSUE TITLE
The FINOS FDC3 AppDirectory JSON does not conform to the standard

### ISSUE THREAD

**Issue by ztanczos** [finos/FDC3#1148]
## Minor Issue
The FDC3 [AppDirectory JSON](https://directory.fdc3.finos.org/v2/apps/) hosted on finos.org does not conform to the AppDirectory specification: for the "symphony" entry the interop.intents.raises contains objects instead of an array of strings.

### Area of Issue
[x] App Directory
[x] API
[ ] Context Data
[ ] Intents
[ ] Desktop Agent Bridging
[ ] Use Cases
[ ] Other

### Issue Description: 
The JSON contains:
```
...
	"interop":{
		"intents":{
			"listensFor":{
				"SendChatMessage":{
					"contexts":["fdc3.chat.message"],
					"displayName":"Send Chat Message"
				},
				"StartChat":{
					"contexts":["fdc3.chat.initSettings","fdc3.contact"],
					"displayName":"Start Chat"
				},
				"ViewMessages":{
					"contexts":["fdc3.searchCriteria"],
					"displayName":"View Messages"
				}
			},
			"raises":{
				"CreateInteraction":{
					"contexts":["fdc3.interaction"],
					"displayName":"Create Interaction"
				},
...
```

but the specification expects an array of simple strings, e.g.: 
```
"interop": {
	"intents": {
		"listensFor": {},
		"raises": {
			"ViewOrders": [
				"fdc3.instrument",
				"fdc3.organization"
			],
			"StartEmail": [
				"fdc3.email"
			]
		}
	},
}
```

**Comment by kriswest** [comment]
Many thanks for reporting @ztanczos 
Assigned to @robmoffat who maintains the FINOS app directory.

**Comment by robmoffat** [comment]
How's this: https://github.com/finos-labs/FDC3-App-Directory/blob/main/_apps/symphony.json

**Comment by kriswest** [comment]
Looks good to me @robmoffat. I don't see any similar errors in the rest of the definitions, hence I think this can be closed.
