### ISSUE TITLE
Result Type Not present in Schema

### ISSUE THREAD

**Issue by robmoffat** [finos/FDC3#1153]
## Minor Issue

Find iNtent looks like this:

> `findIntent(intent: string, context?: Context, resultType?: string): Promise<AppIntent>;`

The schema is this:

https://fdc3.finos.org/assets/files/findIntentAgentRequest.schema-7dbdbd5cb3906249560adb32423643d6.json

Relevant part:
```
 "payload": {
          "title": "FindIntent Request Payload",
          "type": "object",
          "properties": {
            "intent": {
              "title": "Intent name",
              "type": "string"
            },
            "context": {
              "title": "Context argument",
              "$ref": "../context/context.schema.json"
            }
          },
          "required": ["intent"],
          "additionalProperties": false
        },
```

There's no place for `resultType`

Is this a bug?

**Comment by kriswest** [comment]
Correct, thats an omission from the schema and needs fixing.
