### ISSUE TITLE
Desktop Agent Bridging Discussion group 28th Feb 2024

### ISSUE THREAD

**Issue by kriswest** [finos/FDC3#1166]
## Group overview
Discussion group devoted to 'bridging' between FDC3 implementations (aka Desktop Agents), allowing applications running on one Desktop Agent to integrate with FDC3 applications running on additional Desktop Agents and devices for the same user.

Desktop Agent Bridging was added to FDC3 in the 2.1 release as an [@experimental](https://fdc3.finos.org/docs/fdc3-compliance#experimental-features) 5th-Part to the Standard. The group is now dedicated to the discussion of implementations, Q&A on the protocol, and working to improve the protocol further.

### Relevant issue tags
Issues that relate to Desktop Agent Bridging bear the label: 
  [![image](https://user-images.githubusercontent.com/1701764/144856698-e49821ab-9c8e-4daf-99a1-23f4774c1fcd.png)](https://github.com/finos/FDC3/labels/Desktop%20Agent%20Bridging)

## Meeting Date
Wednesday 28th Feb 2024 - 9am (US eastern timezone EDT/EST) / 2pm (London, GMT/BST)

### Zoom info
- **[Join Zoom Meeting](https://zoom.us/j/96940294948?pwd=SjFibVdiN25QSWxva3FqRHY2RUFCdz09)**
- **Meeting ID:** 969 4029 4948
- **Passcode:** 636931
- **Dial-in:**
    | Country      | International Dial-in | Toll-free Dial-in |
    | :---        | :---        | :---        |
    | **US** | [+1 929 205 6099 (New York)](tel:+19292056099) | [877 853 5247](tel:8778535247) |
    | **UK** | [+44 330 088 5830](tel:+443300885830) | [0800 031 5717](tel:08000315717) |
    | **France** | [+33 1 8699 5831](tel:+33186995831) | [0 800 940 415](tel:0800940415) 
    | Find your local number | <https://zoom.us/u/ad2WVnBzb8> | |

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies).

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.
  
- A Discussion Group has no direct decision-making power regarding the FDC3 standard - rather it is intended that anything they propose or work on will result in proposals (via Github issues and PRs) for the Standards Working Group participants to consider and vote on for inclusion in the standard.

## Participation Requirements

**Note:** Meeting participants are expected to accept the terms of the FDC3 license (Community Specification License), understand the governance process and have a CLA in place.  

Please click the following links at the start of the meeting if you have not done so previously.

 - [View the CSL](https://raw.githubusercontent.com/finos/FDC3/master/LICENSE.md)
 - [View the GOVERNANCE of the Project](https://github.com/finos/FDC3/blob/master/GOVERNANCE.md)
 - [Click here to start a PR](https://github.com/finos/FDC3/edit/master/NOTICES.md). 
   - Edit the page to add your details.
   - Hit the save button.
   - Click "Create Pull Request".
   - Click "Accept" on the EasyCLA dialog in the PR's discussion section.
 - [Click here to send email to become a voting participant on the FDC3 Project](mailto:fdc3-participants+subscribe@finos.org?subject=Please%20enroll%20me%20as%20an%20FDC3%20Standards%20Participant&amp;body=HI%2C%20my%20name%20is%20%3CFirstName%20LastName%3E%20and%20I'd%20like%20to%20formally%20participate%20to%20the%20FDC3%20standard%20process.%20I%20plan%20to%20contribute%20as%20%3Cindividual%7Con%20behalf%20of%20organizationName%3E%20and%20I%20have%20reviewed%20the%20policies%20described%20at%20https%3A%2F%2Fgithub.com%2Ffinos%2FFDC3%2Fblob%2Fmaster%2FGOVERNANCE.md%20and%20read%20the%20license%20at%20https%3A%2F%2Fgithub.com%2Ffinos%2FFDC3%2Fblob%2Fmaster%2FLICENSE%20.%20Thank%20you!")

## Tracking Attendance

**Note:** Meeting participants are expected to _add a comment to this GitHub issue_ in order that we can track attendance of FDC3 project meetings.  Please do this at the start of the meeting.
   
## Agenda
- [x] Convene & roll call, review meeting notices (5mins)
- [x] Review action items from previous meeting (5mins)
  - #1145 
- [x] Revisit BackPlane's release process and the NWM release bot
- [x] Testing Bridge implementations
- [x] #1165
- [ ] Building language adaptors via bridging @robmoffat 
- [ ] AOB (5mins)
- Adjourn

N.B. @bingenito sends apologies for absence for this meeting and will raise the topic of federated/online bridges for a subsequent meeting 

## Minutes
- Revisit BackPlane's release process and the NWM release bot
  - There is a partially automated release process already in place via the [semantic release](https://github.com/semantic-release/semantic-release)
    > semantic-release automates the whole package release workflow including: determining the next version number, generating the release notes, and publishing the package.
    - There is a desire to move this (and the associated both account?) to FINOS
    - Vivek to raise an issue for the migration in the BackPlane project's repo
- @kriswest provided an overview of tests written at interop.io to confirm correct operation or a DA Bridge (which is then used to test correct interactions with a Bridge by a Desktop Agent). 
  - @Vivek-NatWest confirmed that access to this test implementation would help to further the BackPlane integration (which could switch to test-driven development if tests exist).
  - A FINOS labs repo would probably be the simplest place to contribute to... @kriswest to request one
  - A small amount of work in the test server implementation will be needed to allow the bridge to be started and stopped
  - A light refactor of private channel tests is also neededto remove the need for access to the bridge's internal state in those tests.
- #1165
  - Closed after clarification of the original design decisions
    - State synchronisation must be done on either joining the bridge or joining a channel
    - If done on joining a channel this introduces delays and introduces greater complexity more state synchronisation events. There are also small races possible during state synchronisation and its better to deal with them on connection only, rather than every time an app or DA joins a channel for the first time.)
- Building language adaptors via bridging @robmoffat
  - We briefly discussed what was being tested in the FDC3 for the Web project, where bridging messages are being used (temporarily), to encode messages between app and DA.
  - Rob proposes to build language adaptors allowing .NET, Java, Python etc. to integrate with a DA - although this would be over a bridge?  
  - Pick up that discussion at the next meeting

## Action Items
- [x] @Vivek-NatWest to raise an issue for release bot migration in BackPlane repo / @robmoffat @maoo Revisit discussion of BackPlane's release process and the NWM release bot
- [x] @kriswest contact help@finos.org to request a finos labs repo - after getting permission to contribute the tests.
- [x] @kriswest Resume discussion of language adaptors at our next meeting

## Untracked attendees

| Full name | Affiliation | GitHub username |
|-----------|-------------|-----------------|
|           |             |                 |

**Comment by robmoffat** [comment]
Rob / FINOS 🍎

**Comment by Vivek-NatWest** [comment]
Vivek/ NatWest

**Comment by kriswest** [comment]
Kris West / interop.io 🚀

**Comment by gilesstevenson** [comment]
Giles / OpenFin

**Comment by Lecss** [comment]
Alex Dumitru / Citi

**Comment by john-ciq** [comment]
John Ghidiu / interop.io

**Comment by hughtroeger** [comment]
Hugh Troeger / FactSet
