### ISSUE TITLE
Use Cases and Workflows Discussion Group - 4th April 2024

### ISSUE THREAD

**Issue by mistryvinay** [finos/FDC3#1180]
## Group overview
Newly rebranded "Use Cases and Workflows" discussion group for FDC3, replacing "Context Data and Intents".

The remit of this discussion group is:  
 - talking about existing or potential financial use-cases
 - unlocking the power of standardisation
 - discussing new ways to collaborate either inside the organisation or firm-to-firm
 - sharing expert insights about how to make the most out of FDC3
 - and collaborating to shaping the future of financial workflows.

### Relevant issue tags
Current open issues that relate to the discussion group: 
[![image](https://github.com/finos/FDC3/assets/1701764/e98dc33e-e35e-4f23-88b4-31c9e4496b59)](https://github.com/finos/FDC3/issues?q=is%3Aissue+is%3Aopen+label%3A%22Use+cases%22)

Specific issues will also be tagged with the labels:
[![image](https://user-images.githubusercontent.com/1701764/139841631-c6bf8697-fafe-4266-8552-63a648625e8b.png)](https://github.com/finos/FDC3/labels/context-data)
[![image](https://user-images.githubusercontent.com/1701764/139841690-969a9d14-a0aa-44a7-bdfe-8c4a43ad30d9.png)](https://github.com/finos/FDC3/labels/intents)

## Meeting Date
Thursday 4 Apr 2024 - 9am (US eastern timezone EST) / 2pm (London, BST)

### Zoom info
- **[Join Zoom Meeting](https://zoom.us/j/96940294948?pwd=SjFibVdiN25QSWxva3FqRHY2RUFCdz09)**
- **Meeting ID:** 969 4029 4948
- **Passcode:** 636931
- **Dial-in:**
    | Country      | International Dial-in | Toll-free Dial-in |
    | :---        | :---        | :---        |
    | **US** | [+1 929 205 6099 (New York)](tel:+19292056099) | [877 853 5247](tel:8778535247) |
    | **UK** | [+44 330 088 5830](tel:+443300885830) | [0800 031 5717](tel:08000315717) |
    | **France** | [+33 1 8699 5831](tel:+33186995831) | [0 800 940 415](tel:0800940415) 
    | Find your local number | <https://zoom.us/u/ad2WVnBzb8> | |

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies).

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.
  
- A Discussion Group has no direct decision-making power regarding the FDC3 standard - rather it is intended that anything they propose or work on will result in proposals (via Github issues and PRs) for the Standards Working Group participants to consider and vote on for inclusion in the standard.

## Participation Requirements

**Note:** Meeting participants are expected to accept the terms of the FDC3 license (Community Specification License), understand the governance process and have a CLA in place.  

Please click the following links at the start of the meeting if you have not done so previously.

 - [View the CSL](https://raw.githubusercontent.com/finos/FDC3/master/LICENSE.md)
 - [View the GOVERNANCE of the Project](https://github.com/finos/FDC3/blob/master/GOVERNANCE.md)
 - [Click here to start a PR](https://github.com/finos/FDC3/edit/master/NOTICES.md). 
   - Edit the page to add your details.
   - Hit the save button.
   - Click "Create Pull Request".
   - Click "Accept" on the EasyCLA dialog in the PR's discussion section.
 - [Click here to send email to become a voting participant on the FDC3 Project](mailto:fdc3-participants+subscribe@finos.org?subject=Please%20enroll%20me%20as%20an%20FDC3%20Standards%20Participant&amp;body=HI%2C%20my%20name%20is%20%3CFirstName%20LastName%3E%20and%20I'd%20like%20to%20formally%20participate%20to%20the%20FDC3%20standard%20process.%20I%20plan%20to%20contribute%20as%20%3Cindividual%7Con%20behalf%20of%20organizationName%3E%20and%20I%20have%20reviewed%20the%20policies%20described%20at%20https%3A%2F%2Fgithub.com%2Ffinos%2FFDC3%2Fblob%2Fmaster%2FGOVERNANCE.md%20and%20read%20the%20license%20at%20https%3A%2F%2Fgithub.com%2Ffinos%2FFDC3%2Fblob%2Fmaster%2FLICENSE%20.%20Thank%20you!")

## Tracking Attendance

**Note:** Meeting participants are expected to _add a comment to this GitHub issue_ in order that we can track attendance of FDC3 project meetings.  Please do this at the start of the meeting.
   
## Agenda
- [x] Convene & roll call, review meeting notices (5mins)
- [x] Review action items from previous meeting (5mins)
  - [x] #1168 
- [x] Discussion of open issues (40mins)
  - [ ] #1164 
  - [x] #1173 
    - [x] #1183 
- [x] AOB & Adjourn (5mins)

## Minutes
- #1173 
  - Walkthrough of end-user personas identified in pervious meeting. 
- #1183 
  - Review of contribution from @Lecss grouping trading activities across Pre-Trade, Trade Execution and Post Trade.
  - @kriswest suggested breaking down this list and investigating further.  The spreadsheet can be [found here](https://docs.google.com/spreadsheets/d/1b506f6v2TFlKHlkhry4CMa1pbMOAP3-biwJJr9gwYAU/edit?usp=sharing).
    - Is it a Context linking use case or is it an Intent use case typically?
    - What Intent would you use? What's the natural Context?
    - By running through the above we can quickly identify where the gaps are.
    - FDC3 naming convention makes it very easy to come up with new Intents. We can create a list of proposed Intents.
    - Output of this exercise would be a series of PR's to add a whole set of capabilities for a future standard release.
    - **Fantastic input from the community in building out the spreadsheet!**  Seeking input from the community on proposals listed in the [spreadsheet](https://docs.google.com/spreadsheets/d/1b506f6v2TFlKHlkhry4CMa1pbMOAP3-biwJJr9gwYAU/edit?usp=sharing).

## Action Items
- [ ] Review end-user personas who would/could be FDC3 users.  #1173 
  - Do we need to add any additional ones?
- [ ] Choose an end-user persona from #1173
  - Provide a summary/list of tasks and actions that are conducted.
  - From a birds-eye-view what are their day to day activities/workflows. 

## Untracked attendees

| Full name | Affiliation | GitHub username |
|-----------|-------------|-----------------|
|           |             |                 |

**Comment by robmoffat** [comment]
Rob Moffat / FINOS 🏎️

**Comment by mistryvinay** [comment]
Vinay Mistry / Symphony 🎵

**Comment by Lecss** [comment]
Alex Dumitru / Citi

**Comment by openfin-johans** [comment]
Johan Sandersson / OpenFin 🎁

**Comment by kriswest** [comment]
Kris West / interop.io 🚀

**Comment by Vivek-NatWest** [comment]
Vivek/ NatWest

**Comment by mthomcfa** [comment]
Michael Thom / CFA Societies Canada
