### ISSUE TITLE
General Meeting - May 7th, 2024

### ISSUE THREAD

**Issue by kriswest** [finos/FDC3#1205]
## Date
7th May 2024 - 10am EDT / 3pm BST

### Meeting recording & Deck

https://github.com/finos/FDC3/assets/1701764/a09e85b4-e30c-414e-a531-04021ef017e1

[FDC3 General Meeting - 7th May 2024.pdf](https://github.com/finos/FDC3/files/15238815/FDC3.General.Meeting.-.7th.May.2024.pdf)

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies).

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call, review meeting notices (5mins)
- [x] Review action items from previous meeting (5mins)
- [x] Announcements
  - FDC3 2.1.0 NPM module released
    - 2.1 standard contexts and intents
    - Intellisense and utilities for Intent and Context names
    - New build / clean audit 
  - FDC3 .NET binding release #1108
    - https://github.com/finos/fdc3-dotnet
    - https://www.nuget.org/packages/Finos.Fdc3
  - FDC3 website update
  - Conformance, Training & Certification
- Updates on current activity in FDC3 Discussion groups:
  - [x] FDC3 Use cases
  - [x] Identity & Threat modelling
  - [x] FDC3 for Web Browsers
  - [x] Desktop Agent Bridging
  - [x] Standards Working Group and other activity
    - (Non-context) event listeners #1136 
    - Better support for tracking/analytics use cases #1200 
- [x] Upcoming FDC3 meetings and OSFF London presentations  
- [x] Q&A (not recorded) (10mins)

## Untracked attendees

| Full name | Affiliation | GitHub username |
|-----------|-------------|-----------------|
|           |             |                 |

**Comment by kriswest** [comment]
Kris West / interop.io 🚀

**Comment by openfin-johans** [comment]
Johan Sandersson / OpenFin 🎁

**Comment by robmoffat** [comment]
Rob Moffat / FINOS 🐄

**Comment by rikoe** [comment]
Riko / Adaptive

**Comment by robmoffat** [comment]
Ashok Tankala

**Comment by hughtroeger** [comment]
Hugh Troeger / FactSet

**Comment by cwatson88** [comment]
Chris Watson / bibbit

**Comment by mistryvinay** [comment]
Vinay Mistry / Symphony 🎵
