### ISSUE TITLE
FDC3 User Adoption Survey

### ISSUE THREAD

**Issue by brooklynrob** [finos/FDC3#124]
## Components to Developing and Executing Survey
- [x] Draft Survey
- [x] Select candidate survey tool
- [x] Stage Survey in candidate tool (@aitana16)
- [x] Collect feedback
- [x] Finalize survey
- [x] Identify people/orgs to distribute survey too
- [x] Create distribution / survey awareness plan
- [x] Distribute Survey
- [x] Close Survey
- [x] Process Results
- [x] Summarize Results
- [x] Review Results within FDC3 Survey
- [x] Create summary / talking points for external socialization of survey results.

**Comment by brooklynrob** [comment]
Let's also draft a blog post to go on the FINOS website about the survey (CC @nkolba @grizzwolf @aitana16)

**Comment by brooklynrob** [comment]
Elements of the distribution / survey awareness plan:
- Email to FDC3 general list (sent by @nkolba? Would someone like to draft this?)
- Post to FINOS website ([drafted in Google docs](https://docs.google.com/document/d/1LIJmnMYFN3TOCGcrpPvqtB2pdccs0kCUrr4yVqB5c-w/edit))
- This Week at FINOS
- Announcement as part of lightning talk at OSSF
- Graphic and announcement on fdc3.finos.org (@aitana16 with Meg, FINOS graphic designers)
- Through FDC3 implementers/vendors to mailing lists 
  - OpenFin
  - Tick42
  - ChartIQ
  - Who else?

Anything more?

**Comment by aitana16** [comment]
Hi @brooklynrob adding a distribution checklist:

FINOS (@aitana16 and @grizzwolf)
- [ ] This Week at FINOS
- [ ] E-mail: community@finos.org
- [ ] FINOS Twitter
- [ ] FINOS LinkedIn
- [ ] Add to OSSF comms
- [ ] FINOS website (www.finos.org) blog post entry 

FDC3: (tbc)
- [ ] E-mail: FDC3 Lists

Vendors:
- [ ] Openfin: Mitra: FINJS list + ask her for other relevant openfin distribution lists
- [ ] ChartIQ (Christian hall?)
- [ ] Glue42

**Comment by nkolba** [comment]
@brooklynrob @aitana16 are we set to close this issue out?

**Comment by aitana16** [comment]
yes @nkolba. 
@brooklynrob can you please close this out? I don't have permissions to do so. thanks!

**Comment by petyosi** [comment]
Hey, are the results of the survey available somewhere?

**Comment by aitana16** [comment]
Hi @petyosi, thanks for your interest. The FDC3 survey results are confidential. Please let me or @mcleo-d know if you have any other questions.

**Comment by mcleo-d** [comment]
> Hi @petyosi, thanks for your interest. The FDC3 survey results are confidential. Please let me or @mcleo-d know if you have any other questions.

Hey @aitana16 - @petyosi is a member of the Glue42 team who I know very well indeed. Are we able to forward him a copy of the survey results or should @nkolba arrange with @lspiro-Tick42?

**Comment by mcleo-d** [comment]
> Hey, are the results of the survey available somewhere?

Hi @petyosi - I've just has a conversation with @aitana16 who's informed me we're unable to distribute the survey results due to the confidentiality agreed with the people who took part.

Apologies for the misinformation, but we need to make sure the terms of the survey are applied. cc @nkolba and @lspiro-Tick42

**Comment by petyosi** [comment]
@mcleo-d - how about the last action item? Or it is still strictly an internal one?
>  Create summary / talking points for external socialization of survey results.

**Comment by mcleo-d** [comment]
Great point @petyosi 👍 

@brooklynrob - @petyosi from the Glue42 team would like to learn from the FDC3 survey that was recently conducted by FINOS. However, we need to keep the confidentiality of the participants safe.

Is there a publicly available version of the survey results that we can share with @petyosi?
