### ISSUE TITLE
Question: Version required in IntentResolution but not provided in RaiseIntentResponse

### ISSUE THREAD

**Issue by Roaders** [finos/FDC3#1269]
### Question Area
 - [ ] App Directory
 - [x] API
 - [ ] Context Data
 - [ ] Intents
 - [ ] Use Cases
 - [ ] Other

### Question

Whilst implementing a `DesktopAgentProxy` we noticed that `IntentResolution` (the return value from `raiseIntent`) has `version` on it but  `RaiseIntentResponse` does not have a version. We were wondering where this version should come from - the `DesktopAgentProxy` or the top level `DesktopAgent`.

Now whilst writing this question I can see that `IntentResolution` does not have version on it in this repo so I assume that we are just on an old version and we should update?

**Comment by kriswest** [comment]
IntentResolution. version never had anywhere to come from, so it was deprecated back in 2.0 I think and made optional: https://fdc3.finos.org/docs/2.0/api/ref/Metadata#intentresolution
I'd say just go ahead and drop it wherever you have it. The meaning of Intents are supposed to be obvious from their names and they are entirely represented by that name only, so I don't think there is any need to have versioning of them in the Standard anyway.

**Comment by Roaders** [comment]
oh yes, you're right. It was optional so we can just ignore it. Thanks

**Comment by kriswest** [comment]
@Roaders I saw a comment somewhere else about releases, but I'm struggling to find it now. If you can point me at it I'll get you an answer.

**Comment by Roaders** [comment]
Do you mean this:
https://github.com/finos/FDC3/commit/20ddf5966a4d103b5409125365b36705fa612caf
?

**Comment by kriswest** [comment]
Yes thats it, will reply over there.
