### ISSUE TITLE
GetAgent setWindowFDC3 parameter

### ISSUE THREAD

**Issue by robmoffat** [finos/FDC3#1274]
We've been discussing whether the [getAgent](https://github.com/finos/FDC3/pull/1191/files#diff-928315b9fee265def6f280dca5a5310e1217cd8851d0f61bfac4529ea64eb680) options should have a parameter for backwards compatibility which will set `window.fdc3` and fire the `fdc3Ready` event.  For pre-existing applications upgrading to FDC3 For the web and making heavy use of those features, this will save a lot of effort when upgrading to `getAgent`.

Question for discussion:

**Should this parameter be set to true or false by default?** i.e.

- TRUE would set `window.fdc3` and fire `fdc3Ready`
- FALSE would not, and you would need to call `getAgent` wherever you need an instance of the `DesktopAgent`.

Some comments from email discussion:

@robmoffat said:

> 7/8. fdc3Ready/window.fdc3 - really this is coming down to what we set for the default then?

@kriswest said:

> I reckon so. I've come to the conclusion that defaulting true will be make retrofit simpler and we like simple. I actually only think we need one option (if setting the global fire the event - they've always gone together in the past, so why separate em now - if you don't need the event, don't listen for it - its not going to hurt anything).

Derek Novavi then suggested that improving backwards compatibility would make FDC3 For The Web easier to accept when it comes to voting.

Thoughts?

**Comment by Roaders** [comment]
so does this mean that we are relaxing or removing the requirement to have `window.fdc3` always set?

**Comment by kriswest** [comment]
@Roaders that is the plan, yes. By making setting it the default we can easily support existing.apps (that add only a `getAgent` call), and allow others to turn it off if they need to (they could also just ignore it).

**Comment by Roaders** [comment]
Great, that sounds good. I agree that defaulting to true makes the mast sense.

**Comment by kriswest** [comment]
I'll restart my opinion as confirmation. I think we should:
- Set `window.fdc3` by default (and handle the fact that it might already be set or frozen by a container as they will continue to do this)
- Fire the `fdc3Ready` event when its set (unless it was already fired by the container!)
- Provide a `setWindowGlobal` flag as an argument to `getAgent`, which is true by default - set to false to disable the behaviour.
- Update the recommendation in the API overview that DAs only set `window.fdc3` when its ready to use, to recommendation that it is set as soon as possible after a window is opened, and to queue any requests made to it until it is ready to use. 
  - DAs setting the reference ASAP will speed up the aquisition of the correct DA and reduce or prevent any issues involving timeouts and failovers.

**Comment by kriswest** [comment]
Closed as decided and implemented
