### ISSUE TITLE
Question: Is This Missing too?

### ISSUE THREAD

**Issue by robmoffat** [finos/FDC3#1277]
I don't see a type `FindIntentsByContextResponse` (which differs from `FindIntentsResponse`) in BrowserTypes - is it missing?

Ok, I am seeing this: 

```
export interface FindIntentsByContextsByContextResponse {
    /**
     * Metadata for messages sent by a Desktop Agent to an App in response to an API call
     */
    meta: AddContextListenerResponseMeta;
    /**
     * A payload for a response to an API call that will contain any return values or an `error`
     * property containing a standardized error message indicating that the request was
     * unsuccessful.
     */
    payload: FindIntentsByContextsByContextResponsePayload;
    /**
     * Identifies the type of the message and it is typically set to the FDC3 function name that
     * the message relates to, e.g. 'findIntent', with 'Response' appended.
     */
    type: "findIntentsByContextResponse";
}
```

note the type name

**Comment by kriswest** [comment]
Yes thats a typo in the Schema title - I'll fix this and #1276 shortly.

**Comment by kriswest** [comment]
...after I figure out how to fix the fact that the code generation command has crested over the maximum length allowed in windows, that is 🤦

**Comment by kriswest** [comment]
Fixed by https://github.com/finos/FDC3/commit/14952aed42b3ae8e214d146c45f4bd123baa7052
Bridging types generation still needs looking at however.

**Comment by kriswest** [comment]
(fixed all the types generation now as well)
