### ISSUE TITLE
Publish JSON schemas for context types to FDC3 website

### ISSUE THREAD

**Issue by rikoe** [finos/FDC3#128]
To finalise the JSON schema work for context schemas began with #120, a number of things need to be done:
- [x] Identify which schemas should be officially published/standardised as part of the first pass. Cross-reference with [Financial Objects][1]. `fdc3.instrument` and `fdc3.contact` are the most important ones to start with. 
- [x] Remove everything apart from `email` property from `fdc3.contact` schema to simplify.
- [x] Publish versioned schema definition files to the FDC3 website, to match the URLs in the schema files, e.g. `https://fdc3.finos.org/schemas/1.0/instrument.schema`
- [x] Make sure the context data [examples][2] line up with the schema definitions
- [x] Add documentation for each signed of schema to the context data website documentation. It could work similarly to e.g. the [API reference documentation][3].

[1]: https://fo.finos.org/docs/fo-library
[2]: https://github.com/FDC3/FDC3/tree/master/examples/context
[3]: https://fdc3.finos.org/docs/1.0/api/DesktopAgent

**Comment by lspiro-Tick42** [comment]
NB I think InstrumentSchema has moved to https://github.com/finos/FDC3/blob/master/src/context/schemas/instrument.schema
