### ISSUE TITLE
Question: AddContextListenerResponsePayload does not contain channelId

### ISSUE THREAD

**Issue by Roaders** [finos/FDC3#1296]
### Question Area
 - [ ] App Directory
 - [x] API
 - [ ] Context Data
 - [ ] Intents
 - [ ] Use Cases
 - [ ] Other

### Question

We're currently implementing our `DesktopAgentProxy` and are using the proposed protocol to communicate between the Root Agent and Proxy Agents.

When implementing `addContextListener` we noticed that the docs for `AddContextListenerRequestPayload` state:

    /**
     * The id of the channel to add the listener to or `null` indicating that it should listen
     * to the current user channel (at the time of broadcast).
     */

So the assumption as we might not be setting the `channelId` on the request message it seems sensible to me to specify which channel was subscribed to in the response message but there is no `channelId` specified.

There is a `listenerUUID` on the `AddContextListenerResponsePayload` but it is not clear what that is for or how we should use it.

**Comment by Roaders** [comment]
After having looked at this a bit closer I think that I have figured it out. Of course the channel Id could well change during the lifespan of a context listener so no channel Id should be used for the subscription.

I would still be interested to hear more about the `listenerUUID` though.

**Comment by kriswest** [comment]
Hi @Roaders, I starteda response here, so I'll send it over in full anyway

I think all this is most easily undertood by referencing the main API docs:

```ts
addContextListener(contextType: string | null, handler: ContextHandler): Promise<Listener>;
```
https://fdc3.finos.org/docs/api/ref/DesktopAgent#addcontextlistener

## Regarding context types

The contextType argument is required and hence must be set in the related `AddContextListenerRequestPayload` message in fdc3 for the web. A `null` value represents listening for all context types in both the API and that message and must not be omitted - an `undefined` value (omitting the key entirely) would not be valid.

The value sent in the request could be sent back in the response - but the shouldn't be necessary and isn't somethinh we've done throughout the messages. Instead, each request message contains a `meta.requestUUID`, which should be quoted in the response message (again as `meta.requestUUID`) ensuring that the client can associate the response with a specific request and use it to resolve the promise returned through the API/DesktopAgentProxy.

## Regarding channel id

The AddContextListenerRequest message supports both `fdc3.addContextListener` (adds a listener to current User channel) and `channel.addContextListener` (adds a listener to a specific channel you've retrieve via `fdc3.getOrCreateChannel` or `fdc3.createPrivateChannel`). So it should be set based on which API call was used.

## Regarding Listener UUID

The payload.listenerUUID value in the response is intended to support the [`Listener` entity](https://fdc3.finos.org/docs/api/ref/Types#listener) returned from API calls that add context, intent or event listeners (such as `addContextListener`). The Listener's job is just to provide an `unsubscribe` function that can be used to remove the handler function that was set. Take a look at `ContextListenerUnsubscribeRequest` and `IntentListenerUnsubscribeRequest` for details of how thats used (essentially its passed back in those messages to indicate which listener is to be removed). 


Hopefully that answers all questions here so I'll close this issue - but feel free to reopen it if any further clarificaiton is needed or you've spotted something we need to fix. I'm hoping to make all of this clear in the docs PR for fodc-for-the-web in due course.
