### ISSUE TITLE
Question: resolvers / channel selectors UI

### ISSUE THREAD

**Issue by Roaders** [finos/FDC3#1307]
### Question Area
 - [ ] App Directory
 - [ ] API
 - [ ] Context Data
 - [ ] Intents
 - [ ] Use Cases
 - [x] Other

### Question

Looking at the messages in `BrowserTypes` there are messages related to Iframes and moving or dragging iframes.

Is it a requirement of the proposed spec that UI elements are presented in an Iframe? That seems to me like it would be an implementation detail. We imagine that the Proxy agent will just add a popup to the dom with no need for an iframe.

I am also not sure why the root agent needs to know when the UI is resized or dragged.

Is there any documentation around this and why this is included in the spec?

**Comment by Roaders** [comment]
Thanks for the quick response. I actually thought you were on holiday already so wasn't expecting you to reply so fast.

You say:

> there is no proprietary library with the UIs imported into the apps

are you specifically referring to UI elements only here? This has led me to wonder where `getAgent` and the `DesktopAgentProxy` implementation come from. I assumed that these would come from an import from fdc3:

```typescript
import { getAgent } from "@finos/fdc3";
```

We are planning on providing UI elements as part of our `DesktopAgentProxy` (it will be replaceable if desired) that will be part of the compiled iframe app. A developer will place the channel selection component wherever they want within their app and there will be no need for iframes. 

I assume that this is supported and ok? The iframe option is only if the proxy does not provide UI and the DA needs to somehow display some UI in the attached iframe or child window without injecting code.

Thanks again. Have a good holiday.

**Comment by kriswest** [comment]
HI @Roaders, yes the `getAgent` and the `DesktopAgentProxy` would be imported from the @finos/fdc3 library (open-source non-proprietary). Part of the goal is to be able to the necessary UIs through that from the Desktop Agent without any additional integration. The options available though it to provide and intent resolver or channel selector UI include:

1. Apps indicate they want them (don't set the flags false when connecting), DA sends back URLs, Desktop Agent Proxy creating iframes and loads them with the URLs
2. Apps indicate that they don't want them (set flags false), then provide their own UIs which can directly use the FDC3 API in their implementation, e.g. 
    - intentResolver: use `findIntent` to check for resolution options, then `raiseIntent` and set the `app` argument to the chosen option
    - channelSelector: use getUserChannels to get data to render, `joinUserChannel`, `leaveUserChannel` and the new addEventListener function to listen for external channel changes)
3. DA loads apps in an iframe, so it can display a channel selector and intent resolver outside of the iframe, so it doesn't bother to provide URLs for the DesktopAgentProxy to inject.

I think what you describe is related to 2. If so I would advise that you use the FDC3 API itself to implement those UIs if you want them to work in other standards-compliant desktop agents (either browser or container). However, if you are also implementing your own DesktopAgentProxy according to the what we're written up for the opensource implementation you can go other ways with it and you can of course just detect you are runnign in someone else's DA and change how you handle things.

>  I actually thought you were on holiday already so wasn't expecting you to reply so fast.
I'm supposed to be, but packing gets boring ;-)

**Comment by kriswest** [comment]
To further clarify the proprietary library comment: What I mean is the goal is to avoid having to have a specific DA-libraries incorporated into app to provide the UIs as that doesn't help us build an FDC3 ecosystem, but rather a more factional one. There is always the option for an application to provide its own UIs, but we also want to support ways for a DA to provide them, without the direct software integration.

In your case you are working on both the apps and dekstop agent. However, if you are going to bring other firm's apps into your DA you'll need a secure means to provide them with the UIs and if your apps are used in a different DA, then you need a means to receive their UI (or to indicate that you've got it handled). 

I hope that helps explain!

**Comment by Roaders** [comment]
Great, thanks Kris
