### ISSUE TITLE
Adding Channel State For JoinUserChannel / AddContextListener

### ISSUE THREAD

**Issue by robmoffat** [finos/FDC3#1311]
## Enhancement Request

Discussion: 
- #1267 

Proposal:

`addContextListenerResponse` and `joinUserChannelResponse` payloads are extended to add `context`.

**Comment by kriswest** [comment]
Note: this was resolved offline through discussion. The DA should send a broadcast event when it knows that current context needs to be delivered after a channel was joined or a contextListener was added.
