### ISSUE TITLE
window.origin Requirement

### ISSUE THREAD

**Issue by robmoffat** [finos/FDC3#1316]
I've been doing integration testing today and here's a thing I came across, not sure if we've already discussed it.

Normally, you call post message like this:

```
w.postMessage(<WCP1Hello message>, { targetOrigin: origin });
```

Where: 

 - `w` is the window you're sending it to
 - `origin` is the origin of that window.

This is kind of belt-and-braces in case the origin changes and you share some data with a destination you didn't mean to.  I have some code to collect together various window.opener / window.parent etc. ancestors to send the WCP1Hello to, however, I can't simply do:

```
w.origin
```

... as this breaks the sandbox model.

However, I can get hold of `document.referrer`, which in most cases should be the thing that opened the window.  It works for both iframes and tabs.  

So I'm just raising this for possible discussion:  
 - Is this the best way to do this?
 - Do we want to use `*` instead?  

The documentation https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage#targetorigin is pretty clear that `*` is frowned upon, but it seems like it might be the right answer in this case.  

Thoughts?

**Comment by robmoffat** [comment]
@novavi

**Comment by kriswest** [comment]
@robmoffat For the initial message outward from app to DA, theres no way for the app to know the DA's origin, so you are correct, it has to be `*`. However, the response back from the DA to app does know the origin and can protect its response (with attached MessagePort) by setting the targetOrigin, which will provide protection against a navigation event that occurred between the two messages.

The identity validation step over the MessagePort provides a further check on the origin not having changed, but this time over the filtered comms channel AND with a match up to the identity URL provided or captured. Hence, setting the targetOrigin on the response isn't critical but is still best practice.

I'd say avoid document.referrer, and simply use the origin from the first message to target the second and live with * on the first message (as it has to be that way!)

Reopen if any part of this doesn't sit right with you.
