### ISSUE TITLE
GetAgentParams Not Optional

### ISSUE THREAD

**Issue by robmoffat** [finos/FDC3#1319]
GetAgentParams should contain all optional parameters:

```
type GetAgentParams = { 
  timeout: number, 
  identityUrl?: string, 
  channelSelector: boolean, 
  intentResolver: boolean,
  dontSetWindowFdc3: boolean,
  failover?: (args: GetAgentParams) => Promise<WindowProxy | DesktopAgent> 
}; 
```

Otherwise, users of getAgent have to supply all parameters when they might just want to supply one.

**Comment by kriswest** [comment]
Fixed by 23020b1cdbcb6294909c8a8cea9e7d657675219a
My bad, I had those set up with defaults, but as we switched to a single object param, you can't actually do that. So all optional it is! Note that the params object itself is also optional.
