### ISSUE TITLE
Question: RaiseIntentResultResponse requestUuid and source

### ISSUE THREAD

**Issue by Roaders** [finos/FDC3#1336]
### Question Area
 - [ ] App Directory
 - [x] API
 - [ ] Context Data
 - [ ] Intents
 - [ ] Use Cases
 - [ ] Other

### Question

when publishing a `RaiseIntentResultResponse` there is no corresponding request message so I am not sure what `requestUuid` and `source` we are suppose to use. To me it makes sense to set the source to be `message.payload.originatingApp` from the `IntentEvent` - in other words the app that raised the intent. For the `requestUuid` it seems that we should use the raiseIntentRequest uuid - the `RaiseIntentResultResponse` needs to be returned to the app that raised the intent so the uuid should match that message so we can confirm that we're getting the response to the correct raise intent request. However, the app handling the intent does not have this uuid. It only has the event uuid that is present on the `IntentEvent`. It does not see the `raiseIntentRequest` message at all.

This is my understanding of the flow of events that should take place:

![image](https://github.com/user-attachments/assets/c5778cd7-8fd5-4351-87e3-04aece2ba85b)

Is this correct?

If so we can see that ProxyOne never sees the raiseIntentRequest message from ProxyTwo so is unable to add it's requestUuid to the response.

**Comment by kriswest** [comment]
As we discussed in a meeting just now, There is a message exchange for Proxy One (the resolving app) to send over the result to the DA (`intentResultRequest` and `intentResultResponse`), which it should then send on to Proxy Two (the raising app) via `raiseIntentResultResponse` as a second response to the original intent request.

Here's the excahnge (althoguh please note its the opposite way round to your diagram, with the raising app on the left and resolving app on the right).

Also as discussed we could do with some explicit quoting of request and event IDs within the exchange. I'll implement PR to add those into the messages and tag both @Roaders and @robmoffat in it to check. That'll happen tomorrow morning now.

```mermaid
sequenceDiagram
    AppA ->> DesktopAgent: raiseIntentRequest
    DesktopAgent ->> AppB: intentEvent
    DesktopAgent ->> AppA: raiseIntentResponse
    AppB ->> DesktopAgent:intentResultRequest
    DesktopAgent ->> AppB: intentResultResponse
    DesktopAgent ->> AppA: raiseIntentResultResponse
```

**Comment by kriswest** [comment]
@Roaders @robmoffat added an eventUuid reference to the intentResultRequest message and did some other small cleanup: ed60bfc044f30593f3f17cd9c5a70ca6f8382f14

Another thing it occurred to me to clarify is exchanges where the intent resolver need to show up:

```mermaid
sequenceDiagram
    AppA ->> DesktopAgent: raiseIntentRequest
    DesktopAgent ->> AppB: intentEvent
    DesktopAgent ->> AppA: raiseIntentResponse
``` 
You get this far and the response comes back with an `AppIntent` rather than an IntentResolution. What should happen is:

```mermaid
sequenceDiagram
    AppA ->> DesktopAgent: raiseIntentRequest
    DesktopAgent ->> AppB: intentEvent
    DesktopAgent ->> AppA: raiseIntentResponse
    break when AppIntent return with multiple options
        DesktopAgent-->AppA: getAgent displays IntentResolver
        AppA-->DesktopAgent: User picks an option
    end
    AppA ->> DesktopAgent: raiseIntentRequest
    Note left of AppA: New request includes specific `app` target<br>/and new requestUuid
    DesktopAgent ->> AppB: intentEvent
    DesktopAgent ->> AppA: raiseIntentResponse
    AppB ->> DesktopAgent: intentResultRequest
    DesktopAgent ->> AppB: intentResultResponse
    DesktopAgent ->> AppA: raiseIntentResultResponse
``` 

Basically, if getAgent() has to show the intent resolver then you might as well raise a new request thereafter with the target. However, if your DA can deal with the resolver without getAgent, then you can complete it with one request:

```mermaid
sequenceDiagram
    AppA ->> DesktopAgent: raiseIntentRequest
    DesktopAgent ->> AppB: intentEvent
    break DA determines there are multiple options
        DesktopAgent-->AppA: Desktop Agent displays IntentResolver
        AppA-->DesktopAgent: User picks an option
    end
    DesktopAgent ->> AppA: raiseIntentResponse
    AppB ->> DesktopAgent: intentResultRequest
    DesktopAgent ->> AppB: intentResultResponse
    DesktopAgent ->> AppA: raiseIntentResultResponse
``` 
Unless you spot any issues with those flows, I'll get them into the docs

**Comment by kriswest** [comment]
Another thing it occurred to me to clarify is exchanges where the intent resolver need to show up:

```mermaid
sequenceDiagram
    AppA ->> DesktopAgent: raiseIntentRequest
    DesktopAgent ->> AppB: intentEvent
    DesktopAgent ->> AppA: raiseIntentResponse
``` 
You get this far and the response comes back with an `AppIntent` rather than an IntentResolution. What should happen is:

```mermaid
sequenceDiagram
    AppA ->> DesktopAgent: raiseIntentRequest
    DesktopAgent ->> AppB: intentEvent
    DesktopAgent ->> AppA: raiseIntentResponse
    break when AppIntent return with multiple options
        DesktopAgent-->AppA: getAgent displays IntentResolver
        AppA-->DesktopAgent: User picks an option
    end
    AppA ->> DesktopAgent: raiseIntentRequest
    Note left of AppA: New request includes specific `app` target<br>/and new requestUuid
    DesktopAgent ->> AppB: intentEvent
    DesktopAgent ->> AppA: raiseIntentResponse
    AppB ->> DesktopAgent: intentResultRequest
    DesktopAgent ->> AppB: intentResultResponse
    DesktopAgent ->> AppA: raiseIntentResultResponse
``` 

Basically, if getAgent() has to show the intent resolver then you might as well raise a new request thereafter with the target. However, if your DA can deal with the resolver without getAgent, then you can complete it with one request:

```mermaid
sequenceDiagram
    AppA ->> DesktopAgent: raiseIntentRequest
    DesktopAgent ->> AppB: intentEvent
    break DA determines there are multiple options
        DesktopAgent-->AppA: Desktop Agent displays IntentResolver
        AppA-->DesktopAgent: User picks an option
    end
    DesktopAgent ->> AppA: raiseIntentResponse
    AppB ->> DesktopAgent: intentResultRequest
    DesktopAgent ->> AppB: intentResultResponse
    DesktopAgent ->> AppA: raiseIntentResultResponse
``` 
Unless you spot any issues with those flows, I'll get them into the docs

**Comment by kriswest** [comment]
@Roaders The `intentEvent` sent to the resolving app will have its own `eventUuid` so I thought it best to quote that rather than the original `requestUuid` as that currently never makes it to the resolving app. The DA would need to track both the `requestUuid` from the raising app and `eventUuid` it sent to the resolving app to connect the two. A DA could, of course, decide to make these the same by forwarding on the `requestUuid` as the `eventUuid` - but personally I think each message should have at least one unique identifier.

Alternatively, we could add the the original `requestUuid` to the `intentEvent` as `intentRequestUuid` and have the resolving app send it back in `intentResultRequestPayload` - that could be in addition to or instead of the `intentEventUuid`?

**Comment by Roaders** [comment]
If I understand it corectly your first suggestion is that the DA would have to store a lookup of `intentEventUuid` to `raiseIntentRequestUuid` so that when it creates and sends back the `raiseIntentResultResponse` it can include that uuid and the proxy can match the `raiseIntentRequest` to the `raiseIntentResultResponse`.

Your second suggestion I think is what I was asking for and means that the DA does not need to store any additional state. I would like it to work like this to avoid any storage of state:

![image](https://github.com/user-attachments/assets/dc858174-6f4f-45d9-a65b-73b39eb32316)


This means that the proxy can compare the generated original requestUuid on the raiseIntentRequest message (the only message it knows about) to the uuid on the `raiseIntentResultResponse` and knows for sure that it is acting on the correct result.

The returned results may be quite long running. For example you could return details about a phone call or a chat once the call has finished so the proxy could be waiting some time and it is not unlikely that another intent could be raised in the meantime.

**Comment by kriswest** [comment]
From the proxy's perspective, it can compare the `requestId` from its original `raiseIntentRequest` to the `raiseIntentResponse` and `raiseIntentResultResponse` either either approach as that always has be quoted - it's not necessary for it to make the round trip through the other proxy for that to happen, so long-running / overlapping intents are already covered.

The only question is whether the DA needs to retain one additional state field, `eventUuid` connected to the `requestUuid` (the existence of which would indicate that the intent was actually sent on) and hence which value that `intentResultRequest` quotes in its payload. To be honest I don't mind a whole lot - but I have an intuition that using the `eventUuid` is more consistent/more secure - but I can't yet back that up with logic.

**Comment by Roaders** [comment]
I might have been being stupid.... I've not actually got round to implementing the intentResultRequest / Response yet. When I do I think I might be able to get hold of the original requestUuid without it round tripping through ProxyTwo.

I'll come back to confirm my stupidity or carry on arguing once I've got round to implementing! 😄

**Comment by Roaders** [comment]
I have now implemented these function and it does work - but it requires me to store state in the DA to matchup the `intentEventUuid` to the `raiseIntentRequestUuid` and the original source app so I know where to route the `raiseIntentResultResponse` message to.

I don't really like storing state in the DA if I don't have to (but I will keep this implementation if we don't agree on my proposed solution) so I'd like to solve this by adding `originatingApp` to the `intentResultRequest` payload and adding `raiseIntentRequestUuid` to the `intentEvent` and `intentResultRequest`. In this way both the source app and the initial uuid are transferred along with the message flow from the initial raising of the intent all the way through to the result being received.

**Comment by kriswest** [comment]
I can go ahead and add `raiseIntentRequestUuid` to `intentEvent` and `intentResultRequest` - I can see how it would be marginally more convenient than the intentEvent's eventUuid, although it does introduce some redundancy. 

However, I'm wary of adding `originatingApp` to `intentResultRequest`. I don't think we can eliminate state entirely as this process is inherently stateful and we should not rely solely on the content of messages for routing them as that opens us up to spoofing. Further, `originatingApp` would take its value from the `intentEvent` where it is an optional property as 'Originating app metadata' for raised intents is still an optional feature of a Desktop Agent (see https://fdc3.finos.org/docs/next/api/spec#originating-app-metadata). if we wanted to base something on it (which I'm not sure we do) we'd should change that first.

**Comment by kriswest** [comment]
@Roaders @robmoffat  see acf8064ca8f03a660ff2832859ae967d2e515713
This creates a new required `raiseIntentRequestUuid` property on `intentEvent` and `intentResultRequest`. The `intentEventUuid` on `intentResultRequest` was not required so I fixed that at the same time.

**Comment by Roaders** [comment]
Thanks Kris. I wasn't sure about the originatingApp either. We don't rely on the source app at all now, this is all handled by our routing system. In this case though we will have to think about the best way of tracking the source app.

I'll implement with these changes and get back to you.

**Comment by Roaders** [comment]
It looks like the `intentEventUuid`  is still there BTW. I think you said you were removing it and I agree that we don't need it anymore.

**Comment by kriswest** [comment]
It is still there as the `IntentEvent` is the message actually being followed up with a result. I've added `raiseIntentRequestUuid` for convenience to relate all these message events to each other but as thats from a message not actually received by the resolving app, but forwarded on, I'm wary of only providing that. I can see other implementors questioning why that is not the reference id used... Personally, if i had to pick one, I'd still go with the intentEventUuid...

**Comment by kriswest** [comment]
Closing as completed - happy to reopen if there's further discussion to do. The current solution is a compromise and includes a redundant id, but thats not a big problem and provides options to DA implementors.
