### ISSUE TITLE
Matching identityUrls to appD records for FDC3 for the Web

### ISSUE THREAD

**Issue by kriswest** [finos/FDC3#1337]
Matching identityURLs to appD records (instead of nominating a specific appD record) can be non-trivial when you have multiple apps from the same origin. Below is a quick implementation of a match function exploring these:

```js
/** Return the AppD record whose URL best matches the input URL or `null` if no match is found.
 *  To be considered a match all elements of the AppD URL (origin, path, searchParams and hash)
 *  must be found in the input URL.
 *  The best match is the AppD URL that contains the most elements from the
 *  input URL.
 */  
let matchUrlToAppD = (url, appDRecords) => {
    console.log(`\tFind match for ${url}`);
    //parse the URL
    const inputUrl = new URL(url);

    //fn to trim trailing / from paths
    const trimTrailingSlash = (path) => {
        if (path.endsWith("/")) {
            const out = path.slice(0, -1);
            //return null if it was just a /
            return out === "" ? null : out;
        } else {
            return path;
        }
    };
                               
    const matchScores = [];

    //score appD records based on the match of their URL to the input URL
    // if any component of the appD record URL is missing from input URL, score 0
    // otherwise count the number of input elements matched 
    appDRecords.map((record) => {
        console.log(`\ttesting appD URL ${record.details?.url}`);
        //record must contain a URL
        if (!record.details?.url) { console.log("\t\tURL fail"); return; }
        
        //parse record URL
        const parsedUrl = new URL(record.details.url);
        
        //origin of URL must match record
        if (parsedUrl.origin !== inputUrl.origin) { console.log("\t\torigin fail"); return; }
        let score = 1;
        
        //path must match if present in appD record - Path of "/" is ignored
        const appDPath = trimTrailingSlash(parsedUrl.pathname);
        if (appDPath) {
            if (trimTrailingSlash(inputUrl.pathname) != appDPath) {
                console.log("\t\tpath fail"); 
                return;
            } else {
                score++;
            }
        }
        
        //hash must match if present in appD record
        if (parsedUrl.hash) {
            if (inputUrl.hash != parsedUrl.hash) {
                console.log("\t\thash fail"); 
                return; 
            } else {
                score++;
            }
        }
        
        if (!!parsedUrl.search) {
            //search params present in appD record must be present in URL
            const recordSearchKeys = parsedUrl.searchParams.keys().toArray();
            for (let i=0; i<recordSearchKeys.length; i++) {
                const key = recordSearchKeys[i];
                if (inputUrl.searchParams.get(key) !== parsedUrl.searchParams.get(key)) {
                    console.log(`\t\tsearch param '${key}' fail, expected '${parsedUrl.searchParams.get(key)}', got '${inputUrl.searchParams.get(key)}'`);
                    return;
                }
            }
            //count matched input URL search params for scoring
            inputUrl.searchParams.keys().forEach((key) => {
                if (parsedUrl.searchParams.get(key) === inputUrl.searchParams.get(key)) {
                    score++;
                } else {
                    console.log(`\t\tinput search param ${key}=${inputUrl.searchParams.get(key)} not found in appD search params ${JSON.stringify(parsedUrl.searchParams.toString())}`);
                }
            });
        } else {
            console.log("\t\tno search string in record");
        }
        
        //everything present in the record was found in the inputUrl
        matchScores.push([score, record]);
    });
    console.log("Match scores:", JSON.stringify(matchScores,null,2));
    
    //return the best scoring match (ignore ties)
    matchScores.sort((a,b) => b[0]-a[0]);
    return matchScores[0][1] ?? null;
};

const appDRecords = [
    {details:{url:"https://example.com/path"}},
    {details:{url:"https://example.com/path?search=shoe"}},
    {details:{url:"https://example.com/path"}},
    {details:{url:"https://example.com/"}},
    {details:{url:"https://google.com/"}},
    {details:{url:"https://example2.com/"}},
    {details:{url:"https://example.com/path?search=text#hash"}},
    {details:{url:"https://example.com/path?search=text"}},
    {details:{url:"https://example.com/#hash"}},
    {details:{path:"some path"}},  
];

//tests are [testName, definition, inputUrl, expectedAppDUrl, appDRecordsToSearch]
const test1 = [
    "test 1",
    "Path and search present, exact match available",
    "https://example.com/path?search=text",
    "https://example.com/path?search=text",
    appDRecords
];
const test2 = 
    ["test 2",
     "Path and hash present, no exact match, need to ignore path in input to match",
     "https://example.com/altPath#hash",
     "https://example.com/#hash",
     appDRecords
    ];
const test3 = [
    "test 3",
    "Path only present, exact match available",
    "https://example.com/path",
    "https://example.com/path",
    appDRecords
];
const test4 = [
    "test 4",
    "Path only present but not matchable, match on domain only",
    "https://example.com/altPath",
    "https://example.com/",
    appDRecords
];
const test5 = [
    "test 5",
    "path, search and hash present, but no match on search param or path, select match without",
    "https://example.com/altPath?search=tulip#hash",
    "https://example.com/#hash",
    appDRecords
];
const test6 = [
    "test 6",
    "Ignore trailing slashes on path",
    "https://example.com#hash",
    "https://example.com/#hash",
    appDRecords
];
const test7 = [
    "test 7",
    "Hash present but unknown, match origin only, ignoring trailing slash",
    "https://example.com#unknownHash",
    "https://example.com/",
    appDRecords
];

const doTest = ([testName,definition,input,expected,appDRecords]) => {
    console.log(`Running ${testName}`);
    console.log(`\t${definition}`);
    const record = matchUrlToAppD(input, appDRecords);
    if (record.details?.url === expected) {
        console.log(`${testName}: PASSED`);
    } else {
        console.log(`${testName}: FAILED\n\tinput   : ${input}\n\texpected: ${expected}\n\treceived: ${record.details?.url}`);
    }
    console.log("----------------------------------------------------------");
};

doTest(test1);
doTest(test2);
doTest(test3);
doTest(test4);
doTest(test5);
doTest(test6);
doTest(test7);
```

**Comment by Roaders** [comment]
My understanding of the problem is as follows:

We need to specify an appD url to match apps against:

```
http://example.com/somePath?workspace=workspaceOne
```

when matching app urls against this all the specified elements in the appD url must be contained in the app url so all these would match:

```
http://example.com/somePath?workspace=workspaceOne#someHash
http://example.com/somePath?workspace=workspaceOne&view=viewOne
http://example.com/somePath?env=uat&workspace=workspaceOne
http://example.com/somePath?env=uat&workspace=workspaceOne&viewOne
```

It is quite likely that the app url that we are given to match against the appD records will not be an exact match. If the app url starts out as 

```
http://example.com/somePath?workspace=workspaceOne
```

the app is fairly likely to append additional elements to it as the  app boots or as the user interacts. This url may become:

```
http://example.com/somePath?workspace=workspaceOne&view=viewOne&entityId=1234#employees
```

this would still be a match for the appD record.

However, if the url is updated and used to compare against appD records we don't know what elements of the url are important. Do we match `workspace`, `view` or `entityId`?

If we had the following records in the directory we would not know which record to match against:

```
http://example.com/somePath?workspace=workspaceOne
http://example.com/somePath?view=viewOne
http://example.com/somePath?entityId=1234
```

I can't see how even a scoring function would be able to decide between these 3 examples.

IMHO if we have a scoring function that means that it is non deterministic and could lead to different apps being matched. This could change when new apps are added to the directory or it could change based on exactly what point in the boot sequence `getAgent` is called and what modifications the url has undergone.

One soslution to this would be to make the identityUrl a required property. It will not change and can be directly compared against the appD records. The only requirement is that it matches the origin that the app is running in.

I am not too familiar with the parameters that are being passed to `getAgent` but surely we only need to pass the identity url? The actual url of the app can be determined by `getAgent` itself and then added to the payload sent to the DA.

**Comment by robmoffat** [comment]
This is really thorough work, well done @kriswest.  I am reading @Roaders comments and wondering if we are over-thinking this:  perhaps we should only allow exact URL matching?  If the app is messing with its URL then it should be overriding the URL field in its `getAgent` call to be the entry point of the application, i.e the value set in the AppD record.  

Would that work?  Or am I missing a corner case?

**Comment by kriswest** [comment]
@Roaders is right that this doesn't prevent all edge cases - but it does cut them down a lot.  In Giles' example:

> ``` http://example.com/somePath?workspace=workspaceOne&view=viewOne&entityId=1234#employees``` 
> 
>``` 
>http://example.com/somePath?workspace=workspaceOne
>http://example.com/somePath?view=viewOne
>http://example.com/somePath?entityId=1234
>```

If one of the elements or some combination must uniquely identify the app (or how else would the webserver know to serve it?). Hence, I suspect this isn't an edge case that will actually occur unless someone is putting duplicate apps (with different appIds) in thge appD.

The reason I looked into this rather than recommending that we make the argument required is for the convenience of app developers... This way we can retain the option to pass no arguments and in the vast majority of cases it will 'just work'<sup>TM</sup>. If there are any issues with recognizing the right config you can add the argument...

**Comment by robmoffat** [comment]
> The reason I looked into this rather than recommending that we make the argument required is for the convenience of app developers... This way we can retain the option to pass no arguments and in the vast majority of cases it will 'just work'TM. If there are any issues with recognizing the right config you can add the argument...

Surely the argument is optional in the API, and if it's not provided by the client then we use the default, and then it becomes required in the schema?

>  I'd be tempted to try and stick to no required params

Absolutely.

**Comment by kriswest** [comment]
Yep, both `identityUrl` and `actualUrl` are already required in the schema so the DA knows/can log whether an override was sent) - meanwhile the param is optional in the getAgent() API. I think thats the best approach for now. 

I'll soften the match requirements to a recommendation in the docs, rather than a very formal specification - I guess DAs can decide how far they go with matching and tighten up the specification one day if it causes any problems.

**Comment by kriswest** [comment]
closed as completed
