### ISSUE TITLE
Question: How does getAgent work if false is sent for intentResolver

### ISSUE THREAD

**Issue by Roaders** [finos/FDC3#1362]
### Question Area
 - [ ] App Directory
 - [x] API
 - [ ] Context Data
 - [ ] Intents
 - [ ] Use Cases
 - [ ] Other

### Question

I am wondering how an app is supposed to work when it has got an api via `getAgent` but it passed `false` for `intentResolver`. If `raiseIntent` is called with no specified app or with an app with no `instanceId` then there is nothing that the DA can do to resolve the app as it's not allowed to spawn a resolver UI.

Is the intention that `raiseIntent` is never called without a fully qualified appIdentifier? The app will use the agent to display a resolver UI and pick an app instance before calling `raiseIntent`?

If this were the case the app author has a bit of work to do to get this ui working:
 * query agent for list of apps
 * display list
 * handle user cancelling
 * handle user picking an existing instance
 * handle user picking an app with no instance and launching a new app then returning that instanceid

At some point, perhaps in version 2.3 perhaps we could add the ability to specify a resolve app callback function that can be send to getAgent. This would allow an app author to build their own resolver UI but once they have got their agent they just have to call `raiseIntent` and not worry about having to do the above steps.

In our local implementation we have a UI resolver interface with a couple of functions:

```typescript
export type ResolveForIntentPayload = {
    context: Context;
    appIdentifier?: UnqualifiedAppIdentifier;
    intent: Intent;
    /**
     * Optional app intent data which contains a list of app instances. If this is not passed the resolver should lookup the list of instances using desktopAgent.findIntent()
     */
    appIntent?: AppIntent;
};

export type ResolveForContextPayload = {
    context: Context;
    appIdentifier?: UnqualifiedAppIdentifier;
    /**
     * Optional list of app intents for this context that each contain a list of app instances. If this is not passed the resolver should lookup the list of instances using desktopAgent.findIntentsByContext()
     */
    appIntents?: AppIntent[];
};

/**
 * Provides a mechanism for resolving an app from an unqualified identifier, an intent, a context or a combination
 */
export interface IAppResolver {
    /**
     * Resolves an app in response to a raiseIntent() function call
     */
    resolveAppForIntent(payload: ResolveForIntentPayload): Promise<FullyQualifiedAppIdentifier>;
    /**
     * resolves an app in response to a raiseIntentForContext() function call
     */
    resolveAppForContext(payload: ResolveForContextPayload): Promise<FullyQualifiedAppIdentifier>;
}
```

If you could optionally specify a similar function when calling getAgent it would allow the app to be resolved by the desktop agent proxy before the request is sent to the DA.

**Comment by kriswest** [comment]
Hi @Roaders. If an app passes `false` to the `intentResolver` parameter of `getAgent()` it is saying that it does not need a intent resolver UI - thats in the control of the app developer. 

Further, they (app developers) can already build their resolver UI or functionality by using the `findIntent` and `findIntentForContext` functions of the Desktop Agent API and if they have done so, or do not include any controls to raise an Intent. This should be the preferred solution as it works in both Desktop Agent preload interfaces and Desktop Agent Proxy / fdc3 for the web.

As per the DesktopAgent reference:

> `findIntent` is effectively granting programmatic access to the Desktop Agent's resolver. It returns a promise resolving to an AppIntent which provides details of the intent, its metadata and metadata about the apps and app instances that are registered to handle it. This can be used to raise the intent against a specific app or app instance.

https://fdc3.finos.org/docs/next/api/ref/DesktopAgent#findintent

As this already allows targetting of raised intents to specific apps or app instances, via data encoded in the `AppIntent`(s) returned, we should be good here already. 

Finally, note that I have seen someone wrap `raiseIntent` before, automatically call `findIntent` (if no target was specified) display a UI to allow the user to select an option then call the actual raiseIntent. Thats works with the current standard in any conformant desktop agent. The only issue I've seen is if you definitely want to start a new instance of an app - the semantics of `raiseIntent` are currently lacking in that regard as you can't firmly specify that. I've been tempted to suggest we modfythe `app` parameter to support that by changing:

```ts
raiseIntent(intent: string, context: Context, app?: AppIdentifier): Promise<IntentResolution>;
```

```ts
raiseIntent(intent: string, context: Context, app?: AppIdentifier | boolean): Promise<IntentResolution>;
```

Where setting `app == true` indicates that you want a new instance to be spawned and `app == false` indicates that you do NOT want a new instance spawned (pick an existing instance - they didn't specify which one so thats up to the DA). If thats to be fixed we'll need to raise a new issue.

**Comment by Roaders** [comment]
```
raiseIntent(intent: string, context: Context, app?: AppIdentifier | boolean): Promise<IntentResolution>;
```

this still doesn't allow you to specify that I want a new instance of particular app id though. I think it's more likely that someone would pick an app from the list and say I want a new instance than someone eaying I want a new instance of any app.

**Comment by kriswest** [comment]
You are correct, I was clearly still battling a bit of COVID brain fog last week. I think I meant set.the instanceId in the appIdentifier to true. It's that or add a second optional argument - although with that you can end up with a conflict when both app.instanceId and the new arg to spawn a new instance are set...

This is obviously a second issue that we should raise separately. As the original question been answered? Custom resolution by an app should be conducted through the API (meaning it works the same way, whichever interface you use). Let me know along with whether you want to raise the new app instance issue, I'm happy to if not.

**Comment by Roaders** [comment]
yes the original question has been answered. Thanks @kriswest
