### ISSUE TITLE
Question: How does Application metadata get into the app directory

### ISSUE THREAD

**Issue by Roaders** [finos/FDC3#1376]
### Question Area
 - [x] App Directory
 - [x] API
 - [ ] Context Data
 - [ ] Intents
 - [ ] Use Cases
 - [ ] Other

### Question

This might be answered in the docs (but I think I've read most of the docs so I probably would have come across it at some point) but I wondering how app instance metadata gets from an app (here I am thinking of an app running in a different browser window communicating with the DA via the DesktopAgentProxy and the communication protocol) back to the app directory (which I assume is owned by the DA).

I am thinking specifically of `title` (although now looking at the docs this is not an instance field). I am thinking specifically of text that will uniquely identify different instances of one app. For example if I have a 'view instrument' app I might have several open identified with the name of the instrument that the app is displaying.

How does the display name for the instance get from the instance to the app directory so when we display an intent resolver UI we can differentiate the different app instances.

Do we support this data changing during the lifetime of the app? If I open an instrument apples then navigate to bananas when the intent resolver opens does it still describe the app as apples or has it been updated to bananas?

**Comment by Roaders** [comment]
so in that case the app title (that might not be the correct property) such as "Instrument Viewer - Apple" that appears in the app resolver is generated by the DA at app opening time then I assume and is a DA concern - the app that is being opened cannot supply this data.

**Comment by kriswest** [comment]
Indeed,.it either comes from the app directory record (which is what's intended in the Standard), or the DA captures metadata some other way. I don't believe there's any explicitly stated requirement in the standard regarding the title, and certainly no way for the app to affect it through the API.
