### ISSUE TITLE
Add Google Analytics to Microsite (fdc3.finos.org)

### ISSUE THREAD

**Issue by brooklynrob** [finos/FDC3#138]
Add Google Analytics to Microsite (fdc3.finos.org) so we can track visits, sessions, traffic, referrers, etc.

**Comment by rikoe** [comment]
@brooklynrob @grizzwolf @mcleo-d @maoo this is very easy to do. See https://docusaurus.io/docs/en/site-config.html#gatrackingid-string.

Unfortunately I do not know the GA id to use for this. I suggest the FINOS team do a PR for this.

**Comment by mcleo-d** [comment]
@maoo or @grizzwolf - I'm more than happy to raise the PR if you can supply the GA id. Let me know using appropriate comms channels 👍

**Comment by brooklynrob** [comment]
@maoo and @grizzwolf have you had a chance to supply @mcleo-d the GA ID?

**Comment by mcleo-d** [comment]
Hi @rikoe - I've noticed this work item has remained open for a number of days. Can you physically assign the issue to @maoo and @grizzwolf so it appears in their order of work?

Many thanks,

James.

**Comment by grizzwolf** [comment]
HI @rikoe - Here is the GA id for FDC3:
FDC3: UA-89349362-8
