### ISSUE TITLE
Leaving App Channels

### ISSUE THREAD

**Issue by Charlotte981** [finos/FDC3#1380]
### Question Area
 - [ ] App Directory
 - [x] API
 - [ ] Context Data
 - [ ] Intents
 - [ ] Use Cases
 - [ ] Other

### Question
Is there a mechanism in the FDC3 standard for leaving app channels?
I'm currently looking at implementing channels in our fdc3 implementation, and realized that while there is a way to leave both user and private channels, I could not find one for app channels. It seems like if there is no way to leave an app channel, there could be a build up of no-longer used channel objects.

**Comment by kriswest** [comment]
Hi @Charlotte981 you are correct that there is no way to 'leave' an app channel. You can of course remove any listeners to the channel (`Listener.unsubscribe()`) and delete any references to the object, allowing for garbage collection in most languages that FDC3 is implemented in. That is a fairly standard approach in, for example, JavaScript where you don't explicitly destroy objects, just remove references to them. 

I'll close this as answered, however, If you foresee a problem here or would like to propose a change please reopen it or create a new issue for the proposal.
