### ISSUE TITLE
Question: Is there any guidance on how to handle unexpected contexts in an IntentHandler

### ISSUE THREAD

**Issue by Roaders** [finos/FDC3#1389]
### Question Area
 - [ ] App Directory
 - [ ] API
 - [ ] Context Data
 - [ ] Intents
 - [ ] Use Cases
 - [x] Other

### Question

If I raise a `StartCall` intent the expected context would most likely be a contact (for example `fdc3.contact`). Is there any information on what to do if an IntentHandler for `StartCall` receives a time range context for example or basically just something completely unexpected. There is nothing that ties intents to contexts when raising an intent so this is a pretty likely scenario - or at least one that we definitely need to handle.

I expect the answer to this is that it is an app implementation detail but I was wondering if there was an expectation around this.

**Comment by kriswest** [comment]
For most intent handlers, there is a type filter set in the appD record that would ensure they are not presented as an option for handling the intent if they don't handle that content type. 

The only situation where that is not the case is when the intent listener is dynamically registered (as per your other question #1388). If such cases I've always had the application check the type of the context and then ignore it if it doesn't handle that type making it, as you say, an app implementation issue. The intentHandler function can either resolve to `void` in that case, or `reject` with an error. In the latter case, the promise returned by `IntentResolution.getResult()` should be rejected with [`ResultError.IntentHandlerRejected`]*(https://fdc3.finos.org/docs/api/ref/Errors#resulterror) to pass on what happened.

**Comment by Roaders** [comment]
ok, thanks @kriswest - I think rejecting with that error is the best course of action.
