### ISSUE TITLE
Shall we have a Context Validator?

### ISSUE THREAD

**Issue by donbasuno** [finos/FDC3#141]
As we finalize JSON Schemas for the various Context Types, does it also make sense to build or integrate with some form of validator?

This would allow a user to easily verify that the context objects produced are correct

Maybe something like https://www.jsonschemavalidator.net/? It looks like be could just submit our schemas here - http://schemastore.org/json/

Thanks,

Johan

**Comment by rikoe** [comment]
Closing this in favour of #218
