### ISSUE TITLE
FDC3 for Web Browsers Discussion group 21st Nov 2024

### ISSUE THREAD

**Issue by kriswest** [finos/FDC3#1443]
## Group overview
Group convened to work on proposals to enable FDC3 use in a web browser, without the use of a browser extension.

The main proposal is now part of the current draft of FDC3 2.2 on the `mina` branch of the FDC3 repo and website (main/unreleased version), see:
- https://fdc3.finos.org/docs/next/api/ref/GetAgent
- https://fdc3.finos.org/docs/next/api/specs/browserDesktopAgents

Open Pull Requests: 
- #1309
- #1424
- #1434
- #1442

### Relevant issue tags
Current open issues that relate to the above concepts with the label: 
[![image](https://user-images.githubusercontent.com/1701764/222422435-9a27f7ab-f73a-4d89-90e7-8dee40361d8e.png)
](https://github.com/finos/FDC3/labels/FDC3%20for%20Web%20Browsers)

## Meeting Date
Thursday 21st November 2024 - 11am (US eastern timezone EST) / 4pm (London, GMT)

### Zoom info
- **[Join Zoom Meeting](https://zoom.us/j/96940294948?pwd=SjFibVdiN25QSWxva3FqRHY2RUFCdz09)**
- **Meeting ID:** 969 4029 4948
- **Passcode:** 636931
- **Dial-in:**
    | Country      | International Dial-in | Toll-free Dial-in |
    | :---        | :---        | :---        |
    | **US** | [+1 929 205 6099 (New York)](tel:+19292056099) | [877 853 5247](tel:8778535247) |
    | **UK** | [+44 330 088 5830](tel:+443300885830) | [0800 031 5717](tel:08000315717) |
    | **France** | [+33 1 8699 5831](tel:+33186995831) | [0 800 940 415](tel:0800940415) 
    | Find your local number | <https://zoom.us/u/ad2WVnBzb8> | |

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies).

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.
  
- A Discussion Group has no direct decision-making power regarding the FDC3 standard - rather it is intended that anything they propose or work on will result in proposals (via Github issues and PRs) for the Standards Working Group participants to consider and vote on for inclusion in the standard.

## Participation Requirements

**Note:** Meeting participants are expected to accept the terms of the FDC3 license (Community Specification License), understand the governance process and have a CLA in place.  

Please click the following links at the start of the meeting if you have not done so previously.

 - [View the CSL](https://github.com/finos/FDC3/blob/main/LICENSE.md)
 - [View the GOVERNANCE of the Project](https://github.com/finos/FDC3/blob/main/GOVERNANCE.md)
 - [Click here to start a PR](https://github.com/finos/FDC3/edit/main/NOTICES.md). 
   - Edit the page to add your details.
   - Hit the save button.
   - Click "Create Pull Request".
   - Click "Accept" on the EasyCLA dialog in the PR's discussion section.
 - [Click here to send email to become a voting participant on the FDC3 Project](mailto:fdc3-participants+subscribe@finos.org?subject=Please%20enroll%20me%20as%20an%20FDC3%20Standards%20Participant&amp;body=HI%2C%20my%20name%20is%20%3CFirstName%20LastName%3E%20and%20I'd%20like%20to%20formally%20participate%20to%20the%20FDC3%20standard%20process.%20I%20plan%20to%20contribute%20as%20%3Cindividual%7Con%20behalf%20of%20organizationName%3E%20and%20I%20have%20reviewed%20the%20policies%20described%20at%20https%3A%2F%2Fgithub.com%2Ffinos%2FFDC3%2Fblob%2Fmain%2FGOVERNANCE.md%20and%20read%20the%20license%20at%20https%3A%2F%2Fgithub.com%2Ffinos%2FFDC3%2Fblob%2Fmain%2FLICENSE%20.%20Thank%20you!")

## Tracking Attendance

**Note:** Meeting participants are expected to _add a comment to this GitHub issue_ in order that we can track attendance of FDC3 project meetings.  Please do this at the start of the meeting.
   
## Agenda
- [x] Convene & roll call, review meeting notices (5mins)
- [x] Review action items from previous meeting (5mins)
  - #1391
- [x] #1430
  - #1442
- [x] Update on the current status of implementation & discussion of how to get involved
  - PRs merged recently: 
    - #1386
    - #1387 was incorporated into the implementation PR (and provides useful TypeGuard functions)
    - #1438 and #1439 addressed minor errors introduced into the bridging schemas
    - #1427 and #1428 adjusted the reference UIs and removed some apps from the demos
    - #1403
- [ ] AOB & Adjourn

## Minutes
- Session Storage proposal (#1442) was reviewed.
  - The proposal was accepted by the meeting, subject further review for clarity. 
  - A deep link was added to simplify review. 
- Recent activity and merged PRs were reviewed with attendees and the current status of the implementation project discussed.
  - @kriswest stated that: the FDC3 community will ultimately have to take ownership of the additions to the codebase to support `getAgent`. Up until now @robmoffat has carried the implementation project. We only get his support (shared with other projects) as FDC3 is strategic initiative this year.
  - @robmoffat It is likely that FINOS will have different priorities next year which may not include FDC3 as a startegic initiative again. @kriswest Hence, it is doubly important that the community take over maintenance and onward development.
  - @kriswest: I'm currently working in the project to: 
    - improve the use of typing (replacing type overrides and the use of `any`), 
    - align the implementation with the connection flow in the documentation, and 
    - improve the separation between the WCP and DACP implementations.
  - @robmoffat Content has been added to the top-level README file in the fdc3-for-web-impl branch to describe the new layout of the repository and to help developers working on it get started.
  - @robmoffat also a number of issues have been created to track implementation tasks, see: https://github.com/finos/FDC3/issues?q=is%3Aopen+is%3Aissue+milestone%3A2.2+label%3A%22FDC3+for+Web+Browsers%22
- AOB
  - @Roaders' TSMorph PRs were discussed: They post-process the generated schemas and produce:
    - Unions of the different message types by type (`RequestMessage`, `ResponseMessage`, `EventMessage`), which enables better typing in code based on them: https://github.com/finos/FDC3/pull/1387#issuecomment-2419628543 
    - TypeGuard predicates (e.g. `isContextListenerUnsubscribeRequest`) that again help with typing.
  - An updated version was just raised as #1444 based on previous feedback
    - Some duplicated generated code was identified during the meeting, to be corrected
    - @robmoffat had already merged the PR into fdc3-for-web-impl and started using the generated code, adding in a set of constants for message type names. 
      - The constants were discussed and (perhaps) considered to be duplicating the types...
    - The performance of the type guards was discussed - they currently involve stringifying messages and then reparsing them using the quicktype generated convert functions, which validate against the schemas. This is potentially costly - but we are unsure as to how costly.
    - An alternative faster implementation would be to just check the type name without validating content - there are merits to both approaches. 
      - It was resolved to create fast `is*` functions and rename the existing ones (that perform validation) to `isValid*`
  - @kriswest recommended that we replace the quicktype generated `AppRequestMessage`, `AgentResponseMessage` and `AgentEventMessage` with the unions as they simply do a better job of typig the same objects.
## Action Items

- [x] ALL review SessionStorage docs PR for clarity #1442
- [x] @Roaders to incorporate feedback on TS Morph PR into #1444, @robmoffat and @kriswest to review and merge into fdc3-for-web-impl

## Untracked attendees

| Full name | Affiliation | GitHub username |
|-----------|-------------|-----------------|
|           |             |                 |

**Comment by paulgoldsmith** [comment]
Paul Goldsmith / Morgan Stanley

**Comment by Davidhanson90** [comment]
David Hanson / Morgan Stanley 🚀

**Comment by Roaders** [comment]
Giles Roadnight / Morgan Stanley

**Comment by robmoffat** [comment]
Rob mOfFaT / fINoS

**Comment by pvoznyuk** [comment]
Pavlo Vozniuk @ RBC CM

**Comment by watson-ew** [comment]
Chris Watson / Elgin White 👋

**Comment by novavi** [comment]
Derek Novavi / S&P Global

**Comment by VedPrakashJha-FMR** [comment]
Ved Jha / Fidelity Investments
