### ISSUE TITLE
What branch of the fdc3 conformance tests uses getAgent()?

### ISSUE THREAD

**Issue by Charlotte981** [finos/FDC3#1481]
### Question Area
 - [ ] App Directory
 - [x] API
 - [ ] Context Data
 - [ ] Intents
 - [ ] Use Cases
 - [ ] Other

### Question
In the FDC3 Web Browsers Discussion group meeting yesterday on the 19th of December, it was mentioned that there was a branch of the fdc3 conformance tests set up to use getAgent() instead of just window.fdc3. I have checked the 2_0_fdc3_for_the_web branch and it appears to use fdc3Ready() instead of getAgent(), so we were wondering if it is a different branch that supports it instead?
We were also wondering what branch of the finos/fdc3 repository has an fdc3 workbench implementation that works with getAgent()?

**Comment by kriswest** [comment]
I'm just looking at this as well @Charlotte981. The fdc3Ready function is actually replaced fdc3-for-web-impl (and derived branches) with a version that use `getAgent` so that is probably correct. The instructions Rob gave me are here: https://github.com/finos/FDC3/pull/1466#issuecomment-2554070141

Note that this is based on having https://github.com/finos/FDC3/tree/fdc3-for-web-impl-getAgent-refactor checked out and replacing the "@kite9/client" dependency with the lcoally checked out fdc3-get-agent pacakage. is that right @robmoffat? I don't see the @kite9/fdc3-get-agent dependency from your instrucitons so I assume you have local changes, one of which is swapping @kite9/client for @kite9/fdc3-get-agent (local checkout).

**Comment by kriswest** [comment]
@Charlotte981 heres the replacement `fdc3Ready` function (for interest's sake): https://github.com/finos/FDC3/blob/442956d906577fdac8bd1d0f75caf4f7611b6b1d/packages/fdc3-get-agent/src/index.ts#L16-L23

**Comment by robmoffat** [comment]
ok, sorry guys, looks like I fat-fingered the push yesterday when I was testing for Kris.

See: https://github.com/finos/FDC3-conformance-framework/blob/2_0_fdc3_for_the_web/package.json

In this version, it's referencing `@kite9/fdc3-get-agent` correctly.   

WRT the `fdc3Ready` function, this is what the conformance framework used previously, and it's still supported (deprecated) by the new `FDC3-for-web-impl` code versions and will be in 2.2.

**Comment by robmoffat** [comment]
> We were also wondering what branch of the finos/fdc3 repository has an fdc3 workbench implementation that works with getAgent()?

`fdc3-for-web-impl` will do you,. this also uses fdc3Ready currently.

**Comment by Charlotte981** [comment]
Awesome, thank you @kriswest @robmoffat for the update.

**Comment by kriswest** [comment]
closing as completed (feel free to reopen if further questions)

**Comment by Roaders** [comment]
@kriswest is this the long term goal for the workbench and conformance tests? To use this `fdc3Ready` function?

I was looking at the workbench and considering a PR that removes it and removed the utility that has a proxy for the agent implementation. I was thinking that we just use `await getAgent()` in all places that need it.

IMHO this would be simpler and easier to follow. Also closer to how people would use it in a real apps so more of an example of how to use it.

**Comment by kriswest** [comment]
Hi @Roaders, I can't speak for @robmoffat who implemented the change, but I suspect it was done that way for expediency and that both projects should switch to `await getAgent()` in due course. We could do with an issue raising for that and would gladly accept a PR for the change ;-) I'm still working on completing my own PR into fdc3-for-web-impl, but may get this after it goes in.

**Comment by Roaders** [comment]
I have a PR that's most of the way through for implementing that so maybe wait a few days till I'm able to finish that before spending the time on it @kriswest

**Comment by Roaders** [comment]
Created issue #1484 and Pr #1485 to migrate workbench to `getAgent()`
