### ISSUE TITLE
Intent Listener callback signature provides no means to return a value

### ISSUE THREAD

**Issue by nicholasdgoodman** [finos/FDC3#155]
## Support Question

Per [site documentation](https://fdc3.finos.org/docs/1.0/api/api-spec#resolution-object):
> If the raising of the intent resolves (or rejects), a standard object will be passed into the resolver function with the following format...

and [elsewhere](https://fdc3.finos.org/docs/1.0/api/DesktopAgent#intentresolution):
> IntentResolution provides a standard format for data returned upon resolving an intent.

However, the call signature for intent handlers is as follows:

```
addIntentListener(intent: string, handler: (context: Context) => void): Listener;
```

As written, the callback does not return a value (it is `void`). Even if we changed this callback signature to return a `data?: object` property to provide a value to the resulting `IntentResolution` object, it is not clear from this API what would happen if a given application has added multiple handlers for the same intent.

**Comment by rikoe** [comment]
@nicholasdgoodman, also see #127 where we have discussed this issue before.

You raise a good point about the result of how to deal with results returned by multiple intent handlers.

**Comment by nicholasdgoodman** [comment]
@rikoe - Oh sorry, realize that #127 is nearly the same as this topic, with the added question regarding multiple listeners. Feel free to close as duplicate.

**Comment by nicholasdgoodman** [comment]
Closing as duplicate.
