### ISSUE TITLE
broadcast has different semantics for channels and desktop agents

### ISSUE THREAD

**Issue by rikoe** [finos/FDC3#160]
According to the latest changes, desktop agent's broadcast is defined like this:
```ts
broadcast(context: Context): void
```
while channel's broadcast is defined like this:
```ts
broadcast(context: Context): Promise<void>
```

I really dislike that the pattern for these two operations do not match, and think it is very unintuitive for consumers.

Personally, I feel that `broadcast` should be fire-and-forget, it is not interesting to know if there was an error of some kind - if the user is not perrmissioned for the channel, or it doesn't exist, nothing will happen. This is in line with how the operation worked in 1.0.

We could change the top-level broadcast to also be async, but this would be a breaking change.

Compare:
```ts
fdc3.broadcast(context)
```
and
```ts
await fdc3.broadcast(context)
```
I do not think it is intuitive for broadcast to be async, or even to have to remember to put an await in front of it. I think I will often forget to do this, leading to brittle code.

**Comment by nicholasdgoodman** [comment]
Having an await-able `broadcast` call is curious, since its not clear when the call should complete. After all subscribers have received it? After it has been handed off to some controller (too implementation specific, IMO).

Like UDP, I agree broadcast should be fire-and-forget.

**Comment by nkolba** [comment]
@rikoe . @nicholasdgoodman  .  I agree.  Let's  keep it fire-and-forget.

**Comment by nkolba** [comment]
Addressed in PR and merged.
