### ISSUE TITLE
FDC3 Explained - demo app for beginners?

### ISSUE THREAD

**Issue by donbasuno** [finos/FDC3#165]
Increasing adoption, improve documentation and create tooling projects are all part of our 2020 roadmap - and coming more from the business side - something I care very much about. I think we all have ideas and demo apps lying around but I wanted to start this issue to gather all our ideas and maybe even do a PR or two.

Demo Apps are great but they don't necessarily show the inner workings of FDC3:
- what is providing the API? 
- what channels are technically available?
- how can I easily send a broadcast from an external app to make sure that my app is working?
- and so on...

I therefore suggest that our first endeavor should a "toolbox" - basically a simple html/javascript page that can be loaded in any container or tool that provides an FDC3 API.

Page loaded in standard Chrome:

![fdc3_explained_browser](https://user-images.githubusercontent.com/19268006/73411244-965b9e80-42fc-11ea-8d9b-8b7095adf545.png)

Page loaded via manifest in OpenFin:

![fdc3_explained_openfin](https://user-images.githubusercontent.com/19268006/73411257-a2dff700-42fc-11ea-89d1-129184840de5.png)

If possible we can host the page in our repo as well as manifest for running it in different environments. I created a working prototype but was not able to run it directly from GitHub - you will need to download the files:

Page: https://github.com/donbasuno/FDC3/blob/master/toolbox/fdc3_explained.html
OpenFin Manifest: https://github.com/donbasuno/FDC3/blob/master/toolbox/openfin/fdc3_explained.json

The code is not pretty (add a Men at Work gif and you are back in the 90s) but the basic broadcast works and can be tested against another demo app.

Please let me know your thoughts!

Thanks,

Johan

**Comment by jonathanteperJPMC** [comment]
demo apps and step-by-step tutorials are a great way for developers to quickly grasp the concepts, with as few misconceptions as possible.

**Comment by donbasuno** [comment]
Hi all,

bumping this one as there has been significant progress on FDC3 Explained with proper support for 1.1 and 1.2.

It's also possible to run the app directly so just point your containers to:

https://donbasuno.github.io/FDC3/toolbox/fdc3_explained.html

Best regards,

Johan
