### ISSUE TITLE
Browser implementation

### ISSUE THREAD

**Issue by cbranca** [finos/FDC3#175]
## Support Question

Hi all. I have two components that supports FDC3. In an desktop agent (f.e. openfin) I can use the opefin fdc3 service (the openfin fcd3 api implementation) to let them talk. But I need to make these two components talk also inside a browser.

In a desktop agent we can use FDC3 for these scenarios:
- communication between apps (components) inside the desktop agent main window
- communication between apps (components) between the desktop agent main window and child windows
- communication between apps (components) between child windows

In a browser, (inside an Angular SPA), the scenarios I would like to cover are:
- communication between apps (components) inside the same window
- communication between apps (components) between window and child windows

A browser implementation would reduce the effort to use different type of communication (window events in browser and fdc3 in desktop agents).
Does it make sense to make a browser FDC3 api implementation (built on top of window events) in order to let them talk with the same api?

Thank you.

**Comment by nkolba** [comment]
Hi @cbranca .  

I agree that it would be convenient if you could use the same apis across these different scenarios.

In-window and (window to window in the same app) communication isn't something that FDC3 explicitly addresses today - but nothing in the standard precludes such a use case.  

So yes, creating a pure-browser implementation could be an interesting exercise.
