### ISSUE TITLE
Should we have an FDC3 URI?

### ISSUE THREAD

**Issue by donbasuno** [finos/FDC3#18]
Filing for discussion and reference - I think this is the best place...

Based on an FDC3 use case - there might be a need for an FDC3 uri (eg fdc3://) so that any application on the desktop could send context to FDC3 without requiring plugins, etc.

**Comment by nkolba** [comment]
I like the idea.  However, I think there are technical challenges with having an fdc3 specific protocol handler (who would own it?).  Maybe a better approach would be to standard REST apis that mapped to FDC3 and could be implemented under a number of different protocols.

**Comment by donbasuno** [comment]
Thanks @nkolba,

couldn't the ownership be handled in the same way as eg HTTP or SIP? User can select which app handles with the standard OS controls?

![image](https://user-images.githubusercontent.com/19268006/63524645-462e1400-c4f4-11e9-8778-2031f8c6e4df.png)

Best regards,

Johan

**Comment by rikoe** [comment]
@donbasuno if only it were that easy! From my experience, to register a custom protocol handler, you need to add it to a specific location in the Windows Registry, referencing the DLL or application that responds to the protocol handler.

This has to be done at install time, and requires an installation with administrative privileges. There is no UI in Windows for registering custom protocol handlers.

All of the protocol handlers in your example are official standardised IETF protocols, e.g. https://tools.ietf.org/html/rfc5341 for the `tel://` protocol. One would have to get the fdc3 protocol standard officially by a recognised standards body, and then integrated into operating systems.

Even then, the protocol assignment only works if the target application supports it, e.g. on my Mac, if I use the `sms://` protocol in Chrome, it hands off to the operating system, which then opens the iMessage application in response.

**Comment by brooklynrob** [comment]
Per discussion at [2019.12.5 FDC3 API Project Meeting](https://finosfoundation.atlassian.net/wiki/spaces/FDC3/pages/1255997614/2019-12-05+Meeting+Notes), this issue will remain open and there still appears to be interest in pursuing it, at least provided there is a core need/use case for adding this.

**Comment by rikoe** [comment]
As discussed during #208, there is currently no way for FDC3 to provide a URI protocol handler unless it has its own installer, this is something implementers would have to do, and because it would clash between multiple providers, probably not likely.

To elevate to a default protocol included in operating systems, it would need to become an IETF standard, and it is simply too early in FDC3's lifetime for this.
