### ISSUE TITLE
Overlap between FDC3 context data and FINOS financial objects

### ISSUE THREAD

**Issue by dcj99** [finos/FDC3#195]
## Support Question

HI there

On the call on 5th May Nick mentioned that next steps might include adding new context data types including RFQs and orders. What would be the overlap between this and the FINOS financial objects program, which is also working on standards for this kind of thing?

Thanks!

David

**Comment by brooklynrob** [comment]
Tagging in @hammadnyc (lead from Citi for FO) for his visibility

**Comment by rikoe** [comment]
@dcj99 good question - the idea has always been that we work closely with Financial Objects on the data types we standardise. They are responsible for the business domain and FDC3 for the technical mapping (in our case to JSON and JSON Schema), although others can adopt the FO recommendations as well.

We would like to continue this arrangement as much as possible when considering more advanced types like orders and RFQs - the existing contact, instrument etc. objects at Financial Objects were proposed by FDC3 originally, and they intentionally mirror each other.

**Comment by nkolba** [comment]
Closing this issue, as it seems the question has been answered (thanks @rikoe!).
