### ISSUE TITLE
May 15 - PMC Meeting

### ISSUE THREAD

**Issue by nkolba** [finos/FDC3#196]
## Date
Friday 15 May 2020 - 9am EST

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username
- Nicholas Kolba, genesis, @nkolba 
- Riko Eksteen, Adaptive, @rikoe 
- Johan Sandersson, FactSet, @donbasuno 
- Brody Wacker, JPM, @bwacker1
- Aitana Myohl, FINOS, @aitana16 

## Agenda
- [x] Convene & roll call (5mins)
- [ ] Review action items from previous meetings (5mins)
- [ ] Review move to github (5 mins)
- [ ] Issue templates for the standards WG (20 mins)
- [ ] Marketing (20 mins) see notes from @toshaellison 
- [ ] AOB & Adjourn (5mins)

## Decisions Made
- [ ] ...

## Action Items
- [ ] ...

### WebEx info
- [Meeting Link](https://finos.webex.com/finos/j.php?MTID=mb24e0868b724abcfa92221ca14207e14)
Description:FDC3 PMC Meeting
Meeting number: 663 444 364
Dial in: 
+1.415.655.0003 USA Toll
+44-20319-88141 UK Toll
Access code: 663 444 364

**Comment by aitana16** [comment]
hi @nkolba I'd like to add the following items to the agenda, right after the roll call. thanks!

- FINOS Point of Contact (meeting attendance,...)
-  Link to [5/1 Meeting minutes](https://finosfoundation.atlassian.net/wiki/spaces/FDC3/pages/1584464025/2020-05-01+Meeting)

**Comment by nkolba** [comment]
Present

**Comment by rikoe** [comment]
👋

**Comment by donbasuno** [comment]
🙌

**Comment by nkolba** [comment]
Notes:

New Issue Templates:

- *Question*
    - Area of question
    -  Description
- *Bug / minor issue*
     - Area of issue
     - Description
- *Enhancement Request*
     - Use case   (1 or more)
     - Workflow description
     - Workflow examples
     - Other information (optional)

@nkolba  to add new templates, will send draft comm for Standards process to group

Expectation is that the agenda for the standards WG will largely be set by the open Enhancement Request issues and active PRs (that originated as Enhancement Requests).  

House Keeping to do:
- Update links / content on site to remove confluence links
- Clean up github wiki (don't need much content here - just port over relevant information from the confluence overview page)
- Add deprecated notice in confluence 
- Update contributing.md to reflect new issues process

@nkolba  to post issues for housekeeping items
