### ISSUE TITLE
test meeting 

### ISSUE THREAD

**Issue by nkolba** [finos/FDC3#200]
@maoo @rikoe - this is a test of the meeting attendance automation.  Please comment on this issue to mark your presence (and test the integration).  Thanks!

**Comment by maoo** [comment]
I like the issue number... #200 !

**Comment by rikoe** [comment]
Present

**Comment by maoo** [comment]
The following items have been added to metrics data (not merged yet tho)

```
maoo@finos.org,Maurizio Pillitu,FINOS,maoo,FDC3,FDC3,PROJECT,2020-05-18
riko@weareadaptive.com,Riko Eksteen,Adaptive Financial Consulting,rikoe,FDC3,FDC3,PROJECT,2020-05-18
```

@nkolba , you're not part of it as you haven't commented the issue; may be the perfect excuse to try the reindexing:
1. add a comment
2. remove the `indexed` label
3. wait a minute
4 add the `indexed` label

**Comment by nkolba** [comment]
test indexing

**Comment by nkolba** [comment]
@maoo - reindexed

**Comment by finos-admin** [comment]
It worked!

```
maoo@finos.org,Maurizio Pillitu,FINOS,maoo,FDC3,FDC3,PROJECT,2020-05-18
riko@weareadaptive.com,Riko Eksteen,Adaptive Financial Consulting,rikoe,FDC3,FDC3,PROJECT,2020-05-18
nick.kolba@genesis.global,Nick Kolba,Individual Contributor,nkolba,FDC3,FDC3,PROJECT,2020-05-18
```

Removing label to cleanup the index.

@nkolba , @rikoe - thanks for enabling this feature, as it helps us consolidating collaboration on GitHub. Let me know if you're interested to enable this on other FINOS projects you're involved with.
