### ISSUE TITLE
Standard WG Meeting - May 28th, 2020

### ISSUE THREAD

**Issue by nkolba** [finos/FDC3#202]
## Date
Thursday 28 May, 2020 - 10am EST

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username
- ...

## Agenda
- [ ] Convene & roll call (5mins)
- [ ] Review action items from previous meetings (5mins)
- [ ] Review enhancement issues (40 mins)
- [ ] AOB & Adjourn (10mins)

## Decisions Made
- [ ] ...

## Action Items
- [ ] ...

### WebEx info
- [Meeting Link](https://finos.webex.com/finos/j.php?MTID=ma4b1de1b9f691d89e4b2ff380ec9687c)
Meeting number: 665 568 411

*More ways to join*
- Join by video system: 
   - Dial 665568411@finos.webex.com
   - You can also dial 173.243.2.68 and enter your meeting number
- Join by phone
   - +1-415-655-0003 US Toll
   - +44-20319-88141 UK Toll
- Access code: 665 568 411

**Comment by nkolba** [comment]
present

**Comment by rikoe** [comment]
present

**Comment by sgd2z** [comment]
!fp

**Comment by donbasuno** [comment]
here!

**Comment by ggeorgievx** [comment]
Present ✅

**Comment by sean-ciq** [comment]
Here!

**Comment by chedzoir** [comment]
Here...

**Comment by neslob** [comment]
checked in

**Comment by pjbroadbent** [comment]
👋

**Comment by vmehtafds** [comment]
🎁

**Comment by zhenyakovalyov** [comment]
here

**Comment by aitana16** [comment]
here!

**Comment by jmedows** [comment]
present

**Comment by thorsent** [comment]
here

**Comment by dcj99** [comment]
here!

**Comment by kriswest** [comment]
present

Kris West
Director of Solutions Engineering
p: +1 800 821 8147  m: +44 (0)7715104292
w: www.chartiq.com  e: kris@chartiq.com
[image: https://www.chartiq.com/chartiq-webinar-series/]
<https://www.chartiq.com/chartiq-webinar-series/>
