### ISSUE TITLE
Add Request/Response - Remote Procedure call style interaction

### ISSUE THREAD

**Issue by lspiro-Tick42** [finos/FDC3#203]
### Use Case:
In order to support work flow type logic, where a user can start a task in one application and then use other applications to complete the task. Using other apps may refer to moving focus to a window from the other app (with context) or possibly requesting some values from that app or other forms of integration.

For example: 
TBA

### Workflow Description
TBA

### Workflow Examples
TBA

### Additional Information
I think attempts to extend Intents to handle these kind of use cases is a mistake, and that it is much better to define a true Request/Response API with control over selecting an Application Instance to respond to the request, receiving responses, controlling whether the call should be Synchronous or not are better suited to a dedicated API rather than trying to force these into the Intents.

A solution to this would be look at the Interop API defined in the Plexus project, https://github.com/finos/plexus-interop-desktop-api/blob/master/src/client-api.ts  which defines Applications, Application Instances, Request/Respoinse, Discovery and more and look at bringing some or all of this into FDC3.

Probably the most important caveat is that request/response and other interop constructs to break the 'no prior knowledge' approach of the FDC3.

**Comment by nkolba** [comment]
Hi Leslie,

Would you be able to add a Workflow Description, Workflow Examples, and a Use Case example to this issue so that we can get it on the agenda for the Standard WG?

**Comment by mcleo-d** [comment]
@lspiro-Tick42 - Just bumping this issue in case you didn't see @nkolba's request for the following items to be added to this issue ...

- Workflow Description
- Workflow Examples
- Use Case example

Thanks 🚀 

James.

**Comment by rikoe** [comment]
@lspiro-Tick42 please remember to fill out this issue with more detail, it's been open for quite a long time. Otherwise I propose who close it for now, as it is easy enough to open a new one (or reopen this one) when you have more detail.

**Comment by lspiro-Tick42** [comment]
Regarding relevance to https://github.com/finos/FDC3/labels/channels%20feeds%20%26%20transactions disucssion group.

The FINOS API specified [here](https://github.com/finos/plexus-interop-desktop-api/blob/master/src/client-api.ts), provides a well thought out and 'real' set of API's to manage instances and also implement 'Request/Response' methods and Streaming, which are both mentioned by Kris as goals for Channels, Feeds and Transactions. 

This API is implemented by Glue42 and also separately by Deutsche Bank (as part of their Plexus/Autobahn broker)

**Comment by kriswest** [comment]
Hey @lspiro-Tick42, is there more to your suggestion that 'go use plexus'? How do you suggest said APIs are used by the FDC3 standard? Should we follow a similar pattern? If so we need to extract that into a proposal and then a PR.

I'm going to present a proposal for feeds today and will post it to the issue afterwards. Happy to compare notes later.

**Comment by lspiro-Tick42** [comment]
I am closing this issue for now. I think that this is important, but I also agree with the feedback that this is too broad for 2.0, I also have too much other stuff to do, to provide the time to move this forward. Finally I think that the other two issues I have proposed (Adding ability to get and set application state and provide a Notification API) are simpler will have more impact for most FDC3 users.
