### ISSUE TITLE
May 29, 2020 PMC Meeting

### ISSUE THREAD

**Issue by nkolba** [finos/FDC3#205]
## Date
Friday 29 May 2020 - 9am EST

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username
- ...

## Agenda
- [ ] Convene & roll call (5mins)
- [ ] Review action items from previous meetings (5mins)
- [ ] Review and groom issues backlog (20 mins)
- [ ] 1.1 Marketing / Messaging updates (20 mins)
- [ ] AOB & Adjourn (10mins)

## Decisions Made
- [ ] ...

## Action Items
- [ ] ...

### WebEx info
- [Meeting Link](https://finos.webex.com/finos/j.php?MTID=mb24e0868b724abcfa92221ca14207e14)
Description:FDC3 PMC Meeting
Meeting number: 663 444 364
Dial in: 
+1.415.655.0003 USA Toll
+44-20319-88141 UK Toll
Access code: 663 444 364

**Comment by nkolba** [comment]
present

**Comment by donbasuno** [comment]
Johan was here

**Comment by rikoe** [comment]
So was Riko
