### ISSUE TITLE
Create typescript definitions for FDC3

### ISSUE THREAD

**Issue by vmehtafds** [finos/FDC3#206]
## Enhancement Request
Should we create a `@types/fdc3` package for typescript definitions for `window.fdc3` global object?

### Use Case:
Currently we are using `openfin-fdc3` npm library to pull in FDC3 API in our TypeScript code.
This has been great as it provides typescript definitions along with it and makes development easier.
We would like to move to using `window.fdc3` object instead but that doesn't come with any types.

I feel this has been talked about few times in our meetings as a good idea but I didn't find any official issue around it. Feel free to close if it is a duplicate.

**Comment by rikoe** [comment]
I think this is a great idea, and something I have suggested in the past as well. We have started putting together some typings for FDC3 internally, and would be happy to see if we can share them.

**Comment by kriswest** [comment]
We were literally just about to submit the same request!

**Comment by nkolba** [comment]
@vmehtafds, we will be moving this forward.  Please see issue #218  .  Closing this issue in the meantime.
