### ISSUE TITLE
publish NPM module for TS interface

### ISSUE THREAD

**Issue by nkolba** [finos/FDC3#21]

**Comment by rikoe** [comment]
Closing for now, until more people are asking for it.

**Comment by brooklynrob** [comment]
Per discussion at [2019.12.5 FDC3 API Project Meeting](https://finosfoundation.atlassian.net/wiki/spaces/FDC3/pages/1255997614/2019-12-05+Meeting+Notes), this issue can be closed, which @rikoe has done.
