### ISSUE TITLE
Context Equivalent of RaiseIntent

### ISSUE THREAD

**Issue by sgd2z** [finos/FDC3#213]
### Use Case:
User selects intent as opposed to intent being required in the API call. 

For example: 
User clicks on a contact. With a contact, the user can have multiple possible Intents. So the user can select one of those intents - "StartChat", "Email", "StartCall, "AddToAddressBook", "OpenInCRM" etc.

### Workflow Description
User clicks on a UI representation of a context
System shows UI with possible Intents/Resolvers
User selects an Intent then raiseIntent is automatically called with the intent and context

### Workflow Examples
User clicks on a contact
System shows a UI to select possible intents and Applications that can resolve these intents.
Caller gets back response data which includes the selected Intent & IntentResolution

### Additional Information
This is currently difficult because it requires two API calls:
- findIntentsByContext 
- raiseIntent 
As an app developer it is not immediately obvious how to combine these APIs in a convenient way. findIntentsByContext does result in a list of intents and then the developer could potentially call that, get the response and then show a UI and raiseIntent from that UI. It would be much more convenient to have that dealt with under the hood so it becomes the responsibility of the desktop integrator as opposed to the app developer.

### Potential solutions
Modify raiseIntent to work without an intent specified:
e.g. 
```
raiseIntent(null, context): Promise<IntentResolution>;
```

Add a new API:
```
raiseContext(context): Promise<IntentResolution>;
```

**Comment by rikoe** [comment]
@sgd2z passing null for the first parameter to skip the second feels like an anti-pattern. What I would propose is the following:

```ts
  // two find intent methods
  findIntent(intent: string, context?: Context): Promise<AppIntent>;
  findIntentsByContext(context: Context): Promise<Array<AppIntent>>;

  // two symmetrical raise intent methods
  raiseIntent(intent: string, context: Context, target?: string): Promise<IntentResolution>;
  raiseIntentForContext(context: Context): Promise<IntentResolution>
```

Would `raiseIntentForContext` need an optional `target` parameter as well? I am tempted to say, based on intended usage, no.

Anyone else like to opine?

**Comment by lspiro-Tick42** [comment]
This would be the first call (I think) which requires an FDC3 API implementation to show a UI. This doesn't seem like a good idea. 
Could we just include a simple JavaScript sample about how to do it, using the findIntent and raiseIntent methods ?

**Comment by rikoe** [comment]
@lspiro-Tick42 I tend to agree, I don't think it's necessary either, but people were adamant at the previous WG meeting that it was needed 🤷‍♂️

**Comment by kriswest** [comment]
I disagree that this would be the first call to require a UI, in the specification under Intent Resolution it says:
> Raising an Intent will return a Promise-type object that will resolve/reject based on a number of factors.
>
>Resolve
>    ...
>    Intent was ambigious, a resolution was chosen by the end user and the chosen application was launched succesfully.
(https://fdc3.finos.org/docs/1.1/api/spec#resolve)

I.e. if there are two apps that can resolve an event, and you didn't provide a target, a UI is required for resolution so that the user can choose.  Your only alternative is to arbitrarily pick one or:
> Reject
>    ...
>    The intent was ambiguous and the resolver experienced an error.
(The error being that you don't have the necessary UI). 

If you want to create an implementation with no UI then you'd do the same thing. You can still resolve if there is only one app with a single intent that has a matching context.

**Comment by sgd2z** [comment]
Didn't have the opportunity to make a video but here is the problem described in pictures:
User clicks on a Symbol and is shown potential intents (find intents by context). This is something an app developer can do with FDC3. One problem is that every app developer will make something different, making a desktop integration platform not look standard:
![image](https://user-images.githubusercontent.com/18012933/88082355-afc50100-cb4f-11ea-93c9-93ef242cc17b.png)

Now, let's say there are multiple apps that can resolve that intent. The app developer now needs to make their menu complicated. In the actions on the above menu - View Chart with AppX, View Chart with AppY. Now we get to the third problem. What if there are several instances of the app open. How does the developer let the user select an open instance vs opening a new instance? The only viable option the developer has is to show the simple menu and then just call raiseIntent and let the desktop integration platform deal with the intent.

Now once the integration platform gets the Intent, it will show up another intent resolver, which will finally allow the user to perform the action they requested with the proper app or app instance.
![image](https://user-images.githubusercontent.com/18012933/88083598-42b26b00-cb51-11ea-92a0-17f9863996f7.png)

Instead, if the app developer could call raiseContext and the desktop integration platform would handle it from that point, they wouldn't need multiple API calls, the user experience would be seamless and consistent across applications and we could deal with all of intent selection and resolver selection in a single consistent UI.

**Comment by rikoe** [comment]
Thanks @sgd2z for this explanation, it makes the use case much clearer.

**Comment by lspiro-Tick42** [comment]
I understand the use case, and the UI solution, the question for me is whether we need to specify a UI piece in the API. Everything you describe can be handled with the API as it currently exists, hence my suggestion to code this as a JavaScript helper showing how the existing API's can be used to deliver this. 
Whilst this does mean that the typical context menu intent is likely to be different from app to app, that seems appropriate to me since each app will have different UX and UI styles.
The only caveat to this is the question of directing a raiseIntent call to a specific instance of an app. IMO this is tied to general request/response logic in FDC3 (which is currently missing)

**Comment by sgd2z** [comment]
@lspiro-Tick42 - I think you missed the second part of the problem described above. An Intent Resolution UI is already required for the spec. Not having something where multiple intents are possible just makes the experience sub optimal for both developers and end users.
