### ISSUE TITLE
PMC Meeting - June 26, 2020

### ISSUE THREAD

**Issue by nkolba** [finos/FDC3#214]
## Date
Friday, 26 June 2020 - 9am EST

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username
- ...

## Agenda
- [ ] Convene & roll call (5mins)
- [ ] Review action items from previous meetings (5mins)
- [ ] AOB & Adjourn (10mins)

## Decisions Made
- [ ] ...

## Action Items
- [ ] ...

### WebEx info
- [Meeting Link](https://finos.webex.com/finos/j.php?MTID=mb24e0868b724abcfa92221ca14207e14)
Description:FDC3 PMC Meeting
Meeting number: 663 444 364
Dial in: 
+1.415.655.0003 USA Toll
+44-20319-88141 UK Toll
Access code: 663 444 364

**Comment by aitana16** [comment]
Hi @nkolba I'm unable to edit the issue to add content to it. Sharing my notes from today's meeting below:

- Introduced Vedha Tejuja (JPMC) to the PMC 
- Discussed Factset participation in PMC
- Discussed Focus of FDC3 project in a post-programs world: product management, invite more participants to PMC
- Discussed FDC3 focus project status during Q2 and next steps: communicate progress to FINOS board (next board meeting is on July 15th); it's understandable that this has been a challenging and unique quarter
- [ ] Agreement to cut length of PMC meetings to 30 minutes going forward (@aitana16 to adjust calendar invite)

**Comment by nkolba** [comment]
Thanks @aitana16 !
