### ISSUE TITLE
DesktopAgent.ts missing getCurrentChannel

### ISSUE THREAD

**Issue by mattjamieson** [finos/FDC3#216]
### Area of Issue
[ ] App Directory
[X] API
[ ] Context Data
[ ] Intents
[ ] Use Cases
[ ] Other

### Issue Description: 
src/api/DesktopAgent.ts is missing
```typescript
  getCurrentChannel() : Promise<Channel>;
```

**Comment by nkolba** [comment]
thanks @mattjamieson !  this is definitely missing from the .ts
