### ISSUE TITLE
DesktopAgent summary on API docs has wrong return type for getCurrentChannel

### ISSUE THREAD

**Issue by mattjamieson** [finos/FDC3#217]
### Area of Issue
[ ] App Directory
[X] API
[ ] Context Data
[ ] Intents
[ ] Use Cases
[X] Other

### Issue Description: 
The summary of the ```DesktopAgent``` interface at the top of https://fdc3.finos.org/docs/1.1/api/ref/DesktopAgent has the incorrect return type for getCurrentChannel. It should be:
```typescript
  getCurrentChannel() : Promise<Channel>;
```

**Comment by nkolba** [comment]
thanks @mattjamieson !  Tagging as a good first issue...
