### ISSUE TITLE
Interested in FDC3 Tooling

### ISSUE THREAD

**Issue by nkolba** [finos/FDC3#218]
This issue is a placeholder for those interested in getting involved with FDC3 tooling projects.  Please reply in comments if you are along with whatever specific interests you have!

There are a few projects ideas that have come up recently.  These are:

- Publishing FDC3 typescript libraries in NPM (Issue #206)
- The FDC3 Explained App (Issue #165)
- A Context Validator (Issue #141)
- Demo apps in general

Thanks!

**Comment by petyosi** [comment]
Interested in helping with the typescript libraries.

**Comment by rikoe** [comment]
🖐️

**Comment by kriswest** [comment]
We are interested in putting someone forward (possible a couple of people from different teams). Typescript libraries, a context validator and demo apps, in general, are all of interest.

**Comment by nkolba** [comment]
@petyosi @rikoe @kriswest .  Terrific!    Sounds like the typescript libraries is the place to start.   If everyone agrees, I'll get a repo created for us to collaborate around.

**Comment by rikoe** [comment]
Incubating repository: https://github.com/nkolba/fdc3-tools

I have added an initial attempt at an fdc3 types package, for those who want to check it out.
