### ISSUE TITLE
Intent resolution data clarification

### ISSUE THREAD

**Issue by pgn-vole** [finos/FDC3#219]
### Question Area
[ ] App Directory
[x] API
[x] Context Data
[x] Intents
[ ] Use Cases
[ ] Other

##  Question

Referring to the API specification, an intent resolution may contain a payload attached to it. This piece of data, as far as I understand, would have been computed by the handler of that intent.
Reference:
https://fdc3.finos.org/docs/1.0/api/api-spec#resolution-object

However, looking at the specification of Intent listener it is not clear to me how does one Intent handler actual does provide this payload back.
Reference:
https://fdc3.finos.org/docs/1.0/api/DesktopAgent#addintentlistener 

```jsx
//Stage order intent handler impl

fdc3.addIntentListener('StageOrder', () =>{
  const order = doStageOrder()
  // How do I provide it back? 
})
```

Could you please clarify that area?

**Comment by rikoe** [comment]
This is an outstanding bug in the API that will be addressed by the upcoming 1.2 release. It is not currently possible to return data with the API as is. See #201 and #127 and #155.

We discussed this at our standards working group meeting last week, in fact.

**Comment by pgn-vole** [comment]
Good to hear that it is looked at! Is there a draft spec of the 1.2 version which is publicly available ?

**Comment by rikoe** [comment]
Nope, it is relatively early on in the process. See #201 for a recent straw man proposal about how this could work. Please join in on the discussion, and attend our standard working group meetings!

**Comment by rikoe** [comment]
Closing in favour of #201
