### ISSUE TITLE
PMC Meeting - July 10, 2020

### ISSUE THREAD

**Issue by nkolba** [finos/FDC3#221]
## Date
Friday, 10th July 2020 - 9am EST

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username
- ...

## Agenda
- [ ] Convene & roll call (5mins) 
- [ ] Review action items from previous meetings, and outstanding [issues](https://github.com/finos/FDC3/issues) (15 mins)
- [ ] AOB & Adjourn (10mins)

## Decisions Made
- [ ] ...

## Action Items
- [ ] ...

### WebEx info
- [Meeting Link](https://finos.webex.com/finos/j.php?MTID=mb24e0868b724abcfa92221ca14207e14)
Description:FDC3 PMC Meeting
Meeting number: 663 444 364
Dial in: 
+1.415.655.0003 USA Toll
+44-20319-88141 UK Toll
Access code: 663 444 364

**Comment by rikoe** [comment]
Here

**Comment by nkolba** [comment]
here

**Comment by aitana16** [comment]
hi!

**Comment by mattjamieson** [comment]
Here

**Comment by kriswest** [comment]
here

**Comment by nkolba** [comment]
@rikoe @mattjamieson @kriswest @lspiro-Tick42 @donbasuno @aitana16.   As per our discussion, I've created a placeholder repo for tooling here: https://github.com/nkolba/fdc3-tools
