### ISSUE TITLE
readme on finos/fdc3 repo needs updating

### ISSUE THREAD

**Issue by nkolba** [finos/FDC3#223]
## Minor Issue
The readme for the FDC3 repo is out of date

### Area of Issue
https://github.com/finos/FDC3/blob/master/README.md

### Issue Description: 

- Link to FINOS Wiki is out of date (confluence wiki is deprecated) .  Link to relevant WG information on Github.  
- Roadmap is out of date and doesn't reflect the new WG structure. We should consider not having a roadmap on the readme.
- There are hard coded links to 1.1 standards.  We should probably not have hard-coded links to specific versions - as this is hard to maintain and will likely go stale.

**Comment by rikoe** [comment]
@nkolba I recall having the roadmap on the readme was a FINOS requirement, as per https://github.com/finos/project-blueprint/blob/master/README.template.md

@aitana16 any thoughts on this?

**Comment by aitana16** [comment]
Hi @rikoe following up on our webex conversation earlier today. As we discussed, it is a requirement to have your roadmap posted on the readme file, and the idea behind it is to make it easily accessible to contributors who arrive at the FDC3 repo without prior knowledge or context on the project. However, it's not required that the roadmap is in .md format which is static and probably not the most adequate for a roadmap. If you're keeping your roadmap in a different format, feel free to add a link to it into the readme file. I hope this helps, please let me know if you have any further questions.
/ cc @nkolba @maoo

**Comment by rikoe** [comment]
Fixed by #275
