### ISSUE TITLE
Represent FX currency pairs (e.g. GBPUSD) with fdc3.instrument context type

### ISSUE THREAD

**Issue by rikoe** [finos/FDC3#227]
### Use Case

An application wants to raise an intent - or broadcast context data - for an FX currency pair. The standardized fdc3.instrument type only really supports stocks, and all the examples so far are stock-based. This use case also really extends to other types of instruments, e.g. commodities, bonds or derivatives.

#### For example 
An FX trading application like [Reactive Trader](https://weareadaptive.com/showcase/) wants to raise a `ViewChart` intent to launch a related application to display a trade with detailed intraday or historical data for the GBPUSD (sterling-dollar) currency pair.

### Workflow Description

In an FX trade blotter, have a "View Chart" button that raises the relevant intent, and launches a charting application for FX, that displays a chart for the relevant currency pair.

### Workflow Examples

```ts
const ccyPair = {
  type: 'fdc3.instrument',
  id: {
    // what goes here?
  }
}

fdc3.raiseIntent('ViewChart', ccyPair)
```

### Additional Information

We are currently approximating this use case with the following type, which is not ideal:

```ts
const ccyPair = {
  type: 'fdc3.instrument',
  id: {
    ticker: 'GBPUSD'
  }
}
```

**Comment by lspiro-Tick42** [comment]
I think using id 'GBPUSD' is OK, but I think we should add the optional fields that allow the instrument to be better described.
my proposal is that we use the Bloomberg originated OpenFIGI classification https://www.openfigi.com, so the currency pair would look like

const ccyPair = {
  type: 'fdc3.instrument',
  securityType: 'cross',
  securityDescription: 'GBPUSD Curncy',
  id: {
    ticker: 'GBPUSD'
  },
 id1: {
    ticker: 'GBP'
  },
 id2: {
    ticker: 'USD'
  },
}

We could also look at using OpenCalais fields (Refinitiv are FINOS members) https://www.refinitiv.com/en/products/intelligent-tagging-text-analytics
But I think its scope is broader so it's harder to apply to just the Instrument definition, but we could ask Refinitiv if they are interested in us referencing OpenCalais in our context types, and if so whether they would assign someone to work with us.

**Comment by rikoe** [comment]
As discussed in #248, we will continue to use "ticker" for currency pairs, as OpenFIGI already does this, and look to add "instrumentType" and "marketSector" properties to the FDC3 instrument type to help distinguish.
