### ISSUE TITLE
PMC Meeting - July 24, 2020

### ISSUE THREAD

**Issue by nkolba** [finos/FDC3#230]
## Date
Friday 24 July, 2020 - 9am EST

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username
- ...

## Agenda
- [ ] Convene & roll call (5mins)
- [ ] Review action items from previous meetings (5mins)
- [ ] Update on tooling projects
- [ ] Context Data approach - what can the PMC do to help move this issue forward?
        - state of the FO Group
         - Prior art
         - Other ideas
- [ ] AOB & Adjourn (10mins)

## Decisions Made
- [ ] ...

## Action Items
- [ ] ...

### WebEx info
- [Meeting Link](https://finos.webex.com/finos/j.php?MTID=mb24e0868b724abcfa92221ca14207e14)
Description:FDC3 PMC Meeting
Meeting number: 663 444 364
Dial in: 
+1.415.655.0003 USA Toll
+44-20319-88141 UK Toll
Access code: 663 444 364

**Comment by aitana16** [comment]
hi!

**Comment by lspiro-Tick42** [comment]
here

**Comment by mattjamieson** [comment]
✅
