### ISSUE TITLE
08 04 2020 FDC3 General Meeting

### ISSUE THREAD

**Issue by aitana16** [finos/FDC3#233]
## Date
08 04 2020 - 10am EST

## Untracked attendees
- Nick Kolba / Genesis / @nkolba
- Amit Rai / Citi
- Eric Linder/  Savanet
- Qia Chen /  Citi
- Randall Dang / Citi

## Agenda
- [ ] Convene & roll call (5mins)
- [ ] Review action items from previous meetings (5mins)
- [ ] AOB & Adjourn (10mins)

## Decisions Made
- [ ] ...

## Action Items
- [ ] ...

### WebEx info
- [Meeting Link](https://finos.webex.com/finos/j.php?MTID=m3015a7e4a511656ceafebda5eadcbe6d)
- Meeting number: 403 028 328

*More ways to join*
- Join by video system: dial 173.243.2.68 and enter your meeting number
- Join by phone
   - +1-415-655-0003 US Toll
   - +44-20319-88141 UK Toll
- Access code: 403 028 328

**Comment by ggeorgievx** [comment]
Present ✅

**Comment by mcleo-d** [comment]
Hello everyone 👋

**Comment by lspiro-Tick42** [comment]
Leslie Spiro, Glue42. lspiro-Tick42

**Comment by donbasuno** [comment]
Hej

**Comment by rikoe** [comment]
👋

**Comment by mpthan** [comment]
Hello

**Comment by mcleo-d** [comment]
@rikoe and @nkolba 

We had a good number of people saying hello in the comments on the call, but the following people need to supply their full details. Are you able to fill in the blanks?

| Attendee | Firm | GitHub Profile (optional) |
|:-----|:-----|:-----|
| Amit Rai |  |  | 
| Eric Linder |  |  |
| Qia Chen |  |  |
| Randall |  |  |
| Tim |  |   |

Thanks 🚀 

James.

**Comment by tim-dinsdale** [comment]
hello Tim Dinsdale OpenFin
