### ISSUE TITLE
PMC Meeting - August 7, 2020

### ISSUE THREAD

**Issue by rikoe** [finos/FDC3#234]
## Date
Friday 07 Aug 2020 - 9am EST

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username
- ...

## Agenda
- [x] Convene & roll call (5mins)
- [x] Review action items from previous meetings (5mins)
- [x] Feedback on general meeting
- [x] Tooling project update
- [x] Review issues
- [x] AOB & Adjourn (10mins)

## Decisions Made
- [ ] ...

## Action Items
- [ ] @lspiro-Tick42 to create an issue about app directory manifest json
- [ ] @rikoe to follow up with Mao about npm publication

### WebEx info
- [Meeting Link](https://finos.webex.com/finos/j.php?MTID=mb24e0868b724abcfa92221ca14207e14)
Description:FDC3 PMC Meeting
Meeting number: 663 444 364
Dial in: 
+1.415.655.0003 USA Toll
+44-20319-88141 UK Toll
Access code: 663 444 364

**Comment by rikoe** [comment]
👋

**Comment by aitana16** [comment]
hi!

**Comment by lspiro-Tick42** [comment]
Leslie Spiro, Tick42, lspiro-Tick42

**Comment by mattjamieson** [comment]
👍

**Comment by donbasuno** [comment]
here i am to save the day!
