### ISSUE TITLE
Should the api be published to npm?

### ISSUE THREAD

**Issue by jonfreedman** [finos/FDC3#236]
## Support Question

I want to use fdc3 within a typescript project - rather than maintaining our own copy of the API it would be nice if we could just reference it via an npm dependency. Is this already available, and if not can it be?

**Comment by rikoe** [comment]
@jonfreedman - great question!

We have been experimenting with typings, and plan to publish them to npm in the future. You can see (and try out) our current efforts here: https://github.com/nkolba/fdc3-tools.

The current plan is to promote the typings into the main fdc3 repo when ready, as they currently duplicate the src files in this repo.

**Comment by mattjamieson** [comment]
If you want to try these out quickly in a project you can use GitPkg:

```json
  "dependencies": {
    "@finos/fdc3-types": "https://gitpkg.now.sh/nkolba/fdc3-tools/packages/fdc3-types?master",
```

**Comment by rikoe** [comment]
The first alpha version of the package is now published at https://www.npmjs.com/package/@finos/fdc3. We are tracking tasks in #261, so closing this one.
