### ISSUE TITLE
PMC Meeting - September 4th, 2020

### ISSUE THREAD

**Issue by nkolba** [finos/FDC3#237]
## Date
Friday 04 Sep 2020 - 9am EST

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username
- ...

## Agenda
- [ ] Convene & roll call (5mins)
- [ ] Review action items from previous meetings (5mins)
- [ ] AOB & Adjourn (10mins)

## Decisions Made
- [ ] ...

## Action Items
- [ ] ...
@mattjamieson @lspiro-Tick42 @rikoe @kriswest @donbasuno @aitana16   please add any agenda items you may have.

### WebEx info
- [Meeting Link](https://finos.webex.com/finos/j.php?MTID=mb24e0868b724abcfa92221ca14207e14)
Description:FDC3 PMC Meeting
Meeting number: 663 444 364
Dial in: 
+1.415.655.0003 USA Toll
+44-20319-88141 UK Toll
Access code: 663 444 364

**Comment by mcleo-d** [comment]
Hello!

**Comment by RichardWagener365** [comment]
hi

**Comment by donbasuno** [comment]
Lalala

**Comment by mattjamieson** [comment]
⚡

**Comment by nkolba** [comment]
here

**Comment by kriswest** [comment]
here
