### ISSUE TITLE
PMC Meeting - September 18th, 2020

### ISSUE THREAD

**Issue by nkolba** [finos/FDC3#245]
## Date
Friday 18th SEP 2020 - 9am EST

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username
- ...

## Agenda
- [ ] Convene & roll call (5mins)
- [ ] Review action items from previous meetings (5mins)
- [ ] Types on NPM 
- [ ] Community Context Definitions
- [ ] AOB & Adjourn (10mins)

## Decisions Made
- [ ] ...

## Action Items
- [ ] ...

### WebEx info
- [Meeting Link](https://finos.webex.com/finos/j.php?MTID=mb24e0868b724abcfa92221ca14207e14)
Description:FDC3 PMC Meeting
Meeting number: 663 444 364
Dial in: 
+1.415.655.0003 USA Toll
+44-20319-88141 UK Toll
Access code: 663 444 364

**Comment by aitana16** [comment]
hi!

**Comment by lspiro-Tick42** [comment]
lspiro-Tick42 hi

**Comment by donbasuno** [comment]
Here

**Comment by RichardWagener365** [comment]
Here

**Comment by kriswest** [comment]
here
