### ISSUE TITLE
Standard WG Meeting - September 24th, 2020

### ISSUE THREAD

**Issue by nkolba** [finos/FDC3#246]
## Date
Thursday 24 SEP 2020 - 10am EST

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username
- ...

## Agenda
- [x] Convene & roll call (5mins)
- [x] **[Community Context Types](https://github.com/finos/FDC3/issues/239)** Quick intro to this topic and get additional feedback.
- [ ] **1.2 Scope** - let's start locking down the 1.2 scope by triaging the [current enhancement issues](https://github.com/finos/FDC3/labels/enhancement) to determine for each:
   - should it definitely be in?
   - should it definitely be out?
   - does it require more investigation to determine?
- [ ] Determine deliverables and next steps for 1.2
   - in scope enhancements need owners who can draft PRs to the spec
   - undecided enhancements need sponsors who can add more context to the issues
- [ ] AOB & Adjourn (10mins)

## Decisions Made
- [ ] ...

## Action Items
- [ ] ...

### WebEx info
- [Meeting Link](https://finos.webex.com/finos/j.php?MTID=ma4b1de1b9f691d89e4b2ff380ec9687c)
Meeting number: 665 568 411

*More ways to join*
- Join by video system: 
   - Dial 665568411@finos.webex.com
   - You can also dial 173.243.2.68 and enter your meeting number
- Join by phone
   - +1-415-655-0003 US Toll
   - +44-20319-88141 UK Toll
- Access code: 665 568 411

**Comment by sgd2z** [comment]
✔

**Comment by ggeorgievx** [comment]
Present ✅

**Comment by kriswest** [comment]
present

**Comment by aitana16** [comment]
hi!

**Comment by lspiro-Tick42** [comment]
Present

**Comment by rikoe** [comment]
👋

**Comment by chedzoir** [comment]
Here!

**Comment by mattjamieson** [comment]
🚀

**Comment by sean-ciq** [comment]
check

**Comment by donbasuno** [comment]
👍

**Comment by dcj99** [comment]
David Jones, ipushpull

**Comment by nkolba** [comment]
here

**Comment by nkolba** [comment]
Thanks everyone for another super-productive meeting!  As discussed, I've added a new issue covering 1.2 scope 

#248
