### ISSUE TITLE
1.2 Scope

### ISSUE THREAD

**Issue by nkolba** [finos/FDC3#248]
At the September Standard WG meeting we decided on the following issues (and ownership) for scope.  Next steps are to develop these issues into PRs that can then be progressed and decided on for final cut of 1.2.

- #201 
   - **Owner**  @nkolba 
   - **Notes**  We will combine #203 as a related issue.  Though @lspiro-Tick42 will make a separate PR for that
- #213 
  - **Owner** @sgd2z
  - **Notes** make a PR!
- #227 
   - **Owner** @rikoe 
   - **Notes** addition of symbol identifier to better support currency pairs (rather than using *ticker*).  More far reaching context type proposals maybe better handled via #239  first.
- #240 
   - **Owner** @seann-ciq
   - **Notes** PR for app metadata as target arg.  Other appD / metadata changes require more discussion and thought and should be punted to 1.3
- #241 
   - **Owner** @sgd2z
   - **Notes** make a PR!
- #242   
   - **Owner** @sgd2z
   - **Notes** More discussion may be nneeded.  PR will be made to help illustrate the use case and mechanics of the UX

Issues #243 and #247 are still in need of scoping.  Let's progress async on the issues in github.

**Comment by kriswest** [comment]
@nkolba re:
> #240
Owner @seann-ciq
Notes PR for app metadata as target arg. Other appD / metadata changes require more discussion and thought and should be punted to 1.3

We'll split the issue into two and supply a PR for appMetadata as target. However, I didn't think that a final resolution was made to punt AppMetadata changes to 1.3 - there is a fairly clear mismatch between the AppD and desktop agent and we believe that AppMetadata should be extended with the appID and version fields to bring them into alignment. We intend to submit this as a separate issue for consideration in 1.2.
