### ISSUE TITLE
PMC Meeting - October 2nd, 2020

### ISSUE THREAD

**Issue by nkolba** [finos/FDC3#250]
## Date
Friday 2 OCT 2020 - 9am EST

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username
- ...

## Agenda
- [ ] Convene & roll call (5mins)
- [ ] Review action items from previous meetings (5mins)
- [ ] Standards Participant PR #249  from @mindthegab 
- [ ] AOB & Adjourn (10mins)

## Decisions Made
- [ ] ...

## Action Items
- [ ] ...

### WebEx info
- [Meeting Link](https://finos.webex.com/finos/j.php?MTID=mb24e0868b724abcfa92221ca14207e14)
Description:FDC3 PMC Meeting
Meeting number: 663 444 364
Dial in: 
+1.415.655.0003 USA Toll
+44-20319-88141 UK Toll
Access code: 663 444 364

**Comment by donbasuno** [comment]
Present

**Comment by mattjamieson** [comment]
👋

**Comment by aitana16** [comment]
hi

**Comment by lspiro-Tick42** [comment]
present

**Comment by nkolba** [comment]
here

**Comment by kriswest** [comment]
here

**Comment by rikoe** [comment]
attented
