### ISSUE TITLE
Support idiomatic ES6 modules in FDC3 API

### ISSUE THREAD

**Issue by rikoe** [finos/FDC3#256]
### Use Case:
As a developer, I would like my FDC3 code to be modern, idiomatic JavaScript, and I only want to include code for the FDC3 functions I actually use.

### Workflow Description
Instead of (or in addition to) using the FDC3 `window` object, developers can use ES6 modules in their code to import FDC3 functionality.

### Workflow Examples
```ts
// import single operations
import { broadcast, raiseIntent, ContextTypes, Intents } from 'fdc3'

broadcast({
    type: ContextTypes.Instrument,
    id: {
        ticker: 'AAPL'
    }
})

const result = await raiseIntent(Intents.ViewChart, {
    type: ContextTypes.Instrument,
    id: {
        ticker: 'MSFT'
    }
})

// import everything
import * as fdc3 from 'fdc3'

fdc3.joinChannel('red')
```

### Additional Information
Such an approach could have multiple benefits:
* Allow tree-shaking to only include those pieces of FDC3 actually being used
* Can rely on import subsystem for fdc3 operations being initialised
* More idiomatic Java/TypeScript, inline with other modules

This functionality could be offered in addition to the current `window.fdc3` model as an alternative.

**Comment by kriswest** [comment]
Doesn't this tie you to a particular vendor implementation of FDC3 at build time? Or would you have a thin layer that directs the calls made to a window.fdc3 instance (allowing this to work with any vendor injecting the Desktop Agent implementation into the window?). I suppose that layer could also handle queuing until the proposed FDC3 ready event fires...

**Comment by rikoe** [comment]
Ha. I just expressed the use case @kriswest, I didn't think about how it would be accomplished 😉 . I think what you suggest (about a thin layer to `window.fdc3`) is a good idea.
