### ISSUE TITLE
Application definition "icons" property

### ISSUE THREAD

**Issue by pgn-vole** [finos/FDC3#257]
### Question Area
[X] App Directory
[ ] API
[ ] Context Data
[ ] Intents
[ ] Use Cases
[ ] Other

##  Question

Could you please clarify how does an application launcher should interpret the icons property of applications within the app directory? 

It is specified for this property to have the below shape:
```jsx
{
 // other app properties
 icons : [
   {  
     icon: "https://foo.com/icon.png"
   }
 ]
}
```

Since `icons` is a list, which item of that list should the launcher use and as an application developer how do I know which item of that list the launcher is going to pick?

I had a look at 2 open source implementations [1] and the logic appears flimsy to me considering that they do arbitrarily pick the first item of that list.

I would think in the first place that multiple icons would be useful so that different sizes of the same icon or even different icons could be exposed to launchers.  However to enable this capability some metadata properties would have to be added to the "icon" model. At the moment it does support a single property "icon" which is meant to be just the url.

1: https://github.com/ChartIQ/finsemble-fdc3/blob/master/src/components/intentResolver/src/app.tsx#L204
   https://github.com/finos/fdc3-desktop-agent/blob/master/src/content.ts#L338

**Comment by nkolba** [comment]
Totally agree.  Would make sense to base on how this is handled in [web app manifest](https://developer.mozilla.org/en-US/docs/Web/Manifest).

**Comment by rikoe** [comment]
If someone is willing to do a PR, I propose we add this to the scope for 1.2?

**Comment by pgn-vole** [comment]
I'm happy to take ownership on that and raise a relevant PR if that's fine with you?

**Comment by rikoe** [comment]
@pgn-vole are you still planning to submit a PR for this one? Would be great to get this into 2.0 as part of other app directory work.
