### ISSUE TITLE
Standard WG Meeting - October 21st, 2020

### ISSUE THREAD

**Issue by nkolba** [finos/FDC3#271]
## Date
Thursday 21 OCT 2020 - 10am EST

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username
- ...

## Agenda
- [x] Convene & roll call (5mins)
- [ ] Review 1.2 action items #248 
- [ ] Review outstanding [PRs](https://github.com/finos/FDC3/pulls)
- [ ] AOB & Adjourn (10mins)

## Decisions Made
- [ ] ...

## Action Items
- [ ] ...

### WebEx info
- [Meeting Link](https://finos.webex.com/finos/j.php?MTID=ma4b1de1b9f691d89e4b2ff380ec9687c)
Meeting number: 665 568 411

*More ways to join*
- Join by video system: 
   - Dial 665568411@finos.webex.com
   - You can also dial 173.243.2.68 and enter your meeting number
- Join by phone
   - +1-415-655-0003 US Toll
   - +44-20319-88141 UK Toll
- Access code: 665 568 411

**Comment by nkolba** [comment]
here

**Comment by mattjamieson** [comment]
🚀

**Comment by donbasuno** [comment]
success

**Comment by sgd2z** [comment]
👻

**Comment by zhenyakovalyov** [comment]
here!

**Comment by pjbroadbent** [comment]
👋

**Comment by toshaellison** [comment]
here

**Comment by lspiro-Tick42** [comment]
Here

**Comment by kriswest** [comment]
h👂

**Comment by rikoe** [comment]
Was there!
