### ISSUE TITLE
PMC Meeting - Friday, October 30th, 2020 - 8am EST / 12pm BST

### ISSUE THREAD

**Issue by nkolba** [finos/FDC3#278]
## Date
Friday 30 OCT 2020 - 8am EST

**Note**: This is at a different time this week due to scheduling conflicts.  A new webex link (just for this meeting) is below.
## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username
- ...

## Agenda
- [ ] Convene & roll call (5mins)
- [ ] Review action items from previous meetings (5mins)
- [ ] Outstanding PRs and Issues
- [ ] AOB & Adjourn (10mins)

## Decisions Made
- [ ] ...

## Action Items
- [ ] ...

### WebEx info
FDC3 PMC Meeting (October 30th 2020 session)
Meeting Link: https://finos.webex.com/finos/j.php?MTID=m07f95d005569fe3481292c9cfa33d958
Meeting number: 127 928 9896
Dial in:  +1.415.655.0003 USA Toll / +44-20319-88141 UK Toll / Access code: 127 928 9896

Agenda: https://github.com/finos/FDC3/issues

**Comment by aitana16** [comment]
hi!

**Comment by kriswest** [comment]
here

**Comment by rikoe** [comment]
👋

**Comment by nkolba** [comment]
was here
