### ISSUE TITLE
PMC Meeting - November 13, 2020

### ISSUE THREAD

**Issue by nkolba** [finos/FDC3#281]
## Date
Friday 13 NOV 2020 - 9am EST

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username
- ...

## Agenda
- [ ] Convene & roll call (5mins)
- [ ] Review action items from previous meetings (5mins)
- [ ] Review PR https://github.com/finos/FDC3/pull/272
- [ ] Review https://github.com/finos/FDC3/pull/273
- [ ] Agenda for next general meeting (Nov 24)
- [ ] AOB & Adjourn (10mins)

## Decisions Made
- [ ] ...

## Action Items
- [ ] ...

### WebEx info
- [Meeting Link](https://finos.webex.com/finos/j.php?MTID=mb24e0868b724abcfa92221ca14207e14)
Description:FDC3 PMC Meeting
Meeting number: 663 444 364
Dial in: 
+1.415.655.0003 USA Toll
+44-20319-88141 UK Toll
Access code: 663 444 364

**Comment by nkolba** [comment]
here

**Comment by mattjamieson** [comment]
👋

**Comment by donbasuno** [comment]
alive and kickin

**Comment by lspiro-Tick42** [comment]
Here

**Comment by rikoe** [comment]
boo 🎃

**Comment by kriswest** [comment]
👍

**Comment by aitana16** [comment]
hi
