### ISSUE TITLE
Nov 24 2020 FDC3 General Meeting

### ISSUE THREAD

**Issue by aitana16** [finos/FDC3#288]
## Date
Nov 24 2020 - 10am EST

## Untracked attendees
- Chris 
- Karan Jain
- Krasimir Krastev / Glue 42
- Nick Kolba / genesys
- Peter Smulovics / Morgan Stanley 
- Rob Underwood / FINOS

## Agenda
- [ ] Convene & roll call (5mins)
- [ ] FDC3 1.2 Update 
- [ ] Demos
- [ ] AOB & Adjourn (10mins)

### WebEx info
- [Meeting Link](https://finos.webex.com/finos/j.php?MTID=m3015a7e4a511656ceafebda5eadcbe6d)
- Meeting number: 403 028 328

*More ways to join*
- Join by video system: dial 173.243.2.68 and enter your meeting number
- Join by phone
   - +1-415-655-0003 US Toll
   - +44-20319-88141 UK Toll
- Access code: 403 028 328

**Comment by lspiro-Tick42** [comment]
I attended

**Comment by ggeorgievx** [comment]
Present ✅

**Comment by aitana16** [comment]
here

**Comment by rikoe** [comment]
👋

**Comment by mattjamieson** [comment]
⚡

**Comment by vmehtafds** [comment]
👍
