### ISSUE TITLE
Dec 4th 2020 PMC Meeting

### ISSUE THREAD

**Issue by aitana16** [finos/FDC3#294]
## Date
Friday 04 Dec 2020 - 9am EST

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username
- ...

## Agenda
- [ ] Convene & roll call (5mins)
- [ ] Review action items from previous meetings (5mins)
- [ ] AOB & Adjourn (10mins)

## Decisions Made
- [ ] ...

## Action Items
- [ ] ...

### WebEx info
- [Meeting Link](https://finos.webex.com/finos/j.php?MTID=mb24e0868b724abcfa92221ca14207e14)
Description:FDC3 PMC Meeting
Meeting number: 663 444 364
Dial in: 
+1.415.655.0003 USA Toll
+44-20319-88141 UK Toll
Access code: 663 444 364

**Comment by rikoe** [comment]
Here

**Comment by aitana16** [comment]
hi

**Comment by lspiro-Tick42** [comment]
on line

**Comment by donbasuno** [comment]
connection established
