### ISSUE TITLE
Standard HTTP header for backend requests

### ISSUE THREAD

**Issue by vmehtafds** [finos/FDC3#296]
## Enhancement Request

Currently a application can determine if they are in a FDC3 enabled platform on the front end by the presence of `window.fdc3` which was standardized. 
This is very useful to have a single front end codebase that work well in both FDC3 environment and non-FDC3 environment (by using the global to turn off any FDC3 visuals/functionality).

But currently there is no standard mechanism for backend requests. We have been resorting to user-agent parsing (i.e regex search `/openfin/i` ) but that is very platform specific. We use the information on the backend to optimize the assets being delivered  and turn on/off features depending on the FDC3 vs non-FDC3 environment.

It would be great if all the FDC3 compliant platforms can implement a standard HTTP header they can send from their platform.

Thoughts?

**Comment by vmehtafds** [comment]
The use case is about including/excluding certain `<script>`  tags on the initial `index.html` request based on the whether the request is coming from a FDC3 platform or not.
If it is not a FDC3 platform, we would rather not include certain `<script>` tags on the page.

**Comment by kriswest** [comment]
I'm not keen on doing this as it would introduce complexity into the implementation of the desktop agent in an area it doesn't currently touch (requests to a server). You'd have to be able to customize the headers on requests or some apps would not work (wouldn't receive the necessary script tags) in your desktop agent. 

There are other solutions that can solve this issue such as supporting a query string on the URL that causes the app to include the additional `<script>` tags.

**Comment by rikoe** [comment]
We discussed this at the Standard Working Group meeting and there was agreement that this does not fall within the scope of the FDC3 standard.
