### ISSUE TITLE
Standard WG Meeting - Jan 7, 2020

### ISSUE THREAD

**Issue by rikoe** [finos/FDC3#298]
## Date
Thursday 7 Jan 2021 - 10am EST

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username
- ...

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://github.com/finos/community/blob/master/governance/Meeting-Procedures.md#run-the-meeting). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://odp.finos.org/docs/finos-maintainers-cheatsheet/).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://github.com/finos/community/blob/master/governance/Code-of-Conduct.md) and all other [FINOS policies](https://github.com/finos/community/tree/master/governance#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [ ] Convene & roll call (5mins)
- [ ] Display [FINOS Antitrust Policy summary slide](https://github.com/finos/community/blob/master/governance/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [ ] Review Meeting Notices (see above)
- [ ] Approve past meeting minutes
- [ ] Review action items from previous meetings (5mins)
- [ ] Discuss 1.2 and 2.0 releases
- Review issues:
  - [ ] https://github.com/finos/FDC3/issues/296
  - [ ] https://github.com/finos/FDC3/issues/284
  - [ ] https://github.com/finos/FDC3/issues/270
  - [ ] https://github.com/finos/FDC3/issues/247
  - [ ] https://github.com/finos/FDC3/issues/243
  - [ ] https://github.com/finos/FDC3/issues/242
- Review PRs:
   - [ ] https://github.com/finos/FDC3/pull/283
   - [ ] https://github.com/finos/FDC3/pull/282
   - [ ] https://github.com/finos/FDC3/pull/268
   - [ ] https://github.com/finos/FDC3/pull/287
- [ ] AOB & Adjourn (10mins)

## Decisions Made
- [ ] ...

## Action Items
- [ ] ...

### WebEx info
- [Meeting Link](https://finos.webex.com/finos/j.php?MTID=ma4b1de1b9f691d89e4b2ff380ec9687c)
Meeting number: 665 568 411

*More ways to join*
- Join by video system: 
   - Dial 665568411@finos.webex.com
   - You can also dial 173.243.2.68 and enter your meeting number
- Join by phone
   - +1-415-655-0003 US Toll
   - +44-20319-88141 UK Toll
- Access code: 665 568 411

**Comment by ggeorgievx** [comment]
Present ✅

**Comment by vmehtafds** [comment]
👍

**Comment by zhenyakovalyov** [comment]
here

**Comment by sgd2z** [comment]
🎈

**Comment by lspiro-Tick42** [comment]
Here for start of meeting

**Comment by aitana16** [comment]
hi!

**Comment by mattjamieson** [comment]
👍

**Comment by toshaellison** [comment]
present

**Comment by nkolba** [comment]
here
