### ISSUE TITLE
PMC Meeting- Jan 8 2021

### ISSUE THREAD

**Issue by rikoe** [finos/FDC3#299]
## Date
Friday 8 Jan 2021 - 9am EST

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username
- ...

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://github.com/finos/community/blob/master/governance/Meeting-Procedures.md#run-the-meeting). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://odp.finos.org/docs/finos-maintainers-cheatsheet/).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://github.com/finos/community/blob/master/governance/Code-of-Conduct.md) and all other [FINOS policies](https://github.com/finos/community/tree/master/governance#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [ ] Convene & roll call (5mins)
- [ ] Display [FINOS Antitrust Policy summary slide](https://github.com/finos/community/blob/master/governance/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [ ] Review Meeting Notices (see above)
- [ ] Approve past meeting minutes
- [ ] Review action items from previous meetings (5mins)
- [ ] Catch-up & review of roadmap for 2021
- [ ] Should FDC3 be a FINOS focus project for Q1 2021
- [ ] AOB & Adjourn (10mins)

## Decisions Made
- [ ] FDC3 aims to be a focus project in Q2 after 1.2 release and community contributions
- [ ] Add 2.0 release to roadmap
- [ ] Add container-agnostic manifest standardisation to appd roadmap
- [ ] Add hosted FDC3 example app directory to roadmap (potentially H2 2021)

## Action Items
- [ ] Finalise repo readme update (Riko)
- [ ] Create/experiment community contributions structure + PR template (?)
- [ ] Glue42 to propose manifest standardisation via PR (Leslie)

### WebEx info
- [Meeting Link](https://finos.webex.com/finos/j.php?MTID=mb24e0868b724abcfa92221ca14207e14)
Description:FDC3 PMC Meeting
Meeting number: 663 444 364
Dial in: 
+1.415.655.0003 USA Toll
+44-20319-88141 UK Toll
Access code: 663 444 364

**Comment by nkolba** [comment]
here

**Comment by mattjamieson** [comment]
🥾

**Comment by lspiro-Tick42** [comment]
me too

**Comment by kriswest** [comment]
Here

**Comment by aitana16** [comment]
hi!

**Comment by donbasuno** [comment]
count me in!

**Comment by rikoe** [comment]
here
