### ISSUE TITLE
Standard WG Meeting - Jan 27, 2020

### ISSUE THREAD

**Issue by rikoe** [finos/FDC3#303]
## Date
Thursday 27 Jan 2021 - 10am EST / 3pm GMT

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username
- ...

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://github.com/finos/community/blob/master/governance/Meeting-Procedures.md#run-the-meeting). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://odp.finos.org/docs/finos-maintainers-cheatsheet/).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://github.com/finos/community/blob/master/governance/Code-of-Conduct.md) and all other [FINOS policies](https://github.com/finos/community/tree/master/governance#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call, review meeting notices (5mins)
- [x] Approve past meeting minutes & review actions from previous meetings (5 mins)
- [x] Review of items and release process for v1.2 (15 mins)
- [x] Plans for v2.0 (15 mins)
- [x] AOB & Adjourn (5mins)

## Decisions Made
- All specifications and schemas will be bumped to v1.2 for release, regardless if they changed or not
- Including app directory in version 2.0 release is highly desirable
- Organize spin-off working groups for larger 2.0 items, e.g. app manifest standardization.

## Action Items
- [ ] Create an issue for items that should be deprecated in v1.2 for removal in v2.0
   * Proposed that "global" channel to be deprecated then removed, joining channels should always be opt-in
   * IntentResolution.data to be deprecated as it is not currently possible to use, and not used in the new AppInstance proposal

### WebEx info
- [Meeting Link](https://finos.webex.com/finos/j.php?MTID=ma4b1de1b9f691d89e4b2ff380ec9687c)
Meeting number: 665 568 411

*More ways to join*
- Join by video system: 
   - Dial 665568411@finos.webex.com
   - You can also dial 173.243.2.68 and enter your meeting number
- Join by phone
   - +1-415-655-0003 US Toll
   - +44-20319-88141 UK Toll
- Access code: 665 568 411

**Comment by agitana** [comment]
hello!

**Comment by sean-ciq** [comment]
Here!

**Comment by ggeorgievx** [comment]
Present ✅

**Comment by mattjamieson** [comment]
👋

**Comment by zhenyakovalyov** [comment]
here!

**Comment by lspiro-Tick42** [comment]
Here

**Comment by pbaize** [comment]
Here

**Comment by tarsillon1** [comment]
Here!

**Comment by TBFactSet** [comment]
hi

**Comment by sgd2z** [comment]
here

**Comment by kriswest** [comment]
here
