### ISSUE TITLE
PMC Meeting- Jan 29, 2021

### ISSUE THREAD

**Issue by rikoe** [finos/FDC3#304]
## Date
Friday 29  Jan 2021 - 9am EST / 2pm GMT

### WebEx info
- [Meeting Link](https://finos.webex.com/finos/j.php?MTID=m25fdfa5101f9d34d7efe0c57fec56bc8)
Description:FDC3 PMC Meeting
Meeting number: 127 829 0895
Dial in: 
+1.415.655.0003 USA Toll
+44-20319-88141 UK Toll
Access code: 127 829 0895

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://github.com/finos/community/blob/master/governance/Meeting-Procedures.md#run-the-meeting). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://odp.finos.org/docs/finos-maintainers-cheatsheet/).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://github.com/finos/community/blob/master/governance/Code-of-Conduct.md) and all other [FINOS policies](https://github.com/finos/community/tree/master/governance#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x]  Convene & roll call, review meeting notices (2mins)
- [ ] Approve past meeting minutes & review actions from previous meeting #299 (3 mins)
- [x] FDC3 leadership changes (8 mins)
- [ ] Review updated FDC3 GitHub Readme (2 mins)
- [ ] Community context types (#239) (10 mins)
- [ ] AOB & Adjourn (5 mins)

## Decisions Made
- [ ] ...

## Action Items
- [ ] ...

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username
- ...

**Comment by kriswest** [comment]
here

**Comment by agitana** [comment]
hi!

**Comment by mattjamieson** [comment]
👍

**Comment by lspiro-Tick42** [comment]
Here

**Comment by donbasuno** [comment]
been there, done that
