### ISSUE TITLE
Introduce a new `fdc3.onChannelChanged(callback)` method

### ISSUE THREAD

**Issue by ggeorgievx** [finos/FDC3#313]
## Enhancement Request

Introduce a new `fdc3.onChannelChanged(callback)` method that calls the provided `callback` with the newly joined channel.

The signature of the method would be:

```ts
onChannelChanged(callback: (newlyJoinedChannel: Channel) => void): Listener;
```

The method would return a `Listener` that would allow unsubscribing from the event.

### Use Case:

Let's say we want to create a Channel Selector Widget that allows the users to navigate between the available system channels. We want to make it available to multiple applications by extracting it in a separate module that the applications depend upon. Let's assume that an application that uses the Channel Selector Widget provides an additional way to its users to change the current channel. Whenever the user switches the channel using that other method our Channel Selector Widget would be still, wrongly, displaying the old channel colour.

It would be convenient if there was a FDC3 event that allowed us to subscribe to channel changes.

### Workflow Description

A developer could use the event to create reactive workflows within his/her application.

### Workflow Examples

Below is a short, very simplified, snippet illustrating the above example.

```js
// Channel Selector Widget module.
class ChannelSelectorWidget {
    private channels = [];
    private currentChannel = null;

    constructor(systemChannels) {
        this.channels = systemChannels;

        fdc3.onChannelChanged((newlyJoinedChannel) => {
            // Updates the channel selector widget to display the colour of the newly joined channel.
            this.setCurrentChannel(newlyJoinedChannel);
        });
    }
}

// Inside of the application.
const systemChannels = await fdc3.getSystemChannels();
const channelSelectorWidget = new ChannelSelectorWidget(systemChannels);


// Somewhere else within the application...
const fancyButton = document.createElement('button');
fancyButton.onclick = () => fdc3.joinChannel('Red');

document.body.appendChild(fancyButton);
```

### Additional Information

A PR for this issue would include only the addition of the method as no new interfaces would be required.

**Comment by sgd2z** [comment]
I think this needs to be made compatible with https://github.com/finos/FDC3/issues/242.
Maybe rename to `onChannelsChanged`

**Comment by rikoe** [comment]
My first reaction is that this is again a desktop agent use case, and not an application interoperability use case.

> Let's say we want to create a Channel Selector Widget that allows the users to navigate between the available system channels. 

We should discuss this in the community, but for me this is not a valid use case for FDC3 to cover. You can certainly implement this in your desktop agent, but until we have an example of an application participating in interop needing access to such an event, I don't think we should add this.

It is important to understand that to keep FDC3 simple, and the API surface lightweight for application developers, we need to really try and restrict ourselves in terms of how many operations and concepts we are adding.

**Comment by pgn-vole** [comment]
Considering that the only way to switch channel is via the desktop agent `fdc3.joinChannel` call, the application relying on fdc3 should be aware of whenever it actually calls that `joinChannel` an therefore be able to act upon that. 
However if the system relying on fdc3 is implemented in a way where something may call `joinChannel`  in an implicit manner outside of an application context, then I would expect that same system to dispatch a properitary event on that matter.

**Comment by kriswest** [comment]
@rikoe We've encountered a use-case for this. Certain applications wish to implement their own channel selector, rather than using a built-in one. This is particularly prevalent in 'native' use cases where it's harder for a framework/container to provide such a UI to an application. In Finsemble we have a WPF titlebar that C#  apps can use, but don't have one for Winforms, JavaFX or Java Swing, where apps have to implement their own channel selector. This is currently not possible without us adding proprietary UI. 

Hence, I support this addition to the spec - but would suggest that the documentation clearly state that this is an optional function intended to support the creation of a channel selector where necessary and that most Desktop agents will provide this for HTML5 applications already - which should be used in preference to applications own selector (for UX consistency - although owing to the event the two would stay in sync with each other).

Also, the argument should be named `handler` rather than `callback` for consistency with other functions.

Compatability with #242 (as @sgd2z comments) would also be nice, changing signature to: 
`onChannelsChanged(handler: (channels: Channel[]) => void): Listener;`

**Comment by kriswest** [comment]
An additional use-case occurred to me while discussing #242 with @lspiro-Tick42. At present, a component that joins a channel needs to query for the current context (via `fdc3.getCurrentChannel()` and then `channel.getCurrentContext()`) if it wants to set the same context and applications already on that channel. However, it has no way to know that it has joined the channel.

Possible solutions include:
- add the proposed `onChannelsChanged` listener
- automatically call any registered context listeners on joining a channel (would make channels more like PubSub topics)
- state in the spec that components are NOT expected to set the current context of the channel when they join it.

**Comment by nkolba** [comment]
@kriswest The spec states that when joining an app to channel, the desktop agent will send the updated context:

“ Apps can join channels. An app can only be joined to one channel at a time. When an app joins a channel it will automatically recieve the current context for that channel.”

**Comment by kriswest** [comment]
Ah that would explain the lack of a `getCurrentContext` function. This should definitely appear in the [joinChannel docs](https://fdc3.finos.org/docs/api/ref/DesktopAgent#joinchannel).  Thanks for the correction @nkolba

**Comment by kriswest** [comment]
Added an issue to clarify behavior on joinChannel in spec and docs: https://github.com/finos/FDC3/issues/418

**Comment by kriswest** [comment]
Note from Channels discussion group:
- This is only useful/necessary if: 
  - You have two channel selectors (one in component, one provided by desktop agent or some loaded module) - this might be considered a poor UX decision
  - You really need to behave differently when connected or not connected to a channel (which is an added complexity that was intended to be dealt with by broadcast being a no-op when not joined to the channel, as described in the specification).
- If the Channel selector widget described in the use-case is implemented by the desktop agent then an API addition shouldn't be needed
- If the channel selector widget is in a separate window, the API addition as described would only notify the application, not the channel selector widget and therefore doesn't solve for the usecase
- If the channel selector widget is module loaded within an application's window then it could provide its own API for selecting the channel OR notifying the widget. It could also override the default fdc3.joinChannel function.

@ggeorgievx given the above notes would you be willing to update the issue description / use-case or close it?
Alternatively, we can put this forward for a vote by the Standards Working Group on whether it should move forward.

**Comment by ggeorgievx** [comment]
Thank you for the amazing summary @kriswest

I will now close the proposal.

Anyone who has or comes up with another use case for `fdc3.onChannelChanged(callback)` please feel free to comment here or start a discussion in the WG.
