### ISSUE TITLE
FDC3 General Meeting - Feb 2, 2021

### ISSUE THREAD

**Issue by rikoe** [finos/FDC3#316]
## Date
2 Feb 2021 - 10am EST / 3pm GMT

### WebEx info
- [Meeting Link](https://finos.webex.com/finos/j.php?MTID=m3015a7e4a511656ceafebda5eadcbe6d)
- Meeting number: 403 028 328

*More ways to join*
- Join by video system: dial 173.243.2.68 and enter your meeting number
- Join by phone
   - +1-415-655-0003 US Toll
   - +44-20319-88141 UK Toll
- Access code: 403 028 328

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://github.com/finos/community/blob/master/governance/Meeting-Procedures.md#run-the-meeting). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://odp.finos.org/docs/finos-maintainers-cheatsheet/).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://github.com/finos/community/blob/master/governance/Code-of-Conduct.md) and all other [FINOS policies](https://github.com/finos/community/tree/master/governance#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [ ] Convene & roll call, review meeting notices (5 mins)
- [ ] FDC3 Announcements (5 mins)
- [ ] FDC3 2021 Roadmap (5 mins)
- [ ] Contributing community context types (5 mins)
- [ ] Demo: FDC3 everywhere - supporting apps on multiple platforms (Leslie Spiro, Glue42 - 15 mins)
- [ ] Demo: Finsemble & FDC3 (Kris West, Cosaic - 15 mins)
- [ ] Q&A and Adjourn (5 mins)

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username:
   - ...

## Decisions Made
- ...

## Action Items
- [ ] ...

**Comment by lspiro-Tick42** [comment]
Here

**Comment by rikoe** [comment]
Here

**Comment by agitana** [comment]
hello

**Comment by ggeorgievx** [comment]
Present ✅

**Comment by tarsillon1** [comment]
Here!

**Comment by mattjamieson** [comment]
👍

**Comment by kriswest** [comment]
Here :mask:

**Comment by donbasuno** [comment]
Present

**Comment by ajaym** [comment]
Here

**Comment by toshaellison** [comment]
I was there!
