### ISSUE TITLE
Community usage of channels, intents and context types

### ISSUE THREAD

**Issue by rikoe** [finos/FDC3#317]
If you are using FDC3 context types and/or intents, please comment on this issue.

FDC3 is working on a process to easily add community contributions to the https://fdc3.finos.org website, until then context types and intent usage can be described here.

### Application

Name: My application
URL: https://myapp.com

###  Intents

Intent name: `ViewAnalysis`
Supported types: `fdc3.instrument`

Intent name: `StartChat`
Supported types: `fdc3.contact`, `fdc3.contactList`

###  Channels

Channel name: `global`
Broadcast types: `fdc3.instrument`
Listen types: `fdc3.organisation`

###  Custom types

Type name: `factset.showOrder`
Example:
```json
{
  "type": "factset.showOrder",
  "id": {
      "orderId": "1234"
   },
  "description": "a really nice order",
  "instrument": { "type": "fdc3.instrument" }
}
```

**Comment by rikoe** [comment]
### Application
Name: Reactive Trader
URL: https://github.com/AdaptiveConsulting/ReactiveTraderCloud
Description: Showcase app for real-time FX Trading

### Channels
Channel name: `global`
Broadcast types: `fdc3.instrument`

### Context Types
Type name: `fdc3.instrument`
Example:
```json
{
  "type": "fdc3.instrument",
  "id": {
      "ticker": "EURUSD"
   }
}
```

**Comment by rikoe** [comment]
### Application
Name: Reactive Analytics
URL: https://github.com/AdaptiveConsulting/ReactiveAnalytics
Description: Demo app to view news and analytics for stocks and FX

### Channels
Channel name: `global`
Broadcast types: `fdc3.instrument`
Listen types: `fdc3.instrument`

### Context Types
Type name: `fdc3.instrument`
Example:
```json
{
  "type": "fdc3.instrument",
  "id": {
      "ticker": "EURUSD"
   }
}
```

**Comment by TBFactSet** [comment]
### **Application**

Name: FactSet
URL: https://my.apps.factset.com/navigator/company-security/targets-and-ratings
Description: FactSet Company Report

 
### **Channels**

Channel name: set by container/FDC3 provider
Broadcast types: fdc3.instrument
Listen types: fdc3.instrument

### **Context Types**

Type name: fdc3.instrument
Example: 

{
"type": "fdc3.instrument",
"id": {
"CUSIP":"G12793108",
"FDS_ID":"FFRK1YL",
"ISIN":"GB0007980591",
"SEDOL":"0798059",
"ticker":"BP",
"FDS_TICKER_EXCHANGE":"BP-LON",
"FDS_TICKER_REGION":"BP-GB"},
"name":"BP p.l.c.",
"exchangeMic":"XLON",
"exchangeMicFds":"LON"
}

**Comment by rbruckheimer** [comment]
### Application
​Name: ChartIQ by Cosaic
URL: https://cosaic.io/chartiq/

### Intents
​Intent name: `ViewChart`
Supported types: 
- `fdc3.instrument`
- `fdc3.instrumentList`
- `fdc3.position`
- `fdc3.portfolio`
- `fdc3.chart`
- `fdc3.dateRange`
- `fdc3.indicator`
- `cosaic.chartiq.state`

See https://github.com/finos/FDC3/blob/03e46320df236f2c566ea9fcb2805358a3e19ad2/docs/context/spec.md, or iterate through list at https://github.com/finos/FDC3/tree/03e46320df236f2c566ea9fcb2805358a3e19ad2/docs/context/ref for descriptions of proposed new and enhanced types https://github.com/finos/FDC3/pull/443

### Channels
​Channel name: System channels (color channels)
Broadcast types: same list as above
Listen types: same list as above

### Custom types
​Type name: `cosaic.chartiq.state`
Example:
```json
{
  "type": "cosaic.chartiq.state",
  "layout": {
      "symbols": [...],
      "interval": {...},
      ...
   }
}
```
The spec for `layout` matches that documented by ChartIQ here: https://documentation.chartiq.com/CIQ.ChartEngine.html#layout

**Comment by kriswest** [comment]
Superceded by new community page in website, closing
