### ISSUE TITLE
Proposal for the creation of an FDC3 / Interoperability training

### ISSUE THREAD

**Issue by mindthegab** [finos/FDC3#342]
Given the current uptake in adoption of FDC3, and in order to further grow the awareness / readiness of the industry to adopt and contribute to the standard, now that FINOS is part of the Linux Foundation, we have a large scale training delivery platform we can leverage - which can also integrate with firms learning management systems and learning paths.

FINOS is proposing to build (and fund) a training curriculum for FDC3 and we'd like to validate the idea with the existing Community and leadership. The target audience would be FDC3 application developers and generally technologists who could benefit from the standard.

As some of you might remember, @rikoe had proposed a potential outline for an instructor led course last year, which I'd like to use as a starting point for gathering feedback / validation.

So here's my asks:
1. Add a 👍 or comment to this issue if you support the idea of a FINOS + LF powered FDC3 training program
2. Add comments below to provide feedback on the outline proposed below and / or to include additional topics you'd like to be covered. 
3. Let us know if you think a self paced (non instructor led) training would be useful and which topics that would ideally cover.

I would appreciate your comments by the March 12th COB.

**Potential FDC3 course (instructor led) outline:**

_Session 1_

- Welcome (10 mins)
- Concepts of Desktop Interoperability and FDC3 (30 mins)
- Q & A (20 mins)

_Session 2_
- Creating an FDC3 App Directory (10 mins)
- Hands-on coding (40 mins)

_Session 3_
- FDC3 context sharing (10 mins)
- Hands-on coding (40 mins)

_Session 4_
- FDC3 intents (10 mins)
- Hands-on coding (30 mins)

Let us know your thoughts!

**Comment by michalbelka** [comment]
Love the idea! Just similar to others, I think more focus on context sharing would be great.

**Comment by kerriganb** [comment]
Training would be wonderful. I know when i first saw the spec, i then said - ok now what... There doesn't seem to be much information on how to go ahead and create a FDC3 desktop agent. Seems more focused on being FDC3 complaint app - which is fine. But how about.

1. hello world type - compliant app (basic intents, communication)
2. hello world type - desktop agent

I know FDC3 is still young - but any thoughts on adding platform specific topics? (layout, notifications etc?)

Also thoughts on inter - desktop agent communication? (specs seems to brush over this a bit)

**Comment by mindthegab** [comment]
Thanks everyone for the amazing and timely feedback. Let me see how best we can integrate all this feedback into a consolidated proposal for final review so we can move forward.

**Comment by rikoe** [comment]
If I summarise the above feedback, would the following seem like a good outline:

- Session 1
**Intro to FDC3**, including motivation, open source and vendor frameworks and tools, how the FDC3 standard & community works, how to get involved, and where to start
- Session 2
**Context data**, including using standardised types, defining your own types through composition, and how to share/contribute your types
- Session 3
**Intents and context sharing**, including how to either raise intents or broadcast data based on application use case, and how to listen to these
- Session 4
**Desktop agents and service discovery/orchestration**, including the role of the app directory, and how you would go about writing your own desktop agent

Ideally, it would be great to pick an example use case/workflow and carry it through all four sessions

**Comment by kerriganb** [comment]
I think that would be great. Also maybe a roadmap on notifications as well.

Get Outlook<https://aka.ms/qtex0l> for iOS
________________________________

**Comment by rikoe** [comment]
> I think that would be great. Also maybe a roadmap on notifications as well.

@kerriganb what do you mean by notifications?

**Comment by mindthegab** [comment]
To close the loop here - thanks to the fantastic input from @rikoe, we are now in the process of building an introductory training for FDC3 which is targeted to be completed by mid Q4.  We decided to start with an introductory training and then, based on feedback and uptake, take next steps (e.g. produce an advanced training).

We will keep this issue open (assigning to you @rikoe) and we can close it with the details later in the year when the training is produced.

**Comment by rikoe** [comment]
Thanks @mindthegab - the current high-level outline is shaping to look as follows (subject to change):
- Introduction to Interoperability
- Introduction to the FDC3 Standard
- Context Data
- Intents and Context Channels
- App Directories
- Desktop Agents and the FDC3 API
- Workflow-driven Design
- The FDC3 Community

Such an online course would be aimed at both technical and business professionals (read: not overly technical), and we believe it is a strong set of content.

Depending on uptake, we could then follow up with a more technical, developer-oriented course that explains how to use FDC3 in detail, with practical exercises.

**Comment by agitana** [comment]
Thank you @rikoe, @sebmos and @ivanfalanga from Adaptive for developing [FDC3: Interoperability for the Financial Desktop (LFS177x)](https://www.finos.org/blog/fdc3-course-simplifies-learning-open-standards-for-financial-desktops?utm_campaign=Subscriptions&utm_medium=email&_hsmi=180755494&_hsenc=p2ANqtz-8d-NaQwRopUPIKHlLdn2Qx4mGXhH37d0jzxWroUoaawELH-b96K-jr-1QBcE32xNHxc-J9D4skkoUxfbbXH6qB3VLgoQ&utm_content=180755494&utm_source=hs_email)! 

Read more about the FDC3 course in this FINOS Blogpost: [FDC3 course simplifies learning open standards for financial desktops](https://www.finos.org/blog/fdc3-course-simplifies-learning-open-standards-for-financial-desktops?utm_campaign=Subscriptions&utm_medium=email&_hsmi=180755494&_hsenc=p2ANqtz-8d-NaQwRopUPIKHlLdn2Qx4mGXhH37d0jzxWroUoaawELH-b96K-jr-1QBcE32xNHxc-J9D4skkoUxfbbXH6qB3VLgoQ&utm_content=180755494&utm_source=hs_email) and join the Adaptive team at the [New York FINOS member meeting (today) and OSSF (tomorrow)](https://events.linuxfoundation.org/open-source-strategy-forum-new-york/) tomorrow!
