### ISSUE TITLE
FDC3 General Meeting - May 4, 2021

### ISSUE THREAD

**Issue by mcleo-d** [finos/FDC3#382]
## Date
4 May 2021 - 10am EST / 3pm GMT

### WebEx info
- [Meeting Link](https://finos.webex.com/finos/j.php?MTID=m3015a7e4a511656ceafebda5eadcbe6d)
- Meeting number: 403 028 328

*More ways to join*
- Join by video system: dial 173.243.2.68 and enter your meeting number
- Join by phone
   - +1-415-655-0003 US Toll
   - +44-20319-88141 UK Toll
- Access code: 403 028 328

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://github.com/finos/community/blob/master/governance/Meeting-Procedures.md#run-the-meeting). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://odp.finos.org/docs/finos-maintainers-cheatsheet/).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://github.com/finos/community/blob/master/governance/Code-of-Conduct.md) and all other [FINOS policies](https://github.com/finos/community/tree/master/governance#policies).

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call, review meeting notices (5mins)
- [x] FDC3 1.2 has been released! (10 mins)
- [x] Looking ahead to FDC3 2.0 (10 mins)
- [x] Please help make FDC3 better (10 mins)
- [x] Q&A (10 mins)

## Decisions Made
- [ ] ...

## Action Items
- [ ] ...

## Untracked attendees
- Full name, affiliation, GitHub username (optional)

**Comment by agitana** [comment]
hi!

**Comment by kriswest** [comment]
🚀 Present

**Comment by rikoe** [comment]
Here

**Comment by mcleo-d** [comment]
Hello ... 🎉

**Comment by chedzoir** [comment]
Here

**Comment by dominicgifford** [comment]
Here

**Comment by novavi** [comment]
Here

**Comment by toshaellison** [comment]
Here (Tosha Ellison, FINOS)

**Comment by psmulovics** [comment]
here (Peter Smulovics, Morgan Stanley)

**Comment by TBFactSet** [comment]
hi

**Comment by donbasuno** [comment]
🎁
