### ISSUE TITLE
Why only positive holdings in a position context?

### ISSUE THREAD

**Issue by dominicgifford** [finos/FDC3#391]
### Question Area
[ ] App Directory
[ ] API
[x] Context Data
[ ] Intents
[ ] Use Cases
[ ] Other

### Question
Looking at [https://github.com/FDC3/FDC3/blob/master/src/context/schemas/position.schema.json](https://github.com/FDC3/FDC3/blob/master/src/context/schemas/position.schema.json) it specifies that the holding value has a min value of zero.

I'm finding it difficult to understand why that is the case and would appreciate any guidance on how I transmit data for a short position which in my portfolio modelling system would be expressed as a negative holding and therefore less than zero.

many thanks

**Comment by kriswest** [comment]
@dominicgifford You make a good point, would you be willing to submit a PR to improve the type?

You'd need to update:
- schema: https://github.com/FDC3/FDC3/blob/master/src/context/schemas/position.schema.json
- type: https://github.com/FDC3/FDC3/blob/d9a1a444b6d4d1dbab39a3a01bf020e33adb3f86/src/context/ContextTypes.ts#L97-L103
- spec: https://github.com/FDC3/FDC3/blob/master/docs/context/spec.md#position
- reference: https://github.com/FDC3/FDC3/blob/master/docs/context/ref/Position.md
