### ISSUE TITLE
PMC Meeting - June 04, 2021

### ISSUE THREAD

**Issue by kriswest** [finos/FDC3#397]
## Date
Friday 04 June 2021 - 9am EST / 2pm GMT

### WebEx info
- [Meeting Link](https://finos.webex.com/finos/j.php?MTID=mb24e0868b724abcfa92221ca14207e14)
Description:FDC3 PMC Meeting
Meeting number: 663 444 364
Dial in:
+1.415.655.0003 USA Toll
+44-20319-88141 UK Toll
Access code: 663 444 364

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://github.com/finos/community/blob/master/governance/Meeting-Procedures.md#run-the-meeting). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://odp.finos.org/docs/finos-maintainers-cheatsheet/).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://github.com/finos/community/blob/master/governance/Code-of-Conduct.md) and all other [FINOS policies](https://github.com/finos/community/tree/master/governance#policies).

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call, review meeting notices (3mins)
- [x] Review actions from previous meeting (2mins)
  - [x] Discuss meeting minutes for PM and SWG meetings
- [x] Adopting the community specification license
  - [x] Governance roles and the purpose of the PMC
  - [x] A formal rewrite of the specification
- [x] Update on Channels Working/Discussion group set-up
- [ ] Reviewing and improving the FDC3 website
  - [ ] Home page
  - [ ] an implementations page
  - [ ] micro-site for the community types initiative
- [x] AOB

## Decisions Made
- (silent-consent) Someone will be appointed for each minute to record minutes (will be @kriswest or @rikoe if both are present)
   - Will annotate how decisions are made (either voting or silent consent)
- (silent-consent) FDC3 would like to move to the new Communication Specification License in the future: https://github.com/finos/standards-project-blueprint
  - The PMC will work to establish the necessary steps and implications to share with the Standards Working Group
- (silent-consent) Sub-groups (e.g. channels) will be called "discussion groups" going forward
- (silent-consent) Reviewing and improving FDC3 website will be discussed at next PMC meeting, with the aim of drafting an issue and solicit contributions

## Action Items
- [ ] Aitana to find out how FINOS can support FDC3 in rewriting specifications, there are concerns about the amount of work involved
- [ ] Start an email thread with FINOS legal team for questions about the move to the CSL
  - How do existing structures map to new model (maintainers, PMC etc.)
  - Do we need buy-in from all previous contributors for previous versions if we adopt CSL for 2.0 onwards
  - How do contributions for version 2.0 before the CSL is adopted apply in terms of the CLA used for the contributions
- [ ] PMC members to review the standards-project-blueprint / Communication Specification license and prepare any further questions for the FINOS legal team

**Comment by mattjamieson** [comment]
:wave:

**Comment by agitana** [comment]
hi!

**Comment by kriswest** [comment]
here

**Comment by dominicgifford** [comment]
Here

**Comment by jgavronsky** [comment]
Jane here

**Comment by lspiro-Tick42** [comment]
Here

**Comment by rikoe** [comment]
hello
