### ISSUE TITLE
Channels, Feeds & Transactions Discussion group

### ISSUE THREAD

**Issue by kriswest** [finos/FDC3#399]
## Meeting notices
Meeting notices from the Standards Working Group meetings apply to all discussion group meetings:
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://github.com/finos/community/blob/master/governance/Meeting-Procedures.md#run-the-meeting). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://odp.finos.org/docs/finos-maintainers-cheatsheet/).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://github.com/finos/community/blob/master/governance/Code-of-Conduct.md) and all other [FINOS policies](https://github.com/finos/community/tree/master/governance#policies).

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Group overview
There are currently 11 open issues in the FDC3 repository, under consideration for the 2.0 release, that relate to the existing concept of **channels** (both the 'system channels' used via the desktop agent API, and 'app channels' interacted with through the Channels API) and new concepts we've discussed introducing: **transactions** (a standardized way to make a request and receive a response back) and **feeds** (a standardized way to request a stream of data, such as a pricing stream). 

Hence, a Channels, Feeds & Transactions discussion group has been proposed - which @kriswest has offered to organise.

If you'd like to get involved please complete [the Doodle poll](https://doodle.com/poll/7urcexayn4h6w55z) to help us pick a time for a first meeting and/or take a look at the list of currently open issues. Discussion of further issues to include or the scope of the group can also be held on the group's issue.

N.B. A Discussion Group has no direct decision-making power regarding the FDC3 standard - rather it is intended that anything they propose or work on will result in proposals (via Github issues and PRs) for the Standards Working Group participants to consider and vote on for inclusion in the standard. As such, participation in a Discussion group is not required for contributing to any particular issue or FDC 2.0 as a whole.

### Relevant issue tags
Current open issues that relate to the above concepts with the label: 
[![](https://user-images.githubusercontent.com/1701764/120999635-422ebd00-c781-11eb-8033-7f6ff251605b.png)](https://github.com/finos/FDC3/labels/channels%20feeds%20%26%20transactions)

  
#### Date
Thursday 1st July 14:00 BST / 09:00 ET
[Event in the FINOS community calendar](https://calendar.google.com/calendar/u/0/r/week/2021/7/1?eid=NnU2cmNmZ2s4bGlpaHZhbGRuc2htdTExYmdfMjAyMTA3MDFUMTMwMDAwWiBmaW5vcy5vcmdfZmFjOG1vMXJmYzZlaHNjZzBkODBmaThqaWdAZw&ctz=America/New_York&sf=true)
This is recurring invite every 2 weeks (initially for 4 iterations)
Anyone who would like to be added to the calendar invite directly should email help@finos.org

#### Agenda
- Introductions and meeting notices (10 mins)
  - Goal of the group
- Overview of (and quick comments on) tickets in scope (10 mins)
- Discuss (30 mins):
  - Defining App & System Channels 
  - Use-cases and initial proposals for Feeds & Transactions
- Arrange action items and volunteers to work on them for next meeting (5 mins)
- AOB & adjourn (5mins)

#### Meeting details
https://finos.webex.com/finos/j.php?MTID=me73c148c2a72069d2e76c3b295e95ae2
Meeting number: 127 111 4958
Password: e3EeiZkzF25
Join by video system
Dial 1271114958@finos.webex.com
You can also dial 173.243.2.68 and enter your meeting number.
Join by phone
+1-415-655-0003 US Toll
+44-20319-88141 UK Toll
Access code: 127 111 4958

**Comment by kriswest** [comment]
Updated with first meeting date: Thursday 1st July 14:00 BST / 09:00 ET

**Comment by thorsent** [comment]
Present

**Comment by ggeorgievx** [comment]
Present ✅

**Comment by kriswest** [comment]
here

**Comment by lspiro-Tick42** [comment]
Here

**Comment by rikoe** [comment]
here

**Comment by mattjamieson** [comment]
:heavy_check_mark:

**Comment by openfin-gavin** [comment]
here

**Comment by algreasley** [comment]
here

**Comment by dcj99** [comment]
here

**Comment by agitana** [comment]
hi, Aitana Myohl (FINOS) here

**Comment by Julia-Ritter** [comment]
Here- Thank you everyone :)

**Comment by agitana** [comment]
## Untracked attendees
- Yvonne Leung / State Street

**Comment by kriswest** [comment]
### Meeting minutes:
- Reviewed existing issues in scope
  - #242 Allow Desktop Agent To Join Multiple Channels
    - PR needs updating (pre 1.2 release)
    - Mix of opinions for and against + some discussion on issue post meeting
    - Should be voted on by the Standards Working Group and either closed or progressed
  - #362 All DesktopAgent and Channel APIs should be async
    - All in favour
    - Needs a PR
  - #313 Introduce a new fdc3.onChannelChanged(callback) method
    - This is only useful/necessary if you have two channel selectors (one in component, one provided by desktop agent) OR you really need to behave differently when connected or not connected to a channel.
    - If the Channel selector widget described in the use-case is implemented by the desktop agent then an API addition shouldn't be needed, plus the API addition as described would only notify the application, not the channel selector widget (which is presumably in a different window) and therefore doesn't solve for the use-case
    - Notes sent back to contributor of issue
    - Should be voted on by the Standards Working Group and either closed or progressed
  - #243 Allow Specification of Channel MetaData during Channel Creation
    - This issue arises from the poor definition of App and System channels - this was a topic of intense debate at the meeting and a common point of confusion for those learning to use the standard for the first time.
    - General agreement that we should work on refining those definitions (and names!) in 2.0.
    - CLOSED: Contributing firm (Coasic) would prefer to close issue and focus on #376 instead
  - #301 Reset Context
    - There remain issues with this proposal - the fdc.null or fdc3.nothing type could be used to enable resets, however, as FDC3 channels retain the last context of each type (rather than just the last context) we need to express which type was reset or reset all types.
    - Propose vote by SWG on whether to:
      - Add a field to null context type to express which type should be reset (default all)
      - All any type to be submitted with a `null` `id` field, with the null context resetting all types
      - Close issue/don't fix
   - #247 and #371 Extending the AppD app definition to to support describing contexts used on system channels and app channels created. 
     - General, if not strong, assent that this additional data would be useful.
     - Defer further discussion until later in scope after refinement of channel definitions #376 and consideration of other extension proposals
   - Should an issue be raised to add support for querying who is on a channel?
     - No strong support for this addition
       - Could be solved via UI in a desktop agent implementation
       - At least one opinion expressed that this was against the spirit of open interop
     - No further action/no issue to be raised
    - #376 Refine the description of App and System channels in the spec to clarify intended use
      - Fairly intense debate
      - App/System channels definition often confuses those new to the standard - particularly the naming
      - These two channel types (+intents) don't solve for all common interop use-cases and likely need augmenting
      - We need to return to use-cases for interop to fully resolve this issue
      - a major release (e.g. 2.0) is the right time to update such a fundamental concept in the standard
      - To be the primary subject of the next meeting
        - solicit write-ups of interop use-cases prior to the meeting for discussion.
        
### Action items
- @kriswest Create an issue for votes proposed so far
- *All* Write up interop use-cases for next meeting
  - @kriswest solicit these and attendance from FDC3 SWG participants
- @kriswest prepare agenda for next meeting - focused on interop use-cases and #376
