### ISSUE TITLE
PMC Meeting - Jul 2, 2021

### ISSUE THREAD

**Issue by rikoe** [finos/FDC3#417]
## Date
Friday 02 Jul 2021 - 9am EST / 2pm GMT

### WebEx info
- [Meeting Link](https://finos.webex.com/finos/j.php?MTID=mb24e0868b724abcfa92221ca14207e14)
Description:FDC3 PMC Meeting
Meeting number: 663 444 364
Dial in:
+1.415.655.0003 USA Toll
+44-20319-88141 UK Toll
Access code: 663 444 364

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://github.com/finos/community/blob/master/governance/Meeting-Procedures.md#run-the-meeting). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://odp.finos.org/docs/finos-maintainers-cheatsheet/).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://github.com/finos/community/blob/master/governance/Code-of-Conduct.md) and all other [FINOS policies](https://github.com/finos/community/tree/master/governance#policies).

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call, review meeting notices (3mins)
- [x] Review actions from previous meeting (2mins)
- [x] FDC3 marketing plan (5 mins)
- [x] Adoption of the new FINOS [Community Specification License](https://github.com/finos/standards-project-blueprint) (10 mins)
- [ ] Purpose of the PMC (10 mins)

## Decisions Made
- Carry over agenda item to next meeting:  Purpose of the PMC

## Action Items
- [ ] (carried over) Aitana to find out how FINOS can support FDC3 in rewriting specifications, there are concerns about the amount of work involved
- [ ] Aitana/Julia to connect with the FINOS marketing team to produce podcasts and blogs as defined in the FDC3 v1.2 Marketing Campaign Planning - Draft
- [ ] Riko to provide detail about the current FDC3 setup and structure to Scott Nicholas
- [ ] Scott Nicholas to report back on whether commenting on an issue constitutes contributing to FDC3 (and therefore binds the commenter to the license
- [ ] Aitana / Julia to check that FINOS requires and confirms CLA for anybody voting on revisions to the specification

**Comment by kriswest** [comment]
here

**Comment by rikoe** [comment]
here

**Comment by mattjamieson** [comment]
:wave:

**Comment by openfin-gavin** [comment]
here

**Comment by agitana** [comment]
hi! Aitana Myohl (FINOS)

**Comment by dominicgifford** [comment]
here

**Comment by donbasuno** [comment]
🎁

**Comment by scooter99boston** [comment]
here

**Comment by jgavronsky** [comment]
Jane here
