### ISSUE TITLE
Channels, Feeds & Transactions Discussion group meeting 15 July 2021

### ISSUE THREAD

**Issue by kriswest** [finos/FDC3#420]
## Group overview
There are currently ~11~ 10 open issues in the FDC3 repository, under consideration for the 2.0 release, that relate to the existing concept of channels (both the 'system channels' used via the desktop agent API, and 'app channels' interacted with through the Channels API) and new concepts we've discussed introducing: transactions (a standardized way to make a request and receive a response back) and feeds (a standardized way to request a stream of data, such as a pricing stream).

### Relevant issue tags
Current open issues that relate to the above concepts with the label: 
[![](https://user-images.githubusercontent.com/1701764/120999635-422ebd00-c781-11eb-8033-7f6ff251605b.png)](https://github.com/finos/FDC3/labels/channels%20feeds%20%26%20transactions)

## Meeting Date
Thursday 15 July 2021 - 9am EST / 2pm GMT

### WebEx info
- [Meeting Link](https://finos.webex.com/finos/j.php?MTID=me73c148c2a72069d2e76c3b295e95ae2)
  Meeting number: 127 111 4958
  Password: e3EeiZkzF25

- Join by video system
  Dial 1271114958@finos.webex.com
  You can also dial 173.243.2.68 and enter your meeting number.
  
- Join by phone
  +1-415-655-0003 US Toll
  +44-20319-88141 UK Toll
  Access code: 127 111 4958

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://github.com/finos/community/blob/master/governance/Meeting-Procedures.md#run-the-meeting). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://odp.finos.org/docs/finos-maintainers-cheatsheet/).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://github.com/finos/community/blob/master/governance/Code-of-Conduct.md) and all other [FINOS policies](https://github.com/finos/community/tree/master/governance#policies).

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.
  
- A Discussion Group has no direct decision-making power regarding the FDC3 standard - rather it is intended that anything they propose or work on will result in proposals (via Github issues and PRs) for the Standards Working Group participants to consider and vote on for inclusion in the standard. As such, participation in a Discussion group is not required for contributing to any particular issue or FDC 2.0 as a whole.

## Agenda
- [x] Convene & roll call, review meeting notices (5mins)
- [x] Review action items from previous meeting (5mins)
- [x] Application Interop use-cases (& whether they are all served by current FDC3 API features) (40mins)
  - Related issues:
    - #376 
    - #201 
    - #203
    - #220
- [x] AOB & Adjourn (5mins)

## Minutes
@kriswest presented notes on interop use-cases:
1. **User-controlled Context linking (system channels)**
  - Predefined colour channels with display metadata - currently called 'System channels'
    - Confusing name, not well defined in docs, only in spec
  - Any member of a channel can post or listen for (typed) context
    - No way to determine sender of messages
  - Currently supported
    - However, you can 'join' any channel with the API, which was probably not intended. Should we enforce only joining system channels?
  - Use-cases:
    - Use Case 1: Equity sell side trader:
    https://fdc3.finos.org/docs/use-cases/uc-1 (workflows 4 & 5)
    - Use Case 15: Sales Floor Base Workflow
    https://fdc3.finos.org/docs/use-cases/uc-15 
    - Use Case 17: Fine-tuning InterOp with Channels
    https://fdc3.finos.org/docs/use-cases/uc-17 
2. **Developer-controlled Context linking (app channels)**
  - Arbitrary named channels - currently called 'App channels'
  - Any member of a channel can post or listen for (typed) context
    - No way to determine sender
  - Currently supported via bus-style communication (with typed last value cache) on channels
  - Use-cases:
    - Use Case 9: Call Transcription to CRM
    https://fdc3.finos.org/docs/use-cases/uc-9 
    - Use Case 10: Real-Time voice trades -> trade ticket population
    https://fdc3.finos.org/docs/use-cases/uc-10 
    - Use Case 15: Sales Floor Base Workflow
    https://fdc3.finos.org/docs/use-cases/uc-15 
    - Use Case 17: Fine-tuning InterOp with Channels
    https://fdc3.finos.org/docs/use-cases/uc-17 
3. **Requesting an action (Raising an intent)**
  - Fire and forget - metadata is returned on what app resolved the intent, but no response data
  - Supported with a context or without (fd3.nothing type, coming soon)
  - Currently supported
  - Use-cases:
    - Use Case 1: Equity sell side trader
    https://fdc3.finos.org/docs/use-cases/uc-1 (workflows 1-3)
    - Use Case 2: Buy side Portfolio Manager
    https://fdc3.finos.org/docs/use-cases/uc-2 (workflows 3-6)
    - Use Case 9: Call Transcription to CRM
    https://fdc3.finos.org/docs/use-cases/uc-9 
    - Use Case 10: Real-Time voice trades -> trade ticket population
    https://fdc3.finos.org/docs/use-cases/uc-10 
    - Use Case 15: Sales Floor Base Workflow
    https://fdc3.finos.org/docs/use-cases/uc-15 
4. **Open an application (optionally with context)**
  - Currently supported (fdc3.open)
    - Although not possible to get a list of available applications through API
    - It IS possible to get a list of apps that can resolve an intent however...
  - Use-cases:
    - Use Case 3: In-house Cross-Platform Launcher
    https://fdc3.finos.org/docs/use-cases/uc-3 
    - Use Case 13: User launches multiple apps from a single container
    https://fdc3.finos.org/docs/use-cases/uc-13 
5. **Requesting a response (a Transaction or intent that returns data)**
  - Raising an intent and receive a single response back with data
    - Part of the original idea for intents, but not fulfilled correctly
  - Not currently supported!
  - Fairly simple proposal to resolve
  https://docs.google.com/document/d/1OTODXIbOifsBSWboAofTtUGRyxiFapcisCf8a65Ex8w/edit?ts=60db4746#heading=h.3tcfym35ggnx
    - Proposal to be posted on issue
    - How long should you wait? Does proposal need to incorporate an optional timeout?
  - Use-cases:
    - Use Case 4: Client-side FX Trader Credit Check
    https://fdc3.finos.org/docs/use-cases/uc-4 
    - Use Case 9: Call Transcription to CRM
    https://fdc3.finos.org/docs/use-cases/uc-9 
    - Use Case 15: Sales Floor Base Workflow
    https://fdc3.finos.org/docs/use-cases/uc-15 
    - Riko’s OSSF talk from 2020 describes a real-world use case in which an intent that returns data is useful:
    https://www.youtube.com/watch?v=sTyEphOHPKw
    **Intent**: ExecuteTrade
    **Context**: TradeRequest (requestId, instrument, side, price, quantity etc.)
    **Return context**: TradeResponse (requestId, tradeId, success/failure, timestamp etc.)
6. Requesting or sending  a (private?) stream of data (a Feed or Stream)
  - A more specific and more restricted channel for communicating with/receiving messages from a specific application on a specific topic
    - Messages to be delivered to a particular entity, NOT shared with other apps
    - Source of messages to be identifiable
    - Multiple responses at regular or irregular intervals
  - A context may be required to characterize the request (e.g. request pricing for specified security)
Stream likely to NOT exist before request (It's impractical to stream prices for every security) and may need to be cleaned up when no longer needed.
    - Track subscription/unsubscription
    - Need to be sure all responses come from the same entity (other apps should not be able to publish messages)
    - Not currently supported!
    - Use-cases:
      - Use Case 5: Buy side Treasurer - client rates across providers
https://fdc3.finos.org/docs/use-cases/uc-5 
      - Request a feed from a particular application that provides Pricing (type of feed) of specific security (context).  
      - RFQs (type) for a particular market sector, client or security (context)
Notifications feed
      - Any use-case where the sender must be known / it is imperative that other apps NOT be able to send their own messages.
      - Working with the container/Dekstop Agent itself, where the feeds are created and used by the desktop agent/container to implement functionality that interacts with the desktop, rather than a specific application. 
        - Feeds might be used to implement functions such as: 
          a. Workspace state saving
          b. Notification
          c. Federated search
          d. Authentication
          e. Lifecycle management (startup dependencies, graceful shutdowns)
          f. User preferences
        - Although FDC3 is not intended to provide an API for an application container, shared facilities like these are common parts of a multi-vendor Desktop and are not easy to implement with FDC3's channels and intents alone. The ability to integrate apps into a common platform is a key aspect of them working together

@lspiro-Tick42 also raised the streams feature in plexus as something we should review in a future meeting.

(Minutes still WIP)

## Action Items
- [x] Raise an issue to change the name of 'system channels' to 'user channels' and update documentation to be clear on what actions can only be performed on a user channel.
  - #430 
- [x] Raise an issue to consider deprecating fdc3.joinChannel as this is intended to be provided by the desktop agent as UI.
  - #431 
- [x] Raise an issue for the transactions proposal (intents that return data)
  - #432 
- [x] Raise an issue to add a stream or feed concept to FDC3 with a summary of the requirements agreed during the meeting. Proposals can then be added to that issue
  - #433

## Untracked attendees

| Full name | Affiliation | GitHub username |
|-----------|-------------|-----------------|
|           |             |                 |

**Comment by kriswest** [comment]
🚀

**Comment by ggeorgievx** [comment]
Present ✅

**Comment by openfin-gavin** [comment]
here

**Comment by thorsent** [comment]
Present

**Comment by lspiro-Tick42** [comment]
Here

**Comment by rikoe** [comment]
hi

**Comment by agitana** [comment]
Aitana Myohl / FINOS

**Comment by jgavronsky** [comment]
Jane@FINOS

**Comment by Julia-Ritter** [comment]
Julia Ritter / FINOS

**Comment by Julia-Ritter** [comment]
Untracked attendees:
- David Jones / ipushpull 
- Terry Thorsen / Cosiac 
- Yin Phyu / IHS Markit
