### ISSUE TITLE
Standard WG Meeting - Jul 22, 2021

### ISSUE THREAD

**Issue by rikoe** [finos/FDC3#425]
## Date
Thursday 22 Jul 2021 - 10am EST / 3pm GMT

### WebEx info
- [Meeting Link](https://finos.webex.com/finos/j.php?MTID=ma4b1de1b9f691d89e4b2ff380ec9687c)
Meeting number: 665 568 411

*More ways to join*
- Join by video system:
   - Dial 665568411@finos.webex.com
   - You can also dial 173.243.2.68 and enter your meeting number
- Join by phone
   - +1-415-655-0003 US Toll
   - +44-20319-88141 UK Toll
- Access code: 665 568 411

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://github.com/finos/community/blob/master/governance/Meeting-Procedures.md#run-the-meeting). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://odp.finos.org/docs/finos-maintainers-cheatsheet/).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://github.com/finos/community/blob/master/governance/Code-of-Conduct.md) and all other [FINOS policies](https://github.com/finos/community/tree/master/governance#policies).

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call, review meeting notices (5mins)
- [x] Review action items from previous meeting (5mins)
- [x] Antitrust policy guidance (5 mins)
- [x] Feedback from Channels, Feeds & Transactions Discussion Group (10 mins)
- [x] Review #413 (10 mins)
- [x] Review #301 (5 mins) [vote](https://github.com/finos/FDC3/issues/301#issuecomment-878980692)
- [x] Review #242 (5 mins) [vote](https://github.com/finos/FDC3/issues/242#issuecomment-878968419)
- [x] Review PRs needed (5 mins)
- [x] AOB & Adjourn (5mins)

## Decisions Made
- All attendees are encouraged to get involved in maintaining the standard by raising, reviewing & voting on issues and PRs, and potentially becoming a maintainer.
- Ensure that agenda item are requested for next SWG meeting at each meeting

## Action Items
- [x] (All) Participate in open votes:
  - multiple appD issues #413
  - #301 [direct link to vote](https://github.com/finos/FDC3/issues/301#issuecomment-878980692)
  - #242 [direct link to vote](https://github.com/finos/FDC3/issues/242#issuecomment-878968419)
- [x] (All) Review votes at next SWG meeting and close or agree to progress and apply `needs pr` label
- [x] @kriswest Create a needs-vote tag to help identify issues that have votes posted on them.
- [x] @rikoe Add to next meeting agenda:
  - issues #386 & #387
  - how we could handle extensions to the FDC3 spec (issue to be raised)
  - how to move to the community specification license

**Comment by ggeorgievx** [comment]
Present ✅

**Comment by dominicgifford** [comment]
here

**Comment by rikoe** [comment]
Present

**Comment by jberes** [comment]
Hello!

**Comment by kriswest** [comment]
here 🤖

**Comment by donbasuno** [comment]
🎁

**Comment by mazydar** [comment]
Present

**Comment by Julia-Ritter** [comment]
Julia / FINOS here

**Comment by jgavronsky** [comment]
Jane / FINOS here

**Comment by lspiro-Tick42** [comment]
Here

**Comment by agitana** [comment]
Aitana Myohl / FINOS
