### ISSUE TITLE
PMC Meeting - Sep 24, 2021

### ISSUE THREAD

**Issue by rikoe** [finos/FDC3#463]
## Date
Friday 24 Sep 2021 - 9am EST / 2pm GMT

### WebEx info
- [Meeting Link](https://finos.webex.com/finos/j.php?MTID=mb24e0868b724abcfa92221ca14207e14)
Description:FDC3 PMC Meeting
Meeting number: 663 444 364
Dial in:
+1.415.655.0003 USA Toll
+44-20319-88141 UK Toll
Access code: 663 444 364

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://github.com/finos/community/blob/master/governance/Meeting-Procedures.md#run-the-meeting). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://odp.finos.org/docs/finos-maintainers-cheatsheet/).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://github.com/finos/community/blob/master/governance/Code-of-Conduct.md) and all other [FINOS policies](https://github.com/finos/community/tree/master/governance#policies).

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call, review meeting notices (3mins)
- [x] Review actions from previous meeting #446 (2mins)
- [x] Linux Foundation assistance with switching to the CSL (5 mins)
- [x] Transfer of PMC responsibilities and discussions to FDC3 maintainers and Standard Working Group (10 mins)
- [x] AOB

## Decisions Made
- This will be the last PMC meeting, with the Standards Working Group and github Maintainers taking over all responsibilities
  - Eliminating these meetings will mean more time is available for discussions groups and organizing work among the maintainers.
  - Setup discussion groups to work on specific areas of the standard and report proposals back to the Standards Working Group. 
    - A maintainer should be responsible for each discussion group and responsible for ensuring minutes are taken and reported back to SWG.

## Action Items
- [x] @agitana to review [FDC3 readme](https://github.com/finos/FDC3/blob/master/README.md) and [website governance details](https://fdc3.finos.org/docs/fdc3-intro#how-is-fdc3-governed) and [get involved page](https://fdc3.finos.org/get-involved) for details about the PMC, governance etc. and submit a PR to update.
- [ ] @finos/fdc3-maintainers Remember to check that PRs have changelog entries when reviewing
- [ ] @kriswest to review diff since 1.2.0 and submit a catchup PR to fill out changelog

**Comment by mattjamieson** [comment]
:racing_car:

**Comment by kriswest** [comment]
Kris // Cosaic

**Comment by lspiro-Tick42** [comment]
Leslie / Glue42

**Comment by rikoe** [comment]
Riko / Adaptive

**Comment by agitana** [comment]
Aitana Myohl / FINOS

**Comment by donbasuno** [comment]
Johan / FactSet
