### ISSUE TITLE
Standard WG Meeting - Oct 28th, 2021

### ISSUE THREAD

**Issue by kriswest** [finos/FDC3#481]
## Date
Thursday 28 Oct 2021 - 10am EST / 3pm GMT

### WebEx info
- [Meeting Link](https://finos.webex.com/finos/j.php?MTID=ma4b1de1b9f691d89e4b2ff380ec9687c)
Meeting number: 665 568 411

*More ways to join*
- Join by video system:
   - Dial 665568411@finos.webex.com
   - You can also dial 173.243.2.68 and enter your meeting number
- Join by phone
   - +1-415-655-0003 US Toll
   - +44-20319-88141 UK Toll
- Access code: 665 568 411

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://github.com/finos/community/blob/master/governance/Meeting-Procedures.md#run-the-meeting). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://odp.finos.org/docs/finos-maintainers-cheatsheet/).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://github.com/finos/community/blob/master/governance/Code-of-Conduct.md) and all other [FINOS policies](https://github.com/finos/community/tree/master/governance#policies).

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [ ] Convene & roll call, review meeting notices (5mins)
- [ ] Review action items from previous meeting (5mins)
  - #459
- [ ] Other recent activity
  - **[Open for review]** #412 
    - #485 
  - **[Open for review]** #430
    -  #479
      - Renames getSystemChannels -> getUserChannels (getSystemChannels remains as a deprecated alias)
      - Renames joinChannel -> joinUserChannel (joinChannel remains as a deprecated alias)
   - **[Open for review]** #314 
      - #437 
   -  **[Open for review]** #165 
      - #367 
   -  **[Recently merged]** #434 
      - #464
   -  **[Recently merged]** #426 
      - #461
   -  **[Recently merged]** #456 
      - #457
   -  **[Recently merged]** #418
      - #454
   -  **[Recently merged]** #448 
      - #449 
   -  **[Recently merged]** #328 
      - #440
- [ ] #466
- [ ] #453 
- [ ] #387 
- [ ] #386 
- [ ] Next meeting agenda
  - To include: 
    - #412 
      - #485 
    - #468
- [ ] AOB & Adjourn (5mins)

## Minutes
- #466 
  - Consensus achieved that we should proceed with this issue
  - Needs PR
  - Offer to help with implementation from @lspiro-Tick42 and @kriswest
  - Review/feedback requested on layout and content proposed (comment on the issue please)
  
- #453
  - Consensus achieved for proceeding with further discussion
  - Add to next meeting agenda (multiple firms to present work on this topic for discussion)
  
- #387 
  - Divided opinions on whether to proceed with #387, with balance of opinion _for_ proceeding
  - Objection to proceeding from one meeting attendee relates to whether the issue falls under the FDC3 Charter 
    - opinions expressed **for** the issue being relevant to the charter (5 participants / firms) 
    - opinions against **for** the issue being relevant to the charter (1 participant / firm).
  - Meeting attendees:
    - expressed the opinion that allowing actions associated with notifications to issue communications to other apps, or raiseIntents for them to be resolved puts this issue within the scope of the charter 
    - expressed the opinion that Notifications are core to many user workflows (including between applications and platforms) and hence they warrant standardisation
    - reported that support for standardized notifications API and ability to route those notificaitons into a container was a feature regularly requested by their customers and that the lack of a standardized, cross platform API for doing so made it difficult for them to fulfill that request.
    - pointed out that the 3 commercial container vendors all support a notificaiton API and UI, with differing APIs (which also differ from the web standard), indicating that this issue does need standardisation
  - It was further discussed that standardisation could be handled via: 
    - Additions to the Desktop Agent API (implementation would then be the province of the Desktop Agent provider)
    - A standardized intent and context standard (The intent could then be handled by applications registered as supporting that intent) 
    - A hybrid approach, where a specific Desktop Agent API is used to submit notifications, but additional functions are also provided for subscribing to the notification data)
  - Consensus achieved that further discussion of this issue is warranted and that specific proposals should be raised for consideration.
    - Please comment on the issue in Github and/or raise proposals for further discussion - once there is further activity on the issue it can be brought back to a future meeting 

- #386 
  - Clarified that this issue does not relate to 'windowing' or 'window management' but rather to the communication of application state, encoded as an FDC3 Context, to a Desktop Agent to be included in a saved workspace or layout.
  - Two meeting attendees indicated that their firms have done work in this area, had encountered problems implementing support for it using existing FDC3 concepts (e.g. Channels, which do not identify the source of context broadcasts) and would support further work on the topic
    - One meeting attendee pointed out that even if the technical issues are solved, transmission of state information will still be a proprietary or unstandardized use of FDC3 for a common feature of a desktop container - indicating that some form of standardisation is warranted
  - One meeting attendee objected to the idea of standardization
    - But was willing to reduce or withdraw that objection is this was recorded as an optional part of the standard (not required for compliance, but with a convention defined in the standard record that MAY be provided by an implementation).
  - One meeting attendee indicated that the technical issue are perhaps relevant to discussions at the Channels, Feeds & Transactions discussion group on the topic of 'feeds' or 'transactions' as these concepts have the potential to solve some of the issues

## Decisions Made
- #466 to be implemented
- #453 is within the charter and there is consensus that work should be undertaken to achieve it
  - Possible approaches to be presented at next meeting
- #387 balance of opinion is that its within charter and there is interest in proceeding
  - Proposals to be raised or further commentary on issue before adding to a future meeting agenda.
  - Can be raised at the Channels, Feeds and Transactions discussion group
- #386 balance of opinion is that we should proceed with further discussion, but as an optional part of the specification (MAY)
  - Proposals to be raised or further commentary on issue before adding to a future meeting agenda.

## Action Items
- [x]  next SWG agenda @kriswest
  - #412 
    - #485 
  - #468 
  - #453
- [ ] Implement PR for #466 @lspiro-Tick42 @kriswest 
  
## Untracked attendees

| Full name | Affiliation | GitHub username |
|-----------|-------------|-----------------|
|           |             |                 |

**Comment by Julia-Ritter** [comment]
Untracked attendees:

- Saurabh Gupta / Natwest Markets 
- Andrew Hampshire / UBS
