### ISSUE TITLE
Improving "Getting Started | FDC3 Charter"

### ISSUE THREAD

**Issue by RexJaeschke** [finos/FDC3#488]
## Formalizing the FDC3 Standard documentation

This issue has been raised as part of work, sponsored by FINOS, to improve and formalize the documentation of the FDC3 standard.

## Summary

**Proposal**
1. See Issue #487 re moving this section and eliminate its heading.

## Scope

**Proposal(s)**

1. This contains trademarks, so we'll need to collect/acknowledge all of those in one place with proper legal notation, and then **not** use that notation with every other use.

2. Change "This <ins>S</ins>~~s~~tandard~~s group~~ is focused specifically on the desktop."

### Participation

**Proposal(s)**

1. Change "To be successful, the ~~FDC3 is expected~~<ins>maintenance and evolution of this Standard needs</ins> to have a critical mass of active participants for its duration."

### Licensing

**Proposal(s)**

1. Change "<ins>All deliverables</ins>~~The FDC3~~ will use Apache 2.0 license or similar ~~for all deliverables~~.

2. The use of "similar" here is problematic. For compliance purposes, what does "similar" mean?

**Comment by kriswest** [comment]
@RexJaeschke In the Licensing section, we'll need to further clarify licenses beyond whats proposed here. Note this proposed update to the readme file in the repo, which also covers licensing:
https://github.com/finos/FDC3/blob/17892008c26a73ff1fd9f6e40ceb8c8bfd58c610/README.md#license

That PR (in full here: https://github.com/finos/FDC3/pull/485/files) is intended to move us towards the proposed FINOS standards governance based on the Community Specification License: https://github.com/finos/standards-project-blueprint/blob/master/4._License.md
(note that PR can be confusing as the version 1.0 of FDC3 was covered by a specific agreement).

Hence, I'll import the chunk from the Readme for now, although we should probably talk about the route to the CSL...
