### ISSUE TITLE
ViewHoldings Intent

### ISSUE THREAD

**Issue by dominicgifford** [finos/FDC3#497]
### Use Case:

1. Investment Manager (IM) is reading a news or research article about an issuer or security
2. IM decides to check their holdings in that issuer or security. 
3. The news or research application offers a ViewHoldings option and a resolver UI could offer all applications that are registered to handle the ViewHoldings intent. 
4. IM selects an application such as an Investment Management Platform where the holdings are then displayed

#### \<ViewHoldings\>
Systems that maintain holdings can handle this intent
Input would be a context that describes the issuer or security i.e. an Organization or Instrument context.
In a request/response scenario there would be no response to the calling application.

### Contexts

- Instrument
- InstrumentList
- Organization
- OrganizationList* - see Details

##### Details
In addition to the details outlined in the use case above, the group might want to consider extending the ViewHoldings intent so that it could also handle InstrumentList or OrganizationList (a new context type that is a collection of Organization objects).

**Comment by dominicgifford** [comment]
Thanks for all the comments and suggestions on today's Context Data and Intents discussion group. One of the questions was about how to identify which holdings/whose holdings to show in the target application. In this case, I would liken ViewHoldings to ViewNews. ViewNews takes a context of a Country/Instrument[List]/Organisation/Portfolio. But nowhere in the payload for the ViewNews intent is there any option to tell the News application whose articles you should show ("just show me articles from the UK broadsheets", for example). The content delivered by the target application remains the business of the target application for ViewNews and I'm proposing the same thing here.

**Comment by rikoe** [comment]
I agree that there is precedent already for this type of use case and intent, and that we don't necessarily need to answer the question "whose holdings" as part of this. This is about providing building blocks for constructing workflows, and I think `ViewHoldings` will be a good addition.

**Comment by pauldyson** [comment]
I'd like to register our support for this proposed intent and also to add that Contact or ContactList would also be a valid context as individual Fund and Portfolio managers 'hold' stock on behalf of their Institutions.
