### ISSUE TITLE
InstrumentList is missing from ContextTypes

### ISSUE THREAD

**Issue by bingenito** [finos/FDC3#500]
## Minor Issue
InstrumentList = 'fdc3.instrumentList' is missing from ContextTypes enum.  ContactList exists as precedent.

### Area of Issue
[ ] App Directory
[ ] API
[x] Context Data
[ ] Intents
[ ] Use Cases
[ ] Other

**Comment by kriswest** [comment]
@bingenito Raised a PR to add the missing type. Will require a release of the NPM module if you are using it from there. As it's an omission it could probably be cherrypicked into a release a 1.2.* release if you need it.
