### ISSUE TITLE
Standard WG Meeting - Nov 18th, 2021

### ISSUE THREAD

**Issue by kriswest** [finos/FDC3#505]
## Date
Thursday 18 Nov 2021 - 10am EST / 3pm GMT

### WebEx info
- [Meeting Link](https://finos.webex.com/finos/j.php?MTID=mfb5a2e624c17af6a585d2da5b86d96af)
Meeting number: 2552 255 0502

*More ways to join*
- Join by video system:
   - Dial 25522550502@finos.webex.com
   - You can also dial 173.243.2.68 and enter your meeting number
- Join by phone
   - +1-415-655-0003 US Toll
   - +44-20319-88141 UK Toll
- Access code: 2552 255 0502
- Password: pbMT7rxay24

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://github.com/finos/community/blob/master/governance/Meeting-Procedures.md#run-the-meeting). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://odp.finos.org/docs/finos-maintainers-cheatsheet/).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://github.com/finos/community/blob/master/governance/Code-of-Conduct.md) and all other [FINOS policies](https://github.com/finos/community/tree/master/governance#policies).

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call, review meeting notices (5 mins)
- [x] Review action items from previous meeting and other recent activity (5 mins)
  - #481 
  - FDC3 training course now available: [Enroll here](https://www.edx.org/course/fdc3-interoperability-for-the-financial-desktop)
  - PRs open for review:
    - #165 
      - #367  (Open todo items)
    - #308
      - #496 
    - #314 
      - #437 (Relevant to today's agenda)
    - #430 
      - #479 
    - #432 
      - #495 
    - #442 
      - #443 (Relevant to #490)
    - #451 
      - #492
    - #498
      - #499 
    - #500
      - #503 
  - New issues for discussion:
    - #506
    - [**Formal specification issues**](https://github.com/finos/FDC3/issues?q=is%3Aissue+is%3Aopen+label%3A%22formal+specification%22)
- [x] Opportunity to comment on #412 (5 mins) 
  - PR: #485 
- [x] #453 (20 mins)
- [ ] #468 (20 mins)
- [ ] AOB & Adjourn (5 mins)

## Minutes
- #412 
  - No objections to the proposed governance updates were raised
  - Governance update comments on #485 will be discussed with the JDF/FINOS
  - All were encouraged to review the PR, which will be merged after comments submitted have been dealt with
- #453 
  - Natwest Markets presented their use-case and work on Desktop Agent Bridging
    - Use-case: 
      - Their users have multiple application types:
        - Freestanding Legacy C# apps
        - Freestanding Javascript apps running in a browser
        - Web apps hosted in containers (Finsemble & OpenFin)
        - Symphony apps
      - Their users also have multiple PCs running these applications
      - They desire interop between all these app types, including across machines
  - Approach they've taken
    - DesktopAgent Backplane infrastructure
      - Implements the Desktop Agent for freestanding C# applications and Javascript apps in a web browser
      - Uses a Bridge service to connect into each desktop agent (e.g. in a web container) - the bridge service is specific to each Desktop Agent implementation
      - Works across multiple machines that the user is logged into
    - Bridge services cannot be fully implemented using the current Desktop Agent API
      - Hence, each bridge service has to be implemented for a specific desktop agent using non-standard access to channels & intents
      - The bridge serives would benefit from standardisation allowing a general-purpose implementation
      - Other issues to look at:
        - How to provide a single/container agnostic IntentResolver UX across the agents
        - How to provide Security (it may not be desirable to repeat all messages to all other desktop agents)
        - Desktop agent discovery on other hosts
    - Natwest Markets is looking into contributing their approach/implementation to FINOS
  - Citi also confirmed that they have the same use-case
    - They have used a slightly different approach based on desktop agents connecting to each other directly to make calls
    - Trying to avoid dependency on a single centralised message bus (for resilience)
  - A meeting participant suggested that we should make compliance with any such extension to the standard optional
  - Consensus was achieved that: 
    - This is an interesting topic within FDC3's charter
    - A discussion group should be formed to work on proposals for extension of the FDC3 standard to support
- #468 
  - An introduction to this issue was given
  - It was observed that: 
    - connection to an AppD is currently required for compliance with the FDC3 specification
    - (according to the memory of one involved) it was not originally intended to be required in order to be compliant with the API specification (the 4 FDC3 specifications were separate)
    - Multiple firms have recently acknowledged the value that the existing AppD specification has had for them (e.g. Citi @ the NY members meeting, see #455) 
    - (according to multiple meeting participants) the AppD includes the definition of both Application records and a REST API for a directory of them and that these can (and have been) used separately
      - The Application record has a similar purpose and format to the W3C's web application manifest ([draft specification](https://w3c.github.io/manifest/) [MDN](https://developer.mozilla.org/en-US/docs/Web/Manifest))
        - ...which is extensible
        - but also does not provide fields needed to represent non-web applications (which are used with FDC3's appD)
    - The issue, as written, highlights some perceived issues with the AppD specification and proposes to deprecate and remove the entire AppD specification 
      - With the exception of the intent metadata (which is shown embedded into multiple different schema formats)
        - A meeting participant observed that: 
          - there isn't much point standardizing this if its embedded in a non-standard record.
          - the proposal could have sought to address the issues rather than removing the entire specification
          - Improving the AppD specification was a specific roadmap commitment for FDC3 2.0
    - Deprecation/removal of AppD is not necessary to allow Desktop Agent implementations to use a different mechanism for resolving intents and `fdc3.open` calls, it could instead be made optional by applying the MAY or SHOULD keywords in the spec, rather than MUST.
  - The end of the meeting curtailed discussion and it was resolved to pick up the discussion again at the next meeting

### Decisions Made
- Consensus that #453 is interesting and worth pursuing
  - Consensus that a discussion group should be formed to work on this, which the FDC3 maintainers will arrange
- Next meeting to be brought forward to 16th December to avoid Xmas

## Action Items
- [x] @kriswest Convene a discussion group to explore desktop agent bridging
  - First meeting: #523  
  - Next meeting: Wednesday 12th Jan 2pm GMT / 9am EST
- [x] @kriswest Next meeting agenda to include:
  - #468 
- [x] @Julia-Ritter Move next meeting appointment to Thursday 16th Dec
- Rolled over from previous meetings
  - [ ] Implement PR for #466 @lspiro-Tick42 @kriswest

## Untracked attendees

| Full name | Affiliation | GitHub username |
|-----------|-------------|-----------------|
|           |             |                 |

**Comment by copiesofcopies** [comment]
Aaron Williamson // FINOS

**Comment by agitana** [comment]
Aitana Myohl / FINOS

**Comment by RandallDang-Citi** [comment]
Randall Dang @Citi

**Comment by openfin-gavin** [comment]
Gavin Lauchlan / OpenFin

**Comment by pbaize** [comment]
Pierre Baize / OpenFin

**Comment by kriswest** [comment]
Kris West / Cosaic

**Comment by mattjamieson** [comment]
:rocket:

**Comment by opoupeney** [comment]
Olivier Poupeney / Symphony

**Comment by Julia-Ritter** [comment]
Julia / FINOS

**Comment by hampshan** [comment]
Andrew Hampshire @ UBS

**Comment by jgavronsky** [comment]
Jane @ FINOS

**Comment by greyseer256** [comment]
Hugh / FactSet

**Comment by sarahstone-cosaic** [comment]
Sarah Stone / Cosaic

**Comment by rikoe** [comment]
Riko Eksteen / Adaptive

**Comment by donbasuno** [comment]
Johan - FactSet

**Comment by Julia-Ritter** [comment]
Untracked attendees:

- Saurabh Gupta / Natwest Markets
- Yacine / UBS
- Manish / NWM

**Comment by kriswest** [comment]
Minutes for the (interesting IMHO) SWG meeting today have been posted in this issue: 
As usual please let me know about any inaccuracies or omissions.

**Comment by openfin-gavin** [comment]
@kriswest I did note that OpenFin has a concern over the community spec license based on previous proposed language that we don't currently see in the suggested text. We'll comment in the issue to track.
