### ISSUE TITLE
Missing ResolveError option when a user cancels raiseIntent

### ISSUE THREAD

**Issue by hampshan** [finos/FDC3#518]
### Area of Issue
[ ] App Directory
[ ] API
[ ] Context Data
[X] Intents
[ ] Use Cases
[ ] Other

### Issue Description: 
If a user cancels the intent resolution (e.g. by purposefully not selecting an application), there is no suitable ResolveError option to indicate this back to the caller of raiseIntent.

It would be useful to indicate this scenario so the code that raises the intent can choose to accept the "error" without raising errors to the user.

### Additional Context:
None

**Comment by kriswest** [comment]
@hampshan See PR #522, does that work for you (comment on the PR pls)?
