### ISSUE TITLE
Desktop Agent Bridging Discussion group

### ISSUE THREAD

**Issue by kriswest** [finos/FDC3#523]
## Group overview
Discussion group for developing proposals for producing bridges between FDC3 implementations (aka Desktop Agents), allowing applications running on one Desktop Agent, to integrate with FDC3 applications running on a second Desktop Agent for the same user.

The interop between applications running on different Desktop Agents aka Platforms would ideally cover
- Channels
- Raising and resolving Intents
- Launching Applications

### Relevant issue tags
Current open issues that relate to the above concepts with the label: 
[![image](https://user-images.githubusercontent.com/1701764/144856698-e49821ab-9c8e-4daf-99a1-23f4774c1fcd.png)](https://github.com/finos/FDC3/labels/Desktop%20Agent%20Bridging)

## Meeting Date
Wednesday 8th December 2021 - 9am EST / 2pm GMT

### WebEx info
- [Meeting Link](https://finos.webex.com/finos/j.php?MTID=m10525a53e3c1fc61a72a28bed0803381)
Meeting number: 2553 223 3803

*More ways to join*
- Join by video system:
   - Dial 625532233803@finos.webex.com
   - You can also dial 173.243.2.68 and enter your meeting number
- Join by phone
   - +1-415-655-0003 US Toll
   - +44-20319-88141 UK Toll
- Access code: 2553 223 3803

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://github.com/finos/community/blob/master/governance/Meeting-Procedures.md#run-the-meeting). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://odp.finos.org/docs/finos-maintainers-cheatsheet/).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://github.com/finos/community/blob/master/governance/Code-of-Conduct.md) and all other [FINOS policies](https://github.com/finos/community/tree/master/governance#policies).

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.
  
- A Discussion Group has no direct decision-making power regarding the FDC3 standard - rather it is intended that anything they propose or work on will result in proposals (via Github issues and PRs) for the Standards Working Group participants to consider and vote on for inclusion in the standard. As such, participation in a Discussion group is not required for contributing to any particular issue or FDC 2.0 as a whole.

## Agenda
- [x] Convene & roll call, review meeting notices (5mins)
- [x] Group goals, deliverables and description of process (5mins)
- [x] Introductions from attendees, to include a description of known use-cases (10mins)
- [x] Presentation of proposals from Citi and Natwest Markets + Q&A (30mins)
- [ ] Arrange Future meetings (5mins)
- [x] AOB & Adjourn (5mins)

## Minutes
- Introductions
  - Aaron Haines: Product manager @ NWM overseeing projects that work with FDC3 implemented in multiple containers/Desktop Agents and non-container legacy apps.
  - Manish: Developer @ NWM working on the Backplane (NWM desktop agent bridge) and FDC3 use in aps. 
  - Georgi Georgiev @ Glue42: FDC3 maintainer, keen to explore bridging opportunities in support of clients.
  - Hugh @ Factset: Software engineer working on FDC3 integrations and expanding usage in platform agnostic way.
  - Jane Gavronsky @ FINOS (CTO): Spends a lot of time talking to firms about their needs and technology solutions @ FINOS that can help solve for them.
  - Mike McClung @ Cosaic: Works on FDC3 support @ Cosiac and keen to understand client use-cases.
  - Qiana Chen @ Citi: Working on adoption of the FDC3 standard at Citi.
  - Randall Dang @ Citi: Development manager responsible for FDC3 community and app directory at Citi. 
  - Sarah Stone @ Cosaic: Product manager for Finsemble at Cosaic
  - Saurabh Gupta @ NWM: Engineering lead for desktop engineering platform, where FDC3 is an important part of automating workflows through app interop.
  - Late joiners:
    - Benjamin McBride @ Wellington
    - Michael & Pierre @ OpenFin
    - Andrew Hampshire @ UBS
- Use-cases / situations:
  - **Natwest markets**
    - We have users working in applications across both multiple PCs, multiplier containers (Finsemble, OpenFin), non-container legacy C# applications and Symphony applications
    - Our direction of travel is towards a web-technologies - but our journey to get there will be long hence we need to support all these application types 
  - **Citi**
    - Similar situation: Finsemble, OpenFin and Symphony applications + some apps running in a web browser that need to share context.
- Citi Proposal for bridging (images reproduced with permission)
  ![image](https://user-images.githubusercontent.com/1701764/145224497-bdc6f84d-234b-49fc-8fc2-419e54fb9eb9.png)
  - Connection between agents is largely via connecting to their app directories, with knowledge of the fact that an a particular appD relates to a particular other agent.
    - Current relationship between AppD and Desktop agent is under discussion
    - Can't provide detail of app instances where Desktop Agent API can.
  - Citi has an extensive app directory and an Intents and Context data repository that's integrated into that AppD
  - Used in multiple containers 
  ![image](https://user-images.githubusercontent.com/1701764/145224691-b3b85b39-746f-4840-98c6-4b277a4238ea.png)
  - Uses a set of adapters to connect other environments (often non-desktop agent based) into a their Finsemble based desktop
    - disadvantages: 
     - need to implement an adapter for each new container/environment
     - depends on one of the desktop agents always being running (centralised)
     - requires knowledge of what channels and intents to listen to - non-system channels are not discoverable, many intent listeners to add
   - Proposal for a better bridging solution:
   ![image](https://user-images.githubusercontent.com/1701764/145225187-4b800adc-d94e-4815-a426-572bf66698a8.png)
     - Extend the FDC3 Desktop Agent API to support direct connections between implementations
       - Each connects to all of the others
       - Uses a new getOrEstablishConnection function
    ![image](https://user-images.githubusercontent.com/1701764/145225848-ed93d92c-153c-48dd-99d6-30266372fd05.png)
    ![image](https://user-images.githubusercontent.com/1701764/145225894-937e780f-a669-41ec-b812-c4e8d94b6f5c.png)
    ![image](https://user-images.githubusercontent.com/1701764/145225929-0c723790-44f9-4326-85ad-a670c7f5db05.png)
    ![image](https://user-images.githubusercontent.com/1701764/145225960-3e003305-d1a4-4f1c-8caf-7329704fbc56.png)
    ![image](https://user-images.githubusercontent.com/1701764/145226007-8f8a6378-b437-47fa-b6b8-a3fc4683ed50.png)
    ![image](https://user-images.githubusercontent.com/1701764/145226793-74a563ce-e742-4456-84ab-4df52f85d026.png) 
      - Summary: A Desktop Agent connects to another, both end up with a connection object, they add a handler to it to receive messages, they can call sendMessage to send on to the other agent.
      - Some revisions to existing FDC3 API calls suggested:  
      ![image](https://user-images.githubusercontent.com/1701764/145228691-7f287214-c7c2-4442-9a72-719ac7cc3613.png)
        - add a target agent - suggested that this actually goes under AppMetadata
  - Problems to resolve
    - System channels differ between Desktop Agents
    - Need to add a handler to notify a desktop agent that a connection was received so it can also receive the Connection object,  without this the `receiveMessage` handler won't get added unless/until the remote container connects back.
      - We may or may not also need to add an additional event or status field indicating connection is ready (i.e. the `receiveMessage` handler has been added by the remote Desktop Agent)
    - Need to define `Resolution`, response from sendMessage, needs to support a variety of different response types so that these can be routed back to the caller (e.g. raiseIntent that ends up on a remote container needs to route an IntentResolution and possibly also subsequent result back to the container that raised it).  
    - Need to figure out discovery of desktop agents and/or however connections between them would be configured.
- Although the Natwest and Citi proposals are based on different topologies (container <-> backplane <-> container vs. container <-> container) the needs of the connection interfaces are similar and could be supported by a similar API.

## Action Items
- [ ] (all interested parties) Document high-level use-cases for connecting containers on issue: #453 
- [ ] (all interested parties) Document detailed use-cases and workflow description (what it looks like to the user) for cross-container functionality on specific API calls
  - e.g. 
    - `raiseIntent` targeting an app instance on another container, 
    - `findIntent` returning app details from multiple containers
    - `broadcast` on a system channel being delivered across multiple containers
    - `broadcast` on a user channel being delivered across multiple containers
    - joining a channel created on another container.
- [x] @kriswest Propose some slots for a next meeting in January (same day of week/time) and post a survey
- [x] @kriswest Next meeting agenda
  - Discuss documentation of detailed use-cases (how should this look to the user)
  - Discuss API proposals
  - Discuss security / where API should be implemented

## Untracked attendees

| Full name | Affiliation | GitHub username |
|-----------|-------------|-----------------|
|           |             |                 |

**Comment by ggeorgievx** [comment]
Present ✅

**Comment by Julia-Ritter** [comment]
Julia / FINOS

**Comment by kriswest** [comment]
Kris West / Cosaic

**Comment by jgavronsky** [comment]
Jane @ FINOS here

**Comment by greyseer256** [comment]
Hugh / FactSet

**Comment by agitana** [comment]
Aitana Myohl / FINOS

**Comment by RandallDang-Citi** [comment]
Randall / Citi

**Comment by pbaize** [comment]
Pierre / OpenFin

**Comment by MichaelMCoates** [comment]
Michael Coates / OpenFin

**Comment by sarahstone-cosaic** [comment]
Sarah Stone / Cosaic

**Comment by Qiana-Citi** [comment]
Qiana / Citi

**Comment by kriswest** [comment]
Options for a next meeting of the group:
- 🎉 Wednesday 5th Jan 2pm GMT / 9am EST
- 🚀 Wednesday 12th Jan 2pm GMT / 9am EST
- ❤️ Wednesday 19th Jan 2pm GMT / 9am EST

**Comment by manishbhutani** [comment]
Manish / NWM

**Comment by RandallDang-Citi** [comment]
These time slot are all good for me.

How about you, Qiana?

**Comment by RandallDang-Citi** [comment]
All the options work for me as well.

Thanks,
Qiana

From: Dang, Yunfeng Randall [ICG-IT] ***@***.***>
Sent: Thursday, December 9, 2021 3:55 PM
To: finos/FDC3; finos/FDC3; Chen, Qia Qiana [ICG-IT]
Cc: Comment
Subject: RE: [finos/FDC3] Desktop Agent Bridging Discussion group (Issue #523)

These time slot are all good for me.

How about you, Qiana?

**Comment by kriswest** [comment]
@Julia-Ritter could you book the next meeting in for Wednesday 12th Jan 2pm GMT / 9am EST, please?

**Comment by Julia-Ritter** [comment]
Hello everyone, 

The new FDC3: Desktop Agent Bridging Discussion Group meeting has been scheduled for **Wednesday 12th Jan 2pm GMT / 9am EST** and a meeting invite has been sent out. Please let me know if you did not receive the calendar invite and need to be added.

Thank you for sharing your meeting preferences- and we look forward to speaking then in January,
Julia
