### ISSUE TITLE
Standard WG Meeting - Dec 16th, 2021

### ISSUE THREAD

**Issue by kriswest** [finos/FDC3#526]
## Date
Thursday 16th Dec 2021 - 10am EST / 3pm GMT

### WebEx info
- [Meeting Link](https://finos.webex.com/finos/j.php?MTID=me941400670d1240bd426d2b2c70b3506)
Meeting number: 665 568 411
Password: pbMT7rxay24

*More ways to join*
- Join by video system:
   - Dial 665568411@finos.webex.com
   - You can also dial 173.243.2.68 and enter your meeting number
- Join by phone
   - +1-415-655-0003 US Toll
   - +44-20319-88141 UK Toll
- Access code: 665 568 411

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://github.com/finos/community/blob/master/governance/Meeting-Procedures.md#run-the-meeting). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://odp.finos.org/docs/finos-maintainers-cheatsheet/).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://github.com/finos/community/blob/master/governance/Code-of-Conduct.md) and all other [FINOS policies](https://github.com/finos/community/tree/master/governance#policies).

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call, review meeting notices (5 mins)
- [x] Review action items from the previous meeting and other recent activity (5 mins)
  - #505 
  - FDC3 training course now available: [Enroll here](https://www.edx.org/course/fdc3-interoperability-for-the-financial-desktop)
  - [**Formal specification issues**](https://github.com/finos/FDC3/issues?q=is%3Aissue+is%3Aopen+label%3A%22formal+specification%22)
- [x] #513 (5 mins)
  - Decision from maintainers on how to proceed
- [x] Overview of proposals from Channel, Feeds & Transactions discussion group (25 mins)
  - A walkthrough of the proposed changes (PRs) to the FDC3 API
  - Review by maintainers underway, with a goal of merging changes after the next FDC3 SWG meeting where consensus on merging the proposals will be checked. 
- [x] #468 (15 mins)
  - Further discussion on ways forward for the AppD. 
- [x] AOB & Adjourn (5 mins)

## Minutes
- A statement regarding the FDC3 maintainer's decision to close issue #513 was read.
  - The author of the issue is requested to raise the issue against the [FINOS standards-project-blueprint instead](https://github.com/finos/standards-project-blueprint/) for consideration by the FINOS board. If changes to that blueprint are made, the FDC3 maintainers will seek to bring those into the FDC3 repository afterwards.
  - A copy of the statement will be posted on the issue
  - Some discussion ensued before the moderator moved the meeting onto the next agenda item.
- A summary of changes proposed by the Channels, Feeds & Transactions group was provided by @kriswest 
  - A copy of the presentation (intended to help participants review the proposals) can be found at: [FDC3 API Changes proposed by Channels, Feeds & Transactions.pdf](https://github.com/finos/FDC3/files/7728888/FDC3.API.Changes.proposed.by.Channels.Feeds.Transactions.pdf)
  - The FDC3 maintainers are aiming to fully review these proposals by the next SWG meeting (27th Jan 2022) and to check consensus that the PRs should be merged at that meeting.
- #468 
  - A brief recap of the discussion from the previous meeting was provided (#505)
  - A participant suggested that the issue is split into multiple issues which deal with the Application Record and AppD separately
  - Discussion was curtailed by the end of the meeting and it was resolved to assign more time to the issue at the next SWG meeting.
 
 
### Decisions Made
- ...

## Action Items
- [x] @kriswest Next meeting agenda to include:
  - #468 
  - Checking consensus that the PRs raised by Channels, Feeds and Transactions should be merged.
- Rolled over from previous meetings
  - [x] Implement PR for #466 @lspiro-Tick42 @kriswest

## Untracked attendees

| Full name | Affiliation | GitHub username |
|-----------|-------------|-----------------|
|           |             |                 |

**Comment by ggeorgievx** [comment]
Present ✅

**Comment by Julia-Ritter** [comment]
Julia / FINOS

**Comment by lspiro-Tick42** [comment]
Leslie / Glue42

**Comment by sarahstone-cosaic** [comment]
Sarah Stone / Cosiac

**Comment by mcleo-d** [comment]
Hi everyone 👋🏻

**Comment by jgavronsky** [comment]
Jane @ FINOS here

**Comment by agitana** [comment]
Aitana Myohl / FINOS

**Comment by bertrand-s** [comment]
Bertrand Laporte / Symphony

**Comment by donbasuno** [comment]
Johan / FactSet 🎁

**Comment by thorsent** [comment]
Terry / Cosaic

**Comment by rikoe** [comment]
Riko / Adaptive

**Comment by mazydar** [comment]
Mazy / OpenFin

**Comment by mattjamieson** [comment]
:christmas_tree:

**Comment by Julia-Ritter** [comment]
Untracked attendees:

- Fergus / Adaptive
- Gab / FINOS 
- Michael Coates / OpenFin
