### ISSUE TITLE
Link intro to governance documentation 

### ISSUE THREAD

**Issue by kriswest** [finos/FDC3#527]
## Formalizing the FDC3 Standard documentation

This issue has been raised as part of work, sponsored by FINOS, to improve and formalize the documentation of the FDC3 standard.

### How is FDC3 governed

**Proposal**
Get started | Introduction contains a section on governance ["How is FDC3 governed"](https://fdc3.finos.org/docs/fdc3-intro#how-is-fdc3-governed). When the updated governance documentation is merged (under the below PR) the introduction should summarize it and link to it for more details  
- PR #485

**Comment by RexJaeschke** [comment]
**Proposal(s):**

## How is FDC3 governed?

FDC3 is hosted within, and governed by the policies of, the [Fintech Open Source Foundation](http://finos.org/) (FINOS). FINOS is an independent nonprofit organization focused on promoting open innovation within financial services.

> **[[insert this paragraph here]]** The Governance Policy identifies the various roles of participants, how the Working Group operates, how decisions are made, and how the Standard is revised. See [FDC3 Governance Policy](xxx#xxx) for complete details.

See the [FDC3 Charter](fdc3-charter#licensing) for details of how deliverables are licensed.
