### ISSUE TITLE
Add backwards compatibility support for the App Directory

### ISSUE THREAD

**Issue by ggeorgievx** [finos/FDC3#553]
PR #437 (issue #314) introduced a breaking change to the App Directory specification, namely changes to the `Application` schema. This issue suggests adding backwards compatibility to the specification by using the versioned URL end-points:
- Introduce `v2` end-points for all newly added changes
- Add back the old Application schema and sort out any component naming issues
- Mark the `v1` end-points as optional/deprecated

**Comment by kriswest** [comment]
I agree with this approach - we opted for the next version to be a major release in order to introduce breaking changes to the appD, but it makes sense to use the versioned URLs to make transitions easier and to keep the URLs aligned with the major version number.
