### ISSUE TITLE
Standard WG Meeting - January 27, 2022

### ISSUE THREAD

**Issue by kriswest** [finos/FDC3#568]
## Date
Thursday 27 Jan 2022 - 10am EST / 3pm GMT

### WebEx info
- [Meeting Link](https://finos.webex.com/finos/j.php?MTID=ma4b1de1b9f691d89e4b2ff380ec9687c)
Meeting number: 665 568 411
Password: pbMT7rxay24

*More ways to join*
- Join by video system:
   - Dial 665568411@finos.webex.com
   - You can also dial 173.243.2.68 and enter your meeting number
- Join by phone
   - +1-415-655-0003 US Toll
   - +44-20319-88141 UK Toll
- Access code: 665 568 411

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://github.com/finos/community/blob/master/governance/Meeting-Procedures.md#run-the-meeting). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://odp.finos.org/docs/finos-maintainers-cheatsheet/).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://github.com/finos/community/blob/master/governance/Code-of-Conduct.md) and all other [FINOS policies](https://github.com/finos/community/tree/master/governance#policies).

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call, review meeting notices (5mins)
- [x] Review action items from previous meeting (5mins)
  - #526 
- [x] Checking consensus on the merging of proposals from the Channels, Feeds & Transactions discussion group into the pre-draft of FDC3 2.0 (20mins)
  - A copy of the presentation (intended to help participants review the proposals) can be found at: [FDC3 API Changes proposed by Channels, Feeds & Transactions.pdf](https://github.com/finos/FDC3/files/7728888/FDC3.API.Changes.proposed.by.Channels.Feeds.Transactions.pdf) 
  - Consensus to be checked on each open issue
- [x] Brief introduction to #569 from Brian Ingenito (discussion to be held at a future meeting) (2mins)
  - also recently raised as #520 
- [x] App Directory issues for FDC3 2.0 (23mins)
  - All open AppD issues can be found at: https://github.com/finos/FDC3/issues?q=is%3Aissue+is%3Aopen+label%3Aapp-directory
    - Recently merged:
      - #314 
        - #437  
    - Existing issues:
      - #247 
      - #369 
      - #370 
      - #371 
    - Recently raised:
      - #550 
      - #551 
      - #553 
      - #555 
      - #556 
      - #557 
      - #558 
      - #559 
      - #560 
      - #561 
      - #562
      - #563 
      - #564 
      - #565 
      - #566 
      - #567 
- [x] AOB & Adjourn (5mins)
  - Upcoming meetings
    - FDC3 General Meeting: Tues 1st Feb 2022 - 10am EST / 3pm GMT
      - To include a demo of the FDC3 X desktop agent browser extension
    - FDC3 Context and Intents Discussion group: Thurs 3rd Feb 2022 - 9am EST / 2pm GMT
    - FDC3 Desktop Agent Bridging Discussion Group: Thurs 10th Feb 2022 - 9am EST / 2pm GMT
    - FDC3 Context and Intents Discussion group: Thurs 17th Feb 2022 - 9am EST / 2pm GMT
    - FDC3 Standard Working Group: Thurs 24th Feb 2022 - 10am EST / 3pm GMT

## Minutes
- **Checking consensus on the merging of proposals from the Channels, Feeds & Transactions discussion group**
  - A brief overview of the process for making additions to the FDC3 standard was provided (
    - issues raised -> discussion -> PRs raised -> consensus of working group checked -> PR merged to master (pre-draft of standard) -> working group votes on adoption as next version of standard
      - For more details see:
        - https://github.com/finos/FDC3/blob/master/GOVERNANCE.md#4standard-development-process
        - https://github.com/finos/FDC3/blob/master/CONTRIBUTING.md
  - No objections were raised to any of the 8 proposals reviewed and consensus was achieved that they should be merged after the reviews by the fdc3 maintainers and editors are completed.
  - However, comments were submitted on two of the proposals :
    - #498
      - PR: #499
      - The findIntent functions end up with two optional parameters, does this cause any problems?
        - Should be checked during the maintainers review
        - Types of the arguments are different (Object vs. String) and could be detected. Otherwise one would have to become required, which is undesirable (as currently only the intent is required).
    - #450
      - PR: #509 
      - How are failures to deliver an intent dealt with? Should this be an issue to examine if we start defining certification tests for apps?
        - @kriswest There is not currently an error in the `ResolveError` enumeration to represent the failure to deliver an intent to a selected (or specified) target app or instance - which applies equally to both existing raiseIntent functionality (where an app is launched) and to this case where it is delivered to an app instance - hence its not an issue with this proposal.
          - This should be raised as a separate issue as it represents a shortcoming in FDC3 - when an intent is raised the resolver has to launch an app then wait for it to add the intent handler necessary to deliver the intent to it, if that never happens there is currently no feedback to the app raising the intent (it would receive an intent resolution but not an error).
            - @kriswest offered to raise this issue
          - If compliance testing was to confirm that an app does handle intents it claims to, we would need to ensure that an appD record is always included with it and examined as part of the testing.

- A brief introduction to #569 (and #520) was provided by @bingenito, along with a use case/reason why this issue can prevent firms from being able to use FDC3
  - Discussion to be held at next SWG meeting

- **AppD**
  - A brief overview of existing and recently raised issues related to the AppD Standard was provided
  - The formation of a Discussion group to work on the issues raised was proposed
    - Proposal was supported by a number of participants
    - Group to meet fortnightly
    - Group to start with examining role/value/necessity of the AppD as part of the FDC3 specification and a compliance requirement for use of the FDC3 API 
    - @kriswest to post poll for dates - not a Thursday due to clashes with other groups 

### Decisions Made
- Channels, Feeds & Transactions proposals to be merged into next pre-draft of FDC3 standard (after review by the FDC3 maintainers are complete) 🎉 
- Discussion group focused on AppD to be formed

## Action Items
- [ ] @finos/fdc3-maintainers to merge all [Channels, Feeds and Transactions PRs](https://github.com/finos/FDC3/pulls?q=is%3Apr+is%3Aopen+label%3A%22channels+feeds+%26+transactions%22)
  - IN PROGRESS: https://github.com/finos/FDC3/pulls?q=is%3Apr+label%3A%22channels+feeds+%26+transactions%22+ 
- [x] @kriswest Raise issue relating to missing ResolveError for failure to deliver an intent to a target app (e.g. becuase intent handler was not added by it)
  - #581
    - PR: #601
- [x] @kriswest to setup discussion group for working on AppD proposals and post poll for first meeting time
- [x] @kriswest add to next SWG meeting agenda:
  - #569
  -  (from context data and intents group) #497 
      - #541

## Untracked attendees

| Full name | Affiliation | GitHub username |
|-----------|-------------|-----------------|
|           |             |                 |

**Comment by Qiana-Citi** [comment]
We've gone through the deck that Kris presented on the proposed API changes and are happy to find that most of the changes are backward compatible. Only the following two items that might have some impact in a way, but that should be acceptable.

> fdc3.addIntentListener(), fdc3.addContextListener() & channel.addContextListener()
> ▪ Change return type from Listener to promise
> ▪ Used only in the minority of implementations, hence, the change will not affect most implementations. 
> 
> fdc3.getInfo()
> ▪ Change return type from ImplementationMetadata to promise
> ▪ new in 1.2 and usage is not yet widespread.

**Comment by bingenito** [comment]
Hi @kriswest, I just created the discussion item - #569.  I'd like the opportunity in the agenda this week for about a minute to raise awareness for review and get on agenda in a future meeting to discuss in more detail.

**Comment by kriswest** [comment]
@bingenito I've added it in (sans discussion as we likely won't have time for it) along with an action item to add it to the next meeting agenda. I've also linked to a near identical issue raised recently by @symphony-adnane.

**Comment by rikoe** [comment]
I can't attend the first part of today's meeting, but I just want to add my vote for the current channel, feeds and transactions PRs - great work everyone who have gotten us this far.

**Comment by mattjamieson** [comment]
:musical_keyboard:

**Comment by ggeorgievx** [comment]
Present ✅

**Comment by kriswest** [comment]
Kris / Cosaic

**Comment by opoupeney** [comment]
Olivier / Symphony

**Comment by bingenito** [comment]
Brian / Morgan Stanley

**Comment by ColinEberhardt** [comment]
here 👍

**Comment by pbaize** [comment]
Pierre / OpenFin

**Comment by mazydar** [comment]
Mazy @ OpenFin

**Comment by hampshan** [comment]
Andrew Hampshire present

**Comment by symphony-adnane** [comment]
Adnane @ Symphony

**Comment by agitana** [comment]
Aitana Myohl / FINOS

**Comment by lspiro-Tick42** [comment]
Leslie / Tick42

**Comment by MichaelMCoates** [comment]
Michael / OpenFin

**Comment by jgavronsky** [comment]
Jane @ FINOS

**Comment by greyseer256** [comment]
Hugh / FactSet  
(sorry forgot to comment yesterday)

**Comment by kriswest** [comment]
A poll has been posted for the first meeting of the App Directory discussion group, please provide your feedback on dates by visiting https://github.com/finos/FDC3/issues/573#issuecomment-1025653973 and clicking on the emojis for times that work for you.
