### ISSUE TITLE
App Directory Discussion group - Feb 08, 2022

### ISSUE THREAD

**Issue by kriswest** [finos/FDC3#573]
## Group overview
Discussion group to develop proposals for the improvement of the App Directory as part of the FDC3 standard. The group will examine the role/value/necessity of the AppD as part of the FDC3 specification and a compliance requirement for use of the FDC3 API, in addition to working on proposals to improve the description and functionality of the App Directory. 

### Relevant tags
Current open issues and PRs that relate to the above concepts with the label: 
[![image](https://user-images.githubusercontent.com/1701764/151783600-e65898db-0145-45bc-b500-2e3cf7b1010a.png)](https://github.com/finos/FDC3/labels/app-directory)

## Meeting Date
Tuesday 8th Feb 2022 - 9am EST / 2pm GMT

### WebEx info
- [Meeting Link](https://finos.webex.com/finos/j.php?MTID=mcb04b7aa90e019b8c97a87f5589c11c4)
Meeting number: 2559 815 9161
Password: JHw9MQbbD35

*More ways to join*
- Join by video system:
   - Dial 25598159161@finos.webex.com
   - You can also dial 173.243.2.68 and enter your meeting number
- Join by phone
   - +1-415-655-0003 US Toll
   - +44-20319-88141 UK Toll
- Access code: 2559 815 9161

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://github.com/finos/community/blob/master/governance/Meeting-Procedures.md#run-the-meeting). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://odp.finos.org/docs/finos-maintainers-cheatsheet/).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://github.com/finos/community/blob/master/governance/Code-of-Conduct.md) and all other [FINOS policies](https://github.com/finos/community/tree/master/governance#policies).

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.
  
- A Discussion Group has no direct decision-making power regarding the FDC3 standard - rather it is intended that anything they propose or work on will result in proposals (via Github issues and PRs) for the Standards Working Group participants to consider and vote on for inclusion in the standard. As such, participation in a Discussion group is not required for contributing to any particular issue or FDC 2.0 as a whole.

## Agenda
- [x] Convene & roll call, review meeting notices (5mins)
- [x] Review issues list and discuss group goals (15mins)
  - All open AppD issues can be found at: https://github.com/finos/FDC3/issues?q=is%3Aissue+is%3Aopen+label%3Aapp-directory
    - Recently merged:
      - #314 
        - #437  
    - Existing issues:
      - #247 
      - #369 
      - #370 
      - #371 
    - Recently raised:
      - #550 
      - #551 
      - #553 
      - #555 
      - #556 
      - #557 
      - #558 
      - #559 
      - #560 
      - #561 
      - #562
      - #563 
      - #564 
      - #565 
      - #566 
      - #567 
- [x] Examine role/value/necessity of the AppD as part of the FDC3 specification and a compliance requirement for use of the FDC3 API (35mins)
- [ ] Arrange next meeting & Adjourn (5mins)

## Minutes
- Discussion was entirely focused on
  - #551
  - Discussion was contentious and unproductive.

## Action Items
- None recorded

## Untracked attendees

| Full name | Affiliation | GitHub username |
|-----------|-------------|-----------------|
|           |             |                 |

**Comment by kriswest** [comment]
Poll for first meeting appointment (expected to repeat fortnightly):
- 😄  Fri 4th Feb 3pm GMT / 10am ET
- 🎉  Mon 7th Feb 4pm GMT / 10am ET
- ❤️  Tues 8th Feb 2pm GMT / 9am ET
- 🚀  Wed 9th Feb 2pm GMT / 9am ET
- 👀  Fri 11th Feb 3pm GMT / 10am ET

(Click the emojis to indicate your availability and/or preference)

**Comment by Julia-Ritter** [comment]
Julia / FINOS

**Comment by openfin-gavin** [comment]
Gavin / OpenFin

**Comment by sarahstone-cosaic** [comment]
Sarah Stone / Cosaic

**Comment by mazydar** [comment]
Mazy | OpenFin

**Comment by thorsent** [comment]
Terry Thorsen / Cosaic

**Comment by ferguskeenan** [comment]
Fergus / Adaptive

**Comment by pbaize** [comment]
Pierre / OpenFin

**Comment by greyseer256** [comment]
Hugh Troeger / FactSet

**Comment by openfin-johans** [comment]
Johan / OpenFin 🎁

**Comment by opoupeney** [comment]
Olivier Poupeney / Symphony

**Comment by jgavronsky** [comment]
Jane @ FINOS here

**Comment by pgn-vole** [comment]
Yacine Zalouani @ UBS
