### ISSUE TITLE
General Meeting - Feb 01, 2022

### ISSUE THREAD

**Issue by kriswest** [finos/FDC3#576]
## Date
01 Feb 2022 - 10am EST / 3pm GMT

### WebEx info
- [Meeting Link](https://finos.webex.com/finos/j.php?MTID=m3015a7e4a511656ceafebda5eadcbe6d)
- Meeting number: 403 028 328

*More ways to join*
- Join by video system: dial 173.243.2.68 and enter your meeting number
- Join by phone
   - +1-415-655-0003 US Toll
   - +44-20319-88141 UK Toll
- Access code: 403 028 328

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://github.com/finos/community/blob/master/governance/Meeting-Procedures.md#run-the-meeting). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://odp.finos.org/docs/finos-maintainers-cheatsheet/).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://github.com/finos/community/blob/master/governance/Code-of-Conduct.md) and all other [FINOS policies](https://github.com/finos/community/tree/master/governance#policies).

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call, review meeting notices (5mins)
- [x] FDC3 2.0 Progress (25 mins)
  - Discussion groups
  - Issues resolved/PRs merged so far
  - Issues agreed and in need of a PR
  - Issues under discussion
  - Upcoming meetings 
- [x] Improving the FDC3 Specification(s) (5 mins)
- [x] FDC3 X Developer Chrome Extension demo (15 mins)
- [x] Q&A & Adjourn (15 mins)

## Action Items
- [ ] ...

## Untracked attendees

| Full name | Affiliation | GitHub username |
|-----------|-------------|-----------------|
|           |             |                 |

**Comment by ggeorgievx** [comment]
Present ✅

**Comment by pierreneu** [comment]
Pierre Neu - Symphony

**Comment by Julia-Ritter** [comment]
Julia / FINOS

**Comment by bertrand-s** [comment]
Bertrand / Symphony

**Comment by kriswest** [comment]
Kris / Cosaic 🚀

**Comment by ColinEberhardt** [comment]
Colin / Scott Logic 👀

**Comment by florian-gandon** [comment]
Florian Gandon / Itiviti

**Comment by lspiro-Tick42** [comment]
Leslie / Glue42

**Comment by troups** [comment]
Simon Troup / Southampton Business School (newbie, formerly Blackrock and others)

**Comment by agitana** [comment]
Aitana Myohl / FINOS

**Comment by westacotta** [comment]
Andy Westacott / Citi

**Comment by ColinEberhardt** [comment]
It's been a while since I was heavily involved in FDC3. From attending this meeting I can see that fantastic progress has, and still is, being made. Kudos to @kriswest @rikoe and the others helping push this forwards on multiple fronts.
