### ISSUE TITLE
Update FDC3 master branch to main

### ISSUE THREAD

**Issue by Julia-Ritter** [finos/FDC3#579]
## Description:

The FDC3 team would like to rename the repo `master` branch to `main`.

**Items**

- [x] Agree on this list of tasks as the plan to move forward
- [x] Prepare a PR with name replacement across the entire codebase; this includes, but is not limited, to links and GitHub actions; this is a good start - https://github.com/search?q=repo%3Afinos%2FFDC3%20master&type=code
- [x] Choose a target date for merging
- [x] Notify community
- [x] Rename the branch and merge the PR
- [x] Post-migration check for broken links

**Comment by maoo** [comment]
@kriswest - happy to support this! I took the freedom to rewrite title and description of the issue; WDYT?

cc @robmoffat @TheJuanAndOnly99

**Comment by kriswest** [comment]
LGTM, that search is revealing more links than I thought there were, so good start!

I'd include doing a post-migration check for broken links at the end of the steps. I think docusaurus does its own link checking and will report build errors if they're found, but we may also want to run a 3rd party tool - neither will find anything until after the branch rename of course.

**Comment by TheJuanAndOnly99** [comment]
PR is ready https://github.com/finos/FDC3/pull/1161.

**Comment by kriswest** [comment]
Merged and completed!
