### ISSUE TITLE
Desktop Agent Bridging Discussion group - Feb 10, 2022

### ISSUE THREAD

**Issue by kriswest** [finos/FDC3#585]
## Group overview
Discussion group for developing proposals for producing bridges between FDC3 implementations (aka Desktop Agents), allowing applications running on one Desktop Agent, to integrate with FDC3 applications running on a second Desktop Agent for the same user.

The interop between applications running on different Desktop Agents aka Platforms would ideally cover
- Channels
- Raising and resolving Intents
- Launching Applications

### Relevant issue tags
- Current open issues that relate to the above concepts with the label: 
  [![image](https://user-images.githubusercontent.com/1701764/144856698-e49821ab-9c8e-4daf-99a1-23f4774c1fcd.png)](https://github.com/finos/FDC3/labels/Desktop%20Agent%20Bridging)
- The original issue is now a github discussion where content can be added and this issue discussed: 
#544

## Meeting Date
Thursday 10 Feb 2022 - 9am EST / 2pm GMT

### WebEx info
- [Meeting Link](https://finos.webex.com/finos/j.php?MTID=ma4b1de1b9f691d89e4b2ff380ec9687c)
Meeting number: 2556 495 5451

*More ways to join*
- Join by video system:
   - Dial 25564955451@finos.webex.com
   - You can also dial 173.243.2.68 and enter your meeting number
- Join by phone
   - +1-415-655-0003 US Toll
   - +44-20319-88141 UK Toll
- Access code: 2556 495 5451

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://github.com/finos/community/blob/master/governance/Meeting-Procedures.md#run-the-meeting). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://odp.finos.org/docs/finos-maintainers-cheatsheet/).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://github.com/finos/community/blob/master/governance/Code-of-Conduct.md) and all other [FINOS policies](https://github.com/finos/community/tree/master/governance#policies).

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.
  
- A Discussion Group has no direct decision-making power regarding the FDC3 standard - rather it is intended that anything they propose or work on will result in proposals (via Github issues and PRs) for the Standards Working Group participants to consider and vote on for inclusion in the standard. As such, participation in a Discussion group is not required for contributing to any particular issue or FDC 2.0 as a whole.

## Agenda
- [x] Convene & roll call, review meeting notices (5mins)
- [x] Review action items from previous meeting (5mins)
  - #543 
- [x] Review proposed requirements list (see [list in discussion](https://github.com/finos/FDC3/discussions/544#discussioncomment-1997387)) (25mins)
- [ ] Discuss implementation challenges list (see [list in discussion](https://github.com/finos/FDC3/discussions/544#discussioncomment-1997387)) (15mins)
- [ ] (if time) discuss next steps
- [x] AOB & Adjourn (5mins)

## Minutes
- The group reviewed agreed the requirements for Desktop Agent Bridging posted at #544
  - a number of the requirements were adjust and new requirements added
  - the group provisionally agreed the requirements pending some edits to wording

## Action Items
- [x] @kriswest handle a number of TODOs related to wording in the requirements posted on [list in discussion](https://github.com/finos/FDC3/discussions/544#discussioncomment-1997387) and circulate once done
- [x] @kriswest create poll for next meeting in 2 weeks (on either Tuesday or Thursday before SWG)
- [x] @kriswest create agenda for next meeting, to focus on implementation challenges and strategy

## Untracked attendees

| Full name | Affiliation | GitHub username |
|-----------|-------------|-----------------|
|           |             |                 |

**Comment by Julia-Ritter** [comment]
Julia / FINOS

**Comment by sarahstone-cosaic** [comment]
Sarah Stone / Cosaic

**Comment by kriswest** [comment]
Kris / Cosaic

**Comment by mattjamieson** [comment]
:heavy_check_mark:

**Comment by opoupeney** [comment]
Olivier Poupeney / Symphony

**Comment by greyseer256** [comment]
Hugh Troeger / FactSet

**Comment by bertrand-s** [comment]
Bertrand / Symphony

**Comment by thorsent** [comment]
Terry Thorsen / Cosaic

**Comment by saurabhguptanwm** [comment]
Saurabh / NWM

**Comment by Julia-Ritter** [comment]
**Untracked attendees:**

- Aaron Haines / NWM
- Manish / NWM
- Qiana Chen / Citi
- Randall Dang / Citi

**Comment by kriswest** [comment]
Poll for next meeting date:
- 🎉 Monday 28th Feb 2pm GMT / 9am EST
- ❤️ Tuesday 1st March 2pm GMT / 9am EST
- 🚀 Wednesday 2nd March 2pm GMT / 9am EST
- 👀 Friday 4th March 2pm GMT / 9am EST
- 👎 Need other options

**Comment by kriswest** [comment]
The requirements at https://github.com/finos/FDC3/discussions/544#discussioncomment-1997387 have been updated as per the action items. In particular please note items: 1, 4, 7 & 8

**Comment by kriswest** [comment]
As no single option in the above Poll worked for a majority (Wed/Fri have 3 participants that can't make Tuesday and Tues have 4 that can't make Wed/Fri, 1 participant couldn't make any) I suggest we push out a week and try again. I'll post a new poll later on today.

**Comment by kriswest** [comment]
New poll for next meeting date:
- 😄  Monday 7th March 2pm GMT / 9am EST
- 🎉 Tuesday 8th March 2pm GMT / 9am EST
- ❤️ Wednesday 9th March 2pm GMT / 9am EST
- 🚀 Thursday 10th March 2pm GMT / 9am EST
- 👀 Friday 11th March 2pm GMT / 9am EST
- 👎 Need other options

**Comment by kriswest** [comment]
Selected date for next meeting: 
❤️ Wednesday 9th March 2pm GMT / 9am EST
