### ISSUE TITLE
Intent Proposal: ViewOrganization

### ISSUE THREAD

**Issue by pauldyson** [finos/FDC3#586]
### Use Case
A Corporate Access administrator is researching a potential invite list for an upcoming IPO. To do this they look at data held in multiple systems such as their Order Management System, their Bookbuilding System, etc in order to determine which of the organisations who have previously participated in offerings may be likely to participate in the IPO they are prepping.

Once they have determined which organisations to target, they will need to figure out which individuals at that organisation to approach. This information will be held in the CRM.

#### ViewOrganization
Just as ViewContact allows a quick navigation to an individual’s information, ViewOrganisation would allow a quick navigation to a company’s information. ViewOrganisation would be called with the Organization context.

### Additional Information
Both ViewContact and ViewOrganization might be better named ViewProfile with either a Contact or Organization context passed. This would be more consistent with the style of ViewAnalysis and ViewNews.

**Comment by openfin-johans** [comment]
Hi @pauldyson,

thanks for filing and including relevant use cases and information! As discussed during the call last week I would be in favour of creating **ViewProfile** as a single intent for both this use case and others currently handled by ViewContact. 

As mentioned it will be consistent with other intents but it might be beneficial to discuss some nice wordings around the different use cases for ViewProfile (eg legal and CRM type information) vs ViewAnalysis (eg market data and financial info).

I would suggest we file a new issue for ViewProfile and close this one.

Once it has been approved, we should deprecate ViewContact.

Best regards,

Johan

**Comment by pauldyson** [comment]
Thanks @openfin-johans, I will do that today

**Comment by pauldyson** [comment]
Replaced with request for ViewProfile https://github.com/finos/FDC3/issues/600
