### ISSUE TITLE
Intent Proposal: ViewInteractions

### ISSUE THREAD

**Issue by pauldyson** [finos/FDC3#589]
### Use Case
A Salesperson is IMing with a Buy Side fund manager who mentions that they haven’t been receiving good services from the analyst covering the sector they specialise in. The Salesperson thinks this isn’t right as she knows the analyst was in a meeting with the fund manager’s firm and so they need to use the CRM to check whether the meeting they’re thinking of went ahead or not.

A Corporate Client Manager is preparing for a client meeting. They start in the BookBuilding system gathering data about a recent fund raise they led and then wants to flip to the CRM to see all the feedback from institutions that attended the related roadshow.

#### ViewInteractions
ViewInteractions should be used when a user wants to see the latest interactions (calls, meetings, conferences, roadshows) on a particular stock or with an individual or organisation. ViewInteraction would be called with the Contact, Organization or Instrument contexts.

**Comment by nemery-flextrade** [comment]
Nit picking but I think this makes more sense to be pluralised (i.e. ViewInteraction**s**)

**Comment by pauldyson** [comment]
So @nemery-flextrade I had this debate with myself. Certainly there is an individual Interaction (a call or a meeting) and you can definitely talk about a group of interactions (many calls and/or meetings) but when we and customers talk about how they work ("interact") with their clients we tend to talk about their "interaction with a client" or their "client interaction" for the general case, which might cover more things than just calls and meetings (e.g. key contacts and client coverage).

But it is a point of very fine detail and I know this might be confusing for non-native English speakers (not to mention native English speakers!) so if the consensus is 'Interactions' is better than 'Interaction' I good with that; I'd just like to be able to receive and service the intent ...

**Comment by nemery-flextrade** [comment]
@pauldyson Yes I see your point, I'd forgotten that it's perfectly valid to say 'show me past interaction with a client' for example.

Fully agree with the point about even native English speakers struggling sometimes!

This in mind I'm happy with either, let's raise it to the group at large on the next call

**Comment by pauldyson** [comment]
Agreed to change to ViewInteractions as there was much confusion over the Interaction/Interactions terminology in the review meeting.
