### ISSUE TITLE
Publish FDC3 Docker image to https://hub.docker.com/u/finos ?

### ISSUE THREAD

**Issue by maoo** [finos/FDC3#609]
### Question Area
[x] Other

### Question

Dear FDC3 team!

I see that FDC3 is distributed as a Docker image on https://github.com/orgs/finos/packages . It would be great to use the official Docker Registry, where FINOS hosts all other images, which is https://hub.docker.com/u/finos ; this would allow us to track consumption of Docker images into [metrics.finos.org](metrics.finos.org).

I'm not sure if the GitHub Docker registry provides any advantage in terms of automation , compared to the automation provided by Docker Registry (see https://docs.docker.com/docker-hub/builds/link-source/ ).

Happy to discuss this further. Thank you!

cc @Julia-Ritter

**Comment by kriswest** [comment]
FDC3 is published as an NPM package, which appears to be what's listed there. Also this issue name mentions waltz rather than FDC3.

Unless I've misunderstood something, I think this issue should be closed.

**Comment by maoo** [comment]
Hi @kriswest , thanks for your quick response! Yes, you're right, apologies for the confusion! I also see that the FDC3 NPM package is hosted on https://www.npmjs.com/package/@finos/fdc3 , which is great.

Closing the issue!
