### ISSUE TITLE
Desktop Agent Bridging Discussion group - 9th March 2022

### ISSUE THREAD

**Issue by kriswest** [finos/FDC3#611]
## Group overview
Discussion group for developing proposals for producing bridges between FDC3 implementations (aka Desktop Agents), allowing applications running on one Desktop Agent, to integrate with FDC3 applications running on a second Desktop Agent for the same user.

The interop between applications running on different Desktop Agents aka Platforms would ideally cover
- Channels
- Raising and resolving Intents
- Launching Applications

### Relevant issue tags
- Current open issues that relate to the above concepts with the label: 
  [![image](https://user-images.githubusercontent.com/1701764/144856698-e49821ab-9c8e-4daf-99a1-23f4774c1fcd.png)](https://github.com/finos/FDC3/labels/Desktop%20Agent%20Bridging)
- The original issue is now a github discussion where content can be added and this issue discussed: 
#544

## Meeting Date
Wednesday 9th Mar 2022 - 9am EST / 2pm GMT

### WebEx info
- [Meeting Link](https://finos.webex.com/finos/j.php?MTID=ma4b1de1b9f691d89e4b2ff380ec9687c)
Meeting number: 2556 495 5451

*More ways to join*
- Join by video system:
   - Dial 25564955451@finos.webex.com
   - You can also dial 173.243.2.68 and enter your meeting number
- Join by phone
   - +1-415-655-0003 US Toll
   - +44-20319-88141 UK Toll
- Access code: 2556 495 5451

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://github.com/finos/community/blob/master/governance/Meeting-Procedures.md#run-the-meeting). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://odp.finos.org/docs/finos-maintainers-cheatsheet/).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://github.com/finos/community/blob/master/governance/Code-of-Conduct.md) and all other [FINOS policies](https://github.com/finos/community/tree/master/governance#policies).

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.
  
- A Discussion Group has no direct decision-making power regarding the FDC3 standard - rather it is intended that anything they propose or work on will result in proposals (via Github issues and PRs) for the Standards Working Group participants to consider and vote on for inclusion in the standard. As such, participation in a Discussion group is not required for contributing to any particular issue or FDC 2.0 as a whole.

## Agenda
- [x] Convene & roll call, review meeting notices (5mins)
- [x] Review action items from previous meeting (5mins)
  -  #585 
- [x] Discuss implementation challenges list (see [list in discussion](https://github.com/finos/FDC3/discussions/544#discussioncomment-1997387)) (30mins)
- [ ] (if time) begin preparation of a proposal (15mins)
- [x] AOB & Adjourn (5mins)

## Minutes
- @kriswest Briefly recapped work we've done so far on requirements see [list in discussion](https://github.com/finos/FDC3/discussions/544#discussioncomment-1997387)
- Connection strategy/wire format:
  - Websocket preferred over, say, REST endpoints
    - Supports bidirectional communication (either client or server can initiate an exchange)
      - the same message format/protocol can be used in either direction, hence it doesn't matter which agent is the server/client 
    - Requires definition of how to respond to a previous message (message guids + references to them in responses) - but permits multiple responses to a message - necessary for intent data responses
    - Can support SSL to secure connections (although this is not ideal when addressed via the loopback address)
    - Can support cross-machine use-cases if socket is bound to an IP address (although this may create some additional security challenges for the DA implementing the websocket server)
  - Authentication
    - Using SSL may not be ideal as DAs will be running on individual desktops, which would mean using DNS and SSL certs for localhost (not advisable) or DNS for each machine with a wild card certificate.
    - Exchanging a signed token (e.g. JWT, a signed response to an auth challenge etc.) is likely a better option
    - Poll to be raised to establish balance of opinion on the need for auth, and whether unidrectional or bi-directional
  - Topology
    - Websocket approach can support different topologies (peer-to-peer connections, a hub or repeater and multiple clients, hybrid schemes)
    - Cross-machine cases can be handled by multiple approaches:
      - A desktop agent that is cross-machine (e.g. NWM backplane) can bridge agents on multiple machines
      - Websocket exposed on a public IP address (rather than localhost) - SSL AND Authentication are more desirable in this case.
    - If multiple DA clients connect to DA acting as the websocket server, it has additional responsibilities:
      - It must act as a repeater, forwarding messages from one of the clients to the others (both outbound messages and replies)
      - ...
- Intents
  - Resolver should be shown only on the DA raising the intent (originating DA)
    - Can be populated with possible targets from other agents by querying them with `findIntent` (as if an app had made that call)
    - Originating DA can return `IntentResolution` after its sent the intent and context across the bridge and received an acknowledgement from the target DA
      - Target DA may need to start an application and wait for an intent listener added before it can confirm delivery of the intent.
    - A further response from target DA will be required for returning results.
- User Channels (System Channels)
  - The list is not defined by the standard - which will cause problems or bridged communication
    - A standard list of [DisplayMetadata](https://fdc3.finos.org/docs/api/ref/Metadata#displaymetadata) Objects could be added to the standard
      - Could/should be considered a breaking change and should be included in FDC3 2.0 
      - @kriswest and @ggeorgievx indicated that their firms are willing to adopt a standard list
      - Natwest Markets and Citi participants stated that they would be very keen for this to happen as their apps are used in multiple different DAs in addition to using multiple DAs at the the same time that they wish to bridge
      - All firms implementing DAs to share their opinions on whether they are willing to adopt a standard list of User Channels (System Channels)
    - An alternative is to only require a standard list through DA bridging where a DA MUST map its own channel list to the standard set, and would have to translate channel names it as it sends and receives them over the bridge - but it'll make for a more confusing user experience (why does the  red channel, land on Glue42 Channel 4 (which is, say, blue)
- App Channels
  - Bridging doesn't need to do anything special when app channels are created or retrieved with `fdc3.getOrCreateChannel` simply passing all messages that are broadcast across the bridge annotated with the channel name is sufficient
    - A DA just needs to check whether anything has added a listener for the channel and to deliver the message
- Volunteer(s) are needed to work on a Websocket protocol proposal 

## Action Items
- [x] @kriswest Create poll to establish how important the group thinks the following features/abilities are  for Desktop Agents
  - Discovery
    - DA's are able to discover each other and self organise/connect
    - Connections between Desktop Agents should be configured manually
  - Authentication
    - Connections between Desktop Agents should be authenticated in at least one direction
    - Connections between Desktop Agents should be authenticated in both directions
    - Connections between Desktop Agents don't need to be authenticated
- [ ] Firms implementing Desktop Agents to share their opinions on whether they are willing to adopt a standard list of User Channels (System Channels)
- [ ] @kriswest to raise issue proposing standardization of channel metadata
- [x] Volunteer(s) are needed to work on a Websocket protocol proposal 

## Untracked attendees

| Full name | Affiliation | GitHub username |
|-----------|-------------|-----------------|
|           |             |                 |

**Comment by mattjamieson** [comment]
:wave:

**Comment by Julia-Ritter** [comment]
Julia / FINOS

**Comment by Soul-Master** [comment]
Sumit / LSEG

**Comment by tpina** [comment]
Tiago Pina / Cosaic

**Comment by WatsonCIQ** [comment]
Chris Watson / Cosaic

**Comment by bertrand-s** [comment]
Bertrand / Symphony

**Comment by saurabhguptanwm** [comment]
Saurabh / NWM

**Comment by openfin-johans** [comment]
Johan / OpenFin 🎁

**Comment by manishbhutani** [comment]
Manish / NWM

**Comment by chedzoir** [comment]
Malcolm / citi

**Comment by Soul-Master** [comment]
Meeting link in description seem to be invalid.

**Comment by MichaelMCoates** [comment]
Michael Coates / OpenFin. Same issue as above ^

**Comment by Soul-Master** [comment]
@MichaelMCoates 
Valid link here 
https://t.sidekickopen07.com/s3t/c/5/f18dQhb0S7kF8bpVtZW1SXtrQ59hl3kW7_k2841CXdp3VNxQgy2Qy9y3W2dykgz8yBd3p101?te=W3R5hFj4cm2zwW3M3CVy4cg9chW3C7NRv3Fbt5SW3M3CVy4cgzxgW45PGCm2RB83vW2fbT4m1V3HMyW1Q4w5R3LFbXYW21gXsj3F4-29W1ZlfDv3K3PQG34MY2&si=8000000001705677&pi=a985d836-6977-436f-933d-461b6b27a5af

**Comment by sarahstone-cosaic** [comment]
Sarah Sone / Cosaic

**Comment by nicopreto** [comment]
Nico Pretorius / Scott Logic
