### ISSUE TITLE
Context Data & Intents Discussion group - 17 Mar 2022

### ISSUE THREAD

**Issue by rikoe** [finos/FDC3#627]
## Group overview
At the FDC3 Use Cases Roundtable London, October 5th 2021 participants agreed that the FDC3 lexicon needs to be expanded, both with additional intents and context types to support Use Cases, but also to include more primitive data types in order to construct complex types. A number of participants also agreed that now is an appropriate time to expand the Lexicon.

See #455 for full details of the meeting outcomes.

This group is being convened to discuss and arrange work to contribute further Context types and Intents to support Use Cases being implemented by participants.

### Relevant issue tags
Current open issues that relate to the discussion group: 
[![image](https://user-images.githubusercontent.com/1701764/139841356-416d9276-81f5-4fce-b5d8-f856d4bda855.png)](https://github.com/finos/FDC3/labels/Context%20Data%20%26%20Intents)

Issues will also be tagged with the labels:
[![image](https://user-images.githubusercontent.com/1701764/139841631-c6bf8697-fafe-4266-8552-63a648625e8b.png)](https://github.com/finos/FDC3/labels/context-data)
[![image](https://user-images.githubusercontent.com/1701764/139841690-969a9d14-a0aa-44a7-bdfe-8c4a43ad30d9.png)](https://github.com/finos/FDC3/labels/intents)

## Meeting Date
Thursday 17 Mar 2022 - 9am EST / 1pm GMT

### WebEx info
- [Meeting Link](https://finos.webex.com/finos/j.php?MTID=mbb193ae433ce8d4366adcecd94355734)
Meeting number: 2556 257 8293

*More ways to join*
- Join by video system:
   - Dial 25564955451@finos.webex.com
   - You can also dial 173.243.2.68 and enter your meeting number
- Join by phone
   - +1-415-655-0003 US Toll
   - +44-20319-88141 UK Toll
- Access code: 2556 257 8293

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://github.com/finos/community/blob/master/governance/Meeting-Procedures.md#run-the-meeting). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://odp.finos.org/docs/finos-maintainers-cheatsheet/).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://github.com/finos/community/blob/master/governance/Code-of-Conduct.md) and all other [FINOS policies](https://github.com/finos/community/tree/master/governance#policies).

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.
  
- A Discussion Group has no direct decision-making power regarding the FDC3 standard - rather it is intended that anything they propose or work on will result in proposals (via Github issues and PRs) for the Standards Working Group participants to consider and vote on for inclusion in the standard. As such, participation in a Discussion group is not required for contributing to any particular issue or FDC 2.0 as a whole.

## Agenda
- [x] Convene & roll call, review meeting notices (5mins)
- [x] Review action items from previous meeting (5mins)
  - #612  
- [x] Intent naming guidelines / standard verbs (10mins)
  - Includes intents that retrieve data vs. those that trigger a UI, e.g. GetInteractions vs. ViewInteractions)
- Discuss issues (35mins):
  - [x] #590 
  - [x] #591 
  - [ ] #592 
  - [ ] #574
- [x] AOB & Adjourn (5mins)

## Minutes
- Intent naming guidelines
  - `View____` and `Start____` are the existing conventions
  - New proposed conventions:
    - `Create` / `Update` / `CreateOrUpdate` for e.g. orders, RFQs
    - `Delete`
    - `Get` (for two-way intents)
    - `Share`
  - `Send` was also discussed, but it was felt that it is too generic
  - Intents sometimes are meant to transfer focus and sometimes not, how do we represent/encode that?
  - Riko to create an issue and PR to move forward with the agreed conventions
- #590 
  - Needs support for both `textBody` and `richTextBody` to correspond with MIME standard, so that both can be used
  - Should to go to PR as is with just text body for now, and then we can add rich text body once that feature is available
- #591
  - Ready to go to PR
- #592 
  - Needs further discussion, potentially in the next meeting if time allows
- #574 
  - The related PRs need to be reviewed
  - Rich text makes sense as an experimental feature 
- Next meeting
  - We need to discuss orders/products - Nathan (FlexTrade) to create an issue to seed the conversation
  - Kris to prepare his data/chart PR  

## Action Items
- Rolled over from previous meetings:
  - [x] @bertrand-s to add rich text usage samples to #575 
  - [x] @kriswest split #443 up into multiple PRs:
    - ISO dates and other primitive types
    - Chart context, settings and static data
    - Position, Trade, Valuation
    - Currency
    - DateRange -> TimeRange
- [ ] @rikoe to open an issue and PR for intent naming conventions
- [x] @nemery-flextrade to create a new issue about representing orders to facilitate discussion

**Comment by Julia-Ritter** [comment]
Hi @pauldyson apologies for the confusion - please go the meeting link here: [https://finos.webex.com/finos/j.php?MTID=mbb193ae433ce8d4366adcecd94355734](https://www.google.com/url?q=https://finos.webex.com/finos/j.php?MTID%3Dmbb193ae433ce8d4366adcecd94355734&sa=D&source=calendar&ust=1647953741250343&usg=AOvVaw2G5TFp7r2Tn0r9Ag_pmpWX)

**Comment by Julia-Ritter** [comment]
[https://finos.webex.com/finos/j.php?MTID=mbb193ae433ce8d4366adcecd94355734](https://www.google.com/url?q=https://finos.webex.com/finos/j.php?MTID%3Dmbb193ae433ce8d4366adcecd94355734&sa=D&source=calendar&ust=1647953741250343&usg=AOvVaw2G5TFp7r2Tn0r9Ag_pmpWX) here is the correct Webex meeting link

**Comment by Julia-Ritter** [comment]
Julia / FINOS

**Comment by nemery-flextrade** [comment]
Nathan / FlexTrade

**Comment by kriswest** [comment]
Kris / Cosaic

**Comment by pierreneu** [comment]
Pierre Neu / Symphony

**Comment by greyseer256** [comment]
Hugh Troeger / FactSet

**Comment by pauldyson** [comment]
Paul / Singletrack

**Comment by bertrand-s** [comment]
Bertrand / Symphony

**Comment by mistryvinay** [comment]
Vinay / Symphony
