### ISSUE TITLE
Desktop Agent Bridging Discussion group - 23rd March 2022

### ISSUE THREAD

**Issue by kriswest** [finos/FDC3#628]
## Group overview
Discussion group for developing proposals for producing bridges between FDC3 implementations (aka Desktop Agents), allowing applications running on one Desktop Agent, to integrate with FDC3 applications running on a second Desktop Agent for the same user.

The interop between applications running on different Desktop Agents aka Platforms would ideally cover
- Channels
- Raising and resolving Intents
- Launching Applications

### Relevant issue tags
- Current open issues that relate to the above concepts with the label: 
  [![image](https://user-images.githubusercontent.com/1701764/144856698-e49821ab-9c8e-4daf-99a1-23f4774c1fcd.png)](https://github.com/finos/FDC3/labels/Desktop%20Agent%20Bridging)
- The original issue is now a github discussion where content can be added and this issue discussed: 
#544

## Meeting Date
Wednesday 23rd Mar 2022 - 9am EDT / 1pm GMT

### WebEx info
- [Meeting Link](https://finos.webex.com/finos/j.php?MTID=m55d4aa79e148c948bf53163690e74fee)
  Meeting number: 2558 920 8729
  Password:7cgQYd2eYT3

*More ways to join*
- Join by video system:
   - Dial 25589208729@finos.webex.com
   - You can also dial 173.243.2.68 and enter your meeting number
- Join by phone
   - +1-415-655-0003 US Toll
   - +44-20319-88141 UK Toll
- Access code: 2558 920 8729

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://github.com/finos/community/blob/master/governance/Meeting-Procedures.md#run-the-meeting). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://odp.finos.org/docs/finos-maintainers-cheatsheet/).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://github.com/finos/community/blob/master/governance/Code-of-Conduct.md) and all other [FINOS policies](https://github.com/finos/community/tree/master/governance#policies).

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.
  
- A Discussion Group has no direct decision-making power regarding the FDC3 standard - rather it is intended that anything they propose or work on will result in proposals (via Github issues and PRs) for the Standards Working Group participants to consider and vote on for inclusion in the standard. As such, participation in a Discussion group is not required for contributing to any particular issue or FDC 2.0 as a whole.

## Agenda
- [x] Convene & roll call, review meeting notices (5mins)
- [x] Review action items from previous meeting (5mins)
  - https://github.com/finos/FDC3/issues/611 
- [x] Review poll results (10mins):
  - Discovery vs. Configuration poll: https://github.com/finos/FDC3/discussions/544#discussioncomment-2338414 
  - Authentication poll: https://github.com/finos/FDC3/discussions/544#discussioncomment-2338433
- [x] Touch base on standardisation of system (user) channels (issue to be raised) (5mins)
- [x] Review Websocket protocol proposals (30mins)
  - https://github.com/finos/FDC3/blob/544-Desktop-Agent-Bridging-Proposal/docs/api-bridging/spec.md
- [x] AOB & Adjourn (5mins)

## Minutes
- **Reviewed poll results:**
  - Discovery vs. Configuration poll: https://github.com/finos/FDC3/discussions/544#discussioncomment-2338414
    - 5 respondees preferred auto-discovery rather, none preferred configuration
    ![image](https://user-images.githubusercontent.com/1701764/159765673-075cf9e3-50d7-4eae-a28e-3ad20d8fc1ea.png)
  - Authentication poll: https://github.com/finos/FDC3/discussions/544#discussioncomment-2338433
    - 4 respondees preferred auth in both directions, none chose another option
    ![image](https://user-images.githubusercontent.com/1701764/159765833-f0cbab29-3b29-4a44-9c25-aff5f1a58e27.png)
  - It was noted that trying to achieve both goals is harder / they are in tension with each other (as you might need to preconfigure auth so that they can connect when they auto-discover each other)
    - Using SSO/auth against an external service might help resolve
  - Both topics to be discussed at next meeting.
  
- **Standardisation of system (user) channels**
  - @openfin-johans indicated that they thought this the only practical way forward (for Desktop Agent bridging) and would be willing
  - @kriswest Indicated Cosaic would be willing and quoted @ggeorgievx (from last meeting) on Glue42 also being willing
  - No objections were raised 
    - it was requested that the standard list be recommend (SHOULD), rather than required (MUST), which received general agreement
    - it was suggested that 6 default channels was sufficient for most usecases
    - it was also suggested that the set from the [fdc3-desktop-agent chrome extension](https://github.com/finos/fdc3-desktop-agent/blob/master/src/system-channels.ts) might be the most open/easiest to adopt set (although glyphs should be added, probably using letters well synced with the assigned ids).
    
- **[Websocket protocol proposal]( https://github.com/finos/FDC3/blob/544-Desktop-Agent-Bridging-Proposal/docs/api-bridging/spec.md)**
  - an overview of the proposal was given - noting that it doesn't yet touch on configuration/auth/discovery only the necessary message exchanges
  - @kriswest requested that other participants review, critique and contribute to the proposal - it is very much a WIP
  - It was suggested that messages should preserve the path that they propagated along, rather than just the source of the message.

## Action Items
- Rolled over from the previous meeting:
  - [ ] @kriswest to raise issue proposing standardization of channel metadata
    - Recommended, but not required
- [x] @kriswest raise a PR for the protocol proposal as a WIP to enable collaboration on refining it
  - #634 
- [ ] **all** Review and comments on protocol proposal are needed (via PR #634).
- [ ] @tpina @WatsonCIQ @kriswest update proposal to preserve message paths, rather than just source details
- [x] @kriswest post agenda for next meeting, to include discussion of discovery and authentication of connections.

## Untracked attendees

| Full name | Affiliation | GitHub username |
|-----------|-------------|-----------------|
|           |             |                 |

**Comment by mistryvinay** [comment]
@kriswest think we have the incorrect day for the above meeting.  Should it be Wed 23rd Mar?

**Comment by kriswest** [comment]
> @kriswest think we have the incorrect day for the above meeting. Should it be Wed 23rd Mar?

Well spotted @mistryvinay  - fixed.

**Comment by Julia-Ritter** [comment]
Julia / FINOS

**Comment by kriswest** [comment]
Kris West / Cosaic

**Comment by robmoffat** [comment]
Rob / FINOS

**Comment by saurabhguptanwm** [comment]
Saurabh / NWM

**Comment by tpina** [comment]
Tiago Pina / Cosaic

**Comment by Qiana-Citi** [comment]
Qiana / Citi

**Comment by timjenkel** [comment]
Tim / Wellington

**Comment by openfin-johans** [comment]
Johan / OpenFin 🎁

**Comment by RandallDang-Citi** [comment]
Randall / Citi

**Comment by greyseer256** [comment]
Hugh / FactSet

**Comment by Soul-Master** [comment]
Sumit / LSEG

**Comment by ChrisHobsonExpero** [comment]
Chris / Expero

**Comment by jgavronsky** [comment]
Jane @ FINOS here

**Comment by MichaelMCoates** [comment]
Michael / OpenFin
