### ISSUE TITLE
FDC3-explained stylesheets do not publish

### ISSUE THREAD

**Issue by kriswest** [finos/FDC3#630]
## Minor Issue
When FDC3-explained is published, its styles.css files are not being copied over to the output correctly and end up missing:
![image](https://user-images.githubusercontent.com/1701764/159004774-8e4a74db-b150-4ce7-aca4-dea0d192182b.png)

Additional info:
- The style file should be found at: https://fdc3.finos.org/toolbox/fdc3-explained/1.2/styles.css
- Original location: https://github.com/finos/FDC3/tree/master/toolbox/fdc3-explained/1.2
- Copy script (looks like it *should* be copying it): https://github.com/finos/FDC3/blob/f885209c21885e2f954c076ed54ad4d506b0f73f/website/package.json#L13

I have vague memories of docusaurus interfering with styles - but not specific enough to be of use

### Area of Issue
[ ] App Directory
[ ] API
[ ] Context Data
[ ] Intents
[ ] Use Cases
[x] Other

**Comment by kriswest** [comment]
@mistryvinay  FYI

**Comment by ashutoshdhande** [comment]
@kriswest Hello sir please review my pull request if it is appropriate and in need of suggestions if any as it is my first PR.

**Comment by kriswest** [comment]
Resolved by #653
