### ISSUE TITLE
Context Data & Intents Discussion group - 31 March 2022

### ISSUE THREAD

**Issue by rikoe** [finos/FDC3#643]
## Group overview
At the FDC3 Use Cases Roundtable London, October 5th 2021 participants agreed that the FDC3 lexicon needs to be expanded, both with additional intents and context types to support Use Cases, but also to include more primitive data types in order to construct complex types. A number of participants also agreed that now is an appropriate time to expand the Lexicon.

See #455 for full details of the meeting outcomes.

This group is being convened to discuss and arrange work to contribute further Context types and Intents to support Use Cases being implemented by participants.

### Relevant issue tags
Current open issues that relate to the discussion group: 
[![image](https://user-images.githubusercontent.com/1701764/139841356-416d9276-81f5-4fce-b5d8-f856d4bda855.png)](https://github.com/finos/FDC3/labels/Context%20Data%20%26%20Intents)

Issues will also be tagged with the labels:
[![image](https://user-images.githubusercontent.com/1701764/139841631-c6bf8697-fafe-4266-8552-63a648625e8b.png)](https://github.com/finos/FDC3/labels/context-data)
[![image](https://user-images.githubusercontent.com/1701764/139841690-969a9d14-a0aa-44a7-bdfe-8c4a43ad30d9.png)](https://github.com/finos/FDC3/labels/intents)

## Meeting Date
Thursday 31 Mar 2022 - 9am EST / 2pm BST

### WebEx info
- [Meeting Link](https://finos.webex.com/finos/j.php?MTID=mbb193ae433ce8d4366adcecd94355734)
Meeting number: 2556 257 8293

*More ways to join*
- Join by video system:
   - Dial 25564955451@finos.webex.com
   - You can also dial 173.243.2.68 and enter your meeting number
- Join by phone
   - +1-415-655-0003 US Toll
   - +44-20319-88141 UK Toll
- Access code: 255 649 55451

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://github.com/finos/community/blob/master/governance/Meeting-Procedures.md#run-the-meeting). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://odp.finos.org/docs/finos-maintainers-cheatsheet/).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://github.com/finos/community/blob/master/governance/Code-of-Conduct.md) and all other [FINOS policies](https://github.com/finos/community/tree/master/governance#policies).

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.
  
- A Discussion Group has no direct decision-making power regarding the FDC3 standard - rather it is intended that anything they propose or work on will result in proposals (via Github issues and PRs) for the Standards Working Group participants to consider and vote on for inclusion in the standard. As such, participation in a Discussion group is not required for contributing to any particular issue or FDC 2.0 as a whole.

## Agenda
- [x] Convene & roll call, review meeting notices (5mins)
- [x] Review action items from previous meeting (5mins)
  - #627  
- [x] Discuss data type and intents for orders/products (15 mins)
  - #644 
- Review open PRs (15 mins)
  - [ ] #619 
  - [ ] #620 
  - [ ] #623
  - [ ] #624  
  - [ ] #625
  - [ ] #632
- Review new issues (10 mins)
  - [ ] #645
  - [ ] #646
  - [ ] #651 
  - [ ] #652
- [ ] AOB & Adjourn (5mins)

## Minutes
- Order context proposal (Issue 644): 
  - Quite a simple first-draft effort at putting an order together.
  - Some discussion around this - FIX thought to be too "non-standard" (written in pencil)
  - FPML / Financial Objects: They mostly try to be exhaustive data types, whereas this is the minimal set of things that can be sent for another application to work. They are pushing around context data vs actual data.
  - Johan: this is about satisfying the customer, interop comes later.
  - We don't want to be the XKCD n+1 standards problem
  - Focus on Order, Trade, Instrument over the next couple of weeks
- Chat Intents
  - Discussion around startChat / viewChat: what are the verbs we are using?
  - Review of the PR
  - App field is the metadata for the platform.
  - Will move to typescript / jsonSchema as the standard progresses.

## Action Items
- [ ] ...

**Comment by kriswest** [comment]
Kris / Cosaic

**Comment by Soul-Master** [comment]
Sumit / LSEG

**Comment by openfin-johans** [comment]
Johan / OpenFin 🎁

**Comment by rikoe** [comment]
Riko / Adaptive

**Comment by WatsonCIQ** [comment]
Chris Watson / Cosaic

**Comment by bertrand-s** [comment]
Bertrand / Symphony

**Comment by pauldyson** [comment]
Paul / Singletrack

**Comment by timjenkel** [comment]
Tim / Wellington

**Comment by dominicgifford** [comment]
Dom / SPGI

**Comment by nemery-flextrade** [comment]
Nathan / FlexTrade

**Comment by jgavronsky** [comment]
Jane @ FINOS here

**Comment by Julia-Ritter** [comment]
**Untracked attendees:**

Matt Jamieson / White Dog
Yacine Zalouani / UBS 
Mike McClung  / Cosaic 
William Stewart / FINBOURNE Technology

**Comment by kriswest** [comment]
@nemery-flextrade @pauldyson @dominicgifford @rikoe and others (including @rbruckheimer who raised the original proposals), just a reminder to take a look at the following issues and provide your views on them before we next meet:
- #645 
- #646 
- #651 
- #652
- #655 
- #656 
- (and to a lesser extent) #654 

I'm sure some have a bearing on/overlap with @nemery-flextrade's :  
- #644 

I'm happy to contribute to them/the relevant PRs, but would appreciate the definitions being refined by participants more closely involved in the use-cases than I.
