### ISSUE TITLE
Standardize a context type representing a Currency

### ISSUE THREAD

**Issue by kriswest** [finos/FDC3#651]
## Enhancement Request

Create a context type that can be used to represent a Currency.

### Use Case:
A Currency context type is needed in order to compose other context types (such as an Order, Trade, Valuation or Position). However, an issue has also been raised to standardize recommended formats for 'primitive' fields, which might include ISO currency codes which may negate the need for this context as part of other context types. 
- #645 

A Currency context type may also be useful as a independent type, allowing it to be broadcast as part of workflows involving FOREX, liquidity pools or pricing. 

#### Currency
Represents and individual Currency.

##### Details

| Property      | Type    | Required | Example Value     |
|--------------|--------|-----------|---------------------|
| `type`           | string  | Yes          | `'fdc3.currency'`    |
| `name`         | string  | No          | `'US Dollar'`           |
| `ISOCODE` * | string  | No          | `'USD'`                   |

\* `ISOCODE` should conform to 3 character alphabetic codes standardized as part of ISO 4217. 

##### Example
```js
const currency = {
    type: 'fdc3.currency',
    name: 'US Dollar',
    ISOCODE: "USD"
}
```

**Comment by nemery-flextrade** [comment]
Per my comment on #645 we need to consider minor currency codes as well
