### ISSUE TITLE
Review Nick Kolba's Open Source Submission

### ISSUE THREAD

**Issue by robmoffat** [finos/FDC3#677]

**Comment by kriswest** [comment]
@robmoffat do you mean the repository being contributed: https://github.com/nkolba/electron-fdc3
Or the contribution issue in the community repository: https://github.com/finos/community/issues/182

What type of reviews are sought?

**Comment by robmoffat** [comment]
Hi Kris, 

This is an action on myself to review:  https://github.com/nkolba/electron-fdc3

I think I should have created this in the FINOS issues list, rather than here.  Do you want me to close this one?

**Comment by kriswest** [comment]
@robmoffat might as well, particularly if creating elsewhere
