### ISSUE TITLE
Desktop Agent Bridging Discussion group 4th May 2022

### ISSUE THREAD

**Issue by kriswest** [finos/FDC3#692]
## Group overview
Discussion group for developing proposals for producing bridges between FDC3 implementations (aka Desktop Agents), allowing applications running on one Desktop Agent, to integrate with FDC3 applications running on a second Desktop Agent for the same user.

The interop between applications running on different Desktop Agents aka Platforms would ideally cover
- Channels
- Raising and resolving Intents
- Launching Applications

### Relevant issue tags
- Current open issues that relate to the above concepts with the label: 
  [![image](https://user-images.githubusercontent.com/1701764/144856698-e49821ab-9c8e-4daf-99a1-23f4774c1fcd.png)](https://github.com/finos/FDC3/labels/Desktop%20Agent%20Bridging)
- The original issue is now a github discussion where content can be added and this issue discussed: 
#544

## Meeting Date
Wednesday 04 May 2020 - 9am EST / 2pm GMT

### WebEx info
- Meeting Link: [insert link](https://finos.webex.com/finos/j.php?MTID=m55d4aa79e148c948bf53163690e74fee)
- Meeting number: 2558 920 8729

*More ways to join*
- Join by video system:
   - Dial 25589208729@finos.webex.com
   - You can also dial 173.243.2.68 and enter your meeting number
- Join by phone
   - +1-415-655-0003 US Toll
   - +44-20319-88141 UK Toll
- Access code: 2558 920 8729

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://github.com/finos/community/blob/master/governance/Meeting-Procedures.md#run-the-meeting). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://odp.finos.org/docs/finos-maintainers-cheatsheet/).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://github.com/finos/community/blob/master/governance/Code-of-Conduct.md) and all other [FINOS policies](https://github.com/finos/community/tree/master/governance#policies).

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.
  
- A Discussion Group has no direct decision-making power regarding the FDC3 standard - rather it is intended that anything they propose or work on will result in proposals (via Github issues and PRs) for the Standards Working Group participants to consider and vote on for inclusion in the standard. As such, participation in a Discussion group is not required for contributing to any particular issue or FDC 2.0 as a whole.

## Agenda
- [x] Convene & roll call, review meeting notices (5mins)
- [x] Review action items from previous meeting (5mins)
- [x] Review updated Bridging proposal (working sessions) (45mins)
- [x] AOB & Adjourn (5mins)

## Minutes
- A quick summary of changes to the proposal (mostly made by @tpina @ Cosaic) was provided.
  - #634
  - Individual message exchanges will be split out of this doc into reference docs before it is merged into the standard
  - Better segregation of fields for message routing vs. fdc3 API call payload should ensure that a general description of protocol is possible without needed full specific for each message exchange - although these are still very useful to document
- Revisited discussion of standardisation of channels
  - There was general consensus that: 
    - it would be a better UX for channels to be matched across desktop agents - even if a mapping/conversion is supported in the bridge its unlikely to feel natural to users
    - Recommended set, but not required for compliance (SHOULD)
    - DAs MAY support channel customisation through config
    - We should aim for 8 channels with display metadata (too many is better than too few)
  - We should support an optional (MAY) ability for the bridge to map/convert channels as they pass through to deal with differences arising
- The standalone bridge MUST be bound to the loopback address (127.0.0.1) rather than a specified IP
  - Inter-machine comms is an internal concern of a bridge and does not need to be specified in the standard
- The standalone bridge SHOULD have a recommended port in the standard to enable discovery
  - however, the Natwest Markets real-world experience of using this approach has involved numerous port conflicts 
  - hence the bridge and desktop agents SHOULD also support a port range which can be scanned for connection
  - both DAs and the bridge MUST support configuration of the bridging port (range)
- Further work is needed on a connection handshake, auth and shame assignment protocol
  - A volunteer is requested to support this work
- Group to meet again in a month's time to review updates to the proposal, before returning to the normal cadence.
  - All requested to review proposal before the next meeting and prepare feedback/submit comments

## Action Items
- Rolled over from the previous meeting:
  - [x] @kriswest to raise issue proposing standardization of channel metadata
    - Recommended set, but not required for compliance (SHOULD)
    - MAY support channel customisation through config
    - 8 channels with display metadata
- [x] @tpina @kriswest update proposal to require bridge is bound on loopback address
- [x] @tpina @kriswest update proposal to include a recommended port and required support for configuration of a port range. 
- **all** review proposal before the next meeting and prepare feedback/submit comments
  - #634
- [x] @Julia-Ritter Cancel next meeting and rebook us to meet in (about) a months time.

## Untracked attendees

| Full name | Affiliation | GitHub username |
|-----------|-------------|-----------------|
|           |             |                 |

**Comment by Julia-Ritter** [comment]
Julia / FINOS

**Comment by tpina** [comment]
Tiago Pina / Cosaic

**Comment by timjenkel** [comment]
Tim / Wellington

**Comment by MichaelMCoates** [comment]
Michael Coates / OpenFin

**Comment by ggeorgievx** [comment]
Georgi / Tick42

**Comment by kriswest** [comment]
Kris West / Cosaic 🚀

**Comment by greyseer256** [comment]
Hugh / FactSet
