### ISSUE TITLE
Remove DNS/SRV Records detail from AppD specification

### ISSUE THREAD

**Issue by kriswest** [finos/FDC3#700]
The appD documentation includes detail in the [discovery section](https://fdc3.finos.org/docs/app-directory/discovery#dnssrv-records) that details DNS/SRV Records that can define the location of an app directory for a specific domain. However, it doesn't define a use case and the description seems incomplete and difficult to interpret. Further, it appears to rely on a list of known domains which support AppD services, which does not currently exist nor has a defined format. 

Further, the existence of this part of the specification muddies the waters for other parts of the specification, specifically fully qualified appIDs, where the appID is qualified as an email like syntax where the [domain name of the app directory is appended to the appID and a host resolution procedure](https://fdc3.finos.org/docs/app-directory/discovery#application-id-namespace-syntax-host-resolution) provided - by suggesting that the appD might be a location other than that determined by the host resolution procedure.

As this part of the specification is written as a proposal, has no documented use case and it's description is incomplete it should be removed from the specification.

**Comment by kriswest** [comment]
@rikoe @nkolba @thorsent do any of you understand the  DNS/SRV Records in the [discovery section](https://fdc3.finos.org/docs/app-directory/discovery#dnssrv-records) of the AppD specification? I've read it it half a dozen times and neither get the use-case or the procedure for using it...

**Comment by thorsent** [comment]
The SRV record is a way to leverage the global DNS system to locate a
specific web service. So it serves as a discovery mechanism.

So for instance, say you wanted to find the location of the appd service
for Cosaic, you could query DNS for the SRV record that matched "appd"+"
cosaic.io". DNS would return a record that would contain, essentially, TCP:
ourappdserver.cosaic.io:3456.

If I'm not mistaken, finos could host an SRV record for each vendor's
verified appd service, thus providing the seed for anyone wishing to
bootstrap the universe of apps.

It's a pretty clever solution to discovery. Not particularly urgent imo but
I think good of the original author to highlight that the standard exists
lest we feel compelled to reinvent the wheel.

**Comment by kriswest** [comment]
Ah ok, so it identifies a specific host and port running the appD for a specified domain. 

Where I thought this was muddying the waters was on fully qualified appIDs. Should the domain or appD host be used to qualify ids? I.e. for appId `myApp`, is it myApp@cosaic.io or myApp@ourappdserver.cosaic.io (port assumed to be 443 as per [Application ID namespace syntax host resolution](https://fdc3.finos.org/docs/app-directory/discovery#application-id-namespace-syntax-host-resolution) section).  However, it is stated in an [earlier section](https://fdc3.finos.org/docs/app-directory/discovery#application-identifier) that the 'AppD location' is used as the 'fully qualified domain name' part of the id.

> If I'm not mistaken, finos could host an SRV record for each vendor's verified appd service, thus providing the seed for anyone wishing to bootstrap the universe of apps.

I'm no expert on DNS, but I don't think this is possible for public DNS. I *think* each domain owner would have to create the SRV record for their domain. This is supported by the known domains section in the spec:
>**Known domains:**
>
>Although SRV records provide the means of resolving the location of an AppD service for a specific domain, there could be a need to know what domains exist in the universe. This would be a list of domains representing all known directory instances. It is recommended that the FDC3/FINOS organization publish a list of known domains which support AppD services. This publication can be handled in multiple ways, such as structured files or API endpoints. This proposal shall not provide a qualified solution to achieve this, but rather draw attention to a potential requirement.

But as stated FINOS could host a list of domains known to host AppD services.

I think my concerns were not valid - rather the article just needs some work to make it easier to digest; in particular, promoting the most common method ([static configuration](https://fdc3.finos.org/docs/app-directory/discovery#static-configuration)) from the end of the article to the beginning. I'll take care of that under the formal spec PR and will close this issue.
