### ISSUE TITLE
Add a recommended set of user channel definitions to the API

### ISSUE THREAD

**Issue by kriswest** [finos/FDC3#717]
## Enhancement Request

Add a set of recommended user channel definitions, with display metadata, to the FDC3 API Standard. 

### Use Case:

The FDC3 API includes a [`fdc3.getUserChannels()`](https://fdc3.finos.org/docs/next/api/ref/DesktopAgent#getuserchannels) (which replaces `fdc3.getSystemChannels()` in FDC3 2.0) function that should return the desktop agent's set of user channels, however, it is left up to each implementation to come up with that set. As these channels are intended for use by end-users (who select which channel an app is on), this has not been an issue in the past.

However, the Desktop Agent Bridging discussion group has identified use cases for a user to be working with multiple desktop agents (on one or more machines) and for those agents to be able to exchange messages through a 'bridge' allowing the apps running under the different agents to interoperate.  If the bridged desktop agents have different sets of user channels the user experience of context sharing via user channels becomes challenging.

While mapping broadcasts from one channel on a first desktop agent to a different channel on another agent is possible via configuration (either static or user administrated in a UI), the UX is still impacted. 

Hence, a set of user channels is proposed for inclusion in the standard, which will be recommended but not required for compliance purposes (SHOULD). A Desktop Agent MAY then also support configuration of their user channels. 

### References:
- https://github.com/finos/FDC3/discussions/544#discussioncomment-1997387
- #611
- #628 
- #692

### Proposed Channels
```JSON
[
    {
        "id": "A",
        "type": "user",
        "displayMetadata": {
            "name": "Channel A",
            "color": "red",
            "glyph": "A"
        }
    },
    {
        "id": "B",
        "type": "user",
        "displayMetadata": {
            "name": "Channel B",
            "color": "orange",
            "glyph": "B"
        }
    },
    {
        "id": "C",
        "type": "user",
        "displayMetadata": {
            "name": "Channel C",
            "color": "yellow",
            "glyph": "C"
        }
    },
    {
        "id": "D",
        "type": "user",
        "displayMetadata": {
            "name": "Channel D",
            "color": "green",
            "glyph": "D"
        }
    },
    {
        "id": "E",
        "type": "user",
        "displayMetadata": {
            "name": "Channel E",
            "color": "lightblue",
            "glyph": "E"
        }
    },
    {
        "id": "F",
        "type": "user",
        "displayMetadata": {
            "name": "Channel F",
            "color": "blue",
            "glyph": "F"
        }
    },
    {
        "id": "G",
        "type": "user",
        "displayMetadata": {
            "name": "Channel G",
            "color": "purple",
            "glyph": "G"
        }
    },
    {
        "id": "H",
        "type": "user",
        "displayMetadata": {
            "name": "Channel H",
            "color": "brown",
            "glyph": "H"
        }
    }
]
```

Note:
- Colors are defined using [CSS standard colors (extended)](https://www.w3.org/wiki/CSS3/Color/Extended_color_keywords). Individual implementations may adjust the specific color chosen but SHOULD choose a shade close to the default specified in [CSS3](https://www.w3.org/wiki/CSS3/Color/Extended_color_keywords)
- Alphanumeric glyph provided for colourblind users, matched to channel id.

**Comment by openfin-johans** [comment]
Hi @kriswest,

I think we should call these the "FDC3 channels" and the recommendation is to use them as a whole set? In any case they should have fdc3 included in the id to clarify and avoid any potential conflicts with other channels already in use with similar ids.

More of an opinion but I think we are better of with HEX colors? It avoids any confusion regarding what "red" is.

{
	"id": "fdc3_A",
	"type": "user",
	"displayMetadata": {
		"name": "Channel A",
		"color": "#FF0000",
		"glyph": "A"
	}
}

Lastly, I think there is a semi-standard in use already with the open source implementation by @nkolba and if we remove E and H from above it's the same. I would challenge anybody to use "brown" anyway :) 

Let's discuss,

Johan

**Comment by kriswest** [comment]
Hi @openfin-johans. I think it was @MichaelMCoates that suggested we keep the hex colors out of it so we don't have to have to discuss the perfect shade of red. However, technically these names do imply a specific hex color in CSS3 (see [standard docs here](https://www.w3.org/TR/css-color-3/#svg-color)).

N.b. in the PR we switched to arabic numerals, rather than latin characters (easier to read when small? more widely recognized?) on @greyseer256's suggestion. 

I'm open to changing the IDs as you suggest to namespace the channels. How about `fdc3.channel.1`?

This channel set was inspired by Nick's (including the progression through colours in spectrum order) but we agreed to expand it to 8 channels for future-proofing.  On review the color set was tweaked slightly for better contrast and to eliminate 'brown' (which was too close to red and purple).

Heres a preview:
![image](https://user-images.githubusercontent.com/1701764/170252064-871c1f73-8ebc-420a-a7f4-ddeeaf1e7f98.png)

PR:
- #727

**Comment by openfin-johans** [comment]
Ah - you are way ahead of me!

I'll move the id discussion to the PR
