### ISSUE TITLE
App Directory Discussion group - Monday 16th May 2022

### ISSUE THREAD

**Issue by kriswest** [finos/FDC3#718]
## Group overview
Discussion group to develop proposals for the improvement of the App Directory as part of the FDC3 standard. The group will examine the role/value/necessity of the AppD as part of the FDC3 specification and a compliance requirement for use of the FDC3 API, in addition to working on proposals to improve the description and functionality of the App Directory. 

### Relevant tags
Current open issues and PRs that relate to the above concepts with the label: 
[![image](https://user-images.githubusercontent.com/1701764/151783600-e65898db-0145-45bc-b500-2e3cf7b1010a.png)](https://github.com/finos/FDC3/labels/app-directory)

A [github discussion](https://github.com/finos/FDC3/discussions/618) is also available for this group (may be used to arrange meetings, agenda ask questions etc.)
## Meeting Date
Thursday 16 May 2022 - 9am EST / 2pm GMT

### WebEx info
- Meeting Link: (https://finos.webex.com/finos/j.php?MTID=m2316d45da678d0203fd86f9342ff63ab) 
- Meeting number: 2551 735 2618
- Password: VscvKptp756

*More ways to join*
- Join by video system:
   - Dial 25517352618@finos.webex.com
   - You can also dial 173.243.2.68 and enter your meeting number
- Join by phone
   - +1-415-655-0003 US Toll
   - +44-20319-88141 UK Toll
- Access code: 2551 735 2618

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://github.com/finos/community/blob/master/governance/Meeting-Procedures.md#run-the-meeting). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://odp.finos.org/docs/finos-maintainers-cheatsheet/).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://github.com/finos/community/blob/master/governance/Code-of-Conduct.md) and all other [FINOS policies](https://github.com/finos/community/tree/master/governance#policies).

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.
  
- A Discussion Group has no direct decision-making power regarding the FDC3 standard - rather it is intended that anything they propose or work on will result in proposals (via Github issues and PRs) for the Standards Working Group participants to consider and vote on for inclusion in the standard. As such, participation in a Discussion group is not required for contributing to any particular issue or FDC 2.0 as a whole.

## Agenda
- [x] Convene & roll call, review meeting notices (5mins)
- [x] Review action items from previous meeting (5mins)
  - #688
  - n.b. #550 was closed
- Review and approve PRs to be added to consolidated AppD update PR (30-45mins)
  - #668 
    - Already included:
      - #570 
      - #658 
      - #666
      - #669 
      - #670
      - #673
      - #675
      - #694 
  - To be reviewed:
    - [x] #671 
    - [x] #695 
    - [x] #696 
    - [ ] #697 
- Discuss other outstanding issues if time permits (0-15mins)
  - [ ] #559
  - [ ] #674
  - [ ] #719
  - [ ] #312 
  - [ ] #563
- [x] AOB & Adjourn (5mins)

## Minutes
- An overview of the consolidated PR so far was provided by @kriswest: #668
- A reminder of the timeline for FDC3 2.0 was requested: 
  - PRs to be presented to SWG by next meeting (Thurs 26th May)
  - Vote on adoption of 2.0 draft at the subsequent meeting (Thurs 23rd June).
- #671
  - The proposed changes were discussed (including the surprising lack of a launch `url` field in the existing standard versions) and it was agreed that the approach (`type`, `details` and `hostManifest` fields) is reasonable.
    - A question was raised regarding whether the keys for the `hostManifest` field need to be standardized
      - @nkolba pointed out that you might need to vary these for different versions of desktop agents (e.g. because they support different FDC3 versions)
      - @kriswest It should probably be the responsibility of individual vendors to document what strings they look for, rather than the Standard. However, we can update the example provided (on request) to show it is for a particular product.
  - (silent) consensus was sought and received to merge the PR into the consolidated appD update PR
- #695 
  - It was commented by several participants that administration systems for appD's will vary and there is no real need to standardize how they do that nor **require** that the expose this endpoint
  - Removing the endpoint from the standard does not prevent an implementation from using it
    - Add a comment to the appD spec that makes it clear that implementations MAY extend the standard endpoints
  - (silent) consensus was sought and received to merge the PR into the consolidated appD update PR
- #696 
  -  @kriswest review some of the discussion on the topic of improving the search endpoint that resulted in a PR to remove it
    - see #370
      - Current API makes it hard to implement a fairly standard keyword search or browse/filter by category
      - Combining results from different appD's would require a far more detailed specification of result weighting
        - The only way to do it well is to retrieve all the entries and implement the search and any necessary filtering client-side
      - There is one current use-case: to perform intent resolution for a Desktop Agent - however several participants commented that this was inefficient and is/would be better handled client-side
      - removing the endpoint from the standard does not prevent an implementation from using it (for example to support a built-in UI) - but does ensure that Desktop Agent implementations or UIs for browsing App Directories won't rely on it
  - (silent) consensus was sought and received to merge the PR into the consolidated appD update PR
- #697 
  -  @nkolba expressed a preference for dropping the `interopUse` element and moving the contents up to the top-level as siblings of the existing `intents` element
  - @nkolba queried the purpose of the `raisesContexts` element, @kriswest clarified that it was to represent contexts that `raiseIntentForContext` is called with and that other ways to handled it were to standardize a 'magic string' to represent _any_ context type, or to rename the element using the API call (i.e. change the elements to`raiseIntent` and `raiseIntentForContext`)
  - The discussion was curtailed by the end of the meeting, it was resolved to continue the discussion on the issue.
  - @kriswest to update PR with suggested changes

## Action Items
- [x] @kriswest #695 
  - Add a comment to the appD spec that makes it clear that implementations MAY extend the standard endpoints
- @kriswest Merge agreed PRs into consolidated update PR:
  - [x] #671 
  - [x] #695 
  - [x] #696
- [x] @kriswest #697 
  -  Explore moving the new elements to the top level of the record and rename based on API call 
- [x] @kriswest ~Recreate consolidated PR so that it gets a preview deployment~ Preview appeared on existing PR...
- [x] @kriswest Send notice of the consolidated PR to Standards Working Group so that it can be reviewed before the next SWG meeting (26th May)
- [ ] @kriswest Prepare next meeting agenda, to include outstanding items
  - [ ] #731
  - [ ] #559
  - [ ] #674
  - [ ] #719
  - [ ] #312 
  - [ ] #563

## Untracked attendees

| Full name | Affiliation | GitHub username |
|-----------|-------------|-----------------|
|           |             |                 |

**Comment by robmoffat** [comment]
Rob / FINOS

**Comment by kriswest** [comment]
Kris / Cosaic 🚀

**Comment by tpina** [comment]
Tiago Pina / Cosaic

**Comment by nkolba** [comment]
Nick Kolba

**Comment by nicopreto** [comment]
Nico Pretorius / Scott Logic

**Comment by dimiter-georgiev** [comment]
Dimiter / Symphony

**Comment by kriswest** [comment]
Minutes have been posted and a preview of the consolidated PR is now available at [here](https://deploy-preview-668--lambent-kulfi-cf51a7.netlify.app) 
- Spec summary: https://deploy-preview-668--lambent-kulfi-cf51a7.netlify.app/docs/next/app-directory/spec
- OpenAPI spec: https://deploy-preview-668--lambent-kulfi-cf51a7.netlify.app/schemas/next/app-directory#tag/Application

Please provide any further feedback on the draft proposal and add your review at:
- #668

**Comment by robmoffat** [comment]
can I close this now?

**Comment by kriswest** [comment]
> can I close this now?

Usually not closed until next meeting. I will however go and close the last meeting, thanks for reminding me!
