### ISSUE TITLE
Generate typescript types for contexts added in 2.0

### ISSUE THREAD

**Issue by kriswest** [finos/FDC3#745]
Prior to release the FDC3 source and NPM module need to be updated with new typescript types for standard contexts generated from the schemas. These go in [src/context/ContextType.ts](https://github.com/finos/FDC3/blob/master/src/context/ContextType.ts) and [src/context/ContextTypes.ts](https://github.com/finos/FDC3/blob/master/src/context/ContextTypes.ts).

A script is provided to do this: https://github.com/finos/FDC3/blob/544-Desktop-Agent-Bridging-Proposal/package.json/#L30-L31
`yarn typegen`

**Comment by kriswest** [comment]
Hi @jonfreedman, thanks for the prompt.
 
Ideally yes, I believe the issue is that the type generator [here](https://github.com/finos/FDC3/blob/fb25cca8e82b4fd3a1b5892d0ac531122567b438/package.json#L30) pulls the schemas from the public URLs via this [array in a JSON file](https://github.com/finos/FDC3/blob/master/src/context/schemas.json). Hence, any new or updated type schemas need to be merged to master and deployed to github pages before the types can be generated. Automation is probably a case of writing another action to run after [the deployment action](https://github.com/finos/FDC3/blob/fb25cca8e82b4fd3a1b5892d0ac531122567b438/.github/workflows/docusaurus.yml#L60-L79) that runs the generator and checks the result back into master.

Making the result (pre-draft of the next version of the standard) available as an npm module version is probably another action worth setting up.

**Comment by jonfreedman** [comment]
Great, sounds like you have the right idea
