### ISSUE TITLE
'ChatRoom' and 'SendChatMessage'

### ISSUE THREAD

**Issue by symphony-jean-michael** [finos/FDC3#765]
### Use Case:
This proposal covers two connected use cases:

- update the 'StartChat' intent to return a reference to the new created Chat room (ChatRoom)
- support the possibility to send messages in existing chats (New intent 'SendChatMessage')

### Description

The 'StartChat' intent has been modified (see PR https://github.com/finos/FDC3/pull/620) to be able to create new chats.
Since the latest version of FDC3, it is now possible that an intent returns data. So, this ticket is to continue the discussion/modification in order to implement the following changes:
- Update the StartChat intent to return a ChatRoom
- Add new intent 'SendChatMessage' that uses the ChatRoom

A request to add the new intent 'SendChatMessage' had already been proposed in the issue: https://github.com/finos/FDC3/issues/574 (But there was no PR yet because the standard did not yet allow to return a result)
This ticket repeats the elements already presented and makes some modifications on the id & appName.

**ChatRoom:**

```js
/**
 * Context returned by StartChat and SendChatMessage
 */
interface ChatRoom {
    type: "fdc3.chat.room";
    providerName: string // Name of the application that created the room / direct chat
    roomId: string // ID or the created room / direct chat
    uri?: string;   // Unique Universal URL to access to the chat room (Should we name the field 'id' or 'uri'?)
    name?: string; // Name of the chat room (This is for information purposes only as the room name may change in the future)
}
```

Example:
```js
const intentResolution = await fdc3.raiseIntent("StartChat", context);

const chatRoom = intentResolution.getResult():

/* // The chatRoom will be like:
  chatRoom = {
    type: "fdc3.chat.room",
    providerName: "Symphony",
    roomId: "j75xqXy25NBOdacUI3FNBH",
    uri: "http://symphony.com/ref/room/j75xqXy25NBOdacUI3FNBH___pqSsuJRdA",
    name: 'My new room'
  };
*/
```

We suggest adding an universal url for the uri. (It could be opened from a browser, a mobile app, etc...)

**SendChatMessage:**
(Related ticket: https://github.com/finos/FDC3/issues/574)

```js
// Start a chat
const intentResolution = await fdc3.raiseIntent("StartChat", context);
const chatRoom = intentResolution.getResult();

//Some time later

let chatMessage: ChatMessage = {
    type: "fdc3.chat.message",
    chatRoom,
    message: "Another message to send in the room"
}

await fdc3.raiseIntent("SendChatMessage", context, intentResolution.source);
```

**Comment by Yannick-Symphony** [comment]
> We suggest using a universal url for the uri. (It could be opened from a browser, a mobile app, etc...)

this has the advantage that if there is no app registered for this intent, the fdc3 bus could suggest to open the associated URI in web browser
