### ISSUE TITLE
Chat Message Container

### ISSUE THREAD

**Issue by Yannick-Symphony** [finos/FDC3#766]
### Use Case:

This proposal describes an initial structure to contain the "message" part of our new messaging-related intents

The objective is to be as generic as possible, building something that not only makes sense for IM chat applications, but also for asynchronous channels such as email

We also want to be flexible: for the textual part of the message we use a record to map mime type to content, allowing us to start with the simplest possible type (plain text) whilst we discuss further enhancements (e.g. markdown). This also allows applications to send multiple types (e.g. always sending plain-text as a "fallback")

The second record maps "entities" to unique IDs. An entity could be something as simple as an image attachment (see first example below), or something more advanced like an fdc3 intent that the user wants to embed into the outgoing message (see second example). The ID will allow us to reference specific entities from specific locations within the text when defining more advanced text formats.   

#### Message

Message to be sent in the context of StartChat or SendChatMessage

##### Details

```ts
export const enum TextMimeTypeEnum {
  'text/plain',
  //later we could extend support like 'text/markdown', 'finos/arbitrarycustomformat' etc
}

export const enum EntityTypeEnum {
  'fileAttachment',
  'fdc3Intent'
  // Later we could extend support to other types such as 'inline-image', 'news'
}

export interface FileAttachmentEntity {
  type: EntityTypeEnum.fileAttachment;
  data: {
    name: string;
    dataUri: string; // Base64 encoded file - 'data:image/png;base64,{BASE64_DATA}';
  }
}

export interface FDC3IntentEntity {
  type: EntityTypeEnum.fdc3Intent;
  data: {
    title: string;    // Text displayed on the button raising the intent
    intent: Intents;  // Intent type (ViewChart, etc...)
    context: Context; 
    app?: TargetApp;
  }
}

type Entity = FileAttachmentEntity | FDC3IntentEntity;

export interface Message {
  text: Partial<Record<keyof typeof TextMimeTypeEnum, string>>;
  entities?: Record<string, Entity>;
}
```

##### Example

Here is an example of a simple text message with attached PNG image. This type of message could very well be sent to an email client, as well as any IM app out there

```ts
const messageWithImage: Message = {
  text: {
    'text/plain': 'Hello, can you see the image attached?'
  },
  entities: {
    '0': {
      type: EntityTypeEnum.fileAttachment,
      data: {
        name: 'myImage.png',
        dataUri: 'data:image/png;base64,iVBORw0KGgoAAAANSUh...'
      }
    }
  }
}

A more advanced example, for clients that are able to take an FDC3 intent and inject it into an action button for example. In future the idea would be to reference this type of intent from within the "text", perhaps as a form of hyperlink

const messageWithIntent: Message = {
  text: {
    'text/plain': 'Hey, have a look at this chart!'
  },
  entities: {
    '0': {
      type: EntityTypeEnum.fdc3Intent,
      data: {
        title: 'Click to view Chart',
        intent: 'ViewChart',
        context: {
          type: 'fdc3.chart',
          instruments: [
            {
              type: 'fdc3.instrument',
              id: {
                ticker: 'EURUSD'
              }
            }
          ],
          range: {
            type: 'fdc3.dateRange',
            starttime: '2020-09-01T08:00:00.000Z',
            endtime: '2020-10-31T08:00:00.000Z'
          },
          style: 'candle'
        }
      }
    }
  }
}
```

### Additional Information

https://github.com/finos/FDC3/pull/620

https://github.com/finos/FDC3/issues/765

**Comment by Yannick-Symphony** [comment]
Hi @kriswest ! 

1. For this would we create a new entity, or just make the entity something generic like "fdc3", and then if it contains just a context it's a context, and if it's got intent+context it's an intent? or would that be too messy?
2. Yes, going further the idea would be to reference entities from within the message body - a possibility in markdown would be to do something like `look at this chart: [price chart](entity://3) pretty nice` (not necessarily that exact syntax, TBD further down the road)
3+4. So something like this?

```
const messageWithIntent: Message = {
  text: {
    'text/plain': 'Hey, have a look at this chart!'
  },
  entities: {
    '0': {
      entityType: EntityTypeEnum.fdc3,
      title: 'Click to view Chart',
      intent: 'ViewChart',
      context: {
        type: 'fdc3.chart',
        instruments: [
          {
            type: 'fdc3.instrument',
            id: {
              ticker: 'EURUSD'
            }
          }
        ],
        range: {
          type: 'fdc3.dateRange',
          starttime: '2020-09-01T08:00:00.000Z',
          endtime: '2020-10-31T08:00:00.000Z'
        },
        style: 'candle'
      }
    }
  }
}
```

**Comment by robmoffat** [comment]
Based on discussion in the intents and context meeting, it is slightly unclear from the use-case exactly what is being addressed here. 

Really, what we are trying to achieve is something like the "share" menu on your phone, where you are presented with a number of destinations (messages, email, WhatsApp) that can accept the shared data.  

It might be worth tidying up the Use Case: part of the description along these lines to make it clearer.
