### ISSUE TITLE
'View Messages' intent

### ISSUE THREAD

**Issue by symphony-jean-michael** [finos/FDC3#768]
### Use Case:

Users may want to search and see some messages. A list of messages will be displayed to the user.

#### ViewMessages

The proposal is to support a new intent `ViewMessages` to search messages.

Intent name: ViewMessages
Display Name: View Messages

### Context

This intent could take as context:
- either an [fdc3.instrument](https://fdc3.finos.org/docs/next/context/ref/Instrument)
- either an [fdc3.contact](https://fdc3.finos.org/docs/next/context/ref/Contact)
- either an [fdc3.organization](https://fdc3.finos.org/docs/next/context/ref/Organization)
- either a new context **fdc3.chat.searchCriteria** (Name inspired from the 'fdc3.chat.initSettings' context)

#### Context: Instrument

This shows messages containing a given ticker. (Like '$AAPL')

##### Example
```js
const instrument = {
    type: "fdc3.instrument",
    id: {
        ticker: "AAPL"
    }
}

fdc3.raiseIntent('ViewMessages', instrument);
```

#### Context: Contact

This shows messages from a specific contact.

##### Example
```js
const contact = {
    type: "fdc3.contact",
    name: "Jane Doe",
    id: {
        email: "jane.doe@mail.com"
    }
}

fdc3.raiseIntent('ViewMessages', contact);
```

#### Context: Contact

This shows messages from a specific organization.

##### Example
```js
const organization = {
    type: "fdc3.organization",
    name: "Symphony"
}

fdc3.raiseIntent('ViewMessages', organization);
```

#### Context: Tag

This shows messages containing a specific tag.

##### Example
```js
const searchTag = {
    type: "fdc3.chat.searchCriteria",
    tag: '#OrderID45788422'
}

fdc3.raiseIntent('ViewMessages', searchTag);
```

### Additional Information

Maybe in the future, we will support a list of Intents/Contact/Organization/Tags. **Out of scope for now.**

**Comment by robmoffat** [comment]
Could we improve the documentation around this use case so that it covers why this needs to involve FDC3 interop?  "A User may want to search messages" is achievable from within a single app (say Symphony)... so we need to be clear why and how users would use this from one app to another.
