### ISSUE TITLE
Context Data & Intents Discussion group - 7 July 2022

### ISSUE THREAD

**Issue by mistryvinay** [finos/FDC3#769]
## Group overview
At the FDC3 Use Cases Roundtable London, October 5th 2021 participants agreed that the FDC3 lexicon needs to be expanded, both with additional intents and context types to support Use Cases, but also to include more primitive data types in order to construct complex types. A number of participants also agreed that now is an appropriate time to expand the Lexicon.
​
See https://github.com/finos/FDC3/issues/455 for full details of the meeting outcomes.
​
This group is being convened to discuss and arrange work to contribute further Context types and Intents to support Use Cases being implemented by participants.

### Relevant issue tags
Current open issues that relate to the discussion group: 
[![image](https://user-images.githubusercontent.com/1701764/139841356-416d9276-81f5-4fce-b5d8-f856d4bda855.png)](https://github.com/finos/FDC3/labels/Context%20Data%20%26%20Intents)

Issues will also be tagged with the labels:
[![image](https://user-images.githubusercontent.com/1701764/139841631-c6bf8697-fafe-4266-8552-63a648625e8b.png)](https://github.com/finos/FDC3/labels/context-data)
[![image](https://user-images.githubusercontent.com/1701764/139841690-969a9d14-a0aa-44a7-bdfe-8c4a43ad30d9.png)](https://github.com/finos/FDC3/labels/intents)

## Meeting Date
Thursday 7 July 2022 - 9am EST / 2pm BST

### WebEx info
- Meeting Link: https://finos.webex.com/finos/j.php?MTID=mbb193ae433ce8d4366adcecd94355734
- Meeting number: 2556 257 8293

*More ways to join*
- Join by video system:
   - Dial 25562578293@finos.webex.com
   - You can also dial 173.243.2.68 and enter your meeting number
- Join by phone
   - +1-415-655-0003 US Toll
   - +44-20319-88141 UK Toll
- Access code: 2556 257 8293

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://github.com/finos/community/blob/master/governance/Meeting-Procedures.md#run-the-meeting). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://odp.finos.org/docs/finos-maintainers-cheatsheet/).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://github.com/finos/community/blob/master/governance/Code-of-Conduct.md) and all other [FINOS policies](https://github.com/finos/community/tree/master/governance#policies).

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.
  
- A Discussion Group has no direct decision-making power regarding the FDC3 standard - rather it is intended that anything they propose or work on will result in proposals (via Github issues and PRs) for the Standards Working Group participants to consider and vote on for inclusion in the standard. As such, participation in a Discussion group is not required for contributing to any particular issue or FDC3 2.0 as a whole.

## Agenda
- [x] Convene & roll call, review meeting notices (5mins)
- [x] Review action items from previous meeting (5mins)
  - #742 

- [x] Discuss Issues (35mins)
  - #765 
  - #766 
  - #767 
  - #768  
  - #387 
  - #592 
  - #771 
- [**FDC3 Implementations**](https://deploy-preview-714--lambent-kulfi-cf51a7.netlify.app/implementations#type-all): Request for containers/app providers to contribute an entry to this page.
    - Application Providers: Please include which version(s) of FDC3 is supported
    - Container Providers: What FDC3 versions do you currently support
- Revisit proposals for standardised Contexts (10mins)
  - [ ] #707 
  - [x] #644 
  - [x] #655 
  - [x] #656
  - [x] What intents need to be created to use the new contexts?
- [x] AOB & Adjourn (5mins)

## Minutes
- #765 
  - add `providerName` (e.g. Symphony)
  - add Id field for room `roomId`
  -`Send*` is not a standard prefix, but no better option, create `SendChatMessage`
  - update example to show how `AppIdentifier` from IntentResolution can be used to target `SendChatMessage`
  - remove the 'Ref' from `ChatRoomRef`
- #766  
  - change `message` name to `ChatMessage`, add context type
  - Entities proposed are likely to be reusable, upgrade to full FDC3 context types
   - lose `data` element to bring entities closer to usual context structure conventions
- #767 
  - Make it really clear chat should display
  - returning the reference is useful, but secondary to primary use case
  - Input types:
    - `ChatRoomRef` is fine
    - Contact should be bringing up the direct chart (rather than a room with a single other contact)
    - Contact List may need to display search results if there are multiple matches
    - Could take `ChatInitSettings` as input to work with list of contacts and resolve via name matching
  - Output:
    - If the chat doesn't exist, will display a modal to create chat
      - if the chat gets created, return its ChatRoom context
      - if none is created return void (rather than throw an error, which will stop the IntentResolution returning)
- #387 
  - no need for an API could be handled by intent resolution
  - notifications based on type of Context
  - create intent to submit a notification 
- #768 
  - @kriswest: I'm not seeing the value in the `fdc3.chat.searchCriteria` as specified
    - `instrument` is its own type and different context types can be passed via an intent
    - The example `tag` is a ticker symbol - instrument does support those: `{ type: "fdc3.instrument", id: { ticker: "AAPL"}}`
      - Provide other examples if there are ones not appropriate to instrument
    - Consider also supporting `fdc3.contact` and `fdc3.organization`
      - appD record configures which you support so these don't need actually need wrapping in a `fdc3.chat.searchCriteria` context, just check the type field of the one you receive.
- #771 
  - @kriswest: this is a *very* useful addition to the standard for intents that perform CRUD operations - ultimately I think it should come with an addition to the intents specification promoting its use
    - might also help us solve issues with errors (IntentResolution)
  - example and field details differ
  - context is not a string but Context
  - needs an enum to standardize `status` values
  - `message` or `description`? definition has one, example has the other

## Action Items
- [x] Release Cycle
  - @kriswest @mistryvinay talk to maintainers about setting up typegen + a 'next' npm build/release as a github action on merge to master so that intents/contexts are released as 'next' as soon as merged
- [x] [Order](#644)/[Trade](#655)/[Position](#656) contexts
  - @dominicgifford to schedule meeting to discuss current status (Thu 14th Jul @ 2pm BST)
    - demo what we have so far
    - capture the goals/guardrails of the Position/Trade/Order contexts and the Intents likely to use them on the proposals in GitHub
    - need to decide whether it is appropriate to wholly consume another standard for these contexts

## Untracked attendees

| Full name | Affiliation | GitHub username |
|-----------|-------------|-----------------|
|           |             |                 |

**Comment by nemery-flextrade** [comment]
Mentioned this offline but I'm unable to attend today's session. If there is any discussion on Order/Trade could someone kindly update me (particularly around adopting some part of the CDM to handle the more complicated securities)?

Many thanks!

**Comment by Julia-Ritter** [comment]
Julia / FINOS

**Comment by kriswest** [comment]
Kris / Cosaic

**Comment by robmoffat** [comment]
Rob / FINOS

**Comment by dominicgifford** [comment]
Dom /  S&P Global

**Comment by symphony-jean-michael** [comment]
Jean-Michael Legait / Symphony
