### ISSUE TITLE
Images are broken on some of the Use case docs pages

### ISSUE THREAD

**Issue by sebbenmbarek** [finos/FDC3#774]
### Area of Issue
[ ] App Directory
[ ] API
[ ] Context Data
[ ] Intents
[X] Use Cases
[ ] Other

### Issue Description: 
Images are broken on some of the Use case pages, as per screenshot below:

### Additional Context:
Screenshot:
<img width="828" alt="image" src="https://user-images.githubusercontent.com/290753/177566648-405ff8b8-2250-4a64-b979-42f255c03777.png">

**Comment by kriswest** [comment]
Many thanks for reporting this @sebbenmbarek, we'll get it sorted out.

**Comment by kriswest** [comment]
fixed
