### ISSUE TITLE
General Meeting - Aug 02, 2022

### ISSUE THREAD

**Issue by mistryvinay** [finos/FDC3#789]
## Date
02 Aug 2022 - 10am EST / 3pm BST

### WebEx info
- [Meeting Link](https://finos.webex.com/finos/j.php?MTID=m3015a7e4a511656ceafebda5eadcbe6d)
- Meeting number: 403 028 328

*More ways to join*
- Join by video system: dial 173.243.2.68 and enter your meeting number
- Join by phone
   - +1-415-655-0003 US Toll
   - +44-20319-88141 UK Toll
- Access code: 403 028 328

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://github.com/finos/community/blob/master/governance/Meeting-Procedures.md#run-the-meeting). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://odp.finos.org/docs/finos-maintainers-cheatsheet/).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://github.com/finos/community/blob/master/governance/Code-of-Conduct.md) and all other [FINOS policies](https://github.com/finos/community/tree/master/governance#policies).

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [ ] Convene & roll call, review meeting notices (5mins)
- [ ] FDC3 2.0 Standard (25mins)
  - Why FDC3 2.0? [_OSFF London_]
  - Release Status
  - Licensing Updates
- [ ] Discussion Group Participation (5mins)
- [ ] Planning for FDC3 2.1 (5mins)
- [ ] Q&A & Adjourn (20mins)

## Untracked attendees

| Full name | Affiliation | GitHub username |
|-----------|-------------|-----------------|
|           |             |                 |

**Comment by kriswest** [comment]
Kris / Cosaic 🚀

**Comment by mistryvinay** [comment]
Vinay / Symphony

**Comment by Julia-Ritter** [comment]
Julia / FINOS

**Comment by jgavronsky** [comment]
Jane / FINOS

**Comment by robmoffat** [comment]
Rob / FINOS

**Comment by hampshan** [comment]
Andrew Hampshire @ UBS

**Comment by mattjamieson** [comment]
:wave:

**Comment by Julia-Ritter** [comment]
**Untracked attendees:**

Nick Kolba / kolbito
Tim Jenkel / Wellington
Riko Eksteen / Adaptive 
Pierre Neu / Symphony 
Leslie Spiro / Glue42
