### ISSUE TITLE
Desktop Agent Bridging Discussion group 28th September 2022

### ISSUE THREAD

**Issue by kriswest** [finos/FDC3#822]
## Group overview
Discussion group for developing proposals for producing bridges between FDC3 implementations (aka Desktop Agents), allowing applications running on one Desktop Agent, to integrate with FDC3 applications running on a second Desktop Agent for the same user.

The interop between applications running on different Desktop Agents aka Platforms would ideally cover
- Channels
- Raising and resolving Intents
- Launching Applications

### Relevant issue tags
- Current open issues that relate to the above concepts with the label: 
  [![image](https://user-images.githubusercontent.com/1701764/144856698-e49821ab-9c8e-4daf-99a1-23f4774c1fcd.png)](https://github.com/finos/FDC3/labels/Desktop%20Agent%20Bridging)
- The original issue is now a github discussion where content can be added and this issue discussed: 
#544

## Meeting Date
Wednesday 28th Sept 2022 - 9am EST / 2pm BST

### WebEx info
- Meeting link: [https://finos.webex.com/finos/j.php?MTID=m55d4aa79e148c948bf53163690e74fee](https://finos.webex.com/finos/j.php?MTID=m55d4aa79e148c948bf53163690e74fee)
- Meeting number: 2558 920 8729

*More ways to join*
- Join by video system:
   - Dial 25589208729@finos.webex.com
   - You can also dial 173.243.2.68 and enter your meeting number
- Join by phone
   - +1-415-655-0003 US Toll
   - +44-20319-88141 UK Toll
- Access code: 2558 920 8729

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies).

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.
  
- A Discussion Group has no direct decision-making power regarding the FDC3 standard - rather it is intended that anything they propose or work on will result in proposals (via Github issues and PRs) for the Standards Working Group participants to consider and vote on for inclusion in the standard.
   
## Agenda
- [x] Convene & roll call, review meeting notices (5mins)
- [x] Review action items from previous meeting (5mins)
  - #798 
- [x] NatWest Markets: [Contribution of BackPlane as a Bridge implementation](https://github.com/finos/community/issues/204) (25 mins)
  - Overview of contribution
  - Demo of current state 
  - Discussion of next steps and how you can get involved.
- [x] Review updates to the proposal (20 mins)
  - Current proposal #634 
    - Preview: https://github.com/finos/FDC3/blob/544-Desktop-Agent-Bridging-Proposal/docs/api-bridging/spec.md
    - Changes:
      - Changed `meta.source` -> `meta.sources` and `errorSources` in response messages to allow messaging to user when DAs don't respond
      - Adjusted pseudocode for bridge message handling for cases where we receive a timeout but also have responses from other agents to process.
      - Exempted PrivateChannels from some cases where bridge messages are not normally generated (but should be for PrivateChannels).
      - Classified message exchanges by type.
      - Completed message exchanges for `broadcast`, `findIntent`, `findIntentsForContext` and `raiseIntent`.
- [x] AOB & Adjourn (5mins)

## Minutes
- An overview and demo of Backplane was provided by the NatWest Markets team.
  - Backplane: 
    - Is run as a service on one or more machines for the same user, independently of any containers or other Destkop Agent implementations
    - Successfully implements multi-machine and multi-container bridging
    - Includes client libraries for javascript and .Net applications
      - The .Net version models a single app as a desktop agent in order to support connection.
  - @kriswest commented: 
    - The version demonstrated (and currently used in production at NWM) appears to use core concepts that are well aligned with the current DAB proposal, despite message formats being slightly different (as the implementation predates the proposal)
      - Multi-machine and multi-container latencies looked good.
  - A version was demonstrated that has been refactored to use the connection workflow from the current DAB proposal, including synchronization of the channel state on connect.
    - @kriswest: 
      - This is a great validation of the proposal content
      - Watch out for capitalisation of field names in messages and unnecessary inclusion of null values.
  - @openfin-johans Standard set of FDC3 channels - does the Backplane have any information on the user channels of is just expecting a match of the channels?
    - BackPlane (and the proposal) are reliant on a common set of system/user channels on each agent for an ideal UX - neither support mapping of channels in the bridge.
    - .Net client had a set of channels matching Finsemble hardcoded into it - it gets state from the bridge but not that list.
  - Discussion is needed on how to best manage contributions since that NWM already has a production working version that predates this proposal, and are developing a version based on the current proposal
  - A participant asked whether the Backplane or Desktop Agent Bridging contemplate bridging external web applications (e.g. in a browser tab)
    - External web applications in a browser could leverage the provided JS client (and model themselves as a Desktop Agent managing a single application) in order to interact with apps running in containers.
    - It was noted that 
      - the same could also apply to Chrome extensions (such as [fdc3-desktop-agent](https://github.com/finos/fdc3-desktop-agent))
      - Several vendor implementations of FDC3 desktop agents also offer adapters to connect to connect into their DA
  - @kriswest: What challenges have been encountered in the implementation of the proposal?
    - Port clashes and resilience to crash (NWM feedback on these was already incorporated into the DAB proposal)
- A brief overview of recent changes to the proposal was provided (see agenda).
  - a complete first draft is expected by next month's meeting
  - from there progress will dependent on review feedback and implementations attempts (such as the the next version of the Backplane project)

## Action Items
- [x] @tpina @kriswest Add recommendation on visual feedback to users on Agent Connect/Disconnect from bridge
- [x] @tpina @kriswest Continue development of proposal, particularly individual message exchanges.
- [ ] **All** Review proposal and provide any further feedback necessary

## Untracked attendees

| Full name | Affiliation | GitHub username |
|-----------|-------------|-----------------|
|           |             |                 |

**Comment by pierreneu** [comment]
Pierre Neu / Symphony

**Comment by tpina** [comment]
Tiago Pina / Coasic

**Comment by ggeorgievx** [comment]
Georgi / Tick42

**Comment by kriswest** [comment]
Kris West / Cosaic

**Comment by timjenkel** [comment]
Tim Jenkel / Wellington

**Comment by mistryvinay** [comment]
Vinay Mistry / Symphony

**Comment by openfin-johans** [comment]
Johan Sandersson / OpenFin 🎁

**Comment by Julia-Ritter** [comment]
Untracked attendees:

- Manish / NatWest Markets 
- Alexandru Dumitru / Citi
- Vivek Giri / NatWest Markets 
- Aaron Haines / NatWest Markets 
- Dimiter Georgiev / Symphony 
- Rajeev Srivastava / NatWest Markets

**Comment by manish-nwm** [comment]
Manish / NWM
