### ISSUE TITLE
Context Data & Intents Discussion group - 3 Nov 2022

### ISSUE THREAD

**Issue by mistryvinay** [finos/FDC3#845]
## Group overview
At the FDC3 Use Cases Roundtable London, October 5th 2021 participants agreed that the FDC3 lexicon needs to be expanded, both with additional intents and context types to support Use Cases, but also to include more primitive data types in order to construct complex types. A number of participants also agreed that now is an appropriate time to expand the Lexicon.
​
See https://github.com/finos/FDC3/issues/455 for full details of the meeting outcomes.
​
This group is being convened to discuss and arrange work to contribute further Context types and Intents to support Use Cases being implemented by participants.

### Relevant issue tags
Current open issues that relate to the discussion group: 
[![image](https://user-images.githubusercontent.com/1701764/139841356-416d9276-81f5-4fce-b5d8-f856d4bda855.png)](https://github.com/finos/FDC3/labels/Context%20Data%20%26%20Intents)

Issues will also be tagged with the labels:
[![image](https://user-images.githubusercontent.com/1701764/139841631-c6bf8697-fafe-4266-8552-63a648625e8b.png)](https://github.com/finos/FDC3/labels/context-data)
[![image](https://user-images.githubusercontent.com/1701764/139841690-969a9d14-a0aa-44a7-bdfe-8c4a43ad30d9.png)](https://github.com/finos/FDC3/labels/intents)

## Meeting Date
Thursday 3 Nov 2022 - 9am EST / 1pm GMT

### WebEx info
- Meeting Link: https://finos.webex.com/finos/j.php?MTID=mbb193ae433ce8d4366adcecd94355734
- Meeting number: 2556 257 8293

*More ways to join*
- Join by video system:
   - Dial 25562578293@finos.webex.com
   - You can also dial 173.243.2.68 and enter your meeting number
- Join by phone
   - +1-415-655-0003 US Toll
   - +44-20319-88141 UK Toll
- Access code: 2556 257 8293

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies).

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.
  
- A Discussion Group has no direct decision-making power regarding the FDC3 standard - rather it is intended that anything they propose or work on will result in proposals (via Github issues and PRs) for the Standards Working Group participants to consider and vote on for inclusion in the standard.
   
## Agenda
- [x] Convene & roll call, review meeting notices (5mins)
- [x] Review action items from previous meeting (5mins)
  - #826 
- [x] Issues that require more discussion (10mins)
  - #387 
    - #828 
- [ ] PR's that are ready to be reviewed (5mins)
  - #824 
- [ ] Revisit proposals for standardised Contexts (5mins)
  - #655 
  - #656 
- [x] PR's that are awaiting updates (0mins)
- [x] PR's ready to merged into 2.1 Milestone release (1mins)
  - #747 
  - #761 
  - #796 
  - #797 
  - #819 
- [x]  Insights into business workflows that could be candidates for further extending FDC3 capabilities? (5mins)
- [x] AOB & Adjourn (5mins)

## Minutes
- #828 
    - Some further discussions and feedback regarding this proposal
      - @gerard-ciq demonstrated this proposal: https://user-images.githubusercontent.com/1701764/201643126-f8766d05-d080-42ab-86d1-e2afdd23d317.mp4
    - To edit an existing notification an `id` field must be included in the notification Context, identifying which is to be updated.
      - Implementations should return the notification object as an intent result, with the id field and any other relevant metadata set. This object can then be edited and resubmitted to edit the notitication.
      - This makes the interfaces to create or update notifications identical (the only difference being that the id is set in the notification) - hence we perhaps should use a single intent (`CreateOrUpdateNotification`) rather than two separate ones.
    - Is "GetNotifications" the correct naming? It's not quite returning notifications, it's returning a channel that you can use to receive messages about new and updated notifications. "GetNotificationsChannel" or "GetNotificationsStream"?
      - The original use case for channel results from intents was referred to as a 'feed'. How about GetNotificationFeed?
- #824 
    - Unfortunately we could not cover this proposal as the creator was not on the call.  Will push this back to next meeting.
    - @robmoffat has also introduced us to the ISDA CDM (Common Domain Model) who are also defining data models in the financial space.
    - Invite a CDM representative to our next meeting to tell us more about CDM and discuss how we can leverage the CDM in context types.
- Revisited open PRs for feedback - most are very close to complete and ready to be consolidated for presentation to the SWG:
  - #747
  - #761
  - #779
  - #794
  - #796
  - #797

## Action Items
- [x] @all Asks for other vendors that may use the`fdc3.order` type to ensure there is an agreement with #824 
- [x] Speak to @nemery-flextrade, @dominicgifford, @hampshan see if they can attend the next meeting
- [x] @mistryvinay add CDM speaker to the December agenda 

## Untracked attendees

| Full name | Affiliation | GitHub username |
|-----------|-------------|-----------------|
|           |             |                 |

**Comment by milindchidrawar** [comment]
Milind Chidrawar / Singletrack

**Comment by pierreneu** [comment]
Pierre Neu @ Symphony

**Comment by Julia-Ritter** [comment]
Julia / FINOS

**Comment by gerard-ciq** [comment]
Gerard Petersen / Cosaic

**Comment by kriswest** [comment]
Kris / Cosaic 🚀

**Comment by eteridvalishvili** [comment]
Eteri / FINOS

**Comment by robmoffat** [comment]
Rob / FINOS

**Comment by WatsonCIQ** [comment]
Chris Watson / Cosaic

**Comment by greyseer256** [comment]
Hugh Troeger / FactSet
