### ISSUE TITLE
Example and Definition Don't Match For App Directory `listensFor`

### ISSUE THREAD

**Issue by robmoffat** [finos/FDC3#846]
### Area of Issue
- [x] App Directory

### Issue Description: 

The specification defines `listensFor` like this:

```
       listensFor:
              type: object
              description: | 
                A mapping of Intents names that an app listens for via `fdc3.addIntentListener()` to their 
                configuration. 
                
                Used to support intent resolution by desktop agents. Replaces the `intents` element used in appD records prior to FDC3 2.0. 
              additionalProperties:
                x-additionalPropertiesName: Intent name
                items:
                  $ref: '#/components/schemas/Intent'
```

According to https://github.com/OAI/OpenAPI-Specification/issues/668#issuecomment-218829120 this implies that the map listens for will have as values an _array_ of intents.  When I generate typescript bindings for this structure I get:

```
    listensFor?: { [key: string]: components['schemas']['Intent'][] };
```

(note the trailing `[]`)

However, in the example, it appears not to be an array:
 
```
"interop": {
  "intents": {
    "listensFor": {
      "ViewChart": { 
        "displayName": "View Chart",
        "contexts": []
      }, 
      "myApp.GetPrice": {}
    },
    "raises": {}
```

(Taken from https://fdc3.finos.org/schemas/2.0/app-directory#tag/Application/paths/~1v2~1apps~1%7BappId%7D/get)

Was the example validated against the schema?

### Additional Context:

Also seems to be true for `raises`, and possibly other things I haven't checked.

**Comment by robmoffat** [comment]
@kriswest

**Comment by robmoffat** [comment]
Further context - I generated the typescript bindings with the `openapi-typescript` package.

**Comment by kriswest** [comment]
@robmoffat the tooling does not validate the example against the definitions (annoyingly). The example is correct, while the schema is off. The issue appears to be this items elements:

https://github.com/finos/FDC3/blob/add64f8302c6dcdc8437cf0e245101e927b69ec2/src/app-directory/specification/appd.yaml#L653

which makes it think the items are an array. It should be removed and `$ref` moved up a level to resolve.

I think `raises` is correct, that should be a mapping of intent names to an array of context types. Whereas listensFor is a mapping of intent names to a single intent object (which itself has an array of context types). 

PR incoming.

**Comment by robmoffat** [comment]
awesome, I'll look out for it
