### ISSUE TITLE
Context Data & Intents Discussion group - 1 Dec 2022

### ISSUE THREAD

**Issue by mistryvinay** [finos/FDC3#868]
## Group overview
At the FDC3 Use Cases Roundtable London, October 5th 2021 participants agreed that the FDC3 lexicon needs to be expanded, both with additional intents and context types to support Use Cases, but also to include more primitive data types in order to construct complex types. A number of participants also agreed that now is an appropriate time to expand the Lexicon.
​
See https://github.com/finos/FDC3/issues/455 for full details of the meeting outcomes.
​
This group is being convened to discuss and arrange work to contribute further Context types and Intents to support Use Cases being implemented by participants.

### Relevant issue tags
Current open issues that relate to the discussion group: 
[![image](https://user-images.githubusercontent.com/1701764/139841356-416d9276-81f5-4fce-b5d8-f856d4bda855.png)](https://github.com/finos/FDC3/labels/Context%20Data%20%26%20Intents)

Issues will also be tagged with the labels:
[![image](https://user-images.githubusercontent.com/1701764/139841631-c6bf8697-fafe-4266-8552-63a648625e8b.png)](https://github.com/finos/FDC3/labels/context-data)
[![image](https://user-images.githubusercontent.com/1701764/139841690-969a9d14-a0aa-44a7-bdfe-8c4a43ad30d9.png)](https://github.com/finos/FDC3/labels/intents)

## Meeting Date
Thursday 1 Dec 2022 - 9am EST / 2pm GMT

### WebEx info
- Meeting Link: https://finos.webex.com/finos/j.php?MTID=mbb193ae433ce8d4366adcecd94355734
- Meeting number: 2556 257 8293

*More ways to join*
- Join by video system:
   - Dial 25562578293@finos.webex.com
   - You can also dial 173.243.2.68 and enter your meeting number
- Join by phone
   - +1-415-655-0003 US Toll
   - +44-20319-88141 UK Toll
- Access code: 2556 257 8293

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies).

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.
  
- A Discussion Group has no direct decision-making power regarding the FDC3 standard - rather it is intended that anything they propose or work on will result in proposals (via Github issues and PRs) for the Standards Working Group participants to consider and vote on for inclusion in the standard.
   
## Agenda
- [x] Convene & roll call, review meeting notices (5mins)
- [x] Review action items from previous meeting (5mins)
  - #845  
- [x] Guest Speaker: Ian Sloyan [Senior Advisor Data & Digital Solutions @ ISDA] (20mins)
  - Presenting the ISDA Common Domain Model (ISDA CDM)
- [x] PR's that are ready to be reviewed (10mins)
  - #824    
  - #779 
- [x] Discussion of open issues (15mins)
  - #828 
  - #852 
  - #853 
  - #854 
  - #855 
  - #856   
- [x] PR's ready to merged into 2.1 Milestone release (1mins)
  - #747 
  - #761 
  - #796 
  - #797 
- [x] AOB & Adjourn (5mins)

## Minutes
- ISDA Common Domain Model presentation by Ian Sloyan
    - Introduction of CDM and how it allows for definition and execution of trade information
      - Greater focus on being able to define derivatives and on post-trade generally (rather than pre-trade, where FDC3 seems more focused)
      - Provides a data and process for post trade lifecycle
      - Also supports legal templates useful when dealing with OTC orders
    - Demo of CDM hierarchy using Rosetta UI
      - Walk through of the various fields and types used to define financial objects
    - Example of a vanilla interest rate swap (IRS) trade using Rosetta
      - Used Rosetta UI to view underlying sample data that was being used in the IRS demo
      - It was noted that CDM relies on inference for typing (e.g. an order is a swap because of what it contains, rather than what it is declared as), rather than the explicitly stated types (as FDC3 does)
    - @kriswest Highlighted FDC3's Context `type` fields as being the most obvious/immediate difference between CDM's and FDC3's approaches.
      - FDC3 currently promotes composition of types from other types - proliferating those type fields throughout a complex object
      - However, it does not *have* to, CDM models could be adopted to represent a type without composition, with sub-contexts still being broadcast-able separately from the full complex type, see: https://fdc3.finos.org/docs/api/spec#broadcasting-and-listening-for-multiple-context-types
  - CDM doesn't currently have a type to fully represent an order pre-trade, but does include many of the components and representations for positions and individual trades.
  - Rosetta UI access - will work with Ian Sloyan to provision some accounts so the FDC3 team can also review the CDM model in more detail.
  - Consent was sought and received from all participants to share the video of the session.
- #824 
    - Looking for more volunteers to support this PR
    - Need to ensure we get coverage for more asset types
    - @mistryvinay & Jane Gavronsky: Drive this discussion to a wider group
      - Speak to client list and firms on how they trade asset classes
      - Reach out to OMS/EMS providers and sell-side organisations
      - Bring back as a topic to next working group, possible email campaign or a "special meeting" specifically for defining order. 
- #779 
    - Consolidate and merge all chat PRs into this one
- #828  
    - Based on feedback for this particular issue next steps would be to put this forward at the next Standards Working Group meeting for validation.
- #852 
    - Verified that this is a bug (in the schema definition which is failing to extend 'Context') and will be closed via the below PR once merged
    - #869 
- #853 
    - Recipient object should be a union type
    - Possible flaw in how the generator handles schemas
    - Recipients is being created by a merge of 'contact' and 'contact list'
    - Probably validates correctly.  But its not a valid set of types you can use
    - Team will continue to dig deeper into this issue.
- Issues that will be reviewed offline by the @finos/fdc3-maintainers and @Yannick-Symphony 
    - #854 
    - #855 
    - #856 

## Action Items
- [x] @mistryvinay to work with Ian Sloyan to provision some demo accounts for Rosetta so we can explore in more detail the ISDA CDM model.
- [x] @mistryvinay & Jane Gavronsky to see how we can widen the group for discussing how orders should be presented over FDC3

## Untracked attendees

| Full name | Affiliation | GitHub username |
|-----------|-------------|-----------------|
|           |             |                 |

**Comment by Julia-Ritter** [comment]
Julia / FINOS

**Comment by symphony-jean-michael** [comment]
Jean-Michael Legait / Symphony

**Comment by milindchidrawar** [comment]
Milind / Singletrack

**Comment by Yannick-Symphony** [comment]
Yannick / Symphony 🦄

**Comment by dominicgifford** [comment]
Dom / SPGI

**Comment by kriswest** [comment]
Kris / Cosaic

**Comment by iansloyan** [comment]
Ian Sloyan / ISDA
