### ISSUE TITLE
Context Data & Intents Discussion group - 5 Jan 2023

### ISSUE THREAD

**Issue by mistryvinay** [finos/FDC3#888]
## Group overview
At the FDC3 Use Cases Roundtable London, October 5th 2021 participants agreed that the FDC3 lexicon needs to be expanded, both with additional intents and context types to support Use Cases, but also to include more primitive data types in order to construct complex types. A number of participants also agreed that now is an appropriate time to expand the Lexicon.
​
See https://github.com/finos/FDC3/issues/455 for full details of the meeting outcomes.
​
This group is being convened to discuss and arrange work to contribute further Context types and Intents to support Use Cases being implemented by participants.

### Relevant issue tags
Current open issues that relate to the discussion group: 
[![image](https://user-images.githubusercontent.com/1701764/139841356-416d9276-81f5-4fce-b5d8-f856d4bda855.png)](https://github.com/finos/FDC3/labels/Context%20Data%20%26%20Intents)

Issues will also be tagged with the labels:
[![image](https://user-images.githubusercontent.com/1701764/139841631-c6bf8697-fafe-4266-8552-63a648625e8b.png)](https://github.com/finos/FDC3/labels/context-data)
[![image](https://user-images.githubusercontent.com/1701764/139841690-969a9d14-a0aa-44a7-bdfe-8c4a43ad30d9.png)](https://github.com/finos/FDC3/labels/intents)

## Meeting Date
Thursday 5 Jan 2023 - 9am EST / 2pm GMT

### WebEx info
- Meeting Link: https://finos.webex.com/finos/j.php?MTID=mbb193ae433ce8d4366adcecd94355734
- Meeting number: 2556 257 8293

*More ways to join*
- Join by video system:
   - Dial 25562578293@finos.webex.com
   - You can also dial 173.243.2.68 and enter your meeting number
- Join by phone
   - +1-415-655-0003 US Toll
   - +44-20319-88141 UK Toll
- Access code: 2556 257 8293

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies).

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.
  
- A Discussion Group has no direct decision-making power regarding the FDC3 standard - rather it is intended that anything they propose or work on will result in proposals (via Github issues and PRs) for the Standards Working Group participants to consider and vote on for inclusion in the standard.
   
## Agenda
- [x] Convene & roll call, review meeting notices (5mins)
- [x] Review action items from previous meeting (5mins)
  - #868 
- [x] Recap from Open Source in Finance Forum - NYC, Dec 8th 2022 (10mins)
- [x] PR's that are ready to be reviewed (10mins)
  - #824 
- [x] Discussion of open issues (20mins)
  - #856
  - #829  
- [x] PR's ready to merged into 2.1 Milestone release (3mins)
  - #747 
  - #761 
  - #869 
  - #875 
  - #882 
- [x] AOB & Adjourn (5mins)

## Minutes
- Recap of Open Source in Finance Forum - NYC by @robmoffat 
  - Walked through keynote speakers, highlighting the importance of FDC3
  - Release of FDC3 Conformance Program which validates if desktop containers adhere to the standard
    - Desktop Agents who conform to the 1.2 standard are Finsemble, Glue42 & Sail 
  - FDC3 App Directory also announced and released during the event.  Further details in the comments below.
  - Expo saw people demonstrate work flows within financial services using Open Source projects
    - Four expos based around FDC3 theme
      - Presentations by Connectifi, Cosaic with State Street Bank, JP Morgan with FactSet & Glue42 and finally NatWest Bank.  Links to the presentations are also included in the comments below. 
  - OSFF Awards were also presented for the following FDC3 related projects which included:
    - FDC3 Conformance Certifications for Cosaic, Sail & Tick42
    - OSS Leadership Award "leading the pack" awarded to the FDC3 Maintainers
    - Going "All In" Award presented to NatWest Markets for contributing backplane
- #824 
  - Looking for more volunteers to support this PR 
- #856 
  - Need people to review this enhancement request prior to next meeting.
- #829 
  - Trying to find a way to pass information to another application - that would not be part of the main context object.
    - Example1: sharing an instrument with another application, the extra context information could be the originating chat room reference. (@pierreneu )
    - Example 2: I want to raise an intent to get a quote using viewQuotes. (@dominicgifford )
      - I want that quote on that trade order context. But from a particular person (additional context) 
    - Provide a way to store referenceId from the originating source application to enable 2-way exchange of information
    - @dimiter-georgiev asked if anyone has any other workflows that would need this referenceId value from the originating source application?
- AOB Topic: Representing FDC3 actions in applications (@pierreneu )
  - Make actions visible to an end user in an application
    - One idea was to represent that through an FDC3 icon
    - Common icons for actions (e.g. Open intents menu, broadcast or share content).
    - Has the group thought about guidelines or ideas on icons
    - New issue raised to track this #889 
  - @robmoffat mentioned that Sail are also interesting in this.  Currently all applications look quite different
    - Maybe introduce 'Design Guidelines' for applications - to look consistent in FDC3

## Action Items
- [ ] ...

## Untracked attendees

| Full name | Affiliation | GitHub username |
|-----------|-------------|-----------------|
|           |             |                 |

**Comment by milindchidrawar** [comment]
Milind Chidrawar / Singletrack

**Comment by mistryvinay** [comment]
Vinay Mistry / Symphony

**Comment by Julia-Ritter** [comment]
Julia / FINOS

**Comment by dimiter-georgiev** [comment]
Dimiter Georgiev / Symphony

**Comment by dominicgifford** [comment]
Dom / SPGI

**Comment by symphony-jean-michael** [comment]
Jean-Michael Legait / Symphony

**Comment by robmoffat** [comment]
Rob / FINOS

**Comment by greyseer256** [comment]
Hugh Troeger / FactSet

**Comment by pierreneu** [comment]
Pierre Neu @ Symphony

**Comment by WatsonCIQ** [comment]
Chris Watson / Cosaic

**Comment by robmoffat** [comment]
## Keynote

- I talk about FDC3 conformance: https://youtu.be/rJuXcnLzEJ4?t=1263
- FDC3 App Directory https://youtu.be/rJuXcnLzEJ4?t=1427

## Expos:

1. Nick Kolba - Connectifi: FDC3 from the desktop to the cloud
2. Cosaic + State Street: FDC3 trade workflow orchestration
3. JPM + FactSet + Glue : Awesome client management with FDC3, Asset & Wealth Management.
4. Citi with Desktop Agent Bridging (Aaron Haines)


## Presentations

1. **Michael Lynch, Symphony & Leslie Spiro, TICK42**.  Real Life Use Cases For FDC3 https://www.youtube.com/watch?v=YGO_GNHs3BA&list=PLmPXh6nBuhJuxRMguDu5rCy74TfVh3fE1 
2. **Nick Kolba, Connectifi, Seb M'Barek Norman & Sons** FDC3 Sail https://youtu.be/5VJzftderO0
3. **Aaron Haines (NWM) and Tiago Pinya (Cosaic)** Connecting Multiple Desktop Agents in Your FDC3 Environmenthttps://youtu.be/-EbFcsx7MeU

## Awards

- **Cosaic, Sail, Tick42** - various conforming desktop agents (1.2)
- **OSS Leadership Award "leading the pack"** -  The FDC3 Maintainers 
- **Going "All In" Award** - NWM, picked up by Aaron Haines, partly for contributing backplane.

**Comment by jgavronsky** [comment]
Jane @ FINOS here
