### ISSUE TITLE
FDC3 2.0 Training Courses 

### ISSUE THREAD

**Issue by robmoffat** [finos/FDC3#895]
## Enhancement Request

As discussed at the last maintainers' meeting, there is appetite for refreshing our FDC3 courses on the LF Training Platform. 

## New Module: Introduction to FDC3

- **Personas**:  people interested in FDC3, executives, users, technology purchasing, business stakeholders
- **Covering**:
  - Philosophy of FDC3:
    - Concept of loose, runtime coupling and how this alleviates integration cycles
    - Context data, and how it doesn't need to be standardized (but can be)
    - Inversion-of-control pattern 
    - Simple use-cases: some examples
    - Example of how you might add FDC3 to an existing app (like Nick showed in his Sail presentation but in theory, without the code)
  - FDC3 Landscape
    - The different components of FDC3 (DA, Apps, Standard, Directory) and how they work together
    - Who is involved in these different areas (vendors, etc.)
    - The fdc3.finos.org website, community page
    - directory.fdc3.finos.org
  - Getting Involved
    - FDC3 Governance
    - Conformance
    - Meetings / Groups / GitHub
    - Standardising things

## Existing Module:  [LF's FDC3 Developer Course](https://training.linuxfoundation.org/training/fdc3-interoperability-for-the-financial-desktop-lfs177x/)

 - Update this to 2.0 API
 - _don't_ cover absolutely everything - just enough to get started.
 - Do it in a use-case-based way, so people can see how an app could be constructed

**Comment by mistryvinay** [comment]
hi @robmoffat @rikoe have made a start on the above listing some updates for the 1.2 course, but also new content for the 2.0 course.

Doc can be found here: https://docs.google.com/spreadsheets/d/1O4sIuV6IqhBO-RF8qiCj87zhBqJebaPfwEDJ-T-yKpU/edit?usp=sharing

**Comment by robmoffat** [comment]
Some notes from the meeting with Flavia:


1.  The process is kicked off with a design document for the course (see attachments).  This irons out audience, objectives, etc.  It's very specific
2.  Following that, course design begins.  LF will project manage us chapter-by-chapter. We provide text and videos (demos).  We create exercises and end-of-chapter test questions.   They will help with feedback and compile it into the actual course.
3.  It's uploaded to the training platform.   LF Training is probably the way to go but there is also EdX.  We do a soft-launch, test it and get some feedback.
4.  We pick a launch date, engage with marketing and get the public involved.

**Comment by robmoffat** [comment]
Course content for 1.2 Course: 

https://docs.google.com/document/d/1v7Omn3vBilKj0fWNY7UN3v_H13Wv6g77Our4taX85Do/edit?usp=drive-slack&ts=63fe09f2

**Comment by kriswest** [comment]
The first course (introduction to FDC3) was launched as LFEL1000: https://www.finos.org/blog/2023-09-11-just-launched-introduction-to-fdc3-lfel1000. 

The second course 'Developing with FDC3' is due to be released at OSFF 1st Nov 2023
