### ISSUE TITLE
Desktop Agent Bridging Discussion group 25th Jan 2023 

### ISSUE THREAD

**Issue by kriswest** [finos/FDC3#897]
## Group overview
Discussion group for developing proposals for producing bridges between FDC3 implementations (aka Desktop Agents), allowing applications running on one Desktop Agent, to integrate with FDC3 applications running on a second Desktop Agent for the same user.

The interop between applications running on different Desktop Agents aka Platforms would ideally cover
- Channels
- Raising and resolving Intents
- Launching Applications

[Current proposal document](https://github.com/finos/FDC3/blob/544-Desktop-Agent_bridging-Proposal-mk2/docs/api-bridging/spec.md)

### Relevant issue tags
- Current open issues that relate to the above concepts with the label: 
  [![image](https://user-images.githubusercontent.com/1701764/144856698-e49821ab-9c8e-4daf-99a1-23f4774c1fcd.png)](https://github.com/finos/FDC3/labels/Desktop%20Agent%20Bridging)
- The original issue is now a github discussion where content can be added and this issue discussed: 
#544

## Meeting Date
Wednesday 25 Jan 2023 - 9am EST / 2pm GMT

### WebEx info
- Meeting link: [https://finos.webex.com/finos/j.php?MTID=m55d4aa79e148c948bf53163690e74fee](https://finos.webex.com/finos/j.php?MTID=m55d4aa79e148c948bf53163690e74fee)
- Meeting number: 2558 920 8729

*More ways to join*
- Join by video system:
   - Dial 25589208729@finos.webex.com
   - You can also dial 173.243.2.68 and enter your meeting number
- Join by phone
   - +1-415-655-0003 US Toll
   - +44-20319-88141 UK Toll
- Access code: 2558 920 8729

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies).

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.
  
- A Discussion Group has no direct decision-making power regarding the FDC3 standard - rather it is intended that anything they propose or work on will result in proposals (via Github issues and PRs) for the Standards Working Group participants to consider and vote on for inclusion in the standard.
   
## Agenda
- [x] Convene & roll call, review meeting notices (5mins)
- [x] Review action items from previous meeting (5mins)
  - #862
- [x] Update from the Backplane project (15min)
  - Getting quickly productive with what we offer
    - Artifacts available to download.
    - Quick start.
  - Brief description of demo attached in Readme.
  - Roadmap
    - Issues, asking for help. 
- [x] Implementation simplicity vs. security for Private Channel message exchanges (10mins)
- [x] Defining the message exchange (JSONSchema vs. OpenAPI vs. AsyncAPI) (10mins)
- [ ] Q&A / proposal feedback discussion & AOB (15mins)
- Adjourn 

## Minutes
- PrivateChannel message exchanges
  - Improved pereamble added to this section explaining approach
  - An explanation of the message routing flow regarding broadcasts and event messages was provided
  - No comments or objections to this approach were raised - no a preference for a simpler scheme which relies on DAs to provide security
    - Group to review and provide feedback/differ opinions
- @kriswest addressed @robmoffat's feedback on the use of OpenAPI vs JSON Schemas vs AsyncAPI
  - Debate the available options and relevant drawbacks/limitations.
  - No one present had experience with AsyncAPI
  - @Vivek-NatWest - Used JSON Schema previously, acknowledges that it isn't the most human readable format, but is useful for generating types in many languages (including TypeScript and.Net)
    - It would be useful for moving the BackPlane project forward - especially for future contributions
  - @kriswest - message payload definitions in OpenAPI/AsyncAPI are (generally JSONSchema, but with the added ability to define endpoints and link to the message exchanges, generate documentation and generate client/server stubs.
    - We will proceed with using JSON Schema to define the messages used in the proposal - future changes should not be too complicated, including upgrade to AsyncAPI definitions
    - NWM BackPlane team to investigate the using AsyncAPI
  - @Vivek-NatWest mentioned FINOS Financial Objects project - what do they use to generate documentation
    - @kriswest older stuff is hand edited - there maybe be more recent things I haven't seen.
    - @Julia-Ritter - Ask the FO maintainers what are they using to automatically generate documentation from JSON Schema or other formats.

- Update from Backplane project
  - @Vivek-NatWest provided an update on the project
    - Focused on improving adoptions by:
      - creating a quickstart guide
      - added sample Hello World example with Finsemble integration
      - lots of work done in the backend - automation of releases, population of release assets, nukpg, etc
    - explained the workflow of the Hello World example in BP
    - Issues created to which they are seeking help to implement https://github.com/finos/backplane/issues
    - @kriswest - Building a testing harness to the Backplane, similar to a conformance testing framework, would provide a way to develop and test without a Desktop Agent being updated to support bridging (which is hard to do until work is complete)
      - suggested adding this item as a issue/milestone to the BP project

- Alex (Citi) - Asked about discovery service and examples of it provided in the repository.
  - @Vivek-NatWest - simple config based discovery provided for multi-machine - intended to be replaced with something more elaborate by firms deploying backplane 
  - for single machine use simply no discovery service is needed (hosted on localhost)

## Action Items
- [x] @kriswest @tpina - Start creating JSON Schema documents for message exchanges (to be used to generate documentation and objects (TypeScript and .NET)
- [x] NWM - Add new milestone or issue to BackPlane project for a Testing Framework
- [x] NWM - Improve documentation Hello World example with details of *both* single and multiple machine use-case
- [x] NWM - Investigate usability of asyncAPI
- [ ] @Julia-Ritter - Ask the FO maintainers what are they using to automatically generate documentation from JSON Schema or other formats

## Untracked attendees

| Full name | Affiliation | GitHub username |
|-----------|-------------|-----------------|
|           |             |                 |

**Comment by tpina** [comment]
Tiago Pina / Finsemble

**Comment by Julia-Ritter** [comment]
Julia / FINOS

**Comment by timjenkel** [comment]
Tim / Wellington

**Comment by kriswest** [comment]
Kris West / Finsemble 🚀

**Comment by manish-nwm** [comment]
Manish / NWM

**Comment by mattjamieson** [comment]
:wave:

**Comment by mistryvinay** [comment]
Vinay Mistry / Symphony

**Comment by WatsonCIQ** [comment]
Chris Watson / Finsemble 👋

**Comment by Vivek-NatWest** [comment]
Vivek / NWM
