### ISSUE TITLE
General Meeting - Feb 7th, 2023

### ISSUE THREAD

**Issue by kriswest** [finos/FDC3#906]
## Date
07 Feb 2023 - 10am EST / 3pm GMT

### WebEx info
- [Meeting Link](https://finos.webex.com/finos/j.php?MTID=m3015a7e4a511656ceafebda5eadcbe6d)
- Meeting number: 403 028 328

*More ways to join*
- Join by video system: dial 173.243.2.68 and enter your meeting number
- Join by phone
   - +1-415-655-0003 US Toll
   - +44-20319-88141 UK Toll
- Access code: 403 028 328

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies).

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call, review meeting notices (5mins)
- [x] FINOS Updates and Announcements (5mins)
  - Conformance Testing update
  - FDC3 Training
  - Meetups
  - FDC3 Workbench update
- [x] FDC3 2.1 Roadmap (5mins)
- [x] Recent activity: Discussion groups, meetings and issues  (15mins):
  - Desktop Agent Bridging update: #861
  - FDC3 for the Web - join the debate: #896
  - Context Data & Intents update
    - Defining contexts and use cases for Orders, Trades and Positions: #904
    - Provide a UX guideline for FDC3: #899 
  - Standards Working Group activity
- [x] Upcoming meetings (5mins)
- [x] QA & Adjourn (10-25mins)

## Meeting deck
[FDC3 General Meeting - 7th Feb 2023.pdf](https://github.com/finos/FDC3/files/10688887/FDC3.General.Meeting.-.7th.Feb.2023.pdf)

## Untracked attendees

| Full name | Affiliation | GitHub username |
|-----------|-------------|-----------------|
|           |             |                 |

**Comment by robmoffat** [comment]
Rob / FINOS

**Comment by novavi** [comment]
Derek Novavi / S&P Global

**Comment by mistryvinay** [comment]
Vinay Mistry / Symphony

**Comment by lspiro-Tick42** [comment]
Leslie / Glue42

**Comment by psmulovics** [comment]
Peter / Morgan Stanley

**Comment by eteridvalishvili** [comment]
Eteri / FINOS

**Comment by openfin-johans** [comment]
Johan / OpenFin 🎁

**Comment by nkolba** [comment]
Nick / Connectifi

**Comment by pierreneu** [comment]
Pierre Neu / Symphony

**Comment by mattjamieson** [comment]
Matt / WhiteDog

**Comment by jgavronsky** [comment]
Jane @ FINOS here

**Comment by WatsonCIQ** [comment]
Watson / Finsemble 👋

**Comment by Julia-Ritter** [comment]
Julia / FINOS

**Comment by greyseer256** [comment]
Hugh / FactSet
