### ISSUE TITLE
FDC3 Certification

### ISSUE THREAD

**Issue by robmoffat** [finos/FDC3#909]
## Marketing
- [x] Set up beta-testing signup form, who they are, relationship to the product, job title, etc.  Google forms. (@robmoffat)

## FDC3 SMEs
- [x] Planning stage.  Be really clear about the audience.  Difficulty of 
- [x] Collect SMEs. - up to 5 solid, diverse people.
- [x] Draft exam scope into a statement.
- [x] Draft a straw-man for the exam blueprint (domains and competencies of the exam).  Chapter headings, subtopics.  5 - 6 buckets.  competencies within that.
- [x] Catalog: product page, blueprint. 
- [x] Wrangle group of 6-8 SME's including super-SME.
- [x] Job-Task Analysis (JTA).  Get SMEs to agree what's in the exam. (they start with the strawman). they come up with the final exam blueprint. 4-hour session, usually.  -> Scope, Title, Domains and Competencies.  Domains weighted for importance (some get more questions than others)
- [x] Badge designed for passers.  [Cred.ly](http://cred.ly/)
- [x] Badge designed for contributors - also a leaderboard.
- [x] Publish a "coming soon" product page.

## Item Writing
- [x] Meet with Certiverse team to set up the SMEs.
- [x] Item Writing. - Even more SMEs.  
- [x] Private blueprint - how difficult to make each item?   
- [x] Peer Review (on Certiverse) - will help us weed out inferior questions (items).

## Beta Testing
- [x] Beta Test - people who write/administer training will take it first!  So, beta performance is often weird. You can get a clear idea of the item performance.  Need around 100 people for this.Announce at a conference and get sign-ups.
- [x] Psychometrician.  On staff at Certiverse.  Tweaks difficult questions, drops lemons.
- [x] We figure out the passing score.  SMEs look at the beta results and figure it out by voting. Led by psychometrician.  Standard Setting

## Release
- [x] Publication
- [x] General Availability

**Comment by robmoffat** [comment]
https://docs.google.com/document/d/16_T5mK8iT0Kll0W1Gbedm-yX584cuXDuaHrmC7DqcHw/edit#

**Comment by robmoffat** [comment]
# FDC3 Certified Practitioner

_The FDC3 Certified Practitioner exam demonstrates a developers’s foundational knowledge and skills in the FDC3 standard and the wider FDC3 ecosystem._


# Who Is It For?

The FDC3 Certified Developer exam is designed for technical business analysts and developers working as FDC3 implementers.  


# About This Certification

A certified FDC3 Practitioner has demonstrated firm conceptual understanding of the key design considerations and rationale of the FDC3 standard.  They have a broad knowledge of the FDC3 ecosystem and the implementation details required to work in the field.


# What It Demonstrates

The practitioner will have demonstrated an ability to deploy FDC3 concepts into real-world use cases, as well as understanding of the limitations of FDC3 and where it is not relevant.  


# Includes



* Online
* Certification valid for 3 Years
* Includes 12 Month Exam Eligibility
* One Retake
* Multiple Choice Exam
* Duration of Exam 90 Minutes


# Experience Level



* Medium


# Domains and Competencies


## FDC3 Concepts (20%)



* What problem is FDC3 trying to solve
* What is in scope and out-of-scope for FDC3
* 


## FDC3 Components (20%)



* Desktop Agents
* Context Data and Intents
* Directory
* Apps


## FDC3 Standard API (20%)



* Broadcasting and Listening to Context
* Creating and Joining User Channels
* Finding and Raising Intents (and the difference between them).
* Opening Apps
* When to raise intent with context, vs. broadcasting.


## Security (10%)



* Bounds of Trust
* Assembling App Directories
* Data leakage scenarios


## Community (10%)



* Who runs FDC3 the Standard
* Who uses FDC3
* How to Contribute (Generally)
* Contributing standard intents and context types.


## Use Cases (20%)



* Solve use-case based scenarios by applying the following FDC3 concepts:
    * Creating context data
    * Creating intents
    * When to use channels
    * Using standard context data
    * Using standard intents
* Good Context Design Theory
* Good Inversion-of-Control theory

**Comment by kriswest** [comment]
Completed!
