### ISSUE TITLE
Desktop Agent Bridging Discussion group 22nd Mar 2023

### ISSUE THREAD

**Issue by kriswest** [finos/FDC3#935]
## Group overview
Discussion group for developing proposals for producing bridges between FDC3 implementations (aka Desktop Agents), allowing applications running on one Desktop Agent, to integrate with FDC3 applications running on a second Desktop Agent for the same user.

The interop between applications running on different Desktop Agents aka Platforms would ideally cover
- Channels
- Raising and resolving Intents
- Launching Applications

[Current proposal document](https://github.com/finos/FDC3/blob/544-Desktop-Agent_bridging-Proposal-mk2/docs/api-bridging/spec.md)

### Relevant issue tags
- Current open issues that relate to the above concepts with the label: 
  [![image](https://user-images.githubusercontent.com/1701764/144856698-e49821ab-9c8e-4daf-99a1-23f4774c1fcd.png)](https://github.com/finos/FDC3/labels/Desktop%20Agent%20Bridging)
- The original issue is now a github discussion where content can be added and this issue discussed: 
#544

## Meeting Date
Thursday 22 Mar 2023 - 9am EDT / 1pm GMT (Note daylight savings in US but NOT UK)

### WebEx info
- Meeting link: [https://finos.webex.com/finos/j.php?MTID=m55d4aa79e148c948bf53163690e74fee](https://finos.webex.com/finos/j.php?MTID=m55d4aa79e148c948bf53163690e74fee)
- Meeting number: 2558 920 8729

*More ways to join*
- Join by video system:
   - Dial 25589208729@finos.webex.com
   - You can also dial 173.243.2.68 and enter your meeting number
- Join by phone
   - +1-415-655-0003 US Toll
   - +44-20319-88141 UK Toll
- Access code: 2558 920 8729

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies).

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.
  
- A Discussion Group has no direct decision-making power regarding the FDC3 standard - rather it is intended that anything they propose or work on will result in proposals (via Github issues and PRs) for the Standards Working Group participants to consider and vote on for inclusion in the standard.
   
## Agenda
- [x] Convene & roll call, review meeting notices (5mins)
- [x] Review action items from previous meeting (5mins)
    - #911
- [x] Updates from the BackPlane Project (10mins)
- [x] JSONSchema definitions for message exchanges (10mins)
- [x] Desktop Agent Bridging Q&A session (25mins)
- [x] AOB & Adjourn (5mins)

## Minutes
- Revisted the topology decisions in the proposal for new participants: [FDC3 Desktop Agent Bridging - The Effect of Different Topologies.pdf](https://github.com/finos/FDC3/files/11040532/FDC3.Desktop.Agent.Bridging.-.The.Effect.of.Different.Topologies.pdf)
- An overview of the JSONSchema definitions for bridging message exchanges was provided by @kriswest and @tpina 

## Action Items
- [x] @kriswest @tpina Continue work on message exchange schema definitions and PR into FDC3 Standard docs
- [x] @kriswest @tpina @Vivek-NatWest meet about implementing testing for BackPlane and using AsyncAPI for documentation

## Untracked attendees

| Full name | Affiliation | GitHub username |
|-----------|-------------|-----------------|
|           |             |                 |

**Comment by tpina** [comment]
Tiago Pina / Finsemble

**Comment by robmoffat** [comment]
Rob / FINOS

**Comment by mistryvinay** [comment]
Vinay Mistry / Symphony 🎵

**Comment by mattjamieson** [comment]
Matt / WhiteDog
