### ISSUE TITLE
Website: FDC3 2.1 Roadmap page has console errors

### ISSUE THREAD

**Issue by julianna-ciq** [finos/FDC3#944]
## Minor Issue
Please use minor issues for discrepancies or errors found in the spec or supporting documentation, examples, and other materials.  If you wish to propose a new feature or a revision to an existing feature, please use the *Enhancement Request* template.

### Area of Issue
[ ] App Directory
[ ] API
[ ] Context Data
[ ] Intents
[ ] Use Cases
[x] Other

### Issue Description: 
On the [FDC3 2.1 Roadmap page](https://fdc3.finos.org/fdc3-roadmap), there are several errors printed to the console, all related to React+Docusaurus:
* TR tags are nested under TABLE instead of TBODY
* Using the attribute `class` instead of `className`
* Using the attributes `colspan` and `rowspan` instead of `colSpan` and `rowSpan`.

I'm willing to contribute this change.

**Comment by kriswest** [comment]
Resolved by #948
