### ISSUE TITLE
Schemas are no longer retrievable by most JSON Schema tools

### ISSUE THREAD

**Issue by kriswest** [finos/FDC3#956]
Since the website hosting switched to netlify, most JSON schema tooling can no longer access the schemas due to the lack of an  'Access-Control-Allow-Origin' header:
![image](https://user-images.githubusercontent.com/1701764/231841128-3a111f44-ee00-49ce-9ba8-132e027d70f7.png)

The below screenie is from app.quicktype.io, but I'm seeing the same in ajv and json-schema-ref-parser and other tools.

We'll need to configure the hosting to set an `Access-Control-Allow-Origin: *` header and the allowed origins will need to be * as this is used from scripts etc. not served from an origin. That shouldn't be a problem as the website is static.

**Comment by TheJuanAndOnly99** [comment]
Hi @kriswest I'm not able to reproduce the error. But have you seen this post on the [support forums](https://answers.netlify.com/t/access-control-allow-origin-policy/1813)? I think it may be helpful.

**Comment by kriswest** [comment]
Thanks @TheJuanAndOnly99, raised a PR to add the netlify.toml file with the header declaration in
#957
