### ISSUE TITLE
FDC3 for Web Browsers Discussion group - 20th April 2023

### ISSUE THREAD

**Issue by kriswest** [finos/FDC3#958]
## Group overview
Group convened to discuss how to enable FDC3 use in a web browser, without the use of a browser extension (such as [fdc3-desktop-agent](https://github.com/finos/fdc3-desktop-agent) or a container).

Issue: https://github.com/finos/FDC3/issues/896
Mailing list discussion: https://groups.google.com/a/finos.org/g/fdc3/c/jCvlLjokBLs

In a recent email on the FDC3 mailing list, @kriswest wrote:

... I also want to add that there is clearly significant interest in the community in enabling FDC3 use on the web. There is a strong use case in that it would enable better onboarding journeys with less drop-off (where you use an app on the web with others before adopting a desktop container or similar).

and:

But there are also additional challenges such as how to make the API available reliably without importing a proprietary module from a particular vendor into every app, how to deal with more than one implementation of API/Desktop Agent in the browser at once, how to do this reliably and securely within the browser sandbox etc.. Work needs to be done in the Standard to solve these issues and to make web browser use possible in a future FDC3 Standard version - which I believe is possible (and likely to involve using a vendor-agnostic FDC3 NPM module to detect and connect to API implementation(s)). However, we're going to need to do that work to enable the aforementioned API implementations to be compliant and if we fail to hold the line now on compliance with the current version of the FDC3 Standard, that may never happen.

### Relevant issue tags
Current open issues that relate to the above concepts with the label: 
[![image](https://user-images.githubusercontent.com/1701764/222422435-9a27f7ab-f73a-4d89-90e7-8dee40361d8e.png)
](https://github.com/finos/FDC3/labels/FDC3%20for%20Web%20Browsers)

## Meeting Date
Thursday 20 April 2023 - 11am EST / 4pm BST

### WebEx info
- Meeting link: [https://finos.webex.com/finos/j.php?MTID=mc297e9962d73ad18f6539745ce79abf9](https://finos.webex.com/finos/j.php?MTID=mc297e9962d73ad18f6539745ce79abf9) 
- Meeting number: 2552 173 3304

*More ways to join*
- Join by video system:
   - Dial 25521733304@finos.webex.com
   - You can also dial 173.243.2.68 and enter your meeting number
- Join by phone
   - +1-415-655-0003 US Toll
   - +44-20319-88141 UK Toll
- Access code: 2552 173 3304

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies).

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.
  
- A Discussion Group has no direct decision-making power regarding the FDC3 standard - rather it is intended that anything they propose or work on will result in proposals (via Github issues and PRs) for the Standards Working Group participants to consider and vote on for inclusion in the standard.
   
## Agenda
- [x] Convene & roll call, review meeting notices (5mins)
- [x] Review action items from previous meeting (15mins)
  - #939 
  - [x] reconfirm the decision to load DA client libraries (after receiving details of what to load), rather than use standardized comms via postMessage for all App/Desktop Agent client -> DesktopAgent communication
- Continue discussion of proposals for a library (standard) to provide access to a Desktop Agent API interface  (35 mins)
    - Proposals posted on #896
      - Detailed proposal with options: https://github.com/finos/FDC3/issues/896#issuecomment-1471736414  
      - The proposal was **reviewed up to the beginning of step 3** in the previous meeting.
    - [ ] Discuss requirements/options for Step 3 (independent web apps)
    - [ ] Discuss requirements/options for Step 4 (Micro-frontend containers (single DOM)
    - [ ] Next steps + request for volunteers to work on proposal drafting
- [ ] AOB & Adjourn (5mins)

## Minutes
- Unfortunately, this meeting failed to make progress through the agenda and was largely spent covering old ground, particularly revisiting the discussion of web containers (step 2), but without new insights. One participant questioned the entire premise of the discussion on multiple occasions, making it very hard to make progress.
- The participants resolved to keep the minutes for this meeting light and to take steps to make the conversation easier to engage in. Several participants complained of the difficulty of understanding the current proposals, or the amount of time it takes to engage in/prepare for the discussion.
- The consensus at the end of the meeting was that steps need to be taken to make it easier to engage in the discussion and hopefully keep future meetings on track, including:
  - Producing a short of requirements and design goals for a solution, against which proposals can be evaluated.
  - Code examples for use of a proposed installer library in applications.
  - Examples of configuration files or requirements that might be needed.
  - The use of polls to enable offline evaluation and voting on proposals.

## Action Items
- [ ] Produce a short lists of requirements and design goals to discuss at the next meeting.
- [ ] Produce some small code examples to inform the discussion at the next meeting.

## Untracked attendees

| Full name | Affiliation | GitHub username |
|-----------|-------------|-----------------|
|           |             |                 |

**Comment by kriswest** [comment]
Kris West / Finsemble 🚀

**Comment by novavi** [comment]
Derek Novavi / S&P Global

**Comment by nkolba** [comment]
Nick Kolba / Connectifi

**Comment by mistryvinay** [comment]
Vinay Mistry / Symphony 🎵

**Comment by Julia-Ritter** [comment]
Julia / FINOS

**Comment by hampshan** [comment]
Andrew Hampshire @ UBS

**Comment by robmoffat** [comment]
Rob / FINOS 🦑

**Comment by WatsonCIQ** [comment]
Chris Watson / Finsemble 👋

**Comment by openfin-johans** [comment]
Johan / OpenFin 🎁
