### ISSUE TITLE
Desktop Agent Bridging Discussion group 26th April 2023

### ISSUE THREAD

**Issue by kriswest** [finos/FDC3#969]
## Group overview
Discussion group for developing proposals for producing bridges between FDC3 implementations (aka Desktop Agents), allowing applications running on one Desktop Agent, to integrate with FDC3 applications running on a second Desktop Agent for the same user.

The interop between applications running on different Desktop Agents aka Platforms would ideally cover
- Channels
- Raising and resolving Intents
- Launching Applications

PR: https://github.com/finos/FDC3/pull/968
[PR preview](https://deploy-preview-968--fdc3.netlify.app/)
[Specification link](https://deploy-preview-968--fdc3.netlify.app/docs/next/api-bridging/spec)

### Relevant issue tags
- Current open issues that relate to the above concepts with the label: 
  [![image](https://user-images.githubusercontent.com/1701764/144856698-e49821ab-9c8e-4daf-99a1-23f4774c1fcd.png)](https://github.com/finos/FDC3/labels/Desktop%20Agent%20Bridging)
- The original issue is now a github discussion where content can be added and this issue discussed: 
#544

## Meeting Date
Wednesday 26 Apr 2023 - 9am EST / 2pm GMT

### WebEx info
- Meeting link: [https://finos.webex.com/finos/j.php?MTID=m55d4aa79e148c948bf53163690e74fee](https://finos.webex.com/finos/j.php?MTID=m55d4aa79e148c948bf53163690e74fee)
- Meeting number: 2558 920 8729

*More ways to join*
- Join by video system:
   - Dial 25589208729@finos.webex.com
   - You can also dial 173.243.2.68 and enter your meeting number
- Join by phone
   - +1-415-655-0003 US Toll
   - +44-20319-88141 UK Toll
- Access code: 2558 920 8729

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies).

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.
  
- A Discussion Group has no direct decision-making power regarding the FDC3 standard - rather it is intended that anything they propose or work on will result in proposals (via Github issues and PRs) for the Standards Working Group participants to consider and vote on for inclusion in the standard.
   
## Agenda
- [x] Convene & roll call, review meeting notices (5mins)
- [x] Review action items from previous meeting (5mins)
  - #935 
- [x] Desktop Agent Bridging PR overview
  - PR: https://github.com/finos/FDC3/pull/968
  - [Proposal preview](https://deploy-preview-968--fdc3.netlify.app/)
    - [Specification link](https://deploy-preview-968--fdc3.netlify.app/docs/next/api-bridging/spec)
- [x] Next Steps (Voting)
- [x] Updates from the BackPlane project
- [x] AOB & Adjourn (5mins)

## Minutes
- A summary of discussions with the BackPlane project on automated testing (with input from @glenn) of BackPlane/bridge clients and the creation of an AsyncAPI spec was provided.
  - Keep variables in testing low: 
    - Create unit tests for a client first
    - Create internal unit tests for bridge server where possible
    - Use the tested client to create integration tests for client and server
  - AsyncAPI should be applicable to the bridging spec. 
    - When the message JSONSchemas are complete we can use them to assemble a detailed asyncAPI spec (and gain dynamic docs ala redoc for openAPI, code generation for tests/clients/server stubs in multiple languages .
- @kriswest and @tpina provided a run-through of the pr #968
  - Added documentation to FDC3 website as a 5th Part including a main specification and reference docs for each message exchange.
  - Experimental flag applied to feature throughout
  - Minor additions to API types (marked experimental) as it makes sense to keep API types together
  - Created JSONSchema definitions for all Bridging connect and interop messages - involving lots of manual review and refinement
  - Added schemas for API types (for when they are encoded in JSON)
    - Used to generate (duplicate) Typescript sources (minus any API function signatures) for Bridging implementations
  - Reorganized schemas (including existing Context schemas) into a /schemas folder, with a folder per type (context/api/bridging)
    - this keeps the reference paths the same whether working with them locally or through the website (previously you could only work through the published schemas on the web as the reference paths would change)
  - Adjusted quicktype code generation scripts to include bridging and API schemas
  - Added generated code for bridging to NPM module.
- @robmoffat  & @mattjamieson discussed the potential for the message exchanges to be used within FDC3 for Web browsers solutions, or internally in desktop agent implementations
  - Lots of reuse possibilities for the schemas/approach
  - May need very minor change on addressing (remove targeting to Desktop Agents if scoped within a single agent), but otherwise generally applicable
- Consent was requested and received for raising the PR with the FDC3 SWG meeting for inclusion in FDC2.1
  - Proposal of an email vote on inclusion was suggested/recommend by @kriswest and @mattjamieson
- @Vivek-NatWest discussed the generation of an AsyncAPI schema incorporating all the message schemas as the ideal next step for the BackPlane project.

## Action Items
- [x] @kriswest Propose Desktop Agent Bridging as a new Part of the FDC3 Standard at the Standards Working Group - an email vote on inclusion is recommended.
- [x] @mattjamieson Test generated typescript files for bridging as part of his bridging demo
- [x] @Vivek-NatWest Test bridging JSON schemas as a part of an async API specification that could be added to the documentation and/or used to generate tests, client libraries and server stubs.
- [ ] **all** review the PR and comment on any issues found
  - #968

## Untracked attendees

| Full name | Affiliation | GitHub username |
|-----------|-------------|-----------------|
|           |             |                 |

**Comment by kriswest** [comment]
Kris West / Finsemble 🚀

**Comment by Vivek-NatWest** [comment]
vivek/natwest

**Comment by mistryvinay** [comment]
Vinay Mistry / Symphony 🎵

**Comment by mattjamieson** [comment]
Matt Jamieson / WhiteDog 🎉

**Comment by robmoffat** [comment]
Rob / FINOS 🪑
