### ISSUE TITLE
Typo in PATENTS-FDC3-1.0.md

### ISSUE THREAD

**Issue by Neha-Balaji** [finos/FDC3#988]
Cloud9 Tehnologies under signatures section. 

Hi, My firm is doing a workshop on contribution to opensource. As part of that, this issue will be fixed and PR will be raised.

**Comment by kriswest** [comment]
Ah `Cloud9 Tehnologies LLC` -> `Cloud9 Technologies LLC` ?

@mindthegab @robmoffat this will probably end being one for you (and team), rather than the FDC3 community.

**Comment by KhurramJalil** [comment]
Opened on 16th May, I didn't see any activity on this active issue for approx. 10 weeks so went ahead and fixed it via following PR.

https://github.com/finos/FDC3/pull/1046 

@kriswest please review when you get some time.
